### PR TITLE
Remove no listeners

### LINKED ISSUE #338: Actions with no listeners that are old should be removed from queue
If an action is old (set in config) and has no more listeners it should just be evicted from the queue, since no one is waiting for the action.

see: https://github.com/TraceMachina/turbo-cache/blob/f15146d0cf94e1a9159f14db775efe4a3e27355d/cas/scheduler/simple_scheduler.rs#L432

We should implement this using timeouts and upon timing out signal to the worker to kill the action.

### PR DESCRIPTION
**Pull request by zbirenbaum**
Fixes #338 

There might be a better way to do this if listeners can be checked before trying to send off the result of an action to them, but I don't know of a way to do that so I'm opening this as a draft. Also was wondering what the easiest way to test for this behavior would be, as I couldn't find a test case for actions without listeners.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/717)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/717)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6kqhn2gDS7jRehOBL:-Ns6kqhn2gDS7jRehOBM:bqh7515) (no related file):*
We have a couple options here.

1. We could call `notify_channel.send()` to tell the worker to terminate the job.
2. We could cancel only queued actions.

I prefer 1, but it'll be more difficult.

___
*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6lLBk2a8CXhINUF3Q:-Ns6lLBk2a8CXhINUF3R:b-tnxtf) (no related file):*
At this phase, I suggest writing some tests.

___
___
*[`nativelink-config/src/schedulers.rs` line 124 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6iFSK6iEGHs6HsM8Q:-Ns6iFSK6iEGHs6HsM8R:b9oegh9) ([raw file](https://github.com/TraceMachina/nativelink/blob/daf9b3bb555f93c5835503b7d6c6b6aaa530992e/nativelink-config/src/schedulers.rs#L124)):*
> ```XML
> 
>     /// Remove action from queue after this much time has elapsed without a listener
>     /// amount of time in seconds.
> ```

nit: End the sentence above and make this line say:
`Units in seconds.`
___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 356 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6ioGB-aa4lgVZyIHk:-Ns6ioGB-aa4lgVZyIHl:bo2jesf) ([raw file](https://github.com/TraceMachina/nativelink/blob/daf9b3bb555f93c5835503b7d6c6b6aaa530992e/nativelink-scheduler/src/simple_scheduler.rs#L356)):*
> ```XML
>                     self.queued_actions_set.insert(action_info.clone());
>                     self.queued_actions.insert(action_info.clone(), awaited_action);
>                     self.metrics.time_without_listeners.reset();
> ```

Don't store this number on `metrics`. Metrics is only for statistics. We should not rely on it for any required features. Users can disable all metrics everywhere, so this may cause issues in weird ways.

**Comment by zbirenbaum** [comment]
> > Reviewed 1 of 1 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/717)_ status: 0 of 1 LGTMs obtained
> 
> _[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6kqhn2gDS7jRehOBL:-Ns6kqhn2gDS7jRehOBM:bqh7515) (no related file):_ We have a couple options here.
> 
>     1. We could call `notify_channel.send()` to tell the worker to terminate the job.
> 
>     2. We could cancel only queued actions.
> 
> 
> I prefer 1, but it'll be more difficult.
> 
> _[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6lLBk2a8CXhINUF3Q:-Ns6lLBk2a8CXhINUF3R:b-tnxtf) (no related file):_ At this phase, I suggest writing some tests.
> 
> _[`nativelink-config/src/schedulers.rs` line 124 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6iFSK6iEGHs6HsM8Q:-Ns6iFSK6iEGHs6HsM8R:b9oegh9) ([raw file](https://github.com/TraceMachina/nativelink/blob/daf9b3bb555f93c5835503b7d6c6b6aaa530992e/nativelink-config/src/schedulers.rs#L124)):_
> 
> > ```
> >     /// Remove action from queue after this much time has elapsed without a listener
> >     /// amount of time in seconds.
> > ```
> 
> nit: End the sentence above and make this line say: `Units in seconds.`
> 
> _[`nativelink-scheduler/src/simple_scheduler.rs` line 356 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6ioGB-aa4lgVZyIHk:-Ns6ioGB-aa4lgVZyIHl:bo2jesf) ([raw file](https://github.com/TraceMachina/nativelink/blob/daf9b3bb555f93c5835503b7d6c6b6aaa530992e/nativelink-scheduler/src/simple_scheduler.rs#L356)):_
> 
> > ```
> >                     self.queued_actions_set.insert(action_info.clone());
> >                     self.queued_actions.insert(action_info.clone(), awaited_action);
> >                     self.metrics.time_without_listeners.reset();
> > ```
> 
> Don't store this number on `metrics`. Metrics is only for statistics. We should not rely on it for any required features. Users can disable all metrics everywhere, so this may cause issues in weird ways.

Got it, my instinct was that using notifications would be a better way but need to read more into how to get it working, the original issue only referenced the queue so got a little confused. I think doing it right will pay dividends in the long run so lets go with number 1.

**Review by allada — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/717)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/717#-Ns6lLBk2a8CXhINUF3Q:-NsJj8FY2uMnGmJ5cGJy:bjqn2u3) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

At this phase, I suggest writing some tests.
</blockquote></details>

Please reword the github description, as it will become the commit message.

___

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/717)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 210 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/717#-NsJni1kCB2Mm7X0nerY:-NsJni1kCB2Mm7X0nerZ:bs9fbja) ([raw file](https://github.com/TraceMachina/nativelink/blob/e159e91fb3c0ec036d39ddb1507955ac5ddc8069/nativelink-scheduler/src/simple_scheduler.rs#L210)):*
> ```XML
>     workers: Workers,
>     active_actions: HashMap<Arc<ActionInfo>, RunningAction>,
>     actions_no_listeners: HashMap<Arc<ActionInfoHashKey>, SystemTime>,
> ```

nit: Lets track this in field in `AwaitedAction` with something like `last_client_event`. This field will need to be updated on every connect of a client and a timer will need to update it periodically if it still has listeners.
___
*[`nativelink-scheduler/src/worker.rs` line 208 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/717#-NsJjvYjBx0WnKXjts-b:-NsJjvYjBx0WnKXjts-c:b-3ls0g2) ([raw file](https://github.com/TraceMachina/nativelink/blob/e159e91fb3c0ec036d39ddb1507955ac5ddc8069/nativelink-scheduler/src/worker.rs#L208)):*
> ```XML
>     }
> 
>     pub fn drop_action(&mut self, action_info: &Arc<ActionInfo>) {
> ```

nit: We don't want to do anything here, we need to worker to send the RPC message back to the scheduler saying it errored/completed and let the normal flow take it.
___
*[`nativelink-util/src/action_messages.rs` line 634 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/717#-NsJjdSh26l6cyNI54YG:-NsJjdSh26l6cyNI54YH:bz0eh84) ([raw file](https://github.com/TraceMachina/nativelink/blob/e159e91fb3c0ec036d39ddb1507955ac5ddc8069/nativelink-util/src/action_messages.rs#L634)):*
> ```XML
>     /// Worker is executing the action.
>     Executing,
>     // TODO(zbirenbaum) Add dropped status and rpc handling for actions which were cancelled due to disconnection
> ```

nit: This is not the RPC message you are looking for, check `worker_api.proto`.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/717)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 61 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/717#-NsVSp_TEGQ4WdzC89TU:-NsVSp_TEGQ4WdzC89TV:b-yjgcg9) ([raw file](https://github.com/TraceMachina/nativelink/blob/8d8777131c23461e37217d8536924bbbf133c356/nativelink-scheduler/src/simple_scheduler.rs#L61)):*
> ```XML
> /// Default timeout for actions without any listeners
> /// If this changes, remember to change the documentation in the config.
> const DEFAULT_NO_LISTENERS_TIMEOUT_S: u64 = 10;
> ```

nit: Lets make this 60 seconds.

**Comment by zbirenbaum** [comment]
Closing this and continuing in #778 which is much more polished and addresses most of the problems here

**Pull request closed without merging**
