### PR TITLE
Ignore fast store

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
# Description

If there's a value in the fast store, but it's been removed from the slow store and the slow store happens to require that value because it's being used for the execution, then this causes the execution to fail.  Add an option to make checks on the store go to the slow store every time to ensure it has the values.  Serving still comes from the fast store.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested on local cluster and added new test for the change.

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633)

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
nit: Isn't it a bug if this feature is disabled? In what situation would we not have the fast store available? If there are two machines with different fast stores (e.g. different in-memory stores) and a common S3 slow store, do we want something like this?:

```
in fast?
  yes: stream from fast store to client
  no: in slow?
    yes: stream from slow store to client (But do we also want something like an implicit slow->fast upload?)
    no: build the artifact and upload to fast
``` 

:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633#-:-Np1ZF9n4gL0eVXTU47P:b74969u)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by chrisstaite-menlo — COMMENTED** [review]
Yeah, I wasn't sure if it was a bug or not, hence making it configurable.  For example, on a worker node, there's no reason to go and check with the slow store if you have everything and increase latency because if you've got it, then it's all good, you have everything to do the work requested.  However, for a proxy to the central storage it's an absolute must.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633#-:-Np3xKVl4bGLklP8cQm2:b-i1pfnc)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-config/src/stores.rs` line 262 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/633#-Np5dYXo5O_bbh3zZg73:-Np5dYXo5O_bbh3zZg74:b-kkbm1c) ([raw file](https://github.com/TraceMachina/nativelink/blob/045e5c2557afbd0a212dc621e962088889e2026d/nativelink-config/src/stores.rs#L262)):*
> ```XML
>     /// will still come from the fast store if it exists.
>     #[serde(default)]
>     pub check_slow_store_only: bool,
> ```

Hmmm, I wounder if this should be always enabled now, and if people need the existence cache, they can use existence caching store as a layer?

**Comment by chrisstaite-menlo** [comment]
*[`nativelink-config/src/stores.rs` line 262 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/633#-Np5dYXo5O_bbh3zZg73:-Np5e8cQ21OPfUr1JeHz:b-2u32mb) ([raw file](https://github.com/TraceMachina/nativelink/blob/045e5c2557afbd0a212dc621e962088889e2026d/nativelink-config/src/stores.rs#L262)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, I wounder if this should be always enabled now, and if people need the existence cache, they can use existence caching store as a layer?
</blockquote></details>

Happy to go with whatever here, obviously it's much faster to look it up in the fast store if we don't care about the slow store (i.e. workers, filesystem slowstore).

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-config/src/stores.rs` line 262 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/633#-Np5dYXo5O_bbh3zZg73:-Np5gM960_gtcCTYrqU4:b-fxz0zv) ([raw file](https://github.com/TraceMachina/nativelink/blob/045e5c2557afbd0a212dc621e962088889e2026d/nativelink-config/src/stores.rs#L262)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

Happy to go with whatever here, obviously it's much faster to look it up in the fast store if we don't care about the slow store (i.e. workers, filesystem slowstore).
</blockquote></details>

From my understanding here's the breakdown of what components would ever call what:

Stores:
* ActionCache should be wrapped in `CompletenessCheckingStore` or else it can serve references to evicted items.
* CAS should be wrapped in `ExistenceCacheStore` and possibly `FastSlowStore`, for dramatic efficiency gains.

Scheduler:
* IIRC, scheduler doesn't actually need a store, unless it wants to extract details out about the job

Workers:
* Only ever calls `.get` & `.update` on CAS, never calls `.has`
* Always requires a `FastSlowStore(fast: FilesystemStore, slow: *)`, but it dynamically casts out the `FilesystemStore` at startup and talks to it directly (ie: bypass the Store interface).

I guess, for simplicity, lets remove this and we can add it back in if we ever find it is a bottleneck.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633)* status: 1 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`nativelink-config/src/stores.rs` line 262 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/633#-Np5dYXo5O_bbh3zZg73:-Np5vTce4tlWCYLywg84:b5c6qsd) ([raw file](https://github.com/TraceMachina/nativelink/blob/045e5c2557afbd0a212dc621e962088889e2026d/nativelink-config/src/stores.rs#L262)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

From my understanding here's the breakdown of what components would ever call what:

Stores:
* ActionCache should be wrapped in `CompletenessCheckingStore` or else it can serve references to evicted items.
* CAS should be wrapped in `ExistenceCacheStore` and possibly `FastSlowStore`, for dramatic efficiency gains.

Scheduler:
* IIRC, scheduler doesn't actually need a store, unless it wants to extract details out about the job

Workers:
* Only ever calls `.get` & `.update` on CAS, never calls `.has`
* Always requires a `FastSlowStore(fast: FilesystemStore, slow: *)`, but it dynamically casts out the `FilesystemStore` at startup and talks to it directly (ie: bypass the Store interface).

I guess, for simplicity, lets remove this and we can add it back in if we ever find it is a bottleneck.
</blockquote></details>

Cool, I'll update to ignore the fast store then.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633#-:-Np66rJj5DvpWC4XiP3o:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633#-:-Np6LUH-Ev5bQ-NJn78n:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Review by adam-singer — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/633)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
