### PR TITLE
Fix clippy::semicolon_if_nothing_returned

### PR DESCRIPTION
**Pull request by SchahinRohani**
## How Has This Been Tested?

`bazel test ...`

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1393)

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1393#-:-O8PIKUW2wy0xxSa_6Bs:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1199 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1393#-O8PI-Au9WBUp7duD4-g:-O8PI-Au9WBUp7duD4-h:b2ni8l0) ([raw file](https://github.com/TraceMachina/nativelink/blob/0534047578fdd32208f9f1b24cdecb36c1a4a0d4/nativelink-worker/src/running_actions_manager.rs#L1199)):*
> ```XML
>                     OutputType::DirectorySymlink(output_symlink) => {
>                         output_directory_symlinks.push(output_symlink);
>                     }
> ```

nit



_Suggestion:_
```XML
                    OutputType::FileSymlink(output_symlink) =>
                        output_file_symlinks.push(output_symlink),
                    OutputType::DirectorySymlink(output_symlink) =>
                        output_directory_symlinks.push(output_symlink),
```

**Review by SchahinRohani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1393)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1199 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1393#-O8PI-Au9WBUp7duD4-g:-O8XD6qv4eNVJtwJSVYy:b-nxuozy) ([raw file](https://github.com/TraceMachina/nativelink/blob/0534047578fdd32208f9f1b24cdecb36c1a4a0d4/nativelink-worker/src/running_actions_manager.rs#L1199)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit
</blockquote></details>

`cargo fmt` formats it like this:

```
OutputType::DirectorySymlink(output_symlink) => {
    output_directory_symlinks.push(output_symlink);
}
```

So i guess the current formatting follows the standard Rust conventions.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1393#-:-O8ZYpfJC29qxUyUD5Qu:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Review by adam-singer — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1393#-:-O8bjCJO73Ngnal_9HfP:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
