### PR TITLE
Make quantity field human readable

### LINKED ISSUE #862: Quantity fields should be human-readable
Instead of this:

```json
"eviction_policy": {
  // 50mb.
  "max_bytes": 50000000,
}
```

We could have this which seems more readable and is standardized in the [Kubernetes Quantity format](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/#Quantity):

```json
"eviction_policy": {
  "max_bytes": "50Mi",
}
```

### PR DESCRIPTION
**Pull request by matdexir**
# Description

Allows for human readable quantity field in the different json config, i.e, 10KB -> 10000.
This implementation still allows for the field being pure unsigned integers, so, it can be seen as offering an alternative configuration

Fixes #862 

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I tested it on a stripped version of [basic_cas.json](https://github.com/TraceMachina/nativelink/blob/main/nativelink-config/examples/basic_cas.json) which allows for writing human readable units rather than large integer values.

## Checklist

- [ ] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NwXjM586RUGkfgagcGu:b-ucfknh)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-config/src/serde_utils.rs` line 54 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NwXj1i7E0RtIEkXNZm2:-NwXj1i7E0RtIEkXNZm3:b-133aph) ([raw file](https://github.com/TraceMachina/nativelink/blob/bd1896946c6520b4b6ad4bd90e7da1853914b70a/nativelink-config/src/serde_utils.rs#L54)):*
> ```XML
>         fn visit_str<E: de::Error>(self, mut v: &str) -> Result<Self::Value, E> {
>             println!("We're supposed to be here {}", v);
>             match v.chars().last().unwrap() {
> ```

I think we should make a new functions for these, like: `convert_duration_with_shellexpand` and `convert_data_size_with_shellexpand`

**Comment by matdexir** [comment]
Hi @allada,
Is there a specific test suite for this feature?

**Review by allada — COMMENTED** [review]
We don't have a test for this, but it'd be trivial to make one.

Pretty much it'd be to take this function (but change it so it passes in a string):
https://github.com/TraceMachina/nativelink/blob/c1d040277cfb7cbb252d57c07a427574ed314e92/src/bin/nativelink.rs#L808

And put it into `nativelink-config`, then a config like this should properly populate:
```json5
{
  "global": {
    "default_digest_size_health_check": "5mb"
  }
}
```

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-Nw_Q570-TdNT-UVEPhz:b2zfj1u)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-22.04, and 1 discussions need to be resolved

**Comment by matdexir** [comment]
I am currently trying to get `bazel test ...` to run but for some reasons it fails. Here are the relevant logs:
```
ERROR: /home/matdexir/Files/Projects/nativelink/nativelink-config/BUILD.bazel:9:13: Rustfmt nativelink-config/nativelink-config.rustfmt.ok failed: (Exit 1): process_wrapper failed: error executing Rustfmt command (from target //nativelink-config:nativelink-config) bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/rules_rust~0.42.1/util/process_wrapper/process_wrapper --touch-file bazel-out/k8-fastbuild/bin/nativelink-config/nativelink-config.rustfmt.ok -- ... (remaining 11 arguments skipped)
Diff in /tmp/nativelink/work/508fecf4260be788cf6e32983d75215d677579d6b11cb2bc2d23db421ee8cfb8/work/nativelink-config/src/serde_utils.rs at line 12:
 // See the License for the specific language governing permissions and
 // limitations under the License.

-use byte_unit::Byte;
-use humantime::parse_duration;
 use std::fmt;
 use std::marker::PhantomData;
 use std::str::FromStr;
Diff in /tmp/nativelink/work/508fecf4260be788cf6e32983d75215d677579d6b11cb2bc2d23db421ee8cfb8/work/nativelink-config/src/serde_utils.rs at line 20:

+use byte_unit::Byte;
+use humantime::parse_duration;
 use serde::{de, Deserialize, Deserializer};
```
I am not too sure what this means since it looks fine to my human eye. Maybe I forgot to update some settings?

**Review by allada — COMMENTED** [review]
You need to run the formatter:
https://github.com/TraceMachina/nativelink/blob/main/CONTRIBUTING.md#fixing-rust-formatting

Looks great though! Maybe 1 test would be useful, but not required. I don't think we test the other fields here, so only do it if you want to learn how to write a new test.

> Reviewed 2 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NweF-Ij87M5_RVW17hu:bf5pplk)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-22.04, and 4 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NweGwnF2J3KNz51R6FY):*
nit: Please expand this comment out a bit more to explain what's being added.
___
*[`nativelink-config/src/serde_utils.rs` line 172 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NweGVel-09wukyvqJ6l:-NweGVel-09wukyvqJ6m:b-5gnu5h) ([raw file](https://github.com/TraceMachina/nativelink/blob/07f285e0bbadae94c3a3351853d2082e1782d849/nativelink-config/src/serde_utils.rs#L172)):*
> ```XML
> 
>         fn visit_str<E: de::Error>(self, v: &str) -> Result<Self::Value, E> {
>             let byte_size = Byte::parse_str(v, true).map_err(de::Error::custom);
> ```

nit: put question mark here instead of the line below.
___
*[`nativelink-config/src/serde_utils.rs` line 174 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NweFbHk1N95yFa0o96w:-NweFbHk1N95yFa0o96x:bgxvsna) ([raw file](https://github.com/TraceMachina/nativelink/blob/07f285e0bbadae94c3a3351853d2082e1782d849/nativelink-config/src/serde_utils.rs#L174)):*
> ```XML
>             let byte_size = Byte::parse_str(v, true).map_err(de::Error::custom);
>             let byte_size_str = byte_size?.as_u64().to_string();
>             (*shellexpand::env(&byte_size_str).map_err(de::Error::custom)?)
> ```

This should be flipped around. Have it parse it from the `shellexpand`, then have it convert the `Byte::parse_str`. This will allow users to use environmental variables that contain things like `5mb` and it'll expand properly.
___
*[`nativelink-config/src/serde_utils.rs` line 213 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NweGbgODg-2P4hBs1aN:-NweGbgODg-2P4hBs1aO:b-qx6bt) ([raw file](https://github.com/TraceMachina/nativelink/blob/07f285e0bbadae94c3a3351853d2082e1782d849/nativelink-config/src/serde_utils.rs#L213)):*
> ```XML
>             let duration = parse_duration(v).map_err(de::Error::custom);
>             let duration_str = duration?.as_secs().to_string();
>             (*shellexpand::env(&duration_str).map_err(de::Error::custom)?)
> ```

nit: ditto from above.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved

___
*[`nativelink-config/src/serde_utils.rs` line 174 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/891#-Nwjia8n7jpwY8BgaHmO:-Nwjia8o9RApc1HoGopK:b-p7m7d5) ([raw file](https://github.com/TraceMachina/nativelink/blob/050f837ef847df3a543358aea0f125a56453bbaa/nativelink-config/src/serde_utils.rs#L174)):*
> ```XML
>             let expanded = (*shellexpand::env(v).map_err(de::Error::custom)?).to_string();
>             let byte_size = Byte::parse_str(expanded, true).map_err(de::Error::custom)?;
>             let byte_size_str = byte_size.as_u64().to_string();
> ```

Just convert this to a `u128` then convert it directory into `Self::Value`.
___
*[`nativelink-config/src/serde_utils.rs` line 212 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NwjkGy_9R95F-ldsJNd:-NwjkGya7ZUQ0V4j7hpc:ba2d074) ([raw file](https://github.com/TraceMachina/nativelink/blob/050f837ef847df3a543358aea0f125a56453bbaa/nativelink-config/src/serde_utils.rs#L212)):*
> ```XML
>             let expanded = (*shellexpand::env(v).map_err(de::Error::custom)?).to_string();
>             let duration = parse_duration(&expanded).map_err(de::Error::custom)?;
>             let duration_str = duration.as_secs().to_string();
> ```

ditto, don't add `.to_string()`

**Review by allada — COMMENTED** [review]
Either is fine. It appears internally to that library it uses u128, which is why I suggested u128.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NwoxU3HE63QQFuSNr5g:bvxgmti)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved

___
*[`nativelink-config/tests/deserialization_test.rs` line 1 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NxA_4EO0X4voaw4Lhmr:-NxA_4EP9zmJx8ToU5Gz:bc4aqi5) ([raw file](https://github.com/TraceMachina/nativelink/blob/a30503b11fcf4be4c5d23dd2eb0099d125aaa5fa/nativelink-config/tests/deserialization_test.rs#L1)):*
> ```XML
> use nativelink_config::serde_utils::{
> ```

nit: Please add copyright header.
___
*[`nativelink-config/tests/deserialization_test.rs` line 6 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NxA_D9pEYgCDDazr_71:-NxA_D9pEYgCDDazr_72:b-acftzp) ([raw file](https://github.com/TraceMachina/nativelink/blob/a30503b11fcf4be4c5d23dd2eb0099d125aaa5fa/nativelink-config/tests/deserialization_test.rs#L6)):*
> ```XML
> 
> #[cfg(test)]
> mod tests {
> ```

nit: To simplify this test a bit, can I suggest instead just write dummy configs in the test with the annotations (like in the config rust files), then convert json5-string to the structs then just ensure the structs match a ground truth?

**Comment by matdexir** [comment]
I'm currently missing a test case for duration values. I haven't found any config files that could make use of duration units from [here](https://github.com/TraceMachina/nativelink/tree/main/nativelink-config/examples). Any idea on where I could get one?

**Review by allada — COMMENTED** [review]
I would instead just make the struct definition in the test file itself and decorate a few fields to test it. I would not test the config directly, that will create complex dependency issues.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NxDUYn_5KZWryWP-mtb:b-ccajf9)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved

**Review by adam-singer — COMMENTED** [review]
@

> Reviewed 3 of 4 files at r2, 2 of 4 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NwedXKK0QKrToGHF84b:b3krf)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 3 discussions need to be resolved

**Review by allada — APPROVED** [review]
Awesome! Thanks for the changes!

:lgtm: 

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NxO6nsf-s4ZIqydKKEI:b-7pjqei)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 1 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/891#-NxO9Y2v4BMlo_3-YnAs:-NxO9Y2w3gJXdHwKbw86:b-pyfnue) (no related file):*
It looks like there's some strange errors when building with bazel. Let me know if you need help figuring them out.

___

**Comment by matdexir** [comment]
That's odd :thinking:
It works all fine on my local machine. Could you give me a reproducible build with docker?

**Review by allada — COMMENTED** [review]
Are you building with bazel or cargo? I suggest trying with bazel.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NxZR4q_4dtEA9vMHZ8x:b-joefdu)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 1 discussions need to be resolved

**Review by aaronmondal — COMMENTED** [review]
@matdexir I believe the Bazel errors are because the Cargo lockfile wasn't regenerated. Bazel reads the lockfile at https://github.com/TraceMachina/nativelink/blob/64ed20a40964b8c606c7d65f76af840bcfc837fd/MODULE.bazel#L53 to determine which dependencies to fetch.

To re-sync the Cargo.toml files with the lockfile, try`cargo generate-lockfile`.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NxZrJiI-7RuuCyVb6g_:b-ghno3f)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, and 1 discussions need to be resolved

**Comment by MarcusSorealheis** [comment]
@matdexir do you need a hand further here?

**Comment by matdexir** [comment]
I think that it should be fixed now. I also have updated it to match the latest release. Let me know if the issue still lingers
Currently `nativelink-store` tests are failing but I am not too sure why since it should technically be out of scope for my current PR 

cc: @allada @aaronmondal @MarcusSorealheis

**Comment by MarcusSorealheis** [comment]
looks like you need to rebase @matdexir

**Comment by matdexir** [comment]
Already did
It should be up to date with https://github.com/TraceMachina/nativelink/commit/0a33c8399e38e9aeb1d76c41f0663d16e9f938ec

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891#-:-NzRCGMKD9k3iM0DZxbV:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

**Review by MarcusSorealheis — COMMENTED** [review]
> Dismissed @allada from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/891)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
