### PR TITLE
Add Operation State API

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description

Introduces nativelink-state and operation_state_manager API

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/937)

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
What a massive PR

**Comment by zbirenbaum** [comment]
> What a massive PR

It’s on top of a second one. Blaise wanted me to do it this way. #927 is the bulk of these changes

**Review by adam-singer — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/937)* status: 0 of 1 LGTMs obtained, and pending CI: windows-2022 / stable

**Review by allada — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/937)* status: 0 of 1 LGTMs obtained, and pending CI: windows-2022 / stable, and 3 discussions need to be resolved

___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/937#-Nz5NOHj9aGLeuLrIS8g):*
nit: Expand this.
___
*[`Cargo.toml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/937#-Nz5NWWU3IAZlhwY7TnC:-Nz5NWWU3IAZlhwY7TnD:bi7fqc2) ([raw file](https://github.com/TraceMachina/nativelink/blob/91ed36eb438313208c7198cc54528e8784679c94/Cargo.toml#L34)):*
> ```TOML
> nativelink-scheduler = { path = "nativelink-scheduler" }
> nativelink-service = { path = "nativelink-service" }
> nativelink-state = { path = "nativelink-state" }
> ```

nit: Don't make this it's own crate, put it under scheduler for now.
___
*[`nativelink-state/src/operation_state_manager.rs` line 43 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/937#-Nz5NgwV9suXvoQ4CxFo:-Nz5NgwV9suXvoQ4CxFp:bc3ytm9) ([raw file](https://github.com/TraceMachina/nativelink/blob/91ed36eb438313208c7198cc54528e8784679c94/nativelink-state/src/operation_state_manager.rs#L43)):*
> ```XML
> #[async_trait]
> pub trait ActionStateResult: Send + Sync + 'static {
>     async fn as_state(&self) -> Result<Arc<ActionState>, Error>;
> ```

nit: Add documentation to these.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/937)* status: 0 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`-- commits` line 16 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/937#-Nz5NOHj9aGLeuLrIS8g):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Expand this.
</blockquote></details>

Done.
___
*[`Cargo.toml` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/937#-Nz5NWWU3IAZlhwY7TnC:-Nz7TRRp8MweVw7vmO1W:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/91ed36eb438313208c7198cc54528e8784679c94/Cargo.toml#L34)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't make this it's own crate, put it under scheduler for now.
</blockquote></details>

Done.
___
*[`nativelink-state/src/operation_state_manager.rs` line 43 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/937#-Nz5NgwV9suXvoQ4CxFo:-Nz7TQV00efr-LwnxRXS:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/91ed36eb438313208c7198cc54528e8784679c94/nativelink-state/src/operation_state_manager.rs#L43)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Add documentation to these.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/937#-:-Nz9fc3j5D6yQhYXBnPO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
