### PR TITLE
Allow ByteStream write restart

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
# Description

The ByteStreamServer write was amended to enable resuming of sessions.  However, Reclient just starts from the begining again.  This would be fine, except we expect it to resume.  Add in a check to see if the first message is the beginning (i.e. its write_offset is zero) and then force a new IdleStream to be created for it.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Reclient build testing.

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/635)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer This one might be a good one for you to sink your teeth into.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/635#-:-Np5mCpJ0iWscX-kLJlq:b-x9qdn5)* status: 0 of 1 LGTMs obtained (waiting on @adam-singer)

**Review by adam-singer — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/635)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-service/src/bytestream_server.rs` line 406 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/635#-Np6isG33QOce0krg1xY:-Np6isG33QOce0krg1xZ:b1vk2gp) ([raw file](https://github.com/TraceMachina/nativelink/blob/11190f9ae03f1b30d509e396b7bd8bbfa0546c00/nativelink-service/src/bytestream_server.rs#L406)):*
> ```XML
>                 };
> 
>                 if write_request.write_offset < 0 {
> ```

Could we cover this case in the test set
___
*[`nativelink-service/src/bytestream_server.rs` line 431 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/635#-Np6glN10-T1IZkhA3qO:-Np6glN10-T1IZkhA3qP:bx1e9on) ([raw file](https://github.com/TraceMachina/nativelink/blob/11190f9ae03f1b30d509e396b7bd8bbfa0546c00/nativelink-service/src/bytestream_server.rs#L431)):*
> ```XML
>                         .slice((tx.get_bytes_written() - write_offset) as usize..)
>                 } else {
>                     if write_offset != tx.get_bytes_written() {
> ```

Can we introduce a test that falls into this case? If I'm understanding the tests correctly we can make test requests have a larger value  for `write_request.write_offset` and end up in this condition, it doesn't seem like the exist test set does fall into this case, if there is cover for it. please ignore

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/635)* status: 0 of 1 LGTMs obtained (waiting on @adam-singer)

___
*[`nativelink-service/src/bytestream_server.rs` line 406 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/635#-Np6isG33QOce0krg1xY:-NpJd0Pp2OxhrFrcPhvb:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/11190f9ae03f1b30d509e396b7bd8bbfa0546c00/nativelink-service/src/bytestream_server.rs#L406)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Could we cover this case in the test set
</blockquote></details>

Done.
___
*[`nativelink-service/src/bytestream_server.rs` line 431 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/635#-Np6glN10-T1IZkhA3qO:-NpJdi2dCqfPvqS2KjBW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/11190f9ae03f1b30d509e396b7bd8bbfa0546c00/nativelink-service/src/bytestream_server.rs#L431)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can we introduce a test that falls into this case? If I'm understanding the tests correctly we can make test requests have a larger value  for `write_request.write_offset` and end up in this condition, it doesn't seem like the exist test set does fall into this case, if there is cover for it. please ignore
</blockquote></details>

Done.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/635#-:-NpLoE7Q-MrR8xWZ75mC:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
