### PR TITLE
Make de/serialized structs compliant with Rust naming practices

### PR DESCRIPTION
**Pull request by caass**
# Description

Rather than using lowercase names for types, we can annotate structs and enums with `serde(rename_all = "snake_case")` to have serde rename things during de/serialization. That way, the code has Rust-style names in the source tree, but the serialized variants remain snake_cased.

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

`bazel test //...` passed

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271)

### CODE REVIEW

**Review by caass — COMMENTED** [review]
I know this passed all the existing tests, but I kind of feel like we should have a serialization test suite. But then again, I also feel like configs should live alongside the things they configure, so maybe that should happen first.

+@adam-singer +@aaronmondal +@allada 

> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-:-O4rdR2n4SnoItbGCOm1:bp0wi22)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal, @adam-singer, and @allada)

**Review by caass — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271)* status: 0 of 3 LGTMs obtained, and all files reviewed, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal, @adam-singer, and @allada)

**Review by allada — CHANGES_REQUESTED** [review]
These configs should be thought of as interfaces. We do not allow any code (other than serde-decorators) inside this crate because it is designed to be logic-less. It could easily cause difficult to manage circular dependencies if we allowed configs to live next to the thing they config. It would also make it near impossible for a user to know what the options of the config are, since they would have to navigate a unknown amount of files. I agree it feels easier to have the config near the thing it configures from the point of view of a person developing nativelink... but from the point of view of someone actually using the config, they definitely don't want to look at the code, they just want the config.

:lgtm: 

> Reviewed 29 of 30 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-:-O4rveMl9zUqG1fxb3Wv:bym4p1u)* status: 1 of 3 LGTMs obtained, and all files reviewed, and 2 discussions need to be resolved (waiting on @aaronmondal and @adam-singer)

___
*[`nativelink-config/src/stores.rs` line 353 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-O4rv07X3hbxlebc9F2p:-O4rv07X3hbxlebc9F2q:b-ge8wxh) ([raw file](https://github.com/TraceMachina/nativelink/blob/b06cca2973f3c370cc23af6f297a2fc6e5e3027d/nativelink-config/src/stores.rs#L353)):*
> ```XML
>     ///
>     #[serde(rename = "ref_store")]
>     Ref(RefStore),
> ```

Lets just call this `RefStore`.
___
*[`nativelink-config/src/stores.rs` line 422 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-O4rv7O7194Dw5eZJrJ8:-O4rv7O7194Dw5eZJrJ9:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/b06cca2973f3c370cc23af6f297a2fc6e5e3027d/nativelink-config/src/stores.rs#L422)):*
> ```XML
>     ///
>     #[serde(rename = "redis_store")]
>     Redis(RedisStore),
> ```

ditto.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-:-O4rypu5EOggmZ80fX65:bnfp4nl)* status: 2 of 3 LGTMs obtained, and all files reviewed, and 2 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-config/src/stores.rs` line 353 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-O4rv07X3hbxlebc9F2p:-O4ryLs6A3JkYfBIU_xS:b-oboipy) ([raw file](https://github.com/TraceMachina/nativelink/blob/b06cca2973f3c370cc23af6f297a2fc6e5e3027d/nativelink-config/src/stores.rs#L353)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets just call this `RefStore`.
</blockquote></details>

I disagree, since `Ref` is the more consistent naming scheme :bike: :hut: :dancer: :man_dancing:
___
*[`nativelink-config/src/stores.rs` line 422 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-O4rv7O7194Dw5eZJrJ8:-O4rybrD139z_Trsx_Dc:b7ukg2r) ([raw file](https://github.com/TraceMachina/nativelink/blob/b06cca2973f3c370cc23af6f297a2fc6e5e3027d/nativelink-config/src/stores.rs#L422)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Vote :bike: :hut:

**Review by caass — COMMENTED** [review]
> I agree it feels easier to have the config near the thing it configures from the point of view of a person developing nativelink... but from the point of view of someone actually using the config, they definitely don't want to look at the code, they just want the config.

I think there's a world where we do some more rustdoc AST magic to get this working, but point taken -- that world is far away from now.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-:-O4sDPMS1SKus-olh8wE:b-ilbdsq)* status: 2 of 3 LGTMs obtained, and all files reviewed, and 2 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-config/src/stores.rs` line 353 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-O4rv07X3hbxlebc9F2p:-O4sDgCL2u1DoIWLNjHP:boelfbe) ([raw file](https://github.com/TraceMachina/nativelink/blob/b06cca2973f3c370cc23af6f297a2fc6e5e3027d/nativelink-config/src/stores.rs#L353)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I disagree, since `Ref` is the more consistent naming scheme :bike: :hut: :dancer: :man_dancing:
</blockquote></details>

@aaronmondal that was my thinking as well. I didn't want to make any breaking changes so I kept it renamed, but yes -- the other stores don't have `Store` in the name either in serialized form or source form. @allada I'll hold off on merging until you give a final :+1: / :-1: on this.

**Review by allada — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271)* status: 2 of 3 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-config/src/stores.rs` line 353 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-O4rv07X3hbxlebc9F2p:-O4ztQPo5yN8AMU8qJsj:b-4kx5wz) ([raw file](https://github.com/TraceMachina/nativelink/blob/b06cca2973f3c370cc23af6f297a2fc6e5e3027d/nativelink-config/src/stores.rs#L353)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

@aaronmondal that was my thinking as well. I didn't want to make any breaking changes so I kept it renamed, but yes -- the other stores don't have `Store` in the name either in serialized form or source form. @allada I'll hold off on merging until you give a final :+1: / :-1: on this.
</blockquote></details>

Nothing in this PR is breaking changes. I was arguing that we are not consistent and I'd rather not use `serde(rename)` at all and instead make breaking changes in a future PR to remove `Store` and other redundant names to be consistent.

As it is now, we are breaking consistency between the names and the configs forcing people to look for `rename` fields to figure out how they are being remapped.

I'm not going to block on this, but not making it `RefStore` is making the code less consistent.

**Review by caass — COMMENTED** [review]
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1271#-:-O4zvHy_ATAjPELEN1ps:b-sd1e3m)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

**Pull request merged**
