### PR TITLE
redis client state

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description
Adds RedisStore based implementation for ClientStateManager trait.
Provides API hooks for adding or filtering Operations.

Requires #1020

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1021)

### CODE REVIEW

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1021)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 2 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 291 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1021#-O-j8S0H9zvbzkIP0fvR:-O-lXzus2gfJCLeWt3El:bpk9x2q) ([raw file](https://github.com/TraceMachina/nativelink/blob/ff55b63aef6ea7d260941085c4ad69b668a02930/nativelink-scheduler/src/redis_operation_state.rs#L291)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Will the value of `s` be included in this map error so we can see what that value is in logs?
</blockquote></details>

That would be ideal but I couldn't figure out how to specify a bound that `V::Error` implements `to_string()` maybe @allada or @caass know how?

Keep in mind this is just a temp function until the actual list api is implemented for the redis store. 
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 312 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1021#-O-j8fhS5nxhW-aEuTZv:-O-lYo6f1SPmVj2MJDBw:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ff55b63aef6ea7d260941085c4ad69b668a02930/nativelink-scheduler/src/redis_operation_state.rs#L312)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

might seem pedantic but should we have small functions that return constructed strings instead of inlining the strings

```
fn build_action_key(hash_key) ->String;
fn build_operations_key(operation) -> String;
etc..
```

Ideally those things are defined in single location but referenced only by code
</blockquote></details>

Done.

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1021)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

**Review by caass — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1021)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 291 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1021#-O-j8S0H9zvbzkIP0fvR:-O-mNytt02EzEUURPBCg:bpzugb) ([raw file](https://github.com/TraceMachina/nativelink/blob/ff55b63aef6ea7d260941085c4ad69b668a02930/nativelink-scheduler/src/redis_operation_state.rs#L291)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

That would be ideal but I couldn't figure out how to specify a bound that `V::Error` implements `to_string()` maybe @allada or @caass know how?

Keep in mind this is just a temp function until the actual list api is implemented for the redis store.
</blockquote></details>

Oh oh I know this one !! `to_string` is part of the [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) trait. The code's shifted around a little bit since this comment was made so I can't offer help specifically around specifying bounds :cry:

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1021)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 291 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1021#-O-j8S0H9zvbzkIP0fvR:-O-mgUQcC-xX3CakGG9X:bhkvjbh) ([raw file](https://github.com/TraceMachina/nativelink/blob/ff55b63aef6ea7d260941085c4ad69b668a02930/nativelink-scheduler/src/redis_operation_state.rs#L291)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Oh oh I know this one !! `to_string` is part of the [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) trait. The code's shifted around a little bit since this comment was made so I can't offer help specifically around specifying bounds :cry:
</blockquote></details>

I figured it out! I got confused because I was trying to do `V::Error: Display` in the `where` clause but it's actually `V::Err: Display`

For pretty much any other trait it would have been `V::Error` since you normally do something like:
```
impl TryFrom<RedisOperation> for ActionState {
    type Error = Error;
```

But for FromString its:
```
impl FromStr for RedisOperation {
    type Err = Error;
```

**Comment by zbirenbaum** [comment]
Changes merged in #1023

**Pull request closed without merging**
