### PR TITLE
Improve debugging on some error messages

### PR DESCRIPTION
**Pull request by allada**
In debugging Scheduler errors when developing the Redis scheduler,
adding these messages to the hints helped find the bugs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313#-:-O5oANlDAhKXTpQ2Qf-g:b-bn1n1c)* status: 0 of 1 LGTMs obtained, and 0 of 27 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer)

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313)* status: 0 of 1 LGTMs obtained, and 2 of 27 files reviewed

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313#-:-O5sripY6KeAMdcrcQPa:bnfp4nl)* status: 2 of 2 LGTMs obtained, and 4 of 27 files reviewed

**Review by adam-singer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313#-:-O5vNkJ14E1RP9nNIpYM:bnfp4nl)* status: 1 of 1 LGTMs obtained, and 4 of 27 files reviewed

**Review by adam-singer — APPROVED** [review]
> Reviewed 2 of 6 files at r3, 2 of 4 files at r4, 6 of 11 files at r7, 9 of 13 files at r8, 2 of 4 files at r9, 2 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 4 files at r10, 24 of 24 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1313)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
