### PR TITLE
Cleanup hash functions to be more idomatic

### PR DESCRIPTION
**Pull request by allada**
Minor change to cleanup the way we deal with the hashing functions to be flexible and easier to work with.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691#-:-Ns-zD2D1GiE9UCrZ4dr:b-gyszd7)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @zbirenbaum)

**Comment by zbirenbaum** [comment]
There was one change to an import I wasn't sure about since it looks like all usages reference the more specific one there prior, but otherwise looks good

**Review by zbirenbaum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04

___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 27 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0FdpBEyHKHB-XeRqg:-Ns0FdpC-ZcziuuBSD_B:b-b897ak) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-store/tests/completeness_checking_store_test.rs#L27)):*
> ```XML
> use nativelink_store::memory_store::MemoryStore;
> use nativelink_util::common::DigestInfo;
> use nativelink_util::digest_hasher::DigestHasherFunc::Blake3;
> ```

Keep this
___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 77 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0FPglAQuU1qCfBVHt:-Ns0FPglAQuU1qCfBVHu:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/26d3984b17a91c2528b6089efbfaf7769b1f52cf/nativelink-store/tests/completeness_checking_store_test.rs#L77)):*
> ```XML
> 
>         let tree_digest =
>             serialize_and_upload_message(&tree, pinned_cas, &mut DigestHasherFunc::Blake3.hasher()).await?;
> ```





_Code snippet:_
```XML
&mut Blake3.hasher()
```
___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 84 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0Fa2hAlScwgIxVEz2:-Ns0Fa2hAlScwgIxVEz3:bwmwsdv) ([raw file](https://github.com/TraceMachina/nativelink/blob/26d3984b17a91c2528b6089efbfaf7769b1f52cf/nativelink-store/tests/completeness_checking_store_test.rs#L84)):*
> ```XML
>         };
> 
>         serialize_and_upload_message(&output_directory, pinned_cas, &mut DigestHasherFunc::Blake3.hasher()).await?;
> ```

&mut Blake3.hasher()
___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 99 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0Fb-x5lv3337_qv_U:-Ns0Fb-x5lv3337_qv_V:bwmwsdv) ([raw file](https://github.com/TraceMachina/nativelink/blob/26d3984b17a91c2528b6089efbfaf7769b1f52cf/nativelink-store/tests/completeness_checking_store_test.rs#L99)):*
> ```XML
>         // The structure of the action result is not following the spec, but is simplified for testing purposes.
>         let action_result_digest =
>             serialize_and_upload_message(&action_result, pinned_ac, &mut DigestHasherFunc::Blake3.hasher()).await?;
> ```

&mut Blake3.hasher()

**Review by zbirenbaum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04

___
*[`nativelink-util/src/digest_hasher.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0J7MQDLxP9rJ_yLzO:-Ns0J7MQDLxP9rJ_yLzP:bgyvl4d) ([raw file](https://github.com/TraceMachina/nativelink/blob/26d3984b17a91c2528b6089efbfaf7769b1f52cf/nativelink-util/src/digest_hasher.rs#L114)):*
> ```XML
> pub trait DigestHasher {
>     /// Update the hasher with some additional data.
>     fn update(&mut self, input: &[u8]);
> ```

u8 isn't long enough

**Review by zbirenbaum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04

___
*[`nativelink-util/src/digest_hasher.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0J7MQDLxP9rJ_yLzO:-Ns0KBMK6yfWrZEb3xME:bvvf5fc) ([raw file](https://github.com/TraceMachina/nativelink/blob/26d3984b17a91c2528b6089efbfaf7769b1f52cf/nativelink-util/src/digest_hasher.rs#L114)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

u8 isn't long enough
</blockquote></details>

Sorry misread this. It's fine
___
*[`nativelink-worker/src/running_actions_manager.rs` line 1048 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0MXSI95-gwWpuZoWX:-Ns0MXSI95-gwWpuZoWY:bple2d9) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-worker/src/running_actions_manager.rs#L1048)):*
> ```XML
>             let data = execution_result.stderr;
>             let digest = compute_buf_digest(&data, &mut hasher.into())
>                 .await
> ```

It doesn't look like this function was changed, so why was the await and error handling removed

**Review by zbirenbaum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1038 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0Mv6Y03aQjYBxqYpy:-Ns0Mv6Y03aQjYBxqYpz:bqujbyh) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-worker/src/running_actions_manager.rs#L1038)):*
> ```XML
>             let data = execution_result.stdout;
>             let digest = compute_buf_digest(&data, &mut hasher.into())
>                 .await
> ```

Here too

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04 (waiting on @zbirenbaum)

___
*[`nativelink-util/src/digest_hasher.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0J7MQDLxP9rJ_yLzO:-Ns0MP_s-7DK0hMtIxfP:b-1qfgmf) ([raw file](https://github.com/TraceMachina/nativelink/blob/26d3984b17a91c2528b6089efbfaf7769b1f52cf/nativelink-util/src/digest_hasher.rs#L114)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Sorry misread this. It's fine
</blockquote></details>

This is a slice of `u8`'s. Any data of any size can be represented this way.

This is also the standard "arbitrary data" type in rust.

Example: https://docs.rs/sha2/latest/sha2/trait.Digest.html#tymethod.update

We could use `AsRef<[u8]>`, which is the exact same as we have here, but the template version.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04 (waiting on @zbirenbaum)

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1048 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0MXSI95-gwWpuZoWX:-Ns0N2WXDfxuM9Kw7AzC:b-1ol2ml) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-worker/src/running_actions_manager.rs#L1048)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

It doesn't look like this function was changed, so why was the await and error handling removed
</blockquote></details>

Because this function is no longer `async`.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04 (waiting on @zbirenbaum)

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1048 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0MXSI95-gwWpuZoWX:-Ns0NE4cCwMyXEcoTgDG:b-wsym28) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-worker/src/running_actions_manager.rs#L1048)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Because this function is no longer `async`.
</blockquote></details>

Also, it can no longer error any more.

**Review by zbirenbaum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04

___
*[`nativelink-worker/src/running_actions_manager.rs` line 1048 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0MXSI95-gwWpuZoWX:-Ns0NOtiA59KDIFlrSJo:bszvpkb) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-worker/src/running_actions_manager.rs#L1048)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Also, it can no longer error any more.
</blockquote></details>

Got it, I didn't see that change made in this PR so wasn't sure. LGTM then after the import thing is fixed

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04 (waiting on @zbirenbaum)

___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 27 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0FdpBEyHKHB-XeRqg:-Ns0NyRKAvp67XN8CtI-:b-abw5ej) ([raw file](https://github.com/TraceMachina/nativelink/blob/6491fc76f5ea3ec8b6a70694694afdfae92f72fa/nativelink-store/tests/completeness_checking_store_test.rs#L27)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Keep this
</blockquote></details>

I did this because all other files do it this way. When there are different enum structs that have the same keys, i prefer to be verbose. In this case sometimes there's:
`ProtoDigestFunction::Blake3` and `DigestHasherFunc::Blake3`

Depending on if the data being referenced is the protobuf version our local version.

On top of it all `Blake3` is a type in the blake3 crate.

**Review by zbirenbaum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 0 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, publish-image, vale, zig-cc ubuntu-20.04

___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 27 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0FdpBEyHKHB-XeRqg:-Ns0Oyt8AR6Q-GxiHl3n:btn461w) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9029bb073a2d56d1a2b713fdb7d6ff4de69ff64/nativelink-store/tests/completeness_checking_store_test.rs#L27)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I did this because all other files do it this way. When there are different enum structs that have the same keys, i prefer to be verbose. In this case sometimes there's:
`ProtoDigestFunction::Blake3` and `DigestHasherFunc::Blake3`

Depending on if the data being referenced is the protobuf version our local version.

On top of it all `Blake3` is a type in the blake3 crate.
</blockquote></details>

Got it

**Review by zbirenbaum — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691#-:-Ns0VTfE4jK51tKvDb5o:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 1 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 27 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0FdpBEyHKHB-XeRqg:-Ns0Xa3W6gVDu_4Iusb5:b-g56538) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9029bb073a2d56d1a2b713fdb7d6ff4de69ff64/nativelink-store/tests/completeness_checking_store_test.rs#L27)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Got it
</blockquote></details>

I think `ProtoDigestFunction` is a private enum, and under the hood it uses TryInto to convert `Self::Blake3` and `Self::SHA256` to the `DigestHasherFunc` types from a generic Value. Do we need to do this specification if we are only importing from DigestHasherFunc and that enum uses the same underlying type?

**Review by zbirenbaum — APPROVED** [review]
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 1 of 1 LGTMs obtained

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-store/tests/completeness_checking_store_test.rs` line 27 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/691#-Ns0FdpBEyHKHB-XeRqg:-Ns0otDL22flm_gBln5c:bqepber) ([raw file](https://github.com/TraceMachina/nativelink/blob/b9029bb073a2d56d1a2b713fdb7d6ff4de69ff64/nativelink-store/tests/completeness_checking_store_test.rs#L27)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

I think `ProtoDigestFunction` is a private enum, and under the hood it uses TryInto to convert Self::Blake3 and Self::SHA256 to the `DigestHasherFunc` types from a Value. Do we need to do this generalization if we are only importing from DigestHasherFunc?
</blockquote></details>

It's more about consistency. People tend to copy-pasta stuff around and I'd rather be consistent first and foremost.

**Review by zbirenbaum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/691)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
