### PR TITLE
[Breaking] Digest function now auto-detected from request (#899)

### PR DESCRIPTION
**Pull request by nfarah86**
# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)
#770 

## Type of change
Kickstarting the glossary

Please delete options that aren't relevant.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/928)

### CODE REVIEW

**Comment by nfarah86** [comment]
@MarcusSorealheis This is the first stab at the glossary. Let me know if you have feedback.

**Comment by nfarah86** [comment]
I don't know why there are 36 file changes here-  I only committed 2. I'm not sure how these changes came about.

**Comment by nfarah86** [comment]
> You need to rebase. You were on a non main branch or maim that was behind

weird-  I rebased the main branch before creating a new branch. That's why I was confused. Should be fixed now.

**Comment by MarcusSorealheis** [comment]
This branch is unclean.

**Comment by MarcusSorealheis** [comment]
@nfarah86 Check this out.

**Pull request closed without merging**
