### PR TITLE
Rename cas CompressionAlgorithm to HttpCompressionAlgorithm

### LINKED ISSUE #1049: Use distinct names for CompressionAlgorithm enums
At the moment we have two:

https://github.com/TraceMachina/nativelink/blob/97abbcd24b4f87f500f6ab2d9898b4a8401d9f3b/nativelink-config/src/stores.rs#L669-L680

https://github.com/TraceMachina/nativelink/blob/97abbcd24b4f87f500f6ab2d9898b4a8401d9f3b/nativelink-config/src/cas_server.rs#L35-L44

This confuses doc generators and introduces unnecessary complexity. We should unify them to a single `CompressionAlgorithm` and handle unsupported cases in consumers.

*Edit:* From the conversation it seems like the easiest short-term fix is to just give the two different enums distinct names.

### PR DESCRIPTION
**Pull request by aaronmondal**
This disambiguates it from `stores::CompressionAlgorithm`.

Fixes #1049

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@caass +@allada +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-:-O0AdqIN5gJ0Au6iT8VQ:b5k3baq)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, and @caass)

**Review by adam-singer — COMMENTED** [review]
This would be considered a breaking change on the config? 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-:-O0AlxeP6lSXtCwJmF-A:b-ac58s2)* status: 0 of 3 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14 (waiting on @allada and @caass)

**Review by aaronmondal — COMMENTED** [review]
@adam-singer I believe only field name changes would be breaking, i.e. if we changed `compression`, `send_compression_algorithm`, or `accepted_compression_algorithms`.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-:-O0AregN9OG345xm8iTh:b-qk2m4j)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @caass)

**Review by caass — CHANGES_REQUESTED** [review]
Just would love you to quickly drive-by update the config struct we touch here to use `#[serde(rename_all)]` instead of `#[clippy::allow(non_camel_case)]`

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-:-O0FDChn5-UXNftFoQXF:b-tnls0p)* status: 0 of 3 LGTMs obtained, and 2 discussions need to be resolved (waiting on @adam-singer, @allada, and @caass)

___
*[`nativelink-config/src/cas_server.rs` line 35 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-O0FCmPJEv6f8cIfP-4T:-O0FCmPJEv6f8cIfP-4U:b-h63q3a) ([raw file](https://github.com/TraceMachina/nativelink/blob/e5bd8ab2529ad11875ab87a0de3b2211b7625ab7/nativelink-config/src/cas_server.rs#L35)):*
> ```XML
> pub type InstanceName = String;
> 
> #[allow(non_camel_case_types)]
> ```

Can you remove this and instead use `#[serde(rename_all = "lowercase")] or `#[serde(rename_all = "lowerCamelCase")]` or whichever you prefer? That way we can use proper-looking rust types but de/serialize to lowercase.
___
*[`nativelink-config/src/cas_server.rs` line 64 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-O0FCST84deb2-ZUpw5G:-O0FCST84deb2-ZUpw5H:b-av1tlz) ([raw file](https://github.com/TraceMachina/nativelink/blob/e5bd8ab2529ad11875ab87a0de3b2211b7625ab7/nativelink-config/src/cas_server.rs#L64)):*
> ```XML
>     /// see: <https://github.com/tracemachina/nativelink/issues/109>
>     ///
>     /// Default: `HttpCompressionAlgorithm::none`
> ```

Nit: I actually don't think this is true? It would be `None::<HttpCompressionAlgorithm>`, which is semantically distinct from `HttpCompressionAlgorithm::none`.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052)* status: 0 of 3 LGTMs obtained, and 2 discussions need to be resolved (waiting on @adam-singer and @caass)

___
*[`nativelink-config/src/cas_server.rs` line 35 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-O0FCmPJEv6f8cIfP-4T:-O0FNLdm2kbYZuFETuOF:bn7y038) ([raw file](https://github.com/TraceMachina/nativelink/blob/e5bd8ab2529ad11875ab87a0de3b2211b7625ab7/nativelink-config/src/cas_server.rs#L35)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Can you remove this and instead use `#[serde(rename_all = "lowercase")] or `#[serde(rename_all = "lowerCamelCase")]` or whichever you prefer? That way we can use proper-looking rust types but de/serialize to lowercase.
</blockquote></details>

Lets break this into a ticket and do it separate. I have some concerns with doing that where it will be confusing to the user on why the json takes `none`, but the config says it's `None`. This is one of the things I really hate about go.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052)* status: 1 of 3 LGTMs obtained, and 1 discussions need to be resolved (waiting on @adam-singer and @caass)

___
*[`nativelink-config/src/cas_server.rs` line 35 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-O0FCmPJEv6f8cIfP-4T:-O0GNwyW1C3t6WaUx9Mu:b-f33enc) ([raw file](https://github.com/TraceMachina/nativelink/blob/e5bd8ab2529ad11875ab87a0de3b2211b7625ab7/nativelink-config/src/cas_server.rs#L35)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets break this into a ticket and do it separate. I have some concerns with doing that where it will be confusing to the user on why the json takes `none`, but the config says it's `None`. This is one of the things I really hate about go.
</blockquote></details>

Done. Let's change this in another PR.

**Review by aaronmondal — COMMENTED** [review]
> Dismissed @caass from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052)* status: 1 of 3 LGTMs obtained (waiting on @adam-singer and @caass)

**Review by aaronmondal — COMMENTED** [review]
> Just would love you to quickly drive-by update the config struct we touch here to use `#[serde(rename_all)]` instead of `#[clippy::allow(non_camel_case)]`

Sounds good. Let's do this globally for all the configs.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-:-O0GOKl451x890NYrVgL:b-savbh2)* status: 1 of 3 LGTMs obtained (waiting on @adam-singer and @caass)

**Review by aaronmondal — COMMENTED** [review]
-@adam-singer -@caass 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1052#-:-O0GOYtf3akyNzmaZeuA:b-kl76ky)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
