### PR TITLE
Add OSFamily property to deployment examples

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@MarcusSorealheis +@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512#-:-Nm-i6GX0BA7dWaFi_tY:b-3thtw4)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @allada and @MarcusSorealheis)

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512#-:-Nm09BuPCZK4xTL3HdEy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by allada — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512)* status: all files reviewed, 2 unresolved discussions (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`deployment-examples/terraform/AWS/scripts/scheduler.json` line 114 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/512#-Nm0AhQtDJAnvMHDwNeZ:-Nm0AhQtDJAnvMHDwNe_:b-m9tzr9) ([raw file](https://github.com/TraceMachina/nativelink/blob/df6f5b94fcc111c66b1f36e7626fd0c7326bcb57/deployment-examples/terraform/AWS/scripts/scheduler.json#L114)):*
> ```JSON
>         "supported_platform_properties": {
>           "cpu_count": "minimum",
>           "cpu_arch": "exact",
> ```

nit: change this back.
___
*[`deployment-examples/terraform/AWS/scripts/scheduler.json` line 116 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/512#-Nm0Aixl3xDSHBfmiMNq:-Nm0Aixl3xDSHBfmiMNr:b-s5xe91) ([raw file](https://github.com/TraceMachina/nativelink/blob/df6f5b94fcc111c66b1f36e7626fd0c7326bcb57/deployment-examples/terraform/AWS/scripts/scheduler.json#L116)):*
> ```JSON
>           "cpu_arch": "exact",
>           "memory_kb": "minimum",
>           "kernel_version": "exact",
> ```

nit: Change this back.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronmondal and @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/512#-Nm0P-Z1C9ErQPdu17o1:-Nm0P-Z1C9ErQPdu17o2:bcxa5px) (no related file):*
Need to add the same config to `worker.json`

___

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512)* status: all files reviewed, 3 unresolved discussions (waiting on @aaronmondal and @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/512#-Nm0P-Z1C9ErQPdu17o1:-Nm2-eLa0Dylhx46Qv_o:b-6s2h2n) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Need to add the same config to `worker.json`
</blockquote></details>

you may need to make it lower case. I don't remember, but it's possible that the case matters.

___

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @allada and @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/512#-Nm0P-Z1C9ErQPdu17o1:-Nm2QnbT8ByHuqzusDrs:b-896fix) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

you may need to make it lower case. I don't remember, but it's possible that the case matters.
</blockquote></details>

Done.

___

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512#-:-Nm2ZMsTEO5hVhnU4IZC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MarcusSorealheis)

**Review by allada — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Pull request merged**
