### PR TITLE
Add OpenSSF scorecard action

### PR DESCRIPTION
**Pull request by aaronmondal**
Ensure that we follow some security best practices.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/486)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@allada +@MarcusSorealheis +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/486#-:-NleCrmT1Xe30ojSz8Ih:btzlv6h)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @adam-singer, @allada, and @MarcusSorealheis)

**Comment by MarcusSorealheis** [comment]
Should this product some artifact or badge in our README

**Review by aaronmondal — COMMENTED** [review]
> Should this product some artifact or badge in our README

This action only runs the checks. The actual badge will be in a different PR.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/486#-:-NlfFPzUAZ2Op0Xd-uzN:bc38zrk)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @adam-singer, @allada, and @MarcusSorealheis)

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/486#-:-Nlg88NEE52Z9Khh211I:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adam-singer and @MarcusSorealheis)

**Pull request merged**
