### PR TITLE
Add awaited action versions

### PR DESCRIPTION
**Pull request by allada**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1163)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@zbirenbaum 
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1163#-:-O1tVL8T5fXXdmrPlCcW:b5ww9g0)* status: 0 of 2 LGTMs obtained, and pending CI: vale (waiting on @adam-singer and @zbirenbaum)

**Review by zbirenbaum — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1163#-:-O1tdBf-8Bd4JYtNPCu-:bg7igkv)* status: 1 of 2 LGTMs obtained (waiting on @adam-singer)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1163#-:-O1tdOZpAgO_2-vPIYhm:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @adam-singer)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1163#-:-O1u7nV793JyptkFqFO9:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Pull request merged**
