### PR TITLE
Migrate integration tests to Bazel and K8s

### PR DESCRIPTION
**Pull request by aaronmondal**
Remove the broken docker-compose workflows, rewrite the tests to be rootlessly runnable via bazel and pin infrastructure outside of Bazel's build graph in Nix.

Each integration test now spins up a nativelink deployment in K8s, runs the test and removes the deployment again. All integration tests now have timeouts to provide faster feedback on failing tests.

Apart from a few dynamically declared IPs the new approach is fully reproducible and can reuse containers from the existing nix workflow.

The "build nativelink with nativelink" test has been removed as the LRE/Remote test already covers that usecase.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/506)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@MarcusSorealheis +@adam-singer +@allada +@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/506#-:-NlzcGu621IbTEmLa8RH:bqhjtm3)* status: 0 of 27 files reviewed, all discussions resolved (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Review by blakehatch — CHANGES_REQUESTED** [review]
> Reviewed 23 of 27 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/506)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronmondal, @adam-singer, @allada, and @MarcusSorealheis)

___
*[`deployment-examples/kubernetes/bazel_k8s_prelude.sh` line 2 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/506#-Nm2VniU66YJiyXBxnme:-Nm2VniU66YJiyXBxnmf:b-jfm6cx) ([raw file](https://github.com/TraceMachina/nativelink/blob/f79a26fe300109647586658079959a99404e982c/deployment-examples/kubernetes/bazel_k8s_prelude.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # Copyright 2022 The Native Link Authors. All rights reserved.
> ```

nit: *2023
___
*[`integration_tests/simple_cache_test.sh` line 2 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/506#-Nm2X6SR37-u9Ltx1veq:-Nm2X6SR37-u9Ltx1ver:bdj8oz3) ([raw file](https://github.com/TraceMachina/nativelink/blob/f79a26fe300109647586658079959a99404e982c/integration_tests/simple_cache_test.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # Copyright 2022 The Native Link Authors. All rights reserved.
> ```

Nit: *2023
___
*[`integration_tests/simple_remote_execution_test.sh` line 80 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/506#-Nm2Z7uB95nngzXHOj2_:-Nm2Z7uB95nngzXHOj2a:b-rcuiei) ([raw file](https://github.com/TraceMachina/nativelink/blob/f79a26fe300109647586658079959a99404e982c/integration_tests/simple_remote_execution_test.sh#L80)):*
> ```Shell
>     '.[] | select(.id.testResult.label=="//:dummy_test") | .testResult.executionInfo.strategy' \
>     "$CACHE_DIR/build_events.json"
> )
> ```

Where is the check for the remote cache having it? Seems like it just does identical checks if it executes remotely before and after a clean?
___
*[`integration_tests/simple_tls_test.sh` line 39 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/506#-Nm2ZfptDa1RJrKnxjdE:-Nm2ZfptDa1RJrKnxjdF:b-d270df) ([raw file](https://github.com/TraceMachina/nativelink/blob/f79a26fe300109647586658079959a99404e982c/integration_tests/simple_tls_test.sh#L39)):*
> ```Shell
> #                    so that we can use the command below instead:
> #
> # RESULTS=$(curl --cacert mycert.crt https://"$CACHE_IP":50071/status 2>&1)
> ```

Should we also check the .pem or is that not necessary?

**Comment by MarcusSorealheis** [comment]
@aaronmondal Can we close this issue now?

**Comment by aaronmondal** [comment]
Sure. I'll revisit this soon but I can do so in another PR.

**Pull request closed without merging**
