### PR TITLE
Fix format issues in markdown files

### LINKED ISSUE #1331: Markdown files have some minor format issues while linting
The current project's markdown files have some minor issues in its formatting.

While running Markdown Linting on my side, I could catch some format issues in markdown files and I think it's worth to fix them to keep our code standard. ;) 

1. [Fenced code blocks should have a language specified](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md040.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/README.md?plain=1#L103-L108
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L397-L399

2. [Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md022.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/SECURITY.md?plain=1#L38-L41
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/SECURITY.md?plain=1#L43-L48
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/SECURITY.md?plain=1#L50-L51

3. [Bare URL used](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md034.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L26
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L27
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L95
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L96
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L202
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CODE_OF_CONDUCT.md?plain=1#L119
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CODE_OF_CONDUCT.md?plain=1#L127
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CODE_OF_CONDUCT.md?plain=1#L128

4. [Fenced code blocks should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md031.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L39-L41
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/deployment-examples/kubernetes/README.md?plain=1#L72-L74
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/deployment-examples/kubernetes/README.md?plain=1#L122-L126
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/deployment-examples/chromium/README.md?plain=1#L77-L79
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/deployment-examples/chromium/README.md?plain=1#L89-L91

5. [Ordered list item prefix](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md029.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L195-L203

6. [Multiple consecutive blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md012.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/CONTRIBUTING.md?plain=1#L217-L219

7. [Multiple spaces after hash on atx style heading](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md012.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/local-remote-execution/README.md?plain=1#L19

8. [Lists should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md032.md)

https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/deployment-examples/kubernetes/README.md?plain=1#L138-L140
https://github.com/TraceMachina/nativelink/blob/84eab85ac7c1e98506e9fdf0749f38db65d057c4/deployment-examples/chromium/README.md?plain=1#L6-L8

### PR DESCRIPTION
**Pull request by aleksdmladenovic**
# Description

Currently, when Markdown Linting is run, there are some minor format issues in markdown files. Checked all markdown files and fixed all relevant issues in them.

Detailed issues can be find in the link below.

Fixes #1331 

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1332)

### CODE REVIEW

**Comment by aleksdmladenovic** [comment]
I caught some format issues in markdown files.
I hope you to check this.

cc: @MarcusSorealheis, @allada, @aaronmondal

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1332#-:-O67R9-iBCk0uMJ9dz2j:bnfp4nl)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Docs Deployment / macos-14, Docs Deployment / ubuntu-24.04

**Comment by aleksdmladenovic** [comment]
Reverted bare URL changes because that raises errors while converting MD files to MDX files in CI.
Plus, rebased. cc: @MarcusSorealheis, @allada

**Review by aaronmondal — APPROVED** [review]
Thanks!

cc @bclark8923 some of these changes might be interesting to you.

:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1332#-:-O6CI6VY1UdnC8ptLGQe:b-k681ex)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

**Pull request merged**
