### PR TITLE
Add Capacitor dashboard to devcluster

### PR DESCRIPTION
**Pull request by aaronmondal**
This lets us view logs and deployment statuses of Kustomizations.

The new dashboard is available via `localhost:9000`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1115)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@blakehatch +@zbirenbaum +@caass 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1115#-:-O1JMfDjEA8jlpIG7V0q:b-rj7os0)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer, @blakehatch, @caass, and @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1115#-:-O1JNvoe51DYKlzIHrOI:bg7igkv)* status: 1 of 4 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer, @blakehatch, and @caass)

___
*[`native-cli/components/embedded/capacitor.yaml` line 22 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1115#-O1JNO1uEaQAS3_j1C0W:-O1JNO1uEaQAS3_j1C0X:b-gs7ym6) ([raw file](https://github.com/TraceMachina/nativelink/blob/f997489edcff864e8d53db1226ca123170ae1878/native-cli/components/embedded/capacitor.yaml#L22)):*
> ```YAML
>   interval: 1h
>   retryInterval: 2m
>   timeout: 5m
> ```

What happens when this timeout is reached?

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1115)* status: 1 of 4 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-22.04, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer, @blakehatch, and @caass)

___
*[`native-cli/components/embedded/capacitor.yaml` line 22 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1115#-O1JNO1uEaQAS3_j1C0W:-O1JOPrzAG2zGoNUHQk4:b-vqg1vp) ([raw file](https://github.com/TraceMachina/nativelink/blob/f997489edcff864e8d53db1226ca123170ae1878/native-cli/components/embedded/capacitor.yaml#L22)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

What happens when this timeout is reached?
</blockquote></details>

The `interval: 1h` means that the dashboard deployment is reconciled every hour.
The `retryInterval: 2m` means that if reconciliation fails, try again after 2 min.
The `timeout: 5m` means that if a reconciliation takes longer than 5 min, consider the reconciliation as failed (i.e. don't get stuck waiting indefinitely for reconciliation).

See here for more infos: https://fluxcd.io/flux/components/kustomize/kustomizations/

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1115#-:-O1Jhtq3DThD06SH3C9G:bnfp4nl)* status: 2 of 4 LGTMs obtained, and 1 discussions need to be resolved (waiting on @blakehatch and @caass)

**Review by aaronmondal — COMMENTED** [review]
-@blakehatch -@caass 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1115#-:-O1JnMjP4UCnxSJdj6BG:b-d5fhef)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Pull request merged**
