### PR TITLE
New AwaitedActionDb implementation

### PR DESCRIPTION
**Pull request by allada**
Adds a new interface between the ClientScheduler logic and the data state data store.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1157)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1157)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-scheduler/src/memory_awaited_action_db.rs` line 165 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1157#-O1ntwDuBJjwDpychJOB:-O1ntwDuBJjwDpychJOC:b-i0kk39) ([raw file](https://github.com/TraceMachina/nativelink/blob/6fec13a177bcb7c22dd6fca99eed6fe31a13666e/nativelink-scheduler/src/memory_awaited_action_db.rs#L165)):*
> ```XML
>                 return Ok(self.awaited_action_rx.borrow().clone());
>             };
>             tokio::pin!(changed_fut);
> ```

fyi: We need the outer scope so this will be dropped, because the return line needs to borrow the data that this future already borrows.

**Review by allada — COMMENTED** [review]
+@adam-singer
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1157#-:-O1o7jaK81iH1SeaFr_Q:brdo00g)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 16 of 25 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1157#-:-O1omG8O2NBG6jP_vgqQ:bnfp4nl)* status: 1 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, ubuntu-22.04, windows-2022 / stable (waiting on @zbirenbaum)

**Review by allada — COMMENTED** [review]
-@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1157#-:-O1rUmVj7z4FoZ_v5tTi:b-qo69s9)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
