### PR TITLE
Use docker to create a buck2 image

### PR DESCRIPTION
**Pull request by adam-singer**
# Description

Combine a nix layer ontop of a ubuntu image for
easy to use toolchain for building buck2.

Fixes https://github.com/TraceMachina/nativelink/issues/1274

## Type of change

- [x] New feature (non-breaking change which adds functionality)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)

### CODE REVIEW

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-:-O524crs77gZJ9rCV3Wb:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`tools/toolchain-buck2/Dockerfile` line 15 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523ORL4y7QduFPgf-C:-O523ORL4y7QduFPgf-D:blbspnh) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L15)):*
> ```Dockerfile
> # limitations under the License.
> 
> FROM ubuntu:22.04@sha256:f9d633ff6640178c2d0525017174a688e2c1aef28f0a0130b26bd5554491f0da AS dependencies
> ```

nit: Please add a date on when this hash was grabbed.
___
*[`tools/toolchain-buck2/Dockerfile` line 37 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523esh00MgzvPkAn2V:-O523esh00MgzvPkAn2W:bph4uam) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L37)):*
> ```Dockerfile
> 
> # hadolint ignore=DL3003,DL3059
> RUN git clone https://github.com/TraceMachina/buck2
> ```

nit: Shouldn't we grab mainline?
___
*[`tools/toolchain-buck2/Dockerfile` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523uYoDxDq0aTNhOqO:-O523uYoDxDq0aTNhOqP:b-51oofc) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L41)):*
> ```Dockerfile
> RUN echo 'if [ -d "/buck2" ]; then\n  nix develop "/buck2" --impure --command bash\nfi' >> /etc/profile
> # hadolint ignore=DL3059
> RUN bash -c 'source /etc/profile && cd buck2 && nix develop'
> ```

nit: Maybe only git clone the repo to grab the `.nix` and/or `.flake` files then remove the files so we have a smaller image?
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O5245HM2qaxsLKzrMam:-O5245HM2qaxsLKzrMan:be46tir) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/toolchain-buck2.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> ```

nit: can we have the copyright and a description of what this file is for?
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 13 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O524MFS9dlMFAE-Z2TN:-O524MFS9dlMFAE-Z2TO:b-hkgm0s) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/toolchain-buck2.sh#L13)):*
> ```Shell
> SRC_ROOT=$(git rev-parse --show-toplevel)
> FLAKE_NIX_FILE="${SRC_ROOT}/flake.nix"
> echo "WARNING: This script will modify and revert the flake.nix"
> ```

nit: Maybe instead make sure the git repo is clean?

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13, and 5 discussions need to be resolved

___
*[`tools/toolchain-buck2/Dockerfile` line 37 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523esh00MgzvPkAn2V:-O52AKps8feX9GzzaI1B:b-3z2jhe) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L37)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Shouldn't we grab mainline?
</blockquote></details>

yes we could, originally I had some custom chains in this repo. I don't think I need them any longer. 
___
*[`tools/toolchain-buck2/Dockerfile` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523uYoDxDq0aTNhOqO:-O529bnuD_iC_08nHUv-:bnd5fwq) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L41)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Maybe only git clone the repo to grab the `.nix` and/or `.flake` files then remove the files so we have a smaller image?
</blockquote></details>

Going to remove this logic, it isn't doing what I had hoped. I had hoped that by doing this it would enter me into a nix shell when nativelink starts. The reality is it all gets ignored once we smash together the nativelink image with this image. Will sync with @aaronmondal on other options. Ideally this is where entrypoint script or other things discussed can make our lives easier. 
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 13 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O524MFS9dlMFAE-Z2TN:-O52Acbs4SdQhTtIcnV2:bki3xes) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/toolchain-buck2.sh#L13)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Maybe instead make sure the git repo is clean?
</blockquote></details>

I don't have a strong opinion on that atm, rather leave as is due to making multiple changes at the same time to quickly test.

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13

___
*[`tools/toolchain-buck2/Dockerfile` line 15 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523ORL4y7QduFPgf-C:-O52BY2P12ckvk4BA-it:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L15)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Please add a date on when this hash was grabbed.
</blockquote></details>

Done.
___
*[`tools/toolchain-buck2/Dockerfile` line 37 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523esh00MgzvPkAn2V:-O52CDSH-znaGy23HLye:bb6un1j) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L37)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

yes we could, originally I had some custom chains in this repo. I don't think I need them any longer.
</blockquote></details>

Done
___
*[`tools/toolchain-buck2/Dockerfile` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O523uYoDxDq0aTNhOqO:-O52CKlm8lmqrMfE65su:bb6un1j) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/Dockerfile#L41)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Going to remove this logic, it isn't doing what I had hoped. I had hoped that by doing this it would enter me into a nix shell when nativelink starts. The reality is it all gets ignored once we smash together the nativelink image with this image. Will sync with @aaronmondal on other options. Ideally this is where entrypoint script or other things discussed can make our lives easier.
</blockquote></details>

Done
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O5245HM2qaxsLKzrMam:-O52DMOr9PL_sxKfKwdh:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/96707500c17bbc1a90c7e9b157f1977be862b811/tools/toolchain-buck2/toolchain-buck2.sh#L2)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: can we have the copyright and a description of what this file is for?
</blockquote></details>

Done.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 8 discussions need to be resolved

___
*[`tools/toolchain-buck2/Dockerfile` line 30 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O541D6lDLemBsM9fSBp:-O541D6lDLemBsM9fSBq:b-5maq7g) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L30)):*
> ```Dockerfile
> 
> RUN curl -L https://go.dev/dl/go1.23.0.linux-amd64.tar.gz -o go1.23.0.linux-amd64.tar.gz
> RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
> ```

You can consolidate these with a pipe to reduce a layer.
___
*[`tools/toolchain-buck2/Dockerfile` line 32 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53x9pa4-7EL301go6S:-O53x9pa4-7EL301go6T:b-ypicjc) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L32)):*
> ```Dockerfile
> RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
> 
> RUN curl -L https://nixos.org/nix/install -o install-nix.sh && \
> ```

The new nix installer provides an SBOM and automatically sets up flake support: https://github.com/DeterminateSystems/nix-installer
___
*[`tools/toolchain-buck2/Dockerfile` line 41 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53xKTu3HqWOd7q9Djs:-O53xKTu3HqWOd7q9Djt:b-flven) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L41)):*
> ```Dockerfile
> RUN git clone https://github.com/facebook/buck2
> # hadolint ignore=DL3059
> RUN bash -c 'source /etc/profile && cd buck2 && nix develop && cd .. && rm -rf buck2'
> ```

To get the tooling from buck2 into the image you can use this instead:

```nix
# Last pinned 2024-08-24
nix develop github:facebook/buck2/d76c189ed6092d7b53506b9411241680923d593b
```
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 33 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53y3Gf8RaZK79zw9R1:-O53y3Gf8RaZK79zw9R2:b7q0tsy) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L33)):*
> ```Shell
> 
> function ecr_login() {
>     aws ecr get-login-password --profile ${ECR_PROFILE} --region ${ECR_REGION} | docker login --username ${ECR_USER} --password-stdin ${ECR}
> ```

nit: linebreaks
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 39 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53yn-B2Su9ZRa87BdC:-O53yn-B2Su9ZRa87BdD:b-o8xntz) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L39)):*
> ```Shell
> docker buildx build --no-cache=${BUILDX_NO_CACHE} \
>     --platform linux/amd64 \
>     -t localhost:5001/toolchain-buck2:latest \
> ```

You can use something like this to make this more generic:

```bash
IMAGE_TAG=$(nix eval .#nativelink-worker-toolchain-buck2.imageTag --raw)
IMAGE_NAME=$(nix eval .#nativelink-worker-toolchain-buck2.imageName --raw)

docker.... \
  -t localhost:5001/${IMAGE_NAME}:${IMAGE_TAG}
```

edit: Ah we're creating multiple images here. Could we make this structure a bit clearer (e.g. via comments)? It's a bit confusing what the difference between `toolchain-buck2`, `nativelink-toolchain-buck2` and `nativelink-worker-toolchain-buck2` is.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 73 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53yGDu2yTpcj8STkv_:-O53yGDu2yTpcj8STkva:b7q0tsy) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L73)):*
> ```Shell
> set +o pipefail
> SHA256_HASH=$(
>     nix run .#nativelink-worker-toolchain-buck2.copyTo docker://localhost:5001/nativelink-toolchain-buck2:latest -- --dest-tls-verify=false 2>&1 |
> ```

nit: linebreaks
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 83 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53yJHS7Ghl3Op32TyX:-O53yJHS7Ghl3Op32TyY:buagrxq) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L83)):*
> ```Shell
> 
> # Patch flake.nix with sha256 value.
> sed -i -E "s|sha256 = \"\"; # DO NOT COMMIT BUCK2 SHA256 VALUE|sha256 = \"${SHA256_HASH}\"; # DO NOT COMMIT BUCK2 SHA256 VALUE|" "${FLAKE_NIX_FILE}"
> ```

no nit: probably can't linebreak here :disappointed:
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 98 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O54-w3e8ouUoR7IEVWc:-O54-w3f4SNze5uHD6ts:bh2fjl) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L98)):*
> ```Shell
> fi
> 
> # Wrap it with nativelink to turn it into a worker.
> ```

The `create-worker` no longer wraps an image with nativelink. Instead, it now just adds a temp directory, a user, coreutils and bash. NativeLink is now mounted into the image at runtime.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 105 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O54-5sq-EhbSDpiGzEA:-O54-5sq-EhbSDpiGzEB:b-au6w3l) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L105)):*
> ```Shell
> 
> # Pull in to local docker and tag.
> docker pull localhost:5001/nativelink-toolchain-buck2:latest
> ```

Instead of docker, use `skopeo copy` since that's what `copyTo` uses under the hood as well (and it's already in the flake). This should let you collapse this to just an ecr_login and a skopeo copy invocation.

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 8 discussions need to be resolved

___
*[`tools/toolchain-buck2/Dockerfile` line 30 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O541D6lDLemBsM9fSBp:-O5E_qsy0xoBbHp2wjaw:b8qliqu) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L30)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

You can consolidate these with a pipe to reduce a layer.
</blockquote></details>

sg, if you have any other ideas of installing go, I'm open to that. Installing via nix might be what I want. Didn't want to mess around with nix too much when we got to this state, whats an easy/quick way to install this version of go without much drama? 
___
*[`tools/toolchain-buck2/Dockerfile` line 32 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53x9pa4-7EL301go6S:-O5E_ZQA7cBJ2GYNoajC:boilg4) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L32)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The new nix installer provides an SBOM and automatically sets up flake support: https://github.com/DeterminateSystems/nix-installer
</blockquote></details>

k, will need to test that out, see what it entails 
___
*[`tools/toolchain-buck2/Dockerfile` line 41 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53xKTu3HqWOd7q9Djs:-O5EZnfFEgr1F-sJwsmF:bsyzs41) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L41)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

To get the tooling from buck2 into the image you can use this instead:

```nix
# Last pinned 2024-08-24
nix develop github:facebook/buck2/d76c189ed6092d7b53506b9411241680923d593b
```
</blockquote></details>

nice, that will sync all the nix deps 
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 83 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53yJHS7Ghl3Op32TyX:-O5EaTdkAWju1k1FtPXh:b-vdfqcl) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L83)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

no nit: probably can't linebreak here :disappointed:
</blockquote></details>

Yes, this is a regex, we probably could but its not worth it.

Done.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 105 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O54-5sq-EhbSDpiGzEA:-O5EafNX14fZqzEM3n32:b-g1tfp5) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L105)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Instead of docker, use `skopeo copy` since that's what `copyTo` uses under the hood as well (and it's already in the flake). This should let you collapse this to just an ecr_login and a skopeo copy invocation.
</blockquote></details>

Can you provide an example? Are you saying just run `.copyTo` ?

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)* status: 1 of 1 LGTMs obtained, and 2 of 4 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 6 discussions need to be resolved

___
*[`tools/toolchain-buck2/Dockerfile` line 41 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53xKTu3HqWOd7q9Djs:-O5HPMNQBVz1xUIjgLFo:bs9yyhf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L41)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nice, that will sync all the nix deps
</blockquote></details>

This isn't perfect atm, I'm wondering of ways we can propagate information out of the container into a metadata layer or manifest labels such that external system could consume them if they needed. I think this is "ok" for now.

Done.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 33 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53y3Gf8RaZK79zw9R1:-O5FwNA9AyK6bmjm4xHM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L33)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: linebreaks
</blockquote></details>

Done.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 73 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53yGDu2yTpcj8STkv_:-O5FwhxL4eErUw4bQvCI:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L73)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: linebreaks
</blockquote></details>

Done.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 98 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O54-w3e8ouUoR7IEVWc:-O5Fx-5NEfvt7OInBVr6:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L98)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The `create-worker` no longer wraps an image with nativelink. Instead, it now just adds a temp directory, a user, coreutils and bash. NativeLink is now mounted into the image at runtime.
</blockquote></details>

Done.
___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 105 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O54-5sq-EhbSDpiGzEA:-O5HPJrN1LMRUBIRUY_Q:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L105)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can you provide an example? Are you saying just run `.copyTo` ?
</blockquote></details>

Done.

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275)* status: 1 of 1 LGTMs obtained, and 2 of 4 files reviewed, and 6 discussions need to be resolved

___
*[`tools/toolchain-buck2/toolchain-buck2.sh` line 39 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O53yn-B2Su9ZRa87BdC:-O5Z814X3lF6n2ejD7pW:b-1k8qo4) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/toolchain-buck2.sh#L39)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

You can use something like this to make this more generic:

```bash
IMAGE_TAG=$(nix eval .#nativelink-worker-toolchain-buck2.imageTag --raw)
IMAGE_NAME=$(nix eval .#nativelink-worker-toolchain-buck2.imageName --raw)

docker.... \
  -t localhost:5001/${IMAGE_NAME}:${IMAGE_TAG}
```

edit: Ah we're creating multiple images here. Could we make this structure a bit clearer (e.g. via comments)? It's a bit confusing what the difference between `toolchain-buck2`, `nativelink-toolchain-buck2` and `nativelink-worker-toolchain-buck2` is.
</blockquote></details>

will follow up on this one because we don't need create worker going forward for this kind of setup

Done.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-:-O5Z9GSMBMbIH0684W7o:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained, and all files reviewed

___
*[`tools/toolchain-buck2/Dockerfile` line 30 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1275#-O541D6lDLemBsM9fSBp:-O5Z8srE14S_YNgQFqt5:b-1jmndh) ([raw file](https://github.com/TraceMachina/nativelink/blob/f2b99b93ad70304daeea836d83703ce09f497104/tools/toolchain-buck2/Dockerfile#L30)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

sg, if you have any other ideas of installing go, I'm open to that. Installing via nix might be what I want. Didn't want to mess around with nix too much when we got to this state, whats an easy/quick way to install this version of go without much drama?
</blockquote></details>

Yeah via nix is probably the way, i.e something like `nix profile install nixpkgs#go`, but we can figure out the details of that later.

**Pull request merged**
