### PR TITLE
Update cloud docs for RBE and Read Only

### PR DESCRIPTION
**Pull request by bclark8923**
# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [x] Documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1322)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Mostly LGTM.  

- Let's split off the workflow disables.
- Make sure to run vale manually on the changed files since the pre-commit hooks don't correctly report warning-level issues.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-:-O607yd5E3qxFdMBXr2S:b57i7j5)* status: 0 of 1 LGTMs obtained, and all files reviewed, and 8 discussions need to be resolved

___
*[`.github/workflows/nix.yaml` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O606Ww4BgvgUvpYhh-i:-O606Ww4BgvgUvpYhh-j:bp5na04) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/.github/workflows/nix.yaml#L10)):*
> ```YAML
>     branches: [main]
>     paths-ignore:
>       - 'docs/**'
> ```

While we're at it, let's also disable the following workflows for doc-only changes:

- `main`
- `native-bazel`
- `native-cargo`
- `image`
- `sanitizers`

I'd probably put all of these disables in a different PR as this is not related to the new RBE documentation.
___
*[`docs/README.md` line 26 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O603h4fBluUvNqiFlrD:-O603h4fBluUvNqiFlrE:b-o30z4n) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/README.md#L26)):*
> ```Markdown
> for build scripts.
> 
> This project requires `bun` and `deno`. The nix flake ships a compatible version of `bun`.
> ```

The flake also ships deno.



_Suggestion:_
```Markdown
compatible versions.
```
___
*[`docs/src/content/docs/nativelink-cloud/api-key.mdx` line 66 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O604Mfq3HqYcYMAV_7s:-O604Mfq3HqYcYMAV_7t:bnoi9q0) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/api-key.mdx#L66)):*
> ```MDX
>   --remote_cache=grpcs://cas-account-id.build-faster.nativelink.net \
>   --remote_header=x-nativelink-api-key=${{ secrets.NATIVELINK_COM_API_HEADER || 'HARD_CODED_READ_ONLY_KEY_HERE' }} \
>   ${{ github.ref == 'refs/heads/main' && ' ' || '--nogenerate_json_trace_profile --remote_upload_local_results=false' }} \
> ```

nit: Is the `&& ' '`  part intentional?
___
*[`docs/src/content/docs/nativelink-cloud/rbe.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O604l-mBOlVyGi_8DCK:-O604l-mBOlVyGi_8DCL:bwnbqta) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/rbe.mdx#L1)):*
> ```MDX
> ---
> ```

Please line-wrap this file at 80 chars where possible to keep it readable on terminal-based editors.
___
*[`docs/src/content/docs/nativelink-cloud/rbe.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O6054mv26gOyxnUY5u3:-O6054mv26gOyxnUY5u4:b2ni8l0) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/rbe.mdx#L10)):*
> ```MDX
> :::
> 
> This guide shows how to configure remote build execution (RBE) for your [Bazel](https://bazel.build/) projects with the
> ```

nit
___
*[`docs/src/content/docs/nativelink-cloud/rbe.mdx` line 14 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O605DHlDBwIpKTjdFsv:-O605DHlDBwIpKTjdFsw:b2ni8l0) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/rbe.mdx#L14)):*
> ```MDX
> 
> ### Basic Configuration
> To enable RBE all you need to do is add the below flag to your Bazel builds:
> ```

nit
___
*[`docs/src/content/docs/nativelink-cloud/rbe.mdx` line 19 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O605N145HBTQBBtPJmX:-O605N145HBTQBBtPJmY:b2ni8l0) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/rbe.mdx#L19)):*
> ```MDX
> ```
> 
> This will run your builds on a Ubuntu 22.04 image *without any* dependencies installed. For most customers we don't expect this to work out of the box as your project most likely depends on installations like GCC/Java/etc. To remedy that, continue with the instructions below to pass in your own images.
> ```

nit



_Suggestion:_
```MDX
users
```
___
*[`docs/src/content/docs/nativelink-cloud/rbe.mdx` line 33 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O605l9oD8TXnloWFcaJ:-O605l9p92Yu65nEbIvi:bbg8z8i) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/rbe.mdx#L33)):*
> ```MDX
> If your images are in your own private image repository, you can pass your repository credentials to allow us to pull your RBE images.
> 
> Here's an example with Amazon ECR (Elastic Container Registry) and the AWS CLI:
> ```

nit: consider using starlight's tabs here, similar to this: https://github.com/TraceMachina/nativelink/blob/913e710d695750d6b51a1feb0ac8a001b04e2b01/docs/src/content/docs/contribute/bazel.mdx?plain=1#L22

**Comment by bclark8923** [comment]
*[`docs/src/content/docs/nativelink-cloud/api-key.mdx` line 66 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O604Mfq3HqYcYMAV_7s:-O62ADb81epZUjBdrZ3I:b1hjqno) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/api-key.mdx#L66)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Is the `&& ' '`  part intentional?
</blockquote></details>

Unfortuately yes, we tried "cleaner" implementations but Github didn't like them

**Review by bclark8923 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1322)* status: 0 of 1 LGTMs obtained, and 2 of 6 files reviewed, and pending CI: Docs Deployment / ubuntu-24.04, Local / ubuntu-22.04, pre-commit-checks, and 3 discussions need to be resolved

___
*[`docs/README.md` line 26 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O603h4fBluUvNqiFlrD:-O62AXnIAZI6-Ly9TkXF:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/README.md#L26)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The flake also ships deno.
</blockquote></details>

Done.
___
*[`docs/src/content/docs/nativelink-cloud/rbe.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O604l-mBOlVyGi_8DCK:-O62Dtbl6arMGHFCrVio:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/docs/src/content/docs/nativelink-cloud/rbe.mdx#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Please line-wrap this file at 80 chars where possible to keep it readable on terminal-based editors.
</blockquote></details>

Done.
___
*[`.github/workflows/nix.yaml` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-O606Ww4BgvgUvpYhh-i:-O62Aq3Q0EvEFrRscof0:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2eb55fb8cc06b1c7627f8e553b9a2d734e248479/.github/workflows/nix.yaml#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

While we're at it, let's also disable the following workflows for doc-only changes:

- `main`
- `native-bazel`
- `native-cargo`
- `image`
- `sanitizers`

I'd probably put all of these disables in a different PR as this is not related to the new RBE documentation.
</blockquote></details>

Done.

**Review by bclark8923 — COMMENTED** [review]
Updated and ran Vale, lemme know if all good!

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-:-O62H3bh1zO28KxTRV-W:btcc593)* status: 0 of 1 LGTMs obtained, and 2 of 6 files reviewed, and pending CI: Docs Deployment / ubuntu-24.04, Local / ubuntu-22.04, pre-commit-checks, and 3 discussions need to be resolved

**Review by aaronmondal — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1322)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1322#-:-O62Q05Q0LUF4OAhqSkH:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13

**Pull request merged**
