### PR TITLE
Fix broken demo button link

### PR DESCRIPTION
**Pull request by SchahinRohani**
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1404)

### CODE REVIEW

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1404)* status: 0 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`web/platform/src/components/qwik/sections/feature.tsx` line 47 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1404#-O8sYkk7-X3IBEFbEUGq:-O8sYkk7-X3IBEFbEUGr:bx9i06b) ([raw file](https://github.com/TraceMachina/nativelink/blob/cd87756bbea39c380f39b5689ba99eedcdd6612d/web/platform/src/components/qwik/sections/feature.tsx#L47)):*
> ```XML
>         ))}
>       </div>
>       <a
> ```

changing this to an `a` will change the style, wont it?

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1404#-:-O8sYp563c6dtpVY1v93:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

**Review by SchahinRohani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1404)* status: 1 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

___
*[`web/platform/src/components/qwik/sections/feature.tsx` line 47 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1404#-O8sYkk7-X3IBEFbEUGq:-O8spgHpDxEDn8O62OkX:b-s0w5zq) ([raw file](https://github.com/TraceMachina/nativelink/blob/cd87756bbea39c380f39b5689ba99eedcdd6612d/web/platform/src/components/qwik/sections/feature.tsx#L47)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

changing this to an `a` will change the style, wont it?
</blockquote></details>

The div ist styled with tailwind classes, i have tested the change to an link on the frontend, and it only put an underline to it.
So i force put the "no-underline!" class with ! and then its the same as the button before.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1404#-:-O9BzCjR7de7Vid4LIKl:bnfp4nl)* status: 2 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

**Pull request merged**
