### PR TITLE
Add Kubernetes example

### PR DESCRIPTION
**Pull request by aaronmondal**
This example starts a fairly complete Kubernetes cluster and showcases
perfectly reproducible remote execution via the local remote execution
toolchain containers.

This example uses a three-layer setup process:

1. The infra layer is a kind cluster with Cilium and MetalLB. This layer
   is built to be easily swappable with more "production grade"
   clusters.
2. The operations layer deploys a few standard applications that are not
   inherently required for NativeLink, but are solid deployments that
   one would likely want running in a cluster. This includes monitoring
   and handling image availability.
3. The application layer is a straightforward `kubectl apply -k .` which
   deploys a NativeLink CAS, Worker and Scheduler. This deployment
   differs from the Docker Compose setup in that it does not make use of
   any system paths and doesn't allow visibility "outside" of the node
   itself. That is, it's a hard requirement that the worker image is
   self-contained. Storage is fully ephemeral in this example and a
   `kubectl delete -k .` will destroy the cache for quick iterations and
   cache testing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/479)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@allada +@MarcusSorealheis +@blakehatch 

FYI the first revision here can be skipped as it's identical to #471 

@allada This is working in my setup and it seems like the cluster also starts up fine in CI. But the build invocation in CI triggers an "UNIMPLEMENTED" error. It seems like the cluster is reachable, but something goes wrong during communication. Maybe I'm doing something wrong in the `.json` configs or platform properties? Is there a way  to get more info out of the `UNIMPLEMENTED` message?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/479#-:-NlW7yMYBMMBecWKjexT:bixoory)* status: 0 of 39 files reviewed, all discussions resolved (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Review by allada — COMMENTED** [review]
> Reviewed 17 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/479)* status: 17 of 39 files reviewed, 13 unresolved discussions (waiting on @aaronmondal, @adam-singer, @blakehatch, and @MarcusSorealheis)

___
*[`deployment-examples/kubernetes/00_infra.sh` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWKU_F-tlVH3sKjK8l:-NlWKU_F-tlVH3sKjK8m:b6vli5x) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/00_infra.sh#L41)):*
> ```Shell
> for node in $(kind get nodes); do
>   docker exec "${node}" mkdir -p "${REGISTRY_DIR}"
>   cat <<EOF | docker exec -i "${node}" cp /dev/stdin "${REGISTRY_DIR}/hosts.toml"
> ```

nit: This seems overly fancy.
___
*[`deployment-examples/kubernetes/cas.json` line 4 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLDsQCQCsQjFZFLhc:-NlWLDsQCQCsQjFZFLhd:bbzd1pq) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L4)):*
> ```JSON
> // `~/.cache/native-link`. It will store all data on disk and
> // allows for restarts of the underlying service. It is optimized
> // so objects are compressed, deduplicated and uses some in-memory
> ```

nit: There are no in-memory operations.
___
*[`deployment-examples/kubernetes/cas.json` line 13 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLVAHA2qJ-TsbVVcn:-NlWLVAHA2qJ-TsbVVco:b-wk6b7r) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L13)):*
> ```JSON
>           "compression": {
>             "compression_algorithm": {
>               "LZ4": {}
> ```

nit: Now lower case in `main`.
___
*[`deployment-examples/kubernetes/cas.json` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWKxYH7bboXc5Oa0cX:-NlWKxYH7bboXc5Oa0cY:b-kjlanc) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L27)):*
> ```JSON
>           }
>         },
>         "verify_size": true,
> ```

fyi: very slow,
___
*[`deployment-examples/kubernetes/cas.json` line 32 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLGjKCMz3zki2ClJ1:-NlWLGjKCMz3zki2ClJ2:b-mwgi29) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L32)):*
> ```JSON
>     },
>     "AC_MAIN_STORE": {
>       "filesystem": {
> ```

nit: From now on, if we ever evict in the CAS, we should use `completeness_checking_store` (on ac) w/ `existance_cache_store` (on cas).
___
*[`deployment-examples/kubernetes/cas.json` line 61 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLSIlBy-j9MC_QUsO:-NlWLSIlBy-j9MC_QUsP:bgh0clh) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L61)):*
> ```JSON
>         },
>         // According to https://github.com/grpc/grpc.github.io/issues/371 16KiB - 64KiB is optimal.
>         "max_bytes_per_stream": 64000, // 64kb.
> ```

nit: No longer needed in `main`.
___
*[`deployment-examples/kubernetes/cas.json` line 96 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWL_HQ4ApXBVnyWADz:-NlWL_HQ4ApXBVnyWAE-:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L96)):*
> ```JSON
>         },
>         // According to https://github.com/grpc/grpc.github.io/issues/371 16KiB - 64KiB is optimal.
>         "max_bytes_per_stream": 64000, // 64kb.
> ```

nit: ditto.
___
*[`deployment-examples/kubernetes/example-do-not-use-in-prod-key.pem` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLgiH4JIpLxZltNA8:-NlWLgiH4JIpLxZltNA9:b-b73yhj) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/example-do-not-use-in-prod-key.pem#L1)):*
> ```
> -----BEGIN PRIVATE KEY-----
> ```

nit: Symlink this file. Git does support symlinks.
___
*[`deployment-examples/kubernetes/example-do-not-use-in-prod-rootca.crt` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLkBrBTfXDJqTGrCP:-NlWLkBrBTfXDJqTGrCQ:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/example-do-not-use-in-prod-rootca.crt#L1)):*
> ```
> -----BEGIN CERTIFICATE-----
> ```

nit: ditto.
___
*[`deployment-examples/kubernetes/worker.json` line 3 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWMqyY8fOf7MOKatGs:-NlWMqyY8fOf7MOKatGt:bv4xdmc) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/worker.json#L3)):*
> ```JSON
> {
>   "stores": {
>     "GRPC_LOCAL_STORE": {
> ```

nit: inline this?
___
*[`deployment-examples/kubernetes/worker.json` line 4 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWMpNpEVzvZ25y7TQi:-NlWMpNpEVzvZ25y7TQj:blpgvs1) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/worker.json#L4)):*
> ```JSON
>   "stores": {
>     "GRPC_LOCAL_STORE": {
>       // Note: This file is used to test GRPC store.
> ```

nit: remove?
___
*[`deployment-examples/kubernetes/worker.json` line 12 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWMukO0VhEMDFMal2j:-NlWMukO0VhEMDFMal2k:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/worker.json#L12)):*
> ```JSON
>     },
>     "GRPC_LOCAL_AC_STORE": {
>       // Note: This file is used to test GRPC store.
> ```

nit: ditto.
___
*[`deployment-examples/kubernetes/worker.json` line 57 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWN9GQ1N-R0em6dHIi:-NlWN9GQ1N-R0em6dHIj:b-4jnf7m) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/worker.json#L57)):*
> ```JSON
>         },
>         "container-image": {
>           "values": ["docker://native-link-toolchain:li84k8gzw2qvmzc9qrx6s2vc690lfy2b"]
> ```

nit: Can we sniff this out somehow with a command and then use an ENV here to set it?
___
*[`deployment-examples/kubernetes/worker.yaml` line 21 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWNG0A7l1JcB0mLisb:-NlWNG0A7l1JcB0mLisc:b-c16z81) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/worker.yaml#L21)):*
> ```YAML
>           env:
>             - name: RUST_LOG
>               value: debug
> ```

nit: Very verbose. Maybe `info` instead?

**Review by adam-singer — COMMENTED** [review]
> Reviewed 18 of 25 files at r1, 5 of 21 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/479)* status: all files reviewed, 14 unresolved discussions (waiting on @aaronmondal, @blakehatch, and @MarcusSorealheis)

___
*[`.bazelrc` line 76 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlZTD1z1UNWCCh-bqb6:-NlZTD1z1UNWCCh-bqb7:bn5d32v) ([raw file](https://github.com/TraceMachina/nativelink/blob/d3cb3b52a0fe6d58ab848ae3d1317b93940dc7d1/.bazelrc#L76)):*
> ```
> build:k8s --config=lre
> build:k8s --remote_instance_name=main
> build:k8s --remote_cache=grpc://172.20.255.200:50051
> ```

What controls the IP configuration, is it always ensured to be these two addresses? Are there additional steps that can make it a hostname from fancy docker commands/configs?

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/479)* status: 6 of 43 files reviewed, 4 unresolved discussions (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`.bazelrc` line 76 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlZTD1z1UNWCCh-bqb6:-Nl_xUv91xEsGaXX81c3:b-j1zt60) ([raw file](https://github.com/TraceMachina/nativelink/blob/d3cb3b52a0fe6d58ab848ae3d1317b93940dc7d1/.bazelrc#L76)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

What controls the IP configuration, is it always ensured to be these two addresses? Are there additional steps that can make it a hostname from fancy docker commands/configs?
</blockquote></details>

Yeah turns out these can slightly differ. On my machines it's these IPs, but on the GHA runners its `172.18.xxx`. I've changed the k8s readme to show how to find out these IPs.
___
*[`deployment-examples/kubernetes/00_infra.sh` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWKU_F-tlVH3sKjK8l:-Nl_y5zt2yaglKbIJ4qO:b-iwmea1) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/00_infra.sh#L41)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This seems overly fancy.
</blockquote></details>

This pattern was masterfully copied from https://kind.sigs.k8s.io/docs/user/local-registry/ :D But it's a fairly common pattern in K8s scripts where we often have to pipe some file into some command while leaving no traces tmp files on the machine.

It even has it's own Wikipedia article :laughing:  https://en.wikipedia.org/wiki/Here_document
___
*[`deployment-examples/kubernetes/cas.json` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWKxYH7bboXc5Oa0cX:-Nlafz2ZDEvlu2ZIb_Kw:b-4vzqal) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L27)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

fyi: very slow,
</blockquote></details>

Is it ok to remove this when using the existence caching store?
___
*[`deployment-examples/kubernetes/cas.json` line 32 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLGjKCMz3zki2ClJ1:-Nlag3IQ94Y5t8aYJEvV:b-puxwvi) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/cas.json#L32)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: From now on, if we ever evict in the CAS, we should use `completeness_checking_store` (on ac) w/ `existance_cache_store` (on cas).
</blockquote></details>

Not sure if this is correct. The order is a bit confusing :sweat_smile: 
___
*[`deployment-examples/kubernetes/example-do-not-use-in-prod-key.pem` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/479#-NlWLgiH4JIpLxZltNA8:-NlaMd-83rsjNGyTOjDG:b-sz70fo) ([raw file](https://github.com/TraceMachina/nativelink/blob/3c899cc1ed8ba179c91fa94b9b850f31a25764bd/deployment-examples/kubernetes/example-do-not-use-in-prod-key.pem#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Symlink this file. Git does support symlinks.
</blockquote></details>

Agreed that it would be nicer. However, Kustomize doesn't allow referencing outside the directory where the `kustomization.yaml` file is located.

I plan to change this setup to a "better practice" one using cert-manager, but defer this to another PR as a certmanager setup seems out of scope at the moment.

**Review by MarcusSorealheis — APPROVED** [review]
LGTM

**Review by adam-singer — APPROVED** [review]
> Reviewed 18 of 37 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/479)* status: 24 of 43 files reviewed, 3 unresolved discussions (waiting on @allada and @blakehatch)

**Comment by C0mbatwombat** [comment]
Thanks @aaronmondal !

**Pull request merged**
