### PR TITLE
Enable blake3 for Bazel builds

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@allada +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565#-:-Nm9D1M-B2IIZQL0VpHl:bchhibo)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer and @allada)

**Review by adam-singer — APPROVED** [review]
Based on https://github.com/bazelbuild/bazel/commit/0a8380bec9dceae1bffabddcccd459e82d8674b1 && https://github.com/bazelbuild/remote-apis/pull/235 should we be considering `SHA256TREE`? Seems like some existing research has been done, at a high level Blake3 might be better for x86/x64 and slower than SHA256 on Arm, SHA256TREE is mentioned in the thread better on both platforms.. Not sure if its worth evaluating which digest to use based on platform, or just keep it simple, pick one for now and revisit later. 

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565#-:-NmC97OM7xvAEst-0a3U:b-gfbqpo)* status: 1 of 2 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04) (waiting on @allada)

**Review by aaronmondal — COMMENTED** [review]
@adam-singer Interesting. Is that used in the same way as the other ones though? If something other than blake3 is faster on arm we could set the digest function to different values for different configurations to get the most out of all CI runners.

cross-ref #566 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565#-:-NmCZM4XD2miuUxAbTbc:b-agmea1)* status: 1 of 2 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04) (waiting on @allada)

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565#-:-NmDN3SY0MvefV4ovOWF:bnfp4nl)* status: 2 of 2 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04)

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: 2 of 2 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/565#-NmDNcE-4PMFn0GweFVS:-NmDNcE-4PMFn0GweFVT:b-6wn68e) (no related file):*
`verify` store does not yet support blake3:

https://github.com/TraceMachina/nativelink/blob/ddf1d74ba952a825e88bc68ed1efd67c6386d190/deployment-examples/docker-compose/local-storage-cas.json#L9

___

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: 2 of 2 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: 2 of 2 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: 2 of 2 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04)

___
*[`deployment-examples/docker-compose/local-storage-cas.json` line 28 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/565#-No7Zcs-7HBYeI6LOOeH:-No7Zcs-7HBYeI6LOOeI:bof3gw5) ([raw file](https://github.com/TraceMachina/nativelink/blob/1f1a3f0cbb753c0e3d774ce6533218eabc30f27b/deployment-examples/docker-compose/local-storage-cas.json#L28)):*
> ```JSON
>         },
>         "verify_size": true,
>         "hash_verification_function": "blake3"
> ```

Hmmm, lets remove verification store here all together. We use it in testing and by default bazel uses sha256, so it'll make this not work "out-of-the-box" unless the user adds cli flags (and has clients that support blake3).

If we remove verification store it should just work.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: 2 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image, windows-2022 / stable

___
*[`deployment-examples/docker-compose/local-storage-cas.json` line 28 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/565#-No7Zcs-7HBYeI6LOOeH:-No8NyAF9PgpCr3DSZoO:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/1f1a3f0cbb753c0e3d774ce6533218eabc30f27b/deployment-examples/docker-compose/local-storage-cas.json#L28)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, lets remove verification store here all together. We use it in testing and by default bazel uses sha256, so it'll make this not work "out-of-the-box" unless the user adds cli flags (and has clients that support blake3).

If we remove verification store it should just work.
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Review by adam-singer — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/565)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Pull request merged**
