### PR TITLE
Remove Terraform examples

### PR DESCRIPTION
**Pull request by aaronmondal**
These are unmaintained and not continuously tested. The documentation likely doesn't work and potentially confuses users.

Remove them to streamline efforts of improving current documentation and to remove a bunch of stale Renovate PRs and vulnerabilities. We can always bring them back from the history.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@allada +@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016#-:-O-Vtlk14fa15emDM1E3:b4y6pzi)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer, @allada, and @blakehatch)

**Review by adam-singer — COMMENTED** [review]
Maybe this sounds pedantic, could/should we move these to a different repo marked as experimental / deprecated? I think its nice to have for a starting point of terraform code. I understand if its overly brittle to have in our main repo.  

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016#-:-O-gxxS92grXyW_c0CAk:b-43rggt)* status: 0 of 3 LGTMs obtained (waiting on @allada and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
Something that TensorFlow did was move things like this to a `contrib` repository with the warning that all code in it wasn't held to the same stability guarantees as the main repo. Should I create a `nativelink-contrib`?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016#-:-O-hh3vQ36iI350YwEpM:b-dwbp1n)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @blakehatch)

**Review by adam-singer — COMMENTED** [review]
I'd just call it contrib, giving it `nativelink-` makes it seem "offical" 

:lgtm:  

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016#-:-O-j5PqC-u6XQfh1w5CL:b-pvzeus)* status: 1 of 3 LGTMs obtained (waiting on @allada and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
Called it graveyard lol https://github.com/TraceMachina/graveyard

-@allada

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016#-:-O-kgigi9EmN60vS-vkn:b-oc0qpz)* status: 1 of 2 LGTMs obtained (waiting on @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
-@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1016#-:-O-kguML3W39so_n1oQN:b-lpnp7r)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Comment by MarcusSorealheis** [comment]
@aaronmondal you should wait on someone senior to review this one. While I feel graveyard is clever, we may need to revisit these deployment examples. 

We can spin up tests for them nightly but not sure they should disappear.

**Pull request merged**
