### PR TITLE
Unbreak docker-compose workflow

### LINKED ISSUE #939: Docker compose workflow breaks CI once again
Update the pinned package versions to unbreak it.

### PR DESCRIPTION
**Pull request by aaronmondal**
Fixes #939

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/940)

### CODE REVIEW

**Review by MarcusSorealheis — COMMENTED** [review]
are we using release candidates?

**Review by aaronmondal — COMMENTED** [review]
@MarcusSorealheis No. We wanted to remove this workflow for a while now, but currently this is still the one that runs the integration tests. It runs them against completely unsupported non-production binaries though, so it's somewhat unclear how useful this really is. The current K8s workflows run a build with remote caching and remote execution against a nativelink deployment with production binaries, but don't test things like TLS encryption at the moment.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/940#-:-Nz2IJ7f12DyuvA7zSPx:bbehqhy)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@allada +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/940#-:-Nz82faC70jTNmvesFEQ:bgtx3ex)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @allada)

**Review by aaronmondal — COMMENTED** [review]
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/940#-:-Nz82tCO1Io9h_9F4yuq:b-gyszd7)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/940#-:-Nz9FreU-bkCb3-gGxWG:bnfp4nl)* status: 1 of 3 LGTMs obtained (waiting on @allada and @zbirenbaum)

**Review by aaronmondal — COMMENTED** [review]
-@allada -@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/940#-:-Nz9nSx68o2ButlBhicV:b-hovqjz)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
