### PR TITLE
Unbreak LRE workflows

### LINKED ISSUE #986: LRE flaky in CI
A lot of flakes are happening because of LRE. It appears that the way it caches or pulls images are causing issues.

example:
https://github.com/TraceMachina/nativelink/actions/runs/9470928434/job/26092947739?pr=924

### PR DESCRIPTION
**Pull request by aaronmondal**
This was caused by an upstream issue that has been fixed in https://github.com/NixOS/nix/pull/9897.

Fixes #986

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1002)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@allada +@adam-singer +@zbirenbaum +@caass 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1002#-:-O-J2fV43X6bfxsQtpkv:b-owa8k8)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer, @allada, @caass, and @zbirenbaum)

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1002#-:-O-Je6pr5mBvvcnrq4Ye:bnfp4nl)* status: 1 of 4 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, pre-commit-checks (waiting on @adam-singer, @caass, and @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1002)* status: 1 of 4 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, pre-commit-checks (waiting on @adam-singer and @caass)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1002#-:-O-KTG2W6dZ-ZL5_nTvj:bnfp4nl)* status: 2 of 4 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, pre-commit-checks (waiting on @adam-singer and @caass)

**Comment by aaronmondal** [comment]
Still too flaky. Superceded by #1013.

**Pull request closed without merging**
