### PR TITLE
Add `StoreDriver::list` for `FilesystemStore`

### PR DESCRIPTION
**Pull request by jhpratt**
part of #995

# Description

This implements and tests the `list` method of the `StoreDriver` trait for `FilesystemStore`. 

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)* status: 0 of 1 LGTMs obtained, and 5 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1546 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Clm791ov0xV4VpPkX:-O1Clm791ov0xV4VpPkY:b-qxbryd) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1546)):*
> ```XML
>         .unwrap()
>         .as_millis();
>     let content_path = format!("content_path_{timestamp}");
> ```

use: `make_temp_path` like the other tests in this file.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1550 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Clyxk8iaDaAtG2fCI:-O1Clyxk8iaDaAtG2fCJ:b-afpoih) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1550)):*
> ```XML
> 
>     // Remove, but here due to previous error seen by Jacob in CI
>     std::fs::create_dir_all(&content_path)
> ```

nit: remove `std::` and use the async tokio functions like the rest of this file does.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1590 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CmSNr-REviAkx4uTS:-O1CmSNr-REviAkx4uTT:b-gzoizg) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1590)):*
> ```XML
> 
>     store
>         .update_oneshot(StoreKey::Digest(expected_digest1), VALUE.into())
> ```

Why not do what `list_test` in `memory_store_test` does?
```rs
    const KEY1: StoreKey = StoreKey::new_str("key1");
    const KEY2: StoreKey = StoreKey::new_str("key2");
    const KEY3: StoreKey = StoreKey::new_str("key3");
    const VALUE: &str = "value1";
    store.update_oneshot(KEY1, VALUE.into()).await?;
    store.update_oneshot(KEY2, VALUE.into()).await?;
    store.update_oneshot(KEY3, VALUE.into()).await?;
```
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1606 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CmzPT85pnbYXknWbq:-O1CmzPT85pnbYXknWbr:bo9ofzh) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1606)):*
> ```XML
>         store
>             .list(range, |key| {
>                 let key_owned = key.borrow().into_owned();
> ```

nit: Inline this, like it is in the other test.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1618 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Cn2diA9cjkycpgdLl:-O1Cn2diA9cjkycpgdLm:b-t3pake) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1618)):*
> ```XML
>         // Test listing all keys.
>         let keys = get_list(&store, ..).await;
>         assert_eq!(
> ```

nit:
```rs
        let keys = get_list(&store, ..).await;
        assert_eq!(keys, vec![KEY1, KEY2, KEY3]);
```

Like the other test?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)* status: 0 of 1 LGTMs obtained, and 6 discussions need to be resolved

___
*[`nativelink-store/Cargo.toml` line 42 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CnG9dCqx2BRFgLZJg:-O1CnG9dCqx2BRFgLZJh:bekq710) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/Cargo.toml#L42)):*
> ```TOML
> shellexpand = "3.1.0"
> tempfile = "3.10.1"
> tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
> ```

nit: Why bring in real time support into this module?

**Review by jhpratt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Cloudflare Pages, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 3 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1546 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Clm791ov0xV4VpPkX:-O1EUeOf6VyKhZKMrLd-:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1546)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

use: `make_temp_path` like the other tests in this file.
</blockquote></details>

done
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1550 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Clyxk8iaDaAtG2fCI:-O1EUgZb42nJ8UjnRTUv:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1550)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: remove `std::` and use the async tokio functions like the rest of this file does.
</blockquote></details>

done
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1590 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CmSNr-REviAkx4uTS:-O1Ec87zAqUxWWWoNMFZ:b4l6hfy) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1590)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Why not do what `list_test` in `memory_store_test` does?
```rs
    const KEY1: StoreKey = StoreKey::new_str("key1");
    const KEY2: StoreKey = StoreKey::new_str("key2");
    const KEY3: StoreKey = StoreKey::new_str("key3");
    const VALUE: &str = "value1";
    store.update_oneshot(KEY1, VALUE.into()).await?;
    store.update_oneshot(KEY2, VALUE.into()).await?;
    store.update_oneshot(KEY3, VALUE.into()).await?;
```
</blockquote></details>

The `StoreKey` goes through SHA256 in `hash_key`, as is the case in `memory_store_test`. I could use the pre-existing method (namely `StoreKey::into_digest`) to auto-create it, but that uses the Blake3 hash. Presumably that would cause a compatibility issue? 
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1606 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CmzPT85pnbYXknWbq:-O1EUuVyEiqA6wjgaAF2:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1606)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Inline this, like it is in the other test.
</blockquote></details>

done
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1618 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Cn2diA9cjkycpgdLl:-O1EU5sa7qtx0vtvipz8:b-gnd6fw) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1618)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit:
```rs
        let keys = get_list(&store, ..).await;
        assert_eq!(keys, vec![KEY1, KEY2, KEY3]);
```

Like the other test?
</blockquote></details>

`KEY1` & others are now `&str`s, not `StoreKey`s, so this wouldn't work. `PartialEq` isn't implemented between the two types (nor should they be imo). This is related to the concern on line 1590 above, so they'll likely be resolved together.
___
*[`nativelink-store/Cargo.toml` line 42 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CnG9dCqx2BRFgLZJg:-O1EUU1B5HRS75Xbm0Cz:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/Cargo.toml#L42)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Why bring in real time support into this module?
</blockquote></details>

done

**Review by jhpratt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 4 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 200 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1ElrLb9_itSG1_8-tt:-O1ElrLb9_itSG1_8-tu:b-kt4cg6) ([raw file](https://github.com/TraceMachina/nativelink/blob/615a66fc38efe4cf5df4025f6951ab1d2908fc81/nativelink-store/tests/filesystem_store_test.rs#L200)):*
> ```XML
>     let separator = std::path::MAIN_SEPARATOR_STR;
>     format!(
>         "{}{separator}{}{separator}{}",
> ```

`make_temp_path` elsewhere in the repository apparently does not touch the OS file system, so the path separator does not matter. That is not the case here, so we need to use `\` for Windows and `/` for everything else. The standard library provides a constant (whose value is OS-dependent) for this purpose, which is what's used here.

One alternative, if it's desired, is to go through a proper `PathBuf`.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)* status: 0 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1590 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CmSNr-REviAkx4uTS:-O1HzZGG2n95BAqCm1fJ:bgowhrq) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1590)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

The `StoreKey` goes through SHA256 in `hash_key`, as is the case in `memory_store_test`. I could use the pre-existing method (namely `StoreKey::into_digest`) to auto-create it, but that uses the Blake3 hash. Presumably that would cause a compatibility issue?
</blockquote></details>

Hmmm, this is an oversite in the `FilesystemStore`. Can we fix `FilesystemStore` first then land this PR?

I know this PR is really close, but it will make the test much cleaner.

Here's some code I started:
https://gist.github.com/allada/dab6535799d044224c439f2ff97d4deb

I created a ticket here:
https://github.com/TraceMachina/nativelink/issues/1108
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 200 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1ElrLb9_itSG1_8-tt:-O1Hyz_q45RAfsOicsjA:bfyuae3) ([raw file](https://github.com/TraceMachina/nativelink/blob/615a66fc38efe4cf5df4025f6951ab1d2908fc81/nativelink-store/tests/filesystem_store_test.rs#L200)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

`make_temp_path` elsewhere in the repository apparently does not touch the OS file system, so the path separator does not matter. That is not the case here, so we need to use `\` for Windows and `/` for everything else. The standard library provides a constant (whose value is OS-dependent) for this purpose, which is what's used here.

One alternative, if it's desired, is to go through a proper `PathBuf`.
</blockquote></details>

Modern versions of windows worth with either since ~WindowsXP.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 205 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Hz5gd0ntleFvHK5g5:-O1Hz5gd0ntleFvHK5g6:b-hfpv23) ([raw file](https://github.com/TraceMachina/nativelink/blob/b1b4419cd3dc7ec54af203689f583909f4e728da/nativelink-store/tests/filesystem_store_test.rs#L205)):*
> ```XML
>     )
> 
>     // env::var_os("TEST_TMPDIR")
> ```

remove.

**Review by jhpratt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1075)* status: 0 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1590 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1CmSNr-REviAkx4uTS:-O1ILzdd8PrLDN8tgm_k:b-9zimos) ([raw file](https://github.com/TraceMachina/nativelink/blob/a73b80af91f6345a4e21f3488accadf8266741dc/nativelink-store/tests/filesystem_store_test.rs#L1590)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, this is an oversite in the `FilesystemStore`. Can we fix `FilesystemStore` first then land this PR?

I know this PR is really close, but it will make the test much cleaner.

Here's some code I started:
https://gist.github.com/allada/dab6535799d044224c439f2ff97d4deb

I created a ticket here:
https://github.com/TraceMachina/nativelink/issues/1108
</blockquote></details>

Sure, I'll take a look into that.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 200 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1ElrLb9_itSG1_8-tt:-O1IG3xmC__ZlSzQcC-C:b-jbghqd) ([raw file](https://github.com/TraceMachina/nativelink/blob/615a66fc38efe4cf5df4025f6951ab1d2908fc81/nativelink-store/tests/filesystem_store_test.rs#L200)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Modern versions of windows worth with either since ~WindowsXP.
</blockquote></details>

Is it capable of handling mixing and matching? CI was failing on Windows before this change, but it passes afterwards.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 205 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1075#-O1Hz5gd0ntleFvHK5g5:-O1IK5ENCuEL6HWi5lJ4:b-9a40rt) ([raw file](https://github.com/TraceMachina/nativelink/blob/b1b4419cd3dc7ec54af203689f583909f4e728da/nativelink-store/tests/filesystem_store_test.rs#L205)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done. That was me experimenting with `PathBuf` stuff and I forgot to remove it outright.

**Pull request closed without merging**
