### PR TITLE
ActionScheduler will now use ActionListener instead of tokio::watch

### PR DESCRIPTION
**Pull request by allada**
This will enable the underlying scheduler to intercept the Drop call allowing easier cleanups of actively listened actions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1091)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-:-O1DYyjS2c-hEhuVHBRd:b-gyszd7)* status: 0 of 1 LGTMs obtained, and pending CI: vale (waiting on @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1091)* status: 0 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 224 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1DtjhJBjUzXrD66FeI:-O1DtjhJBjUzXrD66FeJ:b-g73z37) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L224)):*
> ```XML
>                         };
>                         let Some(pending_txs) = maybe_pending_txs else {
>                             return; // Noone is waiting for this action anymore.
> ```

nit: Nobody
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1DuJCXBLsBLYADkjti:-O1DuJCXBLsBLYADkjtj:bfblu78) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L251)):*
> ```XML
> 
>             let maybe_pending_txs = {
>                 let mut cache_check_actions = cache_check_actions.lock();
> ```

Comment and rename `cache_check_actions`
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 255 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1DtzyY-Ul1c_kjDagb:-O1DtzyY-Ul1c_kjDagc:b-g73z37) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L255)):*
> ```XML
>             };
>             let Some(pending_txs) = maybe_pending_txs else {
>                 return; // Noone is waiting for this action anymore.
> ```

nit: Nobody
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 275 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1Dw3TM5i6UeHal3Z6R:-O1DuRqh4UgXE1gGDDGI:b-7vavkf) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L275)):*
> ```XML
>                 )
>             })?
>             .err_tip(|| "While passing through CacheLookupScheduler::add_action")
> ```

"In CacheLookupScheduler::add_action"

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1091)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 224 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1DtjhJBjUzXrD66FeI:-O1DwXeG-Egqf56Ux0eI:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L224)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

nit: Nobody
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1DuJCXBLsBLYADkjti:-O1DwZSuE1Uufpr1X1su:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L251)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Comment and rename `cache_check_actions`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 255 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1DtzyY-Ul1c_kjDagb:-O1DwoKY1OUiWz_xWmxD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L255)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

nit: Nobody
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 275 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-O1Dw3TM5i6UeHal3Z6R:-O1DwpNc1hE602Zn41c_:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/34da4f3c7f13b4a36a8ed31389bf5bb4fec99413/nativelink-scheduler/src/cache_lookup_scheduler.rs#L275)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

"In CacheLookupScheduler::add_action"
</blockquote></details>

Done.

**Review by zbirenbaum — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1091#-:-O1DxpYL39voBVVC4cnb:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
