### PR TITLE
Moves custom crates to nativelink dirs for disambiguation

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

Two crates, `error` and `proto` needed to be moved into nativelink specific dirs. 

## Type of change

Rename

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/483)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
With this, occurrences of `proto::` and `error::` need to be changed to `nativelink_proto::` and `nativelink_error::`.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/483#-:-NlccOPS0TCweTteY3eC:b5zdc55)* status: 0 of 31 files reviewed, all discussions resolved

**Review by MarcusSorealheis — COMMENTED** [review]
Addressed this 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/483#-:-NleC94p6USRE5ZM2mzG:b-17xdg0)* status: 0 of 110 files reviewed, all discussions resolved

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Mostly LGTM, but I thinkg you need to run 

```
  bazel run \
    --@rules_rust//:rustfmt.toml=//:.rustfmt.toml \
    @rules_rust//:rustfmt
```

To reorder the imports.

> Reviewed 30 of 31 files at r1, 80 of 80 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/483#-:-NleDX966RKFXC1h77K1:bwqymc1)* status: all files reviewed, 1 unresolved discussion (waiting on @MarcusSorealheis)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/483#-NleDHW92qp2r1lrYhBM):*
nit: Try to remember to capitalize the initial letter and remove the trailing period on merge.

**Review by aaronmondal — APPROVED** [review]
> Reviewed 79 of 79 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/483)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MarcusSorealheis)

**Review by aaronmondal — APPROVED** [review]
It's ok to merge this. Ignore the failing proto test. I can send a fix for that immediately after this PR is merged.

> Reviewed 6 of 14 files at r4, 1 of 8 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/483#-:-NlfiEi6Aka2MxYYw0Sq:behrll9)* status: 126 of 132 files reviewed, all discussions resolved (waiting on @allada)

**Pull request merged**
