### PR TITLE
Remove all need for workers to know about ActionId

### PR DESCRIPTION
**Pull request by allada**
Workers should only talk OperationId.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1125)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1125#-:-O1OTlbT65Dk-gTpcceF:b-djxp74)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @zbirenbaum)

**Review by zbirenbaum — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1125#-:-O1OcDIs4-xpVTtGoR0i:bg7igkv)* status: 1 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 756 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1125#-O1Ob42g-6k-TJ0qPCMY:-O1Ob42g-6k-TJ0qPCMZ:bve53mz) ([raw file](https://github.com/TraceMachina/nativelink/blob/44b087fe85404764a4b1df663630e792b8eacf97/nativelink-worker/tests/running_actions_manager_test.rs#L756)):*
> ```XML
>         let execute_request = ExecuteRequest {
>             action_digest: Some(action_digest.into()),
>             digest_function: ProtoDigestFunction::Blake3.into(),
> ```

Wasn't digest_function removed due to being unused in another PR?

**Review by adam-singer — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1125)* status: 1 of 2 LGTMs obtained, and 1 discussions need to be resolved

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1125)* status: 1 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-worker/tests/running_actions_manager_test.rs` line 756 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1125#-O1Ob42g-6k-TJ0qPCMY:-O1OzyH92_5eaNC6Cli1:bx6tx8g) ([raw file](https://github.com/TraceMachina/nativelink/blob/44b087fe85404764a4b1df663630e792b8eacf97/nativelink-worker/tests/running_actions_manager_test.rs#L756)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Wasn't digest_function removed due to being unused in another PR?
</blockquote></details>

No, that was the worker api proto had that message that was removed. This is the ReProto.

**Review by allada — COMMENTED** [review]
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1125#-:-O1P-8kU4uqcEU4hXwca:b-sd1e3m)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

**Pull request merged**
