### PR TITLE
Fix case where resource_name not set in stream error

### PR DESCRIPTION
**Pull request by allada**
The RBE protocol specifies that if the first message in a stream has the resource_name set all subsequent messages do not need to have it set. With this patch we now honor that requirement for GrpcStore hotpath.

closes: #745

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@aaronmondal
+@zbirenbaum 

fyi: @chrisstaite-menlo 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746#-:-Nse9CemAMbTI1hesFsU:b-euw0mn)* status: 0 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @aaronmondal and @zbirenbaum)

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746)* status: 0 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal and @zbirenbaum)

___
*[`nativelink-util/src/proto_stream_utils.rs` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/746#-Nse9ciyAVdmRDjBtD_U:-Nse9ciyAVdmRDjBtD_V:bmyg8kb) ([raw file](https://github.com/TraceMachina/nativelink/blob/ed68586440f0e1708d074bc6aa35516f96593703/nativelink-util/src/proto_stream_utils.rs#L1)):*
> ```XML
> // Copyright 2023-2024 The NativeLink Authors. All rights reserved.
> ```

fyi: Sadly the diff didn't help here, but this file is just removed parts of `grpc_store.rs` merged with `write_request_stream_wrapper.rs` renamed.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746)* status: 0 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal and @zbirenbaum)

___
*[`nativelink-util/src/proto_stream_utils.rs` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/746#-NseAJOn1GDWmm8q7dg9:-NseAJOn1GDWmm8q7dgA:b50mo61) ([raw file](https://github.com/TraceMachina/nativelink/blob/ed68586440f0e1708d074bc6aa35516f96593703/nativelink-util/src/proto_stream_utils.rs#L1)):*
> ```XML
> // Copyright 2023-2024 The NativeLink Authors. All rights reserved.
> ```

This link might be helpful:
https://www.diffchecker.com/VifJIlx2/

It's a copy-paste of what the merged files (only added, no modifications) diffed against the this new file.

**Review by zbirenbaum — APPROVED** [review]
:lgtm: 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746#-:-NseAO5iA6nmPVRgPEGi:bg7igkv)* status: 1 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @aaronmondal)

___
*[`nativelink-util/src/proto_stream_utils.rs` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/746#-NseAJOn1GDWmm8q7dg9:-NseB7e798lGiA7eXdV_:bxv5jtx) ([raw file](https://github.com/TraceMachina/nativelink/blob/ed68586440f0e1708d074bc6aa35516f96593703/nativelink-util/src/proto_stream_utils.rs#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This link might be helpful:
https://www.diffchecker.com/VifJIlx2/

It's a copy-paste of what the merged files (only added, no modifications) diffed against the this new file.
</blockquote></details>

Thanks, the diffchecker helps a ton

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746#-:-NseByv7-2ryI0BkyQCD:bnfp4nl)* status: 2 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable

___
*[`nativelink-util/src/proto_stream_utils.rs` line 123 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/746#-NseAxqc3mnF1c1saSmq:-NseAxqd5iH2sU2ciaxJ:b-5jrx1d) ([raw file](https://github.com/TraceMachina/nativelink/blob/ed68586440f0e1708d074bc6aa35516f96593703/nativelink-util/src/proto_stream_utils.rs#L123)):*
> ```XML
>         // If we successfully got a message, update our internal state with the
>         // message meta data.
>         let maybe_message = match maybe_message {
> ```

nit: Is there some way to make this `maybe_message` logic (and the `let` above) more readable?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/746)* status: 2 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, vale

___
*[`nativelink-util/src/proto_stream_utils.rs` line 123 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/746#-NseAxqc3mnF1c1saSmq:-NseHLPh6wYsjthqG8N4:b-umn4e7) ([raw file](https://github.com/TraceMachina/nativelink/blob/ed68586440f0e1708d074bc6aa35516f96593703/nativelink-util/src/proto_stream_utils.rs#L123)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Is there some way to make this `maybe_message` logic (and the `let` above) more readable?
</blockquote></details>

Done. This is about as far as I think we should take it.

**Pull request merged**
