### PR TITLE
Add Cloud Quickstart to Docs

### PR DESCRIPTION
**Pull request by blakehatch**
# Preview Deployment https://nativelink-docs-ie42aspyt-native-link-web-assets.vercel.app/

# Description

Adds cloud quickstart instructions to documentation and directs users to cloud web app.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/973)

### CODE REVIEW

**Review by MarcusSorealheis — COMMENTED** [review]
Am I correct to assume that this PR is still a draft? I wasn’t sure. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/973#-:-NzfxrLFBJxhSe7k-0ol:bl4ly0h)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks (waiting on @blakehatch)

**Comment by blakehatch** [comment]
> Am I correct to assume that this PR is still a draft? I wasn’t sure.
> 
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/973#-:-NzfxrLFBJxhSe7k-0ol:bl4ly0h)_ status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks (waiting on @blakehatch)

I can make it a draft but the content is just 1:1 reflected from the cloud app.

**Comment by MarcusSorealheis** [comment]
@aaronmondal what do you think about Stale bots like https://github.com/actions/stale

**Comment by aaronmondal** [comment]
@MarcusSorealheis generally seems useful, although I also feel like stale prs/issues are still "manually" manageable. No strong opinion whether we should automate this.

@blakehatch closing this one as it's outdated and was already added to the doch in other changes.

**Pull request closed without merging**
