### PR TITLE
Remove unused proto field

### PR DESCRIPTION
**Pull request by allada**
Removes unused proto field in worker api.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1117)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1117#-:-O1KDg4N65DyrJRmVI86:b-bn1n1c)* status: 0 of 1 LGTMs obtained, and pending CI: vale (waiting on @adam-singer)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1117#-:-O1KJexDBgKRKkF_04Hh:bnfp4nl)* status: 0 of 1 LGTMs obtained (waiting on @adam-singer)

**Review by allada — COMMENTED** [review]
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1117#-:-O1KL-lQ11RD7i6wZUAp:b-quuhec)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by adam-singer — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1117#-:-O1Kp1v20G5CMvXKrJS3:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
