### PR TITLE
Move ActionSchedulerListener to ActionStateResult

### PR DESCRIPTION
**Pull request by allada**
These APIs were near identical and with the new scheduler/worker design
we will be eventually removing the ActionScheduler API and moving it to
the ClientStateManager API (eventually renamed).

towards #1213

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 
+@zbirenbaum 

There's 2 patches in-flight, so please review just last commit of this PR. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237#-:-O3a5DIiCtGa3q-sputq:b-lxjq3m)* status: 0 of 2 LGTMs obtained, and 0 of 38 files reviewed, and pending CI: Analyze (javascript-typescript), pre-commit-checks, vale (waiting on @adam-singer and @zbirenbaum)

**Review by allada — COMMENTED** [review]
Dependent PRs are landed, so full review is preferred.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237#-:-O3cZ5a27CEgzXCzkqu2:b-7y3tll)* status: 0 of 2 LGTMs obtained, and 0 of 38 files reviewed, and pending CI: pre-commit-checks (waiting on @adam-singer and @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237#-:-O3d9gnr4GxAwmEsBwPj:bg7igkv)* status: 1 of 2 LGTMs obtained, and 4 of 38 files reviewed, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 83 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1237#-O3dA9e47dQ5qYc045cs:-O3dA9e47dQ5qYc045ct:bsezigt) ([raw file](https://github.com/TraceMachina/nativelink/blob/c159e7efdaa3cc8d81df3ca50b93e8bff76a64c7/nativelink-scheduler/src/simple_scheduler.rs#L83)):*
> ```XML
>             .await
>             .err_tip(|| "In SimpleSchedulerActionStateResult")?;
>         Arc::make_mut(&mut action_state).operation_id = self.client_operation_id.clone();
> ```

Nit: can we document this? I'm a little confused on why the operation ID here is set to client operation id. Previously it was a separate field.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237)* status: 1 of 2 LGTMs obtained, and 4 of 38 files reviewed (waiting on @adam-singer)

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 83 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1237#-O3dA9e47dQ5qYc045cs:-O3dKZdAC44NRwLMD5MY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c159e7efdaa3cc8d81df3ca50b93e8bff76a64c7/nativelink-scheduler/src/simple_scheduler.rs#L83)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Nit: can we document this? I'm a little confused on why the operation ID here is set to client operation id. Previously it was a separate field.
</blockquote></details>

Done.

**Review by adam-singer — COMMENTED** [review]
> Reviewed 13 of 14 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237)* status: 1 of 2 LGTMs obtained, and 14 of 38 files reviewed

**Review by allada — COMMENTED** [review]
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237#-:-O3fAZZD4SNGvr0NOhy-:b-sd1e3m)* status: 1 of 1 LGTMs obtained, and 14 of 38 files reviewed

**Review by allada — COMMENTED** [review]
> Reviewed 13 of 14 files at r3, 24 of 24 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1237)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
