### PR TITLE
Set max line length to Rust's defaults

### PR DESCRIPTION
**Pull request by aaronmondal**
... which is 100 🫠

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@allada +@zbirenbaum +@MarcusSorealheis +@adam-singer 

Inspired by a conversation in https://github.com/TraceMachina/nativelink/pull/748 noting that we sometimes have some hard-to-read long lines.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750#-:-NsiswnrAHs5IrvxbE5d:bjrbqdo)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer, @allada, @MarcusSorealheis, and @zbirenbaum)

**Review by adam-singer — COMMENTED** [review]
Is the default style guide 100 not 99 ? https://doc.rust-lang.org/nightly/style-guide/#:~:text=Use%20spaces%2C%20not%20tabs.,a%20line%20is%20100%20characters. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750#-:-NsjCKGSAF1JtnISL7sK:bmr4n6u)* status: 0 of 4 LGTMs obtained (waiting on @allada, @MarcusSorealheis, and @zbirenbaum)

**Review by zbirenbaum — COMMENTED** [review]
I was under the impression that it's 100 as well

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750#-:-NsjFAz_622Cmd9XVtim:bxf1hv4)* status: 0 of 4 LGTMs obtained (waiting on @adam-singer, @allada, and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
Oh yeah looks like my information was outdated: https://github.com/rust-lang/rust-guidelines/pull/12

I updated the commit message. The value is "set to default" by removing the `max_width` line in `.rustfmt.toml`, so this PR is already using the 100 line length limit.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750#-:-NsjLn9lCN5OGzPLOLX7:b-6kn2kd)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, zig-cc ubuntu-20.04 (waiting on @adam-singer, @allada, @MarcusSorealheis, and @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
I'm less invested in what the setting is and more of "we have a setting we like and is enforced by tooling", so with that reasoning will give a shipit. I do wonder if "now is the right time" to land this change, usually these kind of sweeping changes of formatting bork others reviews/rebase. If nothing big in flight and we are good with the setting, :lgtm: 

> Reviewed 93 of 93 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750#-:-NsjuVhSD19boGg6oGqX:bbomffn)* status: 1 of 4 LGTMs obtained (waiting on @allada, @MarcusSorealheis, and @zbirenbaum)

**Review by aaronmondal — COMMENTED** [review]
-@zbirenbaum -@allada -@MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/750#-:-Nsjy8gyBhnC369xtsEB:b8ee0vk)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
