### PR TITLE
Fix `cargo test -p nativelink-store` after 4896b5c

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1540)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
Observed in https://github.com/TraceMachina/nativelink/pull/1489

+@allada

cc @KGrewal1

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1540#-:-OE12-e42-NT-h0X3HYy:bu2a8i7)* status: 0 of 1 LGTMs obtained, and 0 of 2 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @allada)

**Comment by KGrewal1** [comment]
Running this locally fixes the compile issue! Guess it was due to how rust handles feature unification across workspaces, meaning it only showed up when running `cargo test -p nativelink-store`

**Review by SchahinRohani — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1540#-:-OE1Fy-OBPsd43Dh2qFz:bnfp4nl)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: NativeLink.com Cloud / Remote Cache / macos-14 (waiting on @allada)

**Review by aaronmondal — COMMENTED** [review]
-@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1540#-:-OE1HjDaBZIsTdIqmf8U:b-r9zead)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
