### PR TITLE
QA fixes for scheduler-v2

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description
Introduces various code quality improvements to scheduler-v2 which allow bazel test to pass.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)

### CODE REVIEW

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and pending CI: vale, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 258 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18sdN00gt_CFGpxTTD:-O18sdN00gt_CFGpxTTE:bjt952r) ([raw file](https://github.com/TraceMachina/nativelink/blob/7e1d597c929b85a8ae1d2e9328c2b91772672326/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L258)):*
> ```XML
>         let timestamp = (insert_timestamp ^ u64::MAX).to_be_bytes();
> 
>         // TODO: I can't find a way to make clippy not complain about this that doesn't introduce another complaint.
> ```

Using  `#[cfg_attr(rustfmt, rustfmt_skip)]` gives a clippy deprecation error to use `#[rustfmt::skip]` but using `#[rustfmt::skip]` on just this line instead of the function gives a different error regarding experimental feature usage.
___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 283 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18sUTC8clkLLgYBFb6:-O18sUTC8clkLLgYBFb7:bpwoln2) ([raw file](https://github.com/TraceMachina/nativelink/blob/7e1d597c929b85a8ae1d2e9328c2b91772672326/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L283)):*
> ```XML
> // Ensure the size of the sort key is the same as a `u64`.
> assert_eq_size!(AwaitedActionSortKey, u128);
> ```

I'm not sure what to do about this whole code section tbh.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18sLiSCd3yWBXNLfgA:-O18sLiSCd3yWBXNLfgB:b62eg9l) ([raw file](https://github.com/TraceMachina/nativelink/blob/7e1d597c929b85a8ae1d2e9328c2b91772672326/nativelink-scheduler/src/scheduler_state/state_manager.rs#L114)):*
> ```XML
>     }
> 
>     #[allow(clippy::mutable_key_type)]
> ```

Can we find some way to not use mutable keys?

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and 5 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 284 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18uANv8M6Mgk1o3uhS:-O18uANv8M6Mgk1o3uhT:bxlp265) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L284)):*
> ```XML
> assert_eq_size!(AwaitedActionSortKey, u128);
> 
> // TODO: Shouldn't these be tests? Why are we inlining asserts here.
> ```

I'm not sure what to do about this whole section.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 259 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18uHpYDtS00TSQDE_1:-O18uHpYDtS00TSQDE_2:b-c2tdka) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L259)):*
> ```XML
>     }
> 
>     // TODO: ActionInfo isn't an error. The compiler wants to box this
> ```

Remove comment once implementation is given the goahead.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 300 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18uVjz2wBaY6eQlTgg:-O18uVjz2wBaY6eQlTgh:blq72dc) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L300)):*
> ```XML
>                     });
>             let Some(mut sorted_awaited_action) = maybe_sorted_awaited_action else {
>                 // TODO: Either use event on all of the above error here, but both is overkill.
> ```

Address this comment.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and 8 discussions need to be resolved

___
*[`nativelink-scheduler/BUILD.bazel` line 58 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18vGP54htyyn6tF0g0:-O18vGP54htyyn6tF0g1:b-jn7l7s) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/BUILD.bazel#L58)):*
> ```Starlark
>         "@crates//:serde",
>         "@crates//:serde_json",
>         "@crates//:static_assertions",
> ```

@jhpratt said that we can use `assert!()` now instead as of recent versions of rust... maybe we should try?
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18vZZrCoIP-qXTdoAT:-O18vZZrCoIP-qXTdoAU:bsybmos) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/cache_lookup_scheduler.rs#L47)):*
> ```XML
> use crate::platform_property_manager::PlatformPropertyManager;
> 
> // TODO: Document this type. Why is it only used in CacheLookupScheduler for subscription.
> ```

```rs
/// A future containing the resolved `ClientOperationId` once it is figured out.
/// This future may be cloned and will always yield the same value once resolved.
type SubscriptionFuture = SharedFuture<oneshot::Receiver<ClientOperationId>>;
```
___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 284 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18uANv8M6Mgk1o3uhS:-O18wK8XBcr7WeS5rPux:b-42rtk9) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L284)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

I'm not sure what to do about this whole section.
</blockquote></details>

We could make them tests, but since this entire struct is `const`, we can just make the compiler test the functions for us.

No need to build a binary for these, when the compiler can test it.
___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 365 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18wea70aJ673KZa23p:-O18wea70aJ673KZa23q:b-zi2enl) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L365)):*
> ```XML
>                 .get_worker_id()
>                 .map_or(String::new(), |v| v.to_string())
>                 .to_string(),
> ```

nit: `.to_string()` probably not needed here.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and 8 discussions need to be resolved

___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18vZZrCoIP-qXTdoAT:-O18xu0CAgPXI7Lr9gkz:b-28mc0t) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/cache_lookup_scheduler.rs#L47)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

```rs
/// A future containing the resolved `ClientOperationId` once it is figured out.
/// This future may be cloned and will always yield the same value once resolved.
type SubscriptionFuture = SharedFuture<oneshot::Receiver<ClientOperationId>>;
```
</blockquote></details>

Actually:
```rs
/// A future containing the resolved `ClientOperationId` once it is figured out.
/// This future may be cloned and will always yield the same value once resolved.
type ClientOperationIdFuture = SharedFuture<oneshot::Receiver<ClientOperationId>>;
```

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and pending CI: vale, and 5 discussions need to be resolved

___
*[`nativelink-scheduler/BUILD.bazel` line 58 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18vGP54htyyn6tF0g0:-O19GcOxDeFfZEaqdeVP:b2ncqjo) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/BUILD.bazel#L58)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

@jhpratt said that we can use `assert!()` now instead as of recent versions of rust... maybe we should try?
</blockquote></details>

I tried this but couldn't get any of it to compile using the `assert!` equivalents. 
___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 47 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18vZZrCoIP-qXTdoAT:-O19GqthDe-LhwlNsALR:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/cache_lookup_scheduler.rs#L47)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Actually:
```rs
/// A future containing the resolved `ClientOperationId` once it is figured out.
/// This future may be cloned and will always yield the same value once resolved.
type ClientOperationIdFuture = SharedFuture<oneshot::Receiver<ClientOperationId>>;
```
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18sLiSCd3yWBXNLfgA:-O19GSPS4UZowqFbC1gn:b-1l2ycy) ([raw file](https://github.com/TraceMachina/nativelink/blob/7e1d597c929b85a8ae1d2e9328c2b91772672326/nativelink-scheduler/src/scheduler_state/state_manager.rs#L114)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Can we find some way to not use mutable keys?
</blockquote></details>

Discussed offline. Added to top level so only one ignore is necessary.

**Review by allada — COMMENTED** [review]
> Reviewed 11 of 15 files at r1, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and 7 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 255 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O1CnkPWE823eIg9DY0E:-O1CnkPWE823eIg9DY0F:bqpvhvq) ([raw file](https://github.com/TraceMachina/nativelink/blob/a5c750a6c5354bb0a2a409999b88d8a8e26474e4/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L255)):*
> ```XML
>         let priority = ((priority as i64 + MIN_I32) as u32).to_be_bytes();
> 
>         let timestamp = (insert_timestamp ^ u64::MAX).to_be_bytes();
> ```

nit: While here can we say:
```rs
// Invert our timestamp so the larger the timestamp the lower the number.
// This makes timestamp descending order instead of ascending.
```
___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 283 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O1Co2gy628qjHbib90d:-O1Co2gy628qjHbib90e:bdabcfu) ([raw file](https://github.com/TraceMachina/nativelink/blob/a5c750a6c5354bb0a2a409999b88d8a8e26474e4/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L283)):*
> ```XML
> 
> // TODO: Shouldn't these be tests? Why are we inlining asserts here.
> // Also there are a ton of complaints about every part of this and it's not maintainable code.
> ```

Then just fix it. Don't write a comment in the code complaining unless there's a clear path on how to fix it.
___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 292 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O1CoCL50ailkmbjDc0C:-O1CoCL50ailkmbjDc0D:b-tcnmc7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a5c750a6c5354bb0a2a409999b88d8a8e26474e4/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L292)):*
> ```XML
>     // This effectively inverts the priority to now have the highest priority
>     // be the lowest timestamps.
>     AwaitedActionSortKey(0x9234_5678_6543_210f_edcb_a987_9abc_def0).0
> ```

nit: Is this required? The underscores on the original was done that way to show where the different variables live:
```
0x92345678_6543210fedcba987_9abcdef0
-priority-_----timestamp---_--hash--
```
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 259 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18uHpYDtS00TSQDE_1:-O1CpSwzAHzxg8FgL109:b-tgd7y2) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L259)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Remove comment once implementation is given the goahead.
</blockquote></details>

Looking over the code, it looks like we should instead be passing in `unique_qualifier: &ActionInfoHashKey` and `priority: i32`

This will solve both problems if we rewrite this.

We might also want to make the return:
`Result<Option<Arc<ClientActionStateResult>>, Error>`
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 300 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O18uVjz2wBaY6eQlTgg:-O1CpsI3A0C2Aa5R1Y67:bsvykzk) ([raw file](https://github.com/TraceMachina/nativelink/blob/a72ea49324e3a1353ccf3679edd72711c2eeab9c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L300)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Address this comment.
</blockquote></details>

If this happens it's kind of a big deal. If these get out of sync we have major problems, and worried about not being loud enough.

I would say we event and return an error here.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 445 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O1CqTDHDHMPAFkjIf2h:-O1CqTDHDHMPAFkjIf2i:b-g61o5f) ([raw file](https://github.com/TraceMachina/nativelink/blob/a5c750a6c5354bb0a2a409999b88d8a8e26474e4/nativelink-scheduler/src/scheduler_state/state_manager.rs#L445)):*
> ```XML
>             let inner = state.inner.lock().await;
> 
>             #[allow(clippy::mutable_key_type)]
> ```

needed still?

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/awaited_action.rs` line 283 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O1Co2gy628qjHbib90d:-O1Dl58s1jLKZnDWyWCD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a5c750a6c5354bb0a2a409999b88d8a8e26474e4/nativelink-scheduler/src/scheduler_state/awaited_action.rs#L283)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Then just fix it. Don't write a comment in the code complaining unless there's a clear path on how to fix it.
</blockquote></details>

Done.

**Review by zbirenbaum — COMMENTED** [review]
> Dismissed @allada from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1089)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 445 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1089#-O1CqTDHDHMPAFkjIf2h:-O1Do8-520L0vjylgF6b:b2nhswy) ([raw file](https://github.com/TraceMachina/nativelink/blob/a5c750a6c5354bb0a2a409999b88d8a8e26474e4/nativelink-scheduler/src/scheduler_state/state_manager.rs#L445)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

needed still?
</blockquote></details>

Yes

**Comment by zbirenbaum** [comment]
Merged in #1092

**Pull request closed without merging**
