### PR TITLE
Revert "Release NativeLink v0.3.0"

### PR DESCRIPTION
**Pull request by aaronmondal**
Reverts TraceMachina/nativelink#838

The tag workflow is broken and needs to be fixed first.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/843)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@blakehatch

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/843#-:-Nv45-LU9cn_6jVm0Zak:bb2hqjt)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @blakehatch)

**Review by blakehatch — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/843#-:-Nv456wICsq0Aly1OCNv:bg7igkv)* status: 1 of 3 LGTMs obtained (waiting on @adam-singer and @allada)

**Review by aaronmondal — COMMENTED** [review]
-@allada -@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/843#-:-Nv45Nfp10rPHbVJHWmy:b-y3f1vg)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by blakehatch — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/843)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
