### PR TITLE
Support remote build execution on main and read-only remote cache on PRs

### PR DESCRIPTION
**Pull request by bclark8923**
# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
I think it's good to have this as an example, but it should be clearly marked in a way that doesn't suggest that we encourage this way of implementing remote execution.

- If this is intended to be an example on how to do remote execution with legacy setups we should add documentation for this approach and clearly mark it as a "toy" example, perhaps with a single cpp file or some external repo like abseil.
- If this is intended as reference implementation to speed up our own build this should generate a `rust_toolchain` configuration and conditionally enable that via a flake module that generates a .bazelrc file. This way we fully control the toolchain, have reproducibility across machines and can reuse the CI cache during local invocations.

In both cases we should have a corresponding k8s deployment for the `native-cli` to test this without the cloud as well.

> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277#-:-O50kkqN38zw3A071wNf:b-7avo5d)* status: 0 of 1 LGTMs obtained, and 5 of 7 files reviewed, and pending CI: nativelink-dot-com-rbe-test, and 1 discussions need to be resolved

___
*[`.container` line 1 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1277#-O50kKSX94RT3MEHG7d4:-O50kKSX94RT3MEHG7d5:btcc0ao) ([raw file](https://github.com/TraceMachina/nativelink/blob/5b39ce03b3543c3edb85020077eda726d0edc67b/.container#L1)):*
> ```
> 299166832260.dkr.ecr.us-east-2.amazonaws.com/nativelink-rbe:b9eb8103fa5015e670791232062ba40c492866c3250fe575216a532a90c22e43
> ```

What is this file?

**Review by adam-singer — APPROVED** [review]
@aaronmondal do we no longer need to use create-worker.nix in this kind of setup? 


:lgtm:

> Reviewed 2 of 5 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277#-:-O5JasP73ky_68U2bKH2:bickkh4)* status: 1 of 1 LGTMs obtained, and 5 of 7 files reviewed, and 1 discussions need to be resolved

**Review by bclark8923 — COMMENTED** [review]
> Dismissed @aaronmondal from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277)* status: 1 of 1 LGTMs obtained, and 5 of 7 files reviewed

___
*[`.container` line 1 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1277#-O50kKSX94RT3MEHG7d4:-O5PE6P3Ey-HFzv8SbTb:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/5b39ce03b3543c3edb85020077eda726d0edc67b/.container#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

What is this file?
</blockquote></details>

Done.

**Review by bclark8923 — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277#-:-O5PRYhu8rFPW9GQgoPp:bnfp4nl)* status: 2 of 1 LGTMs obtained, and all files reviewed, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, nativelink-dot-com-cache-cloud-legacy-dockerfile-test

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277)* status: 2 of 1 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04

**Review by bclark8923 — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1277)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
