### PR TITLE
Cache Pruning and Promoting Functionality Added

### LINKED ISSUE #329: S3 Action Cache Cleaner
Create rust program to walk S3 Action Cache and delete un-referenced items not in the n items most recently used under a certain age threshold.

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

Adds functionality for walking the Action Cache to promote items to the ideal order and allowing the CAS to prune itself in the EvictingMap.

Fixes #329

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tests if the items being promoted to the top of the LRU cache are in the correct old -> new order.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/346)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @blakehatch)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 90 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiAUNIn7N5TNfxSJi9v:-NiAUNIn7N5TNfxSJi9w:bi3nmc1) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L90)):*
> ```XML
> 
> async fn sort_digests_old_to_new(
>     digests: Vec<DigestInfo>,
> ```

nit: Since we are not taking ownership of this `Vec` we should not force the caller to materialize it into a vec if it is not needed.

So, use `impl Iterator<DigestInfo>` instead. This will allow the compiler to possibly optimize here if it can.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 92 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiAUpTC4RLBwCEfRADP:-NiAUpTC4RLBwCEfRADQ:b-7vguxa) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L92)):*
> ```XML
>     digests: Vec<DigestInfo>,
>     ac_store: &Arc<(dyn Store + 'static)>,
> ) -> Result<Vec<DigestInfo>, Error> {
> ```

nit: Similar to above, try and pass out an iterator here. It also gives the compiler visibility into optimization possibilities.

eg: `Result<impl Iterator<DigestInfo>>`
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 93 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiAUEgg6WiVNZEEBIx1:-NiAUEgg6WiVNZEEBIx2:b-d8ro22) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L93)):*
> ```XML
>     ac_store: &Arc<(dyn Store + 'static)>,
> ) -> Result<Vec<DigestInfo>, Error> {
>     let mut digest_times: Vec<(DigestInfo, SystemTime)> = Vec::new();
> ```

nit: `Vec::with_capacity(digests.len())`

This will save a few mallocs.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 95 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiASgVq2NG_A9QMroun:-NiASgVq2NG_A9QMrouo:b-dfx9bj) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L95)):*
> ```XML
>     let mut digest_times: Vec<(DigestInfo, SystemTime)> = Vec::new();
>     for digest in &digests {
>         let action_result = get_action_from_store(ac_store, digest, "".to_string());
> ```

Why not just `.await` here?
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 96 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiATD-y3S3C5X0qokOn:-NiATD-zAEikj_Zofi3e:b8rsgkv) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L96)):*
> ```XML
>     for digest in &digests {
>         let action_result = get_action_from_store(ac_store, digest, "".to_string());
>         let action_result = action_result.await.unwrap();
> ```

It would be easier if you convert this to an `action_messages::ActionResult` using `to_execute_response` first.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 96 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiATDk95ND015RudBLC:-NiATDk95ND015RudBLD:b3s8vdv) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L96)):*
> ```XML
>     for digest in &digests {
>         let action_result = get_action_from_store(ac_store, digest, "".to_string());
>         let action_result = action_result.await.unwrap();
> ```

Nit: We avoid `.unwrap()` as it causes a panic, instead use `.err_tip(|| "some message")?`
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 115 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiAVA3y0ePJtNpGpHGv:-NiAVA3y0ePJtNpGpHGw:b-i7dha0) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L115)):*
> ```XML
> 
> pub async fn walk_ac_and_order_items(
>     digests: Vec<DigestInfo>,
> ```

nit: Also use iterator.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 116 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiAVF2aERA5NW3WxYVa:-NiAVF2aERA5NW3WxYVb:b-21yiym) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L116)):*
> ```XML
> pub async fn walk_ac_and_order_items(
>     digests: Vec<DigestInfo>,
>     ac_store: &Arc<dyn Store>,
> ```

nit: Pass: `Pin<&dyn Store>`. This will give the caller more freedom.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 95 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiASgVq2NG_A9QMroun:-NiCei8k9M5pX6oC-Z1e:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L95)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Why not just `.await` here?
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 96 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiATD-y3S3C5X0qokOn:-NiCek4jB7xzhiL3_1IA:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L96)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It would be easier if you convert this to an `action_messages::ActionResult` using `to_execute_response` first.
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 116 at r2](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiAVF2aERA5NW3WxYVa:-NiCeu0d3PVDBSsXI1nA:bg19eic) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/fdbde16f8c35848689a576783908615e301690ca/cas/scheduler/cache_lookup_scheduler.rs#L116)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Pass: `Pin<&dyn Store>`. This will give the caller more freedom.
</blockquote></details>

Can't convert `Pin<&dyn Store>` to `&Arc<dyn Store>`, would have to change too many external functions such as `get_action_from_store` that would be out of scope of this PR.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @blakehatch)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 94 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGg7LB6LeOdn4OJ7wE:-NiGg7LCE6o8PSr3EbP6:bclw93n) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L94)):*
> ```XML
> ) -> Result<impl Iterator<Item = DigestInfo>, Error> {
>     let digests_vec: Vec<_> = digests.collect();
>     let mut digest_times: Vec<(DigestInfo, SystemTime)> = Vec::with_capacity(digests_vec.len());
> ```

If you want to declare the type, use `Vec::<(DigestInfo, SystemTime)>::with_capacity(digests_vec.len());`

But don't declare the type unless it's not clear. Rust can figure it the type.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 102 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgi2Q1cB10uIxVI81:-NiGgi2Q1cB10uIxVI82:b-i9cwo1) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L102)):*
> ```XML
>         let execution_metadata = action_result
>             .execution_metadata
>             .ok_or_else(|| tonic::Status::new(Code::Unknown, "Execution metadata is missing".to_string()))?;
> ```

nit: Use `.err_tip()`
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 104 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgzJW1cc3aiGk9vdm:-NiGgzJW1cc3aiGk9vdn:bu79isr) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L104)):*
> ```XML
>             .ok_or_else(|| tonic::Status::new(Code::Unknown, "Execution metadata is missing".to_string()))?;
> 
>         let completion_time: SystemTime = match execution_metadata.execution_completed_timestamp {
> ```

nit: Don't use this. Rely on the order from the input args.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 134 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGhQUZEuKbv3yWeQa0:-NiGhQUZEuKbv3yWeQa1:b-rlybao) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L134)):*
> ```XML
> 
>     for digest in sorted_digests.clone() {
>         pinned_store.has(digest).await?;
> ```

nit: Use `.has_with_results()` it is much more optimized for this use case.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @allada)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 94 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGg7LB6LeOdn4OJ7wE:-NiH-gML97P2qQJH8QBn:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L94)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

If you want to declare the type, use `Vec::<(DigestInfo, SystemTime)>::with_capacity(digests_vec.len());`

But don't declare the type unless it's not clear. Rust can figure it the type.
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 102 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgi2Q1cB10uIxVI81:-NiH-m0B6mt6oqBHpGr5:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L102)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Use `.err_tip()`
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 104 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgzJW1cc3aiGk9vdm:-NiH2tqkE6oOvBlHagIR:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L104)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Don't use this. Rely on the order from the input args.
</blockquote></details>

Done.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 134 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGhQUZEuKbv3yWeQa0:-NiH2s6U0DsYQJVDu69B:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L134)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Use `.has_with_results()` it is much more optimized for this use case.
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, all discussions resolved

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 102 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgi2Q1cB10uIxVI81:-NiKt2pYBmfn3tt8WGwO:bacw3t3) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L102)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Use `make_err!(Code::Internal, "...")`
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 104 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgzJW1cc3aiGk9vdm:-NiKtJY28rg9fHItz7Ox:ba74t74) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L104)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Still, I don't think you should sort at all. The input order is your sort key.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @blakehatch)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 127 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiKuiEq4hbUVnqF1mDE:-NiKuiErDAWOGtSGY2HZ:b7b52j2) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/a4be00dfa617d2fa7e22089bffb984732c5e906d/cas/scheduler/cache_lookup_scheduler.rs#L127)):*
> ```XML
> 
> pub async fn walk_ac_and_order_items(
>     digests: impl Iterator<Item = DigestInfo>,
> ```

Since now you are needing the data as a slice, require the caller to bring it in as a slice. This will remove the need to make a copy of the data (`.collect()` will copy the data) if not needed.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 137 at r6](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiKuywS9kMMahSHEe95:-NiKuywS9kMMahSHEe96:ba5fuli) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/a4be00dfa617d2fa7e22089bffb984732c5e906d/cas/scheduler/cache_lookup_scheduler.rs#L137)):*
> ```XML
>     pinned_store.has_with_results(&digests_vec, &mut results).await?;
> 
>     Ok(digests_vec.into_iter())
> ```

if any of the `results` are `None` we probably want to flag the digest to be removed. Probably a good idea to return the failed items.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @blakehatch)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 102 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgi2Q1cB10uIxVI81:-Ni_MPUJ8SXt6WD4a2Mw:boiym3f) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L102)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like it was changed.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 104 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgzJW1cc3aiGk9vdm:-Ni_MSWP7BkVnNLaxokR:b7imacw) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L104)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

I made the sorting function public so it can be used on the input before it's put into the action cache walker function instead of using it internally in the action cache walker. Can remove it if preferred.
</blockquote></details>

Yeah, I still feel this function should not be the one to do the sorting, it should be the caller that does the sorting.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 134 at r7](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-Ni_KIAPAWQ947m28TTh:-Ni_KIAPAWQ947m28TTi:bhb2lwe) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/4a226e37a395a40c9966dbf64a3dfc66bcfa6940/cas/scheduler/cache_lookup_scheduler.rs#L134)):*
> ```XML
>     pinned_store.has_with_results(digests, &mut results).await?;
> 
>     let mut remove_digests = Vec::new();
> ```

nit: You can potentially save an allocation using:

```rs
use std::iter::zip;
Ok(zip(digests, results).filter_map(|(digest, result)| result.map_or_else(|| Some(digest), |_| None)).collect())
```

**Review by allada — COMMENTED** [review]
looks good, but lets do the verification store changes first.

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-:-Nibqmwq2YzW41ip_-q4:bsbhbj6)* status: 1 of 2 files reviewed, all discussions resolved

**Review by blakehatch — COMMENTED** [review]
Yes prioritizing those

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-:-Nijc36Q8ObONqkWS1Xr:b-gatlax)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @allada)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 102 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgi2Q1cB10uIxVI81:-Ni__1c1Ezp1rRVuPkbJ:bp7oczq) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L102)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Doesn't look like it was changed.
</blockquote></details>

Got removed with the function.
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 104 at r5](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-NiGgzJW1cc3aiGk9vdm:-Ni_Zkd5AzY-dfJ2jq_b:b-c3dros) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/35ee96a8efa1b8195cc2af8f99f1376369b88668/cas/scheduler/cache_lookup_scheduler.rs#L104)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, I still feel this function should not be the one to do the sorting, it should be the caller that does the sorting.
</blockquote></details>

Makes sense, removed it!
___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 134 at r7](https://reviewable.io/reviews/TraceMachina/turbo-cache/346#-Ni_KIAPAWQ947m28TTh:-Nijc-j9EE6EH2N4GjUx:b-896fix) ([raw file](https://github.com/TraceMachina/turbo-cache/blob/4a226e37a395a40c9966dbf64a3dfc66bcfa6940/cas/scheduler/cache_lookup_scheduler.rs#L134)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: You can potentially save an allocation using:

```rs
use std::iter::zip;
Ok(zip(digests, results).filter_map(|(digest, result)| result.map_or_else(|| Some(digest), |_| None)).collect())
```
</blockquote></details>

Done.

**Review by blakehatch — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/346#-:-NjOr8no1nuPhxL4mz08:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @allada)

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/346)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @blakehatch)

___
*[`-- commits` line 8 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiAZoH3NWfpAPn3iSD):*
nit: Merge these into the same commit.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 203 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiALgQ8VQ6HOEYSJP8:-NjiALgQ8VQ6HOEYSJP9:b-j7foe5) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L203)):*
> ```XML
>         };
> 
>         // let action_result3 = ActionResult {
> ```

nit: Needless comments.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 213 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiANsF7SzFU6NevMZk:-NjiANsF7SzFU6NevMZl:b-j7foe5) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L213)):*
> ```XML
>         let proto_action_result1: ProtoActionResult = action_result1.into();
>         let proto_action_result2: ProtoActionResult = action_result2.into();
>         //let proto_action_result3: ProtoActionResult = action_result3.into();
> ```

nit: Needless comments.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 223 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiAOIt-pB6UbJWUrHV:-NjiAOIt-pB6UbJWUrHW:b-j7foe5) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L223)):*
> ```XML
>         proto_action_result2.encode(&mut bytes)?;
>         pinned_store.update_oneshot(file2_digest, bytes.clone().into()).await?;
>         //bytes.clear();
> ```

nit: Needless comments.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 233 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiAQ-pCHRZOqBuxMNh:-NjiAQ-pCHRZOqBuxMNi:bt08wza) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L233)):*
> ```XML
>         let remove_digests = walk_ac_and_order_items(&digests, &store).await?;
> 
>         println!("DIGESTS TO REMOVE");
> ```

nit: Needless println.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 235 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiARdIDeew9K1QAR_h:-NjiARdIDeew9K1QAR_i:bt08wza) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L235)):*
> ```XML
>         println!("DIGESTS TO REMOVE");
> 
>         println!("{:?}", remove_digests);
> ```

nit: Needless println.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/346)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @allada)

___
*[`-- commits` line 8 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiAZoH3NWfpAPn3iSD):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Merge these into the same commit.
</blockquote></details>

Done.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 203 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiALgQ8VQ6HOEYSJP8:-NjmKc_rBrIJaYBl6jJV:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L203)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needless comments.
</blockquote></details>

Done.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 213 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiANsF7SzFU6NevMZk:-NjmKdPS-w0ya8_sLBRt:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L213)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needless comments.
</blockquote></details>

Done.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 223 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiAOIt-pB6UbJWUrHV:-NjmKe3xEcosE1xhWKoT:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L223)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needless comments.
</blockquote></details>

Done.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 233 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiAQ-pCHRZOqBuxMNh:-NjmKi9AEgDLbV38ob8i:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L233)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needless println.
</blockquote></details>

Done.
___
*[`cas/scheduler/tests/cache_lookup_scheduler_test.rs` line 235 at r8](https://reviewable.io/reviews/tracemachina/native-link/346#-NjiARdIDeew9K1QAR_h:-NjmKiuU4U64OQ23YD3r:b-896fix) ([raw file](https://github.com/tracemachina/native-link/blob/196b4605506fcbdb20c4cdafb2979041ed53bc84/cas/scheduler/tests/cache_lookup_scheduler_test.rs#L235)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Needless println.
</blockquote></details>

Done.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/native-link/346)* status: all files reviewed, 1 unresolved discussion (waiting on @blakehatch)

___
*[`cas/scheduler/cache_lookup_scheduler.rs` line 88 at r9](https://reviewable.io/reviews/tracemachina/native-link/346#-NjmvLbv23YGYsOdLch4:-NjmvLbv23YGYsOdLch5:b-6gxi9m) ([raw file](https://github.com/tracemachina/native-link/blob/e422897291246f293fe6d58297956e6c3f539f75/cas/scheduler/cache_lookup_scheduler.rs#L88)):*
> ```XML
> }
> 
> pub async fn walk_ac_and_order_items(
> ```

This is not wired up to anything, so it does nothing in production.

**Pull request closed without merging**
