### PR TITLE
Add helm chart deployment example for EKS with doc instructions

### LINKED ISSUE #731: Add EKS Helm Chart Example to Deployment Examples

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

Adds an example helm chart with instructions (Both in README and Docs site) to deployment examples.

Fixes #731 

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
Overall, this looks good. Can you put an `eks` directory in `aws`?

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Mostly LGTM, apart from the `tgz` archive.

FYI I'd also recommend taking a look at the `values.yaml` from Cilium which I think are really good: https://github.com/cilium/cilium/tree/v1.15.1/install/kubernetes/cilium

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732#-:-NsTe50GAUtTbx_-sj58:b-xt3vp4)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTXter6asCcxVYkwnM):*
nit: shorten the commit message
___
*[`deployment-examples/eks/README.md` line 5 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTY60e2VVlZbhHwxLI:-NsTY60e2VVlZbhHwxLJ:bu3i37l) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/README.md#L5)):*
> ```Markdown
> ### Step 1: Installing Helm Chart
> 
> Finally, you can download and install the Helm chart from the `nativelink.tgz` tarball linked below, which deploys the CAS component into the EKS cluster. Additional components for remote execution, such as the scheduler and workers, can be added later.
> ```

Let's use the "unpackaged" chart. Instead of the `.tgz` archive we can commit the raw files inside it instead. Users can then clone the repo and apply the chart. Otherwise we'd have to add additional hardening pipelines since we'd be tracking binary files in the repository.
___
*[`deployment-examples/eks/README.md` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsT_PdGD3uvFt-KF-8R:-NsT_PdGD3uvFt-KF-8S:b-oknmig) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/README.md#L36)):*
> ```Markdown
> ```json5
> {
> 	"Version": "2012-10-17",
> ```

nit: something looks wrong with the tabs here
___
*[`deployment-examples/eks/values.yaml` line 109 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTcND69Tl-xQ4ufqbb:-NsTcND69Tl-xQ4ufqbc:b72uabf) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L109)):*
> ```YAML
>   className: "nginx"
>   annotations:
>     cert-manager.io/cluster-issuer: letsencrypt-tls-issuer
> ```

nit: Where does the cert-manager deployment come from?
___
*[`deployment-examples/eks/Dist/nativelink.tgz` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTa0U36HFjh3ew3JG5:-NsTa0U36HFjh3ew3JG6:b-n9om3t) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/Dist/nativelink.tgz#L0)):*
Storing binary files in git makes it impossible to see diffs between different versions of these files. This can turn into major security risks as it's unclear where the archive comes from. The workaround for this is to create such archives via automated pipelines where a bot packages the raw text files, signs the `tgz` and pushes it onto a separate branch that is read-only for humans.

For this example that would be way too much work to set up, so we can use Helm's "unpackaged" chart instead.
___
*[`deployment-examples/eks/templates/cas/service.yaml` line 15 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTdXJM1JxT_5Ph_sb9:-NsTdXJM1JxT_5Ph_sbA:b-xk5z0g) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/templates/cas/service.yaml#L15)):*
> ```YAML
>       targetPort: {{ .Values.cas.service.grpcPort }}
>     - name: metrics
>       port: 50061
> ```

nit: should these be hardcoded?
___
*[`nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTdbzbCOdvnfGJXB3d:-NsTdbzbCOdvnfGJXB3e:b6d7pp7) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx#L1)):*
> ```MDX
> # EKS Helm Chart Deployment
> ```

Reminder to remove this and generate if from the doc setup.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`deployment-examples/eks/values.yaml` line 5 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTg9UA9lyP7UF-GwDF:-NsTg9UA9lyP7UF-GwDG:b-g7tlii) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L5)):*
> ```YAML
>   repository: ghcr.io/tracemachina/nativelink
>   pullPolicy: IfNotPresent
>   # Overrides the image tag whose default is the chart appVersion.
> ```

Let's add a link to https://github.com/TraceMachina/nativelink/pkgs/container/nativelink so that users can see where to find additional tags.

**Review by adam-singer — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Comment by MarcusSorealheis** [comment]
> Let's add a link to https://github.com/TraceMachina/nativelink/pkgs/container/nativelink so that users can see where to find additional tags.

This is smart.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`deployment-examples/eks/Dist/nativelink.tgz` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTa0U36HFjh3ew3JG5:-NsaJm7B2xVAiwyUwjGK:b-or10wa) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/Dist/nativelink.tgz#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Storing binary files in git makes it impossible to see diffs between different versions of these files. This can turn into major security risks as it's unclear where the archive comes from. The workaround for this is to create such archives via automated pipelines where a bot packages the raw text files, signs the `tgz` and pushes it onto a separate branch that is read-only for humans.

For this example that would be way too much work to set up, so we can use Helm's "unpackaged" chart instead.
</blockquote></details>

Agreed, we should avoid storing binaries at all costs, future us will appreciate it.

Just ask the chrome `git` history.
___
*[`nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsaJzWS-vOdZ678bK3s:-NsaJzWS-vOdZ678bK3t:b-ei2ogb) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx#L36)):*
> ```MDX
> ```json5
> {
> 	"Version": "2012-10-17",
> ```

nit no tabs please.

**Review by MarcusSorealheis — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTXter6asCcxVYkwnM):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: shorten the commit message
</blockquote></details>

+1 
___
*[`deployment-examples/eks/README.md` line 5 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTY60e2VVlZbhHwxLI:-NsdJ8s638WgiSY5lNPf:bq6vfdf) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/README.md#L5)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's use the "unpackaged" chart. Instead of the `.tgz` archive we can commit the raw files inside it instead. Users can then clone the repo and apply the chart. Otherwise we'd have to add additional hardening pipelines since we'd be tracking binary files in the repository.
</blockquote></details>

Agreed here
___
*[`deployment-examples/eks/README.md` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsT_PdGD3uvFt-KF-8R:-NsdJBwB2sgGXjN467Yj:b-jd1zui) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/README.md#L36)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: something looks wrong with the tabs here
</blockquote></details>

two spaces
___
*[`deployment-examples/eks/values.yaml` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsdJWYc2xHlbyHfhG3K:-NsdJWYc2xHlbyHfhG3L:bajcc3f) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L6)):*
> ```YAML
>   pullPolicy: IfNotPresent
>   # Overrides the image tag whose default is the chart appVersion.
>   tag: "v0.2.0"
> ```

Ideally we'd use a `latest` tag to ensure that customers start with the latest stable release, or we can do `stable` for tags that we have run for at least two weeks once we get our release cadence down pat. 
___
*[`deployment-examples/eks/values.yaml` line 112 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsdKDhHCXErR2DBmp8i:-NsdKDhHCXErR2DBmp8j:b-ehgihl) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L112)):*
> ```YAML
>     nginx.ingress.kubernetes.io/backend-protocol: GRPC
>   hosts:
>     - host: cas.nativelink.some-domain.com # DNS name to expose for the CAS service
> ```

nit: Is there something we can do here to ensure that this one is always an [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) by default? Basically, it could point to our infra so if the user doesn't set this up we can at least function for the first run and instruct them to point to their own, otherwise provide helpful error text. 

this is a nit and non-blocking and something we can obviously iterate on. cc @allada 
___
*[`deployment-examples/eks/templates/cas/service.yaml` line 15 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTdXJM1JxT_5Ph_sb9:-NsdL5DV9CPZVHF7PRkR:b-ddcc0y) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/templates/cas/service.yaml#L15)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: should these be hardcoded?
</blockquote></details>

My opinion: there should be sane defaults, and hardcoded or not is something I will defer to you two and @kubevalet
___
*[`nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTdbzbCOdvnfGJXB3d:-NsdLNwu5sjmre0G-1RM:b-bfqewe) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Reminder to remove this and generate if from the doc setup.
</blockquote></details>

What's that mean? I think there are both generated docs and hand-written documents. They both serve purposes and are valuable if a pain to maintain. There's something revealing and self-fulfilling about writing docs about your code and updating docs related to your changes. 
___
*[`nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsaJzWS-vOdZ678bK3s:-NsdLdi71mHms9P469jr:b32v57) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx#L36)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit no tabs please.
</blockquote></details>

+1

**Review by MarcusSorealheis — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732#-:-NtbA0K7EiMLeDCUfeVx:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTXter6asCcxVYkwnM):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[`deployment-examples/eks/README.md` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsT_PdGD3uvFt-KF-8R:-NtgjMu247_2vJ8CNXdx:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/README.md#L36)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

two spaces
</blockquote></details>

Done.
___
*[`deployment-examples/eks/Dist/nativelink.tgz` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTa0U36HFjh3ew3JG5:-NtgjNeA-5DbwW_pSvMg:b-1y04uw) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/Dist/nativelink.tgz#L)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Agreed, we should avoid storing binaries at all costs, future us will appreciate it.

Just ask the chrome `git` history.
</blockquote></details>

Need to include something for now with the README but we should have a contingency plan for this.
___
*[`nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTdbzbCOdvnfGJXB3d:-NtgjW1Z7GsOzSjjo55b:b-wpll6m) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx#L1)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

What's that mean? I think there are both generated docs and hand-written documents. They both serve purposes and are valuable if a pain to maintain. There's something revealing and self-fulfilling about writing docs about your code and updating docs related to your changes.
</blockquote></details>

I'm probably going to make a script that makes docs that also show up in READMEs sync with each other and then add something to CI to enforce that they're the same. Deployment examples are a good examples of docs that should be like this but hand-written docs in some areas are unavoidable. I have an opinion between both of you on this but I would like to start moving the needle in the automation direction.
___
*[`nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx` line 36 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsaJzWS-vOdZ678bK3s:-Ntgk0FT3pv8p2QZYOQb:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/nativelink-docs/docs/deployment-examples/EKS-Helm-Chart-Deployment.mdx#L36)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`deployment-examples/eks/values.yaml` line 5 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTg9UA9lyP7UF-GwDF:-Ntgj8MG8Yp_Ubq4DoLS:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L5)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's add a link to https://github.com/TraceMachina/nativelink/pkgs/container/nativelink so that users can see where to find additional tags.
</blockquote></details>

Ditto
___
*[`deployment-examples/eks/values.yaml` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsdJWYc2xHlbyHfhG3K:-Ntgj9Wk7MCwzzLupYpD:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L6)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

Ideally we'd use a `latest` tag to ensure that customers start with the latest stable release, or we can do `stable` for tags that we have run for at least two weeks once we get our release cadence down pat.
</blockquote></details>

Ditto
___
*[`deployment-examples/eks/values.yaml` line 109 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTcND69Tl-xQ4ufqbb:-Ntgj3z14ulukhpbic_Y:bvefjke) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L109)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Where does the cert-manager deployment come from?
</blockquote></details>

Done, file was removed.
___
*[`deployment-examples/eks/values.yaml` line 112 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsdKDhHCXErR2DBmp8i:-NtgjA5S-_56W7wPZVh2:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/values.yaml#L112)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

nit: Is there something we can do here to ensure that this one is always an [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) by default? Basically, it could point to our infra so if the user doesn't set this up we can at least function for the first run and instruct them to point to their own, otherwise provide helpful error text. 

this is a nit and non-blocking and something we can obviously iterate on. cc @allada
</blockquote></details>

Ditto
___
*[`deployment-examples/eks/templates/cas/service.yaml` line 15 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/732#-NsTdXJM1JxT_5Ph_sb9:-NtgjAutDytRgFtaNOhy:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/485bcb04c3a52dba45e616bacbd83054e100fe90/deployment-examples/eks/templates/cas/service.yaml#L15)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

My opinion: there should be sane defaults, and hardcoded or not is something I will defer to you two and @kubevalet
</blockquote></details>

Ditto

**Review by blakehatch — COMMENTED** [review]
> Dismissed @MarcusSorealheis and @aaronmondal from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732)* status: 1 of 1 LGTMs obtained

**Review by aaronmondal — COMMENTED** [review]
@allada Can we force-push main to remove this PR from the git history? IMO we must remove the archive introduced here at all costs.

cc @blakehatch Could we do this PR again with the `.tgz` in unzipped form? If we need it right now, let's create some separate forked repository for it.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/732#-:-NtleRn_B-TP6Quk-YBw:b-cw36cb)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
