### PR TITLE
Refactor fs.rs to use call_with_permit scheme

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description
Refactor fs.rs to use call_with_permit scheme

## Checklist

- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741)

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741)* status: 0 of 1 LGTMs obtained

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYrYpm3SL20udgfwbV):*
nit: Would be nice to have a bit more information (just like one or two sentences) in the body of the commit message.
___
*[`nativelink-util/src/fs.rs` line 285 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYr7B_1sUTOTc9B_YK:-NsYr7B_1sUTOTc9B_YL:b45h) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L285)):*
> ```XML
>         Ok(res) => res,
>         Err(_) => Err(make_err!(Code::Internal, "background task failed")),
>     }
> ```





_Suggestion:_
```XML
    tokio::task::spawn_blocking(move || f(permit))
        .await
        .unwrap_or_else(|e| Err(make_err!(Code::Internal, "background task failed: {e:?}")))
```
___
*[`nativelink-util/src/fs.rs` line 434 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYnn7Y6I2_Itmx8gPK:-NsYnn7Y6I2_Itmx8gPL:bt697by) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L434)):*
> ```XML
> }
> 
> pub async fn rename(from: impl AsRef<Path>, to: impl AsRef<Path>) -> Result<(), Error> {
> ```

nit: I really appreciate these simplifications. Something I noticed is that I think we could change all the function signatures to use `PathBuf` like so:

```
pub async fn rename(from: PathBuf, to: PathBuf) -> Result<(), Error> {
    call_with_permit(move |_| std::fs::rename(from, to).map_err(Into::into)).await
}
```

I played around with this a bit and it seems like using `PathBuf` instead of all the manual `Cow` and `OsStr` also makes the filesystem store much easier on the eyes.
___
*[`nativelink-util/src/fs.rs` line 437 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYqoJp7GmQ3R_pCwWt:-NsYqoJp7GmQ3R_pCwWu:b4yy9pr) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L437)):*
> ```XML
>     let from = from.as_ref().to_owned();
>     let to = to.as_ref().to_owned();
>     call_with_permit(move |_| std::fs::rename(from, to).map_err(|e| e.into())).await
> ```

nit: You could change all the `|e| e.into()` to `Into::into` or `Into::<Error>::into`.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741#-:-NsYrtat8OC-7HZIfyY3:bnfp4nl)* status: 1 of 1 LGTMs obtained

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, vale

___
*[`nativelink-util/src/fs.rs` line 285 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYr7B_1sUTOTc9B_YK:-Ns_jby21jIaxg-SNuxX:b-qhr6jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L285)):*
> ```XML
>         Ok(res) => res,
>         Err(_) => Err(make_err!(Code::Internal, "background task failed")),
>     }
> ```

I like this as well
___
*[`nativelink-util/src/fs.rs` line 434 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYnn7Y6I2_Itmx8gPK:-Ns_jfSHACHdkKSg_Jha:b8g6khm) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L434)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: I really appreciate these simplifications. Something I noticed is that I think we could change all the function signatures to use `PathBuf` like so:

```
pub async fn rename(from: PathBuf, to: PathBuf) -> Result<(), Error> {
    call_with_permit(move |_| std::fs::rename(from, to).map_err(Into::into)).await
}
```

I played around with this a bit and it seems like using `PathBuf` instead of all the manual `Cow` and `OsStr` also makes the filesystem store much easier on the eyes.
</blockquote></details>

Changing the signature here breaks types in a couple other places. I'm happy to make the changes but not sure if I should in this PR since this is a backport of other code that was already shipped. Let me know your thoughts
___
*[`nativelink-util/src/fs.rs` line 437 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYqoJp7GmQ3R_pCwWt:-Ns_lN4h2SDTj7hsnvRM:bo2ek8r) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L437)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: You could change all the `|e| e.into()` to `Into::into` or `Into::<Error>::into`.
</blockquote></details>

`Into::<Error>::into` seems a bit clearer as to what's going on so I'll go with that

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741#-:-NsaJUig7uhpw1LbUk-s:bnfp4nl)* status: 2 of 1 LGTMs obtained

___
*[`nativelink-util/src/fs.rs` line 434 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYnn7Y6I2_Itmx8gPK:-NsaJ2Kg8Z-tdzrcDi8T:b-i7apam) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L434)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Changing the signature here breaks types in a couple other places. I'm happy to make the changes but not sure if I should in this PR since this is a backport of other code that was already shipped. Let me know your thoughts
</blockquote></details>

Yeah, I'd use `PathBuf` when all possible. `Cow` is just to remove the need for a copy when able, but `PathBuf` can suffice in many/all cases.

**Review by aaronmondal — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741)* status: 2 of 1 LGTMs obtained

___
*[`nativelink-util/src/fs.rs` line 434 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/741#-NsYnn7Y6I2_Itmx8gPK:-NsdnwTFAUtGuqpAyiLU:b-gozq94) ([raw file](https://github.com/TraceMachina/nativelink/blob/270233648943bc983652b049e8754e838ff6c53b/nativelink-util/src/fs.rs#L434)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah, I'd use `PathBuf` when all possible. `Cow` is just to remove the need for a copy when able, but `PathBuf` can suffice in many/all cases.
</blockquote></details>

Let's defer these signature changes to another PR.

**Review by aaronmondal — APPROVED** [review]
FYI @zbirenbaum You'll need to click the "resolve" and "acknowledge buttons in Reviewable, that'll unblock this PR for merging.


:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/741#-:-NsdoE2F9ozhy30QKzNg:b-s1hnjz)* status: 2 of 1 LGTMs obtained

**Pull request merged**
