### PR TITLE
Remove all uses of salt and put under ActionUniqueQualifier

### PR DESCRIPTION
**Pull request by allada**
We no longer need `salt` as part of the action key, because we now put the key as an value in an enum in ActionUniqueQualifier.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 
+@zbirenbaum 

Please review `r1->r2`.

These changes depend on: https://reviewable.io/reviews/TraceMachina/nativelink/1125

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126#-:-O1OUeqd21Ydor_ZoPl6:b-85ww9p)* status: 0 of 1 LGTMs obtained

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126)* status: 0 of 2 LGTMs obtained, and pending CI: vale, and 1 discussions need to be resolved (waiting on @adam-singer and @zbirenbaum)

___
*[`nativelink-scheduler/src/cache_lookup_scheduler.rs` line 216 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1126#-O1OUtfY0ENmg_3jONBF:-O1OUtfY0ENmg_3jONBG:bg2n4kn) ([raw file](https://github.com/TraceMachina/nativelink/blob/ba52c7fb76bba56ff5485b91cd516712f867dc64/nativelink-scheduler/src/cache_lookup_scheduler.rs#L216)):*
> ```XML
>             .await
>             {
>                 match ac_store.has(action_info.unique_qualifier.digest).await {
> ```

I'm not sure WTF we were doing here, it looks like we were doing the check twice for some reason?!?!
___
*[`nativelink-scheduler/tests/action_messages_test.rs` line 107 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1126#-O1OVaNV9sYd2Sud_c-X:-O1OVaNV9sYd2Sud_c-Y:b-1ap837) ([raw file](https://github.com/TraceMachina/nativelink/blob/ba52c7fb76bba56ff5485b91cd516712f867dc64/nativelink-scheduler/tests/action_messages_test.rs#L107)):*
> ```XML
> 
> #[nativelink_test]
> async fn highest_priority_action_first() -> Result<(), Error> {
> ```

fyi: We don't allow `ActionInfo` or the new structs be used to sort or equality check any more, so these tests are useless.

**Review by allada — COMMENTED** [review]
`r3->r4`

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126#-:-O1OXDK03UhukhwsvUTd:bqd858x)* status: 0 of 2 LGTMs obtained, and pending CI: vale, and 1 discussions need to be resolved (waiting on @adam-singer and @zbirenbaum)

**Review by adam-singer — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 19 of 20 files at r3, 1 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126)* status: 0 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @zbirenbaum)

**Review by allada — COMMENTED** [review]
Ready for review.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126#-:-O1P-SHz96fuZHs230xS:b8pt725)* status: 0 of 2 LGTMs obtained, and pending CI: vale, and 1 discussions need to be resolved (waiting on @adam-singer and @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
> Reviewed 19 of 20 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1126)* status: 0 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @zbirenbaum)

**Pull request merged**
