### PR TITLE
[Breaking] Migrate to Bzlmod

### PR DESCRIPTION
**Pull request by aaronmondal**
The new builds bootstrap the crate_universe binary which increases compatibility with various platforms.

New supported builds:

- Native Bazel on MacOS
- Nix-wrapped Cargo fon MacOS

In addition, a new `--config=linux_zig` was added which allows building nativelink with a more hermetic (but not perfectly hermetic) toolchain on systems that can't use the LRE toolchains. The zig-cc toolchain runs a lot slower than the LRE toolchains but is more similar to the LRE toolchain and at least somewhat reduces variation between compilers.

This commit is somewhat of a regression in terms of hermeticity and reproducibility. The bzlmod migration moved the Cargo.Bazel.lock file to an autogenerated MODULE.bazel.lock, but we have to gitignore that file for now since rules_rust currently doesn't create the same lockfiles on Linux and MacOS.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
Wow. I did not expect this one so quickly.

**Comment by MarcusSorealheis** [comment]
> a new --config=linux_zig was added which allows building nativelink with a more hermetic

> This commit is somewhat of a regression in terms of hermeticity and reproducibility

As written, these two states can read as contradictory. However, I think I understand what you mean. Am I correct in my interpretation to understand that some characteristics hermeticity improved while others got worse? 
Regarding the path to bit wise identical and reproducible builds, is this effort a step in the correct direction?

**Review by aaronmondal — COMMENTED** [review]
+@MarcusSorealheis +@adam-singer +@allada

CC @blakehatch @kubevalet it could be interesting to see how the toolchains in `.bazelrc` are set up. Essentially, the build uses whatever it finds on your system locally (no configuration, default behavior) but if you pass `--config=linux_zig` or `--config=lre` it switches over to a specific toolchain. Ultimately a goal is to have all our supported platforms mapped out with fully hermetic and remote-exec compatible toolchains and then to enable `BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1` globally in `.bazelrc`.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626#-:-NosFgHcBPEv6weE9I9W:b-e5i72n)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @MarcusSorealheis)

**Review by adam-singer — COMMENTED** [review]
What is the quick tl'dr for someone to test this on mac, would `bazel test //...` be a good smoke screen when pulling down this patch? 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626#-:-Not8l-m94RTRGB2QvLe:bo1ic8n)* status: 0 of 3 LGTMs obtained (waiting on @allada and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @MarcusSorealheis)

___
*[`.github/workflows/native-bazel.yaml` line 59 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/626#-NotTXH31_4VwUOr1kfa:-NotTXH31_4VwUOr1kfb:b50orou) ([raw file](https://github.com/TraceMachina/nativelink/blob/8bc74b1d1361ee42ae10161d38678a86e844c8d1/.github/workflows/native-bazel.yaml#L59)):*
> What is the quick tl'dr for someone to test this on mac, would `bazel test //...` be a good smoke screen when pulling down this patch?

Yes. This is the CI workflow that tests it. Note that this only works using a native toolchain but *not* in a nix shell (that would be tested in the nix-bazel workflow instead).
___
*[`local-remote-execution/rbe-configs-gen.nix` line 4 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Not6xpMCIPRysu5Y12b:-NotURRCBFw3CcJXEBhA:b-xig42j) ([raw file](https://github.com/TraceMachina/nativelink/blob/8bc74b1d1361ee42ae10161d38678a86e844c8d1/local-remote-execution/rbe-configs-gen.nix#L4)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

do we want to depend on an `rc` here or is this auto generated code we might not control?
</blockquote></details>

This version includes changes to the java toolchains with Bazel 7. Between 5.1.2 and this ´rc´are just six commits https://github.com/bazelbuild/bazel-toolchains/compare/v5.1.2...v5.1.3-rc1

**Review by adam-singer — APPROVED** [review]
@aaronmondal worked for me out of the box! 
:lgtm:

> Reviewed 2 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626#-:-NotsWNs492_hrCyG_xu:b-qo8gz8)* status: 1 of 3 LGTMs obtained (waiting on @allada and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 1 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @allada and @MarcusSorealheis)

___
*[`tools/rules_rust_deduplicate_sysroot.diff` line 12 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Not8HIQ98Hefz7TC4TI:-NozKOFtBRnvdSPPlkmI:buqlrbu) ([raw file](https://github.com/TraceMachina/nativelink/blob/8bc74b1d1361ee42ae10161d38678a86e844c8d1/tools/rules_rust_deduplicate_sysroot.diff#L12)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Hard to tell is this env always set or just set on mac? I think its only a mac respected env variable. Did these rules patches come from the upstream PR thats not merged into rules_rust?
</blockquote></details>

This was https://github.com/bazelbuild/rules_rust/pull/2422 with your added change for `DYLD_LIBRARY_PATH`. This actually doesn't seem to have any effect, so I changed it back to the original and added the sources of the patches to the `MODULE.bazel`.

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 1 of 3 LGTMs obtained, and pending CI: asan / ubuntu-22.04 (waiting on @allada and @MarcusSorealheis)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626#-:-Np5nEOw9LLCW5VTskQU:bnfp4nl)* status: 1 of 3 LGTMs obtained, and pending CI: asan / ubuntu-22.04 (waiting on @allada and @MarcusSorealheis)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626#-:-Np5ngMV95jU3nVLpX7s:bnfp4nl)* status: 1 of 3 LGTMs obtained, and pending CI: asan / ubuntu-22.04 (waiting on @allada and @MarcusSorealheis)

___
*[`.github/workflows/native-bazel.yaml` line 59 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/626#-NotTXH31_4VwUOr1kfa:-Np5nKrWEa5GWngATw6a:b-1y6j7w) ([raw file](https://github.com/TraceMachina/nativelink/blob/8bc74b1d1361ee42ae10161d38678a86e844c8d1/.github/workflows/native-bazel.yaml#L59)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

> What is the quick tl'dr for someone to test this on mac, would `bazel test //...` be a good smoke screen when pulling down this patch?

Yes. This is the CI workflow that tests it. Note that this only works using a native toolchain but *not* in a nix shell (that would be tested in the nix-bazel workflow instead).
</blockquote></details>

sgtm, I'd say one impediment that gets to me is not being able to run the rust formatter or get the clippy rules checking, which I assume doesn't require nix? Getting past that for now is a huge win

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 37 of 43 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 1 of 3 LGTMs obtained, and pending CI: asan / ubuntu-22.04 (waiting on @MarcusSorealheis)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5ohFu1Qe1R9jS39WA):*
Hmmm, should we push on `rust_rules` people to fix this and consider it blocking?

I'm not sure we should force people to run more complex bazel commands to get going.
___
*[`.github/workflows/main.yml` line 53 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5rDiRCZxDVHxJD7ld:-Np5rDiRCZxDVHxJD7le:bl2rw3m) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/.github/workflows/main.yml#L53)):*
> ```YAML
>         docker run --rm --net=host -w /root/nativelink -v $PWD:/root/nativelink trace_machina/nativelink:builder sh -c ' \
>           bazel clean && \
>           bazel test --config=linux_zig //... \
> ```

nit: We should have at least one workflow not use zig.
___
*[`local-remote-execution/MODULE.bazel` line 12 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5s-vDBj6QZ--eVZbv:-Np5s-vDBj6QZ--eVZbw:b-9ole09) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/local-remote-execution/MODULE.bazel#L12)):*
> ```Starlark
> bazel_dep(name = "platforms", version = "0.0.8")
> bazel_dep(name = "rules_cc", version = "0.0.9")
> bazel_dep(name = "rules_java", version = "7.3.2")
> ```

nit: Why `rules_java`?
___
*[`local-remote-execution/MODULE.bazel` line 14 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5rxfnAoJn7b09tj07:-Np5rxfnAoJn7b09tj08:b-tjygwn) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/local-remote-execution/MODULE.bazel#L14)):*
> ```Starlark
> bazel_dep(name = "rules_java", version = "7.3.2")
> 
> # register_execution_platforms("//generated/config:platform")
> ```

nit: Should be removed?
___
*[`tools/rules_rust_bindgen_linkopts.diff` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5qDkbBBauGFUx97T1:-Np5qDkbBBauGFUx97T2:bph8nzg) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/tools/rules_rust_bindgen_linkopts.diff#L1)):*
> ```Diff
> diff --git a/bindgen/private/bindgen.bzl b/bindgen/private/bindgen.bzl
> ```

Did we upstream this? We should reference the upstream PR if we did, and if not we should upstream it.
___
*[`tools/rules_rust_deduplicate_sysroot.diff` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5qMIRD_nI0wIQzov1:-Np5qMIRD_nI0wIQzov2:b-rqxvo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/tools/rules_rust_deduplicate_sysroot.diff#L1)):*
> ```Diff
> diff --git a/rust/private/rustc.bzl b/rust/private/rustc.bzl
> ```

ditto.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 1 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable (waiting on @allada and @MarcusSorealheis)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5ohFu1Qe1R9jS39WA):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmmm, should we push on `rust_rules` people to fix this and consider it blocking?

I'm not sure we should force people to run more complex bazel commands to get going.
</blockquote></details>

This actually simplifies the setup as the only command required for building is `bazel build`. The lockfile is autogenerated and the new approach obsoletes the `CARGO_BAZEL_REPIN=1` commands for dependency updates.

I think `rules_rust` is aware of this, but it's apparently a nontrivial thing to fix. Once they do fix it we can add the lockfile back, but it'll be an invisible change for users.
___
*[`local-remote-execution/MODULE.bazel` line 12 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5s-vDBj6QZ--eVZbv:-Np68LxKEEQDvTU_Yq05:b2k07ls) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/local-remote-execution/MODULE.bazel#L12)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Why `rules_java`?
</blockquote></details>

This is similar to `rules_cc`. The java rules were originally built into Bazel, but are now superceded by `rules_java`. It's often not visible because most projects use the legacy builtin rules.
___
*[`tools/rules_rust_bindgen_linkopts.diff` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5qDkbBBauGFUx97T1:-Np68z9XBqfN5FG6a78e:bhx0nx8) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/tools/rules_rust_bindgen_linkopts.diff#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Did we upstream this? We should reference the upstream PR if we did, and if not we should upstream it.
</blockquote></details>

This is  from https://github.com/bazelbuild/rules_rust/pull/2422

It's documented in the `git_override` for rules_rust in the `MODULE.bazel` file.
___
*[`tools/rules_rust_deduplicate_sysroot.diff` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5qMIRD_nI0wIQzov1:-Np69EJx30-2sXvxeIH1:btoej5c) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/tools/rules_rust_deduplicate_sysroot.diff#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

This is from https://github.com/bazelbuild/rules_rust/pull/2428

It's documented in the `git_override` for rules_rust in the `MODULE.bazel` file.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626#-:-Np85E4S5SbBpP9IN1TI:bnfp4nl)* status: 2 of 3 LGTMs obtained (waiting on @MarcusSorealheis)

___
*[`.github/workflows/native-bazel.yaml` line 75 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np84AWs0wZowduWL8hf:-Np84AWs0wZowduWL8hg:b-8hejq6) ([raw file](https://github.com/TraceMachina/nativelink/blob/b645cd02c59c98c5b082c446b3abc0ec82a40bf8/.github/workflows/native-bazel.yaml#L75)):*
> ```YAML
>       fail-fast: false
>       matrix:
>         os: [ubuntu-20.04, ubuntu-22.04]
> ```

nit: Lets add 18.04.

cc: @chrisstaite-menlo , you should be happy about this, as it'll make 18.04 officially supported :smile: 
___
*[`local-remote-execution/MODULE.bazel` line 12 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np5s-vDBj6QZ--eVZbv:-Np852kRC3XFke6KPCxb:b-20einm) ([raw file](https://github.com/TraceMachina/nativelink/blob/bc2bcf4508acf8662c8e2ab02054ba73caae147e/local-remote-execution/MODULE.bazel#L12)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This is similar to `rules_cc`. The java rules were originally built into Bazel, but are now superceded by `rules_java`. It's often not visible because most projects use the legacy builtin rules.
</blockquote></details>

Lets add a comment for that.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 2 of 3 LGTMs obtained, and pending CI: Vercel, pre-commit-checks (waiting on @MarcusSorealheis)

___
*[`.github/workflows/native-bazel.yaml` line 75 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/626#-Np84AWs0wZowduWL8hf:-NpChS_Q60DCxYWtCqEs:bghejvn) ([raw file](https://github.com/TraceMachina/nativelink/blob/b645cd02c59c98c5b082c446b3abc0ec82a40bf8/.github/workflows/native-bazel.yaml#L75)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets add 18.04.

cc: @chrisstaite-menlo , you should be happy about this, as it'll make 18.04 officially supported :smile:
</blockquote></details>

I tried to, but 18.04 isn't supported in GHA anymore. We need to set up self-hosted Ubuntu 18 runners if we want that.

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 2 of 3 LGTMs obtained, and pending CI: pre-commit-checks (waiting on @MarcusSorealheis)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/626#-NpClI8530pu3qjxyrqs):*
nit: This is not `Breaking` from what I can tell.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: 2 of 2 LGTMs obtained

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/626#-NpClI8530pu3qjxyrqs):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This is not `Breaking` from what I can tell.
</blockquote></details>

True. I'll remove the `[Breaking]` when squash merging.

**Review by aaronmondal — COMMENTED** [review]
> Dismissed @adam-singer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/626)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Pull request merged**
