### PR TITLE
Rearrange docs and align content with README

### LINKED ISSUE #567: Align Docs and READMEs
Align content of Quickstart docs and READMEs

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

Align content in docs with README and restructure page order.

Fixes #567

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/571)

### CODE REVIEW

**Review by adam-singer — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/571)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by aaronmondal — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/571)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by aaronmondal — COMMENTED** [review]
@blakehatch @MarcusSorealheis Should we pull this in before #572?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/571#-:-NmCmRE3CcfAVJ_IWiFW:bduxir2)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by blakehatch — COMMENTED** [review]
Doesn't matter too much since the site will reflect the changes either way but up to @MarcusSorealheis on that.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/571#-:-NmCq6_-2AO0m0nIuZY6:b-vuettj)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Comment by MarcusSorealheis** [comment]
I think this is fine.

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/571#-:-NmDduXd9M-7ezPcaHMD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
