### PR TITLE
Fix the dates on case studies.

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

The publication date on one of our case studies was wrong. 

## Type of change

Please delete options that aren't relevant.

- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1357)

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1357#-:-O7aeFE-6iTNvnYatYGy:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Installation / macos-13, Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04), and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1357#-O7ae28sDfXAzmsRdBna):*




_Suggestion:_
```
Fix the date on Samsung case study
```
___
*[`web/platform/src/content/posts/CaseStudy_Samsung.md` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1357#-O7ae6Cx7_uKyBe9jahL:-O7ae6Cy0N2QASY8XTyn:bj0mjlk) ([raw file](https://github.com/TraceMachina/nativelink/blob/f7e136002137a7c7197670c322c4e4a991562dd8/web/platform/src/content/posts/CaseStudy_Samsung.md#L6)):*
> ```Markdown
> image: https://static.wixstatic.com/media/48be99_30ae224dc45f453d80e48f7b9078d330~mv2.png/v1/fill/w_648,h_394,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/x%20(3).png
> slug: case-study-samsung
> pubDate: 2024-08-13
> ```

nit: while we're at it, could you double-check the date of the ciq case study as well? That one also looks wrong.

**Review by SchahinRohani — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1357)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04, and 2 discussions need to be resolved

**Comment by SchahinRohani** [comment]
:lgtm:

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1357)* status: 2 of 1 LGTMs obtained, and 1 of 2 files reviewed, and pending CI: windows-2022 / stable, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1357#-O7ae28sDfXAzmsRdBna):*
Done.

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @aaronmondal from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1357)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
