### PR TITLE
Add Docker example for Goma build.

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
This adds an example deployment for a Goma build service.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/201)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 10 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_ZsSwN59Xcq-CXsf6Z:-N_ZsSwN59Xcq-CXsf6_:b-588cm7) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L10)):*
> ```Diff
>  						{
> -							Name:  "container-image",
> -							Value: *platformContainerImage,
> ```

I don't think you need to remove this if you make `container-image` property a `Priority`.
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 12 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_Zs8PwEe53PykzRKlr:-N_Zs8PwEe53PykzRKls:bk58gug) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L12)):*
> ```Diff
> -							Value: *platformContainerImage,
> +							Name:  "cpu_count",
> +							Value: "1",
> ```

Hmm interesting. I think this use case could easily be addressed by a scheduler impl that rewrites platform properties.

For example, in your case, it always adds `cpu_count = 1` to all jobs and removes `container-image`.
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 51 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_ZscZnEtX412A4SnFV:-N_ZscZo8oSAtLpsO25_:b-rqxvo7) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L51)):*
> ```Diff
>  			rootDir = winpath.ToPosix(rootDir)
>  		}
> -		r.addPlatformProperty(ctx, "InputRootAbsolutePath", rootDir)
> ```

ditto.

**Review by allada — COMMENTED** [review]
This is pretty neat, I'll test it out later this week. I want to start gathering metrics on real world applications to start measuring performance and how it can be better/faster/less-problems. Right now I use `turbo-cache` to test itself, but it's a bit too small of a project to get very good metrics. So i've been wanting to compile chromium, but it's daunting. Having a Goma layer will help a ton!

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201#-:-N_Zstnu32MhWuZbl6gv:b-3r6u2q)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @chrisstaite-menlo)

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: all files reviewed, 5 unresolved discussions (waiting on @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-goma/docker-compose.yml` line 92 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_aRjgMCsmclOnjfK9M:-N_aRjgNDmMlKKKS-0UN:bccfwfr) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/docker-compose.yml#L92)):*
> ```YAML
>     restart: always
>     command: |
>       /remoteexec_proxy --port 5051 --remoteexec-addr turbo_cache_scheduler:50052 --remote-instance-name main --insecure-remoteexec --exec-missing-input-limit 0 --exec-check-missing-timeout 60s --exec-check-cache-timeout 10s --exec-response-timeout 30s --exec-upload-blobs-timeout 120s --exec-execute-timeout 120s --exec-input-tree-timeout 60s --exec-setup-timeout 60s
> ```

These should probably be in separate lines. In case you can't remember all the different line break syntaxes (like me :laughing:) see the `Supported` section in the first answer here: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines.

I believe in this case it's `>`?
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/Dockerfile` line 1 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_aTTKsCKtfbxu4VC-6:-N_aTTKsCKtfbxu4VC-7:b-ia07fj) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/Dockerfile#L1)):*
> ```Dockerfile
> FROM golang:1.18-alpine
> ```

If 1.20 works it might be faster.

**Comment by chrisstaite-menlo** [comment]
Need to update README.md and probably add a guide (or at least a link to one) on how to set up Goma client.

**Comment by chrisstaite-menlo** [comment]
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 42 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_dLXAhAiVDs-CRL3O7:-N_dLXAhAiVDs-CRL3O8:bpi2ef5) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L42)):*
> ```Diff
>  	}
>  
> -	symAbsOk := r.f.capabilities.GetCacheCapabilities().GetSymlinkAbsolutePathStrategy() == rpb.SymlinkAbsolutePathStrategy_ALLOWED
> ```

It's worth noting this is all from when I was using BuildGrid, and I didn't check to see if it was necessary for turbo-cache.  It might be that we can remove this and the other absolute path changes too.

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: all files reviewed, 7 unresolved discussions (waiting on @aaronmondal and @allada)

___
*[`deployment-examples/docker-compose-goma/docker-compose.yml` line 92 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_aRjgMCsmclOnjfK9M:-N_hzdbe9Y1jq9q4HRWW:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/docker-compose.yml#L92)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

These should probably be in separate lines. In case you can't remember all the different line break syntaxes (like me :laughing:) see the `Supported` section in the first answer here: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines.

I believe in this case it's `>`?
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/Dockerfile` line 1 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_aTTKsCKtfbxu4VC-6:-N_hzhnIC8m_uiNXZ5Q9:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/Dockerfile#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

If 1.20 works it might be faster.
</blockquote></details>

Done.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @aaronmondal and @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-goma/docker-compose.yml` line 81 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qI4aHDU5Q-ecR_czc:-N_qI4aHDU5Q-ecR_czd:bqroeuy) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/docker-compose.yml#L81)):*
> ```YAML
>     build:
>       context: ./turbo-cache-goma
>     image: turbo-cache-goma:local
> ```

For consistency can we do something similar to the way it is done above? Or change above to be like this?
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/Dockerfile` line 19 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qIekE8SRXsgF4hUPs:-N_qIekE8SRXsgF4hUPt:b-z76mn1) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/turbo-cache-goma/Dockerfile#L19)):*
> ```Dockerfile
> EXPOSE 5050
> 
> CMD ["/remoteexec_proxy", "--port", "5050", \
> ```

nit: You really need these `\` when it's already an a list?
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 12 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_Zs8PwEe53PykzRKlr:-N_qIqR3B15dITPts52R:b-qgttks) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L12)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Hmm interesting. I think this use case could easily be addressed by a scheduler impl that rewrites platform properties.

For example, in your case, it always adds `cpu_count = 1` to all jobs and removes `container-image`.
</blockquote></details>

Implemented!
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch_noauth.diff` line 9 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_dM-mj784qrPpvYQEv:-N_qJ7oY58rHMcEO699l:b-1xgi28) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch_noauth.diff#L9)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

It's also worth noting that I haven't actually tried this patch, we use OAuth for authentication which is why this is broken out.  I sourced this patch from elsewhere and the origin is lost in time.
</blockquote></details>

If we make these `env`, I think it will make a lot more sense, because then we can make a readme about how to use it with OAuth.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: 9 of 10 files reviewed, 11 unresolved discussions (waiting on @aaronmondal and @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-goma/precondition_script.sh` line 1 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qNgAaEj8PfVHN9AQr:-N_qNgAaEj8PfVHN9AQs:bz964zx) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/precondition_script.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

nit: suggest renaming this to make it clear this runs on the worker nodes.
___
*[`deployment-examples/docker-compose-goma/scheduler.json` line 36 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qOWP47fJHg9YV5_JV:-N_qOWP47fJHg9YV5_JW:b3dj66y) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/scheduler.json#L36)):*
> ```JSON
>         }
>       },
>       "cas": {
> ```

Do we need to serve CAS here? Does goma support servicing CAS and scheduler requests on separate endpoints?
___
*[`deployment-examples/docker-compose-goma/worker.json` line 42 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qOvpZEK6T8Xpufsk7:-N_qOvpZEK6T8Xpufsk8:bafnefe) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/worker.json#L42)):*
> ```JSON
>         "uri": "grpc://${SCHEDULER_ENDPOINT:-127.0.0.1}:50061",
>       },
>       "entrypoint_cmd": "$@",
> ```

nit: I think I broke this didn't I? I think if it's set it requires a file now and unconditionally sends arguments to it.

**Review by allada — COMMENTED** [review]
Man, I haven't used goma since when I used to work on Chrome. I don't miss it though, but also glad to see it supports BRE now. It used to be it's own thing.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201#-:-N_qPFu43toq0ihT_Wnr:bf4yjmz)* status: 9 of 10 files reviewed, 11 unresolved discussions (waiting on @aaronmondal and @chrisstaite-menlo)

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: 6 of 11 files reviewed, 10 unresolved discussions (waiting on @aaronmondal and @allada)

___
*[`deployment-examples/docker-compose-goma/docker-compose.yml` line 81 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qI4aHDU5Q-ecR_czc:-NaBari405-UVchZwMc8:b-y5dg57) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/docker-compose.yml#L81)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

For consistency can we do something similar to the way it is done above? Or change above to be like this?
</blockquote></details>

Are you just saying to switch around the `build` and `image`?
___
*[`deployment-examples/docker-compose-goma/scheduler.json` line 36 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qOWP47fJHg9YV5_JV:-NaBb2Y27ear5Tsjqp5C:b2726f2) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/scheduler.json#L36)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Do we need to serve CAS here? Does goma support servicing CAS and scheduler requests on separate endpoints?
</blockquote></details>

Unfortunately not...
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 10 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_ZsSwN59Xcq-CXsf6Z:-NaBbGHkA8nySzRBmSdn:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L10)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I don't think you need to remove this if you make `container-image` property a `Priority`.
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 42 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_dLXAhAiVDs-CRL3O7:-NaBbHoL6Nc5K1LohABH:b-vmk0a) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L42)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

It's worth noting this is all from when I was using BuildGrid, and I didn't check to see if it was necessary for turbo-cache.  It might be that we can remove this and the other absolute path changes too.
</blockquote></details>

I just checked and the capabilities server returns this:
`symlink_absolute_path_strategy: SymlinkAbsolutePathStrategy::Disallowed.into(),`
I'm not sure if all these changes can just be removed or not... might be because we're not executing inside the container than it's like this?
___
*[`deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff` line 51 at r1](https://reviewable.io/reviews/allada/turbo-cache/201#-N_ZscZnEtX412A4SnFV:-NaBbUnnAVxnRcnB-9bR:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/8f56b971fbbbb457ac8689dcad5635c3c5f2ad6b/deployment-examples/docker-compose-goma/turbo-cache-goma/remoteexec_patch.diff#L51)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @aaronmondal and @chrisstaite-menlo)

___
*[`deployment-examples/docker-compose-goma/Dockerfile` line 1 at r3](https://reviewable.io/reviews/allada/turbo-cache/201#-NaSZ76s-0GpAjD7ps3O:-NaSZ76t5tsIJfhPlAM2:b-nvnbna) ([raw file](https://github.com/allada/turbo-cache/blob/4e043c19fab033af394138ddc1f4771eef9b49cc/deployment-examples/docker-compose-goma/Dockerfile#L1)):*
> ```Dockerfile
> # Copyright 2022 The Turbo Cache Authors. All rights reserved.
> ```

It looks like this file is only adds a tiny bit of dependencies needed by the worker in `chromium-worker`.

To get around this, I suggest instead modifying the `Dockerfile` in `docker-examples` and adding a build argument for something like `ADDITIONAL_BUILD_INSTALL_CMD` or similar that defaults to `true` and if overridden can be used to do some additional dependency installation.

**Comment by kschzt** [comment]
I tried to get this going (running a 512-core goma + buildbarn setup), but haven't been able to get past this error in goma-server's log yet:

`exec call: error in check missing blobs: rpc error: code = Unimplemented desc = missing blobs: rpc error: code = Unimplemented`

I did get somewhere with just replacing buildbarn's CAS with turbo-cache's, but would love to try turbo-cache for everything. /cc @allada - our team builds Chromium with goma several times per day :)

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: 2 of 13 files reviewed, 6 unresolved discussions (waiting on @aaronmondal and @allada)

___
*[`deployment-examples/docker-compose-goma/docker-compose.yml` line 81 at r2](https://reviewable.io/reviews/allada/turbo-cache/201#-N_qI4aHDU5Q-ecR_czc:-NdZT-Ii9jbhH9bgMPdK:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/f9e12b9c29f5584a5b52700a08ebd7daa7235302/deployment-examples/docker-compose-goma/docker-compose.yml#L81)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I mean prefix it with `allada/` (ie: namespace).
</blockquote></details>

Done.
___
*[`deployment-examples/docker-compose-goma/Dockerfile` line 1 at r3](https://reviewable.io/reviews/allada/turbo-cache/201#-NaSZ76s-0GpAjD7ps3O:-NdZSlwo0gOo6yGHhjnK:b-896fix) ([raw file](https://github.com/allada/turbo-cache/blob/4e043c19fab033af394138ddc1f4771eef9b49cc/deployment-examples/docker-compose-goma/Dockerfile#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

It looks like this file is only adds a tiny bit of dependencies needed by the worker in `chromium-worker`.

To get around this, I suggest instead modifying the `Dockerfile` in `docker-examples` and adding a build argument for something like `ADDITIONAL_BUILD_INSTALL_CMD` or similar that defaults to `true` and if overridden can be used to do some additional dependency installation.
</blockquote></details>

Done.

**Comment by allada** [comment]
I picked up this PR and in the process of testing. Give me a day or two to finish up and let's resync this.

I did find at least 1 bug in turbo-cash that Goma exposed in the filesystem store. I'm still getting some rare strange behavior with some files that appear to be corrupted or something.

**Comment by chrisstaite-menlo** [comment]
I've also found a bug in the PropertyModifierScheduler in that it doesn't add "removed" properties to the `known_properties` map.

**Comment by chrisstaite-menlo** [comment]
I don't like that solution, the PropertyModifierScheduler ought to deal with it itself.  I've got a patch incoming.

**Comment by chrisstaite-menlo** [comment]
Turns out the Goma remoteexec_proxy patch is entirely redundant.  I've removed it :)

**Comment by chrisstaite-menlo** [comment]
I've updated our internal systems to use the docker containers produced by this now and have updated the README with details of enabling authentication.

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 2 of 10 files at r1, 1 of 4 files at r3, 5 of 9 files at r4, 1 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronmondal and @allada)

**Review by allada — COMMENTED** [review]
I was able to completely build chromium in remote environment. I'll be uploading 2 PRs. One is to fix a bug, the other is pretty much a mirror of this PR so we can see the deltas.

> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201#-:-NdeybT3BmcmoR-vtK7M:b3blfae)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronmondal)

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronmondal)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/201#-Ndp8E7C4rVJ0ik0FxW0:-Ndp8E7C4rVJ0ik0FxW1:bio2nxk) (no related file):*
FYI, I have a local goma config setup that I have been playing with that I'm mostly satisfied with. I'll create a delta patch between these two and send it over to you to look at. My stuff was based on yours, so it's nearly identical.

___

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/allada/turbo-cache/201)* status: all files reviewed, 5 unresolved discussions (waiting on @aaronmondal and @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/allada/turbo-cache/201#-Ne0fFEK2r8EcIl1XDrR:-Ne0fFEK2r8EcIl1XDrS:b-ulmfeq) (no related file):*
Here's the goma example I was using:
https://github.com/allada/turbo-cache/pull/267

It's based on this PR. It was working on my local machine. I also landed a bunch of changes that make some of the stuff in here possible.

___

**Pull request closed without merging**
