### PR TITLE
Add list api to StoreApi and MemoryStore

### PR DESCRIPTION
**Pull request by allada**
Adds the list() api to all stores, but unimplemented by default.

Implements list() api for MemoryStore.
    
towards: #995

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1003)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@caass 

fyi: @adam-singer, @zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-:-O-JsqQo2Iq6s5noSSjh:bcg424i)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Installation / macos-13, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, and 1 discussions need to be resolved (waiting on @caass)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-O-JsukN1kIIHsio5gqr:-O-JsukN1kIIHsio5gqs:b-x1vszz) (no related file):*
Note: This PR is dependent on #996 landing first.

___

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-:-O-KJrec8VaTdwx-9EvZ:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, and 1 discussions need to be resolved (waiting on @caass)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-:-O-KVMTi91SJPeK897he:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, and 2 discussions need to be resolved (waiting on @caass)

___
*[`nativelink-util/src/evicting_map.rs` line 224 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-O-KULfSEGfpwTO4IJG_:-O-KULfSEGfpwTO4IJGa:b654udr) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d79e46485fb5ee95aa64a89f703f248f66bea92/nativelink-util/src/evicting_map.rs#L224)):*
> ```XML
>     }
> 
>     pub async fn range<F, Q>(&self, prefix_range: impl RangeBounds<Q>, mut handler: F) -> usize
> ```

Might be good to add some comments documenting this function. I think a handler in this context would usually be used for state mutation or an event trigger and would receive the current count, key, and value and can cause some event to trigger.

It might be clearer to rename `handler` to something like `stop_fn` or `end fn`

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1003)* status: 0 of 1 LGTMs obtained, and pending CI: Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale (waiting on @caass)

___
*[`nativelink-util/src/evicting_map.rs` line 224 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-O-KULfSEGfpwTO4IJG_:-O-P5-StEkvnZVLdHacM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3d79e46485fb5ee95aa64a89f703f248f66bea92/nativelink-util/src/evicting_map.rs#L224)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Might be good to add some comments documenting this function. I think a handler in this context would usually be used for state mutation or an event trigger and would receive the current count, key, and value and can cause some event to trigger.

It might be clearer to rename `handler` to something like `stop_fn` or `end fn`
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
-@caass +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1003#-:-O-RplZW5ebBsF0ZWUEh:bcrmjlc)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
