### PR TITLE
Decouple automated K8s deployments

### PR DESCRIPTION
**Pull request by aaronmondal**
This change allows deploying nativelink in various new configurations, including cache-only and multi-toolchain setups.

The new setup is significantly more modular and lets us add and remove toolchains at runtime.

Includes a reordering of the deployment logic to ensure that Alerts get deployed before the GitRepository that triggers them. For demo and CI this comes at the cost of an additional dummy GitRepository. This tradeoff seems well worth it as the previous ordering was entirely wrong and unreliable.

Fixes the flakiness of the LRE workflow where it often gets stuck in the `Waiting for Tekton pipelines` loop.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1531)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@SchahinRohani 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1531#-:-ODhfXh_EWM58x0hXqdS:bj5atnp)* status: 0 of 1 LGTMs obtained, and 0 of 43 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @SchahinRohani)

**Review by SchahinRohani — APPROVED** [review]
I like the modularity approach! But what do you think of moving `kubernetes/overlays/chromium`, `kubernetes/overlays/lre-manual`, `kubernetes/overlays/lre` into the `deploy/*` directory and  removing the `kubernetes/overlays` directory. We could avoid that layer and reduce a little bit of complexity.

> Reviewed 43 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1531#-:-ODk7AnqEKQBiyihS_lS:b-b6ab2t)* status: 0 of 1 LGTMs obtained, and all files reviewed, and 2 discussions need to be resolved (waiting on @SchahinRohani)

___
*[`.github/workflows/lre.yaml` line 141 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1531#-ODk7OGO7RUBTsD7qYlI:-ODk7OGO7RUBTsD7qYlJ:b-naix5h) ([raw file](https://github.com/TraceMachina/nativelink/blob/73a3966872a3d32e5c9353fb0bc586e0e00a8a05/.github/workflows/lre.yaml#L141)):*
> ```YAML
>       - name: Trigger pipelines
>         run: |
>           nix develop --impure --command bash -c 'cat > dummy-repo.yaml << EOF
> ```

nit: Nice idea! We might find a better a way in future, but this ensures for now that we are having the right ordering for flux!
___
*[`kubernetes/nativelink/kustomization.yaml` line 7 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1531#-ODk7mnAE3zShiSUmMK9:-ODk7mnAE3zShiSUmMKA:b-17uy7l) ([raw file](https://github.com/TraceMachina/nativelink/blob/73a3966872a3d32e5c9353fb0bc586e0e00a8a05/kubernetes/nativelink/kustomization.yaml#L7)):*
> ```YAML
> resources:
>   - nativelink.yaml
>   - ../resources/insecure-certs
> ```

nit: Out of scope for this PR, but there might a better way to inject the necessary certs.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1531)* status: 0 of 1 LGTMs obtained, and 36 of 43 files reviewed, and pending CI: Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, pre-commit-checks (waiting on @SchahinRohani)

___
*[`.github/workflows/lre.yaml` line 141 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1531#-ODk7OGO7RUBTsD7qYlI:-ODlH2UrERBxFwGnH_LU:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/73a3966872a3d32e5c9353fb0bc586e0e00a8a05/.github/workflows/lre.yaml#L141)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

nit: Nice idea! We might find a better a way in future, but this ensures for now that we are having the right ordering for flux!
</blockquote></details>

Done.
___
*[`kubernetes/nativelink/kustomization.yaml` line 7 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1531#-ODk7mnAE3zShiSUmMK9:-ODlH5kgEzw-dNYaED7L:b-brqlkj) ([raw file](https://github.com/TraceMachina/nativelink/blob/73a3966872a3d32e5c9353fb0bc586e0e00a8a05/kubernetes/nativelink/kustomization.yaml#L7)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

nit: Out of scope for this PR, but there might a better way to inject the necessary certs.
</blockquote></details>

Done. Yeah this should be using cert-manager. I'll add it at some point :+1:

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 36 of 43 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1531)* status: 0 of 1 LGTMs obtained, and all files reviewed (waiting on @SchahinRohani)

**Pull request merged**
