### PR TITLE
Enhance configuration documentation

### LINKED ISSUE #958: Configuration Documentation Enhancement
Currently we do not document our configuration object sufficiently enough.

We need to accomplish three goals:

1) Break out each key and explain all the options, with a plan to update after refactoring the configuration object.

In the same way that there are some pages of deployment examples, we need a sub-page for each configuration key so that people can isolate what they need to understand if they choose to. For example, `experimental_promtheus` should also have its own sub-page explaining how it works. 

image

2) Provide a lot more configuration examples by use case.

In the same way that we `Deployment Examples`, we should also have `Configuration Examples`, such that the current `Configuration` should become `Configuration Options`. 

3) Include documentation in our docs for Buck2 and Reclient.

We also need a top level page for describing how you can use NativeLink with Buck2 and one for how you can use NativeLink with Reclient. For example, we need to include concepts like injecting `cpu_count` values for Reclient, as has appeared in the Slack.

### PR DESCRIPTION
**Pull request by blakehatch**
# Preview Deployment: https://nativelink-docs-git-fork-blakehat-76e9db-native-link-web-assets.vercel.app/

# Description
Enhances the documentation for configurations. 

Fixes #958 

## Type of change
- [x] This change requires a documentation update

## Checklist
- [x] Updated documentation if needed
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970)

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
I think the best solution is for you to have the same top level page you have and to add another nav link, `Configuration Breakdown`. What do you think?

Something like:

```json
{
    "label": "Configuration Breakdown",
    "position": 2,
    "link": {
      "type": "generated-index",
      "description": "Explore the configuration JSON object."
    }
  }
  ```

**Review by MarcusSorealheis — APPROVED** [review]
This is fine. Let's merge this and iterate.

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, macos-13, pre-commit-checks, and 7 discussions need to be resolved

___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_XRb49V6fTSvJblen:-Nz_XRb49V6fTSvJbleo:b-1wislo) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L10)):*
> ```MDX
> 
> NativeLink uses a JSON file as the configuration format. This section of the
> documentation will breakdown the anatomy of this configuration file with step-by-step instructions on its assembly.
> ```

While not directly relevant, might be useful for hinting at different configurations can be used for different types of servers. Nativelink can be bound together in a single configuration, a practical production deployment would contain different configurations for the different types of servers. Maybe thats not in this section of documentation, but somewhere this should be identified and explained on the practical level.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 33 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_Xx77CMLF7SjP9Awl:-Nz_Xx77CMLF7SjP9Awm:bevfx9p) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L33)):*
> ```MDX
> ### Store Name
> 
> The value of `stores` includes top-level keys, which are user supplied names stores. The following example, defines the `AC_MAIN_STORE`.
> ```

Should we also use some language that hints keys can be referenced in other contexts?
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 50 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YN8d01oLJJ2Dbzx5:-Nz_YN8e0WTA6-pR3FNS:blg0p5m) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L50)):*
> ```MDX
> 
> Once the store has been named and its object exists,
> the next key is the type of store. The options are `filesystem`, `memory`, `compression`, `dedup`, `fast_slow`, `verify`, and `experimental_s3_store`.
> ```

Is there ability to use direct linking to the definition or reference to what `filesystem` is in this context instead of highlighting it with "`", like the code docs page or source code (ideally not)?
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 79 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YuRcDdddzZBjMNZc:-Nz_YuRcDdddzZBjMNZd:bhgmryr) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L79)):*
> ```MDX
>         "eviction_policy": {
>           // 500mb.
>           "max_bytes": 500000000,
> ```

Friendly names have landed, we should use those for docs https://github.com/TraceMachina/nativelink/commit/da2c4a70662267b2f8e8992ea42a439a0e7ab2ec 
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 98 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZO8C9f0o-OLj3lLv:-Nz_ZO8C9f0o-OLj3lLw:by64lyd) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L98)):*
> ```MDX
> ### Worker Array
> 
> The value of `workers` includes a top level array that embeds the worker metadata. This array always begins with the `local` object, which is the only item permitted at this time.
> ```

Can we give a one line statement of what being "local" means even if it sounds trivial ?
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZhA6AWsK-WmVRYjr:-Nz_ZhA6AWsK-WmVRYjs:b-c4zplp) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L114)):*
> ```MDX
> ### Local Worker Object Members
> 
> The Local object has five components, `worker_api_endpoint`, `cas_fast_slow_store`, `upload_action_results`,`work_directory`, and `platform_properties`.
> ```

There is a lot to unpack here, should we expand a little bit on what each of them mean with human explained example?
___
*[`nativelink-docs/docs/configuration/Reference.mdx` line 14 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz__QCrELxokCl4gZVq:-Nz__QCrELxokCl4gZVr:b6blpc0) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Reference.mdx#L14)):*
> ```MDX
> <Tabs>
>     <TabItem value="stores" label="Stores" default>
>         | Key                                      | Type          | Description                                                                 | Example                                   |
> ```

Possible to add code generated docs or code linked html refs?

**Comment by blakehatch** [comment]
> > Reviewed 2 of 7 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970)_ status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, macos-13, pre-commit-checks, and 7 discussions need to be resolved
> 
> _[`nativelink-docs/docs/configuration/Assembling.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_XRb49V6fTSvJblen:-Nz_XRb49V6fTSvJbleo:b-1wislo) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L10)):_
> 
> > ```mdx
> > NativeLink uses a JSON file as the configuration format. This section of the
> > documentation will breakdown the anatomy of this configuration file with step-by-step instructions on its assembly.
> > ```
> 
> While not directly relevant, might be useful for hinting at different configurations can be used for different types of servers. Nativelink can be bound together in a single configuration, a practical production deployment would contain different configurations for the different types of servers. Maybe thats not in this section of documentation, but somewhere this should be identified and explained on the practical level.
> 
> _[`nativelink-docs/docs/configuration/Assembling.mdx` line 33 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_Xx77CMLF7SjP9Awl:-Nz_Xx77CMLF7SjP9Awm:bevfx9p) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L33)):_
> 
> > ```mdx
> > ### Store Name
> > 
> > The value of `stores` includes top-level keys, which are user supplied names stores. The following example, defines the `AC_MAIN_STORE`.
> > ```
> 
> Should we also use some language that hints keys can be referenced in other contexts?
> 
> _[`nativelink-docs/docs/configuration/Assembling.mdx` line 50 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YN8d01oLJJ2Dbzx5:-Nz_YN8e0WTA6-pR3FNS:blg0p5m) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L50)):_
> 
> > ```mdx
> > Once the store has been named and its object exists,
> > the next key is the type of store. The options are `filesystem`, `memory`, `compression`, `dedup`, `fast_slow`, `verify`, and `experimental_s3_store`.
> > ```
> 
> Is there ability to use direct linking to the definition or reference to what `filesystem` is in this context instead of highlighting it with "`", like the code docs page or source code (ideally not)?
> 
> _[`nativelink-docs/docs/configuration/Assembling.mdx` line 79 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YuRcDdddzZBjMNZc:-Nz_YuRcDdddzZBjMNZd:bhgmryr) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L79)):_
> 
> > ```mdx
> >         "eviction_policy": {
> >           // 500mb.
> >           "max_bytes": 500000000,
> > ```
> 
> Friendly names have landed, we should use those for docs [da2c4a7](https://github.com/TraceMachina/nativelink/commit/da2c4a70662267b2f8e8992ea42a439a0e7ab2ec)
> 
> _[`nativelink-docs/docs/configuration/Assembling.mdx` line 98 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZO8C9f0o-OLj3lLv:-Nz_ZO8C9f0o-OLj3lLw:by64lyd) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L98)):_
> 
> > ```mdx
> > ### Worker Array
> > 
> > The value of `workers` includes a top level array that embeds the worker metadata. This array always begins with the `local` object, which is the only item permitted at this time.
> > ```
> 
> Can we give a one line statement of what being "local" means even if it sounds trivial ?
> 
> _[`nativelink-docs/docs/configuration/Assembling.mdx` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZhA6AWsK-WmVRYjr:-Nz_ZhA6AWsK-WmVRYjs:b-c4zplp) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L114)):_
> 
> > ```mdx
> > ### Local Worker Object Members
> > 
> > The Local object has five components, `worker_api_endpoint`, `cas_fast_slow_store`, `upload_action_results`,`work_directory`, and `platform_properties`.
> > ```
> 
> There is a lot to unpack here, should we expand a little bit on what each of them mean with human explained example?
> 
> _[`nativelink-docs/docs/configuration/Reference.mdx` line 14 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz__QCrELxokCl4gZVq:-Nz__QCrELxokCl4gZVr:b6blpc0) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Reference.mdx#L14)):_
> 
> > ```mdx
> > <Tabs>
> >     <TabItem value="stores" label="Stores" default>
> >         | Key                                      | Type          | Description                                                                 | Example                                   |
> > ```
> 
> Possible to add code generated docs or code linked html refs?

Do keep in mine that Assembling is a direct rip from a README in the codebase. I'd rather fix these is a separate PR and sync them instead of making the content diverge here, so we have more ability to automate docs in the future.

**Comment by blakehatch** [comment]
> > > Reviewed 2 of 7 files at r1, all commit messages.
> > > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970)_ status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, macos-13, pre-commit-checks, and 7 discussions need to be resolved
> > 
> > 
> > _[`nativelink-docs/docs/configuration/Assembling.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_XRb49V6fTSvJblen:-Nz_XRb49V6fTSvJbleo:b-1wislo) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L10)):_
> > > ```mdx
> > > NativeLink uses a JSON file as the configuration format. This section of the
> > > documentation will breakdown the anatomy of this configuration file with step-by-step instructions on its assembly.
> > > ```
> > 
> > 
> > While not directly relevant, might be useful for hinting at different configurations can be used for different types of servers. Nativelink can be bound together in a single configuration, a practical production deployment would contain different configurations for the different types of servers. Maybe thats not in this section of documentation, but somewhere this should be identified and explained on the practical level.
> > _[`nativelink-docs/docs/configuration/Assembling.mdx` line 33 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_Xx77CMLF7SjP9Awl:-Nz_Xx77CMLF7SjP9Awm:bevfx9p) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L33)):_
> > > ```mdx
> > > ### Store Name
> > > 
> > > The value of `stores` includes top-level keys, which are user supplied names stores. The following example, defines the `AC_MAIN_STORE`.
> > > ```
> > 
> > 
> > Should we also use some language that hints keys can be referenced in other contexts?
> > _[`nativelink-docs/docs/configuration/Assembling.mdx` line 50 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YN8d01oLJJ2Dbzx5:-Nz_YN8e0WTA6-pR3FNS:blg0p5m) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L50)):_
> > > ```mdx
> > > Once the store has been named and its object exists,
> > > the next key is the type of store. The options are `filesystem`, `memory`, `compression`, `dedup`, `fast_slow`, `verify`, and `experimental_s3_store`.
> > > ```
> > 
> > 
> > Is there ability to use direct linking to the definition or reference to what `filesystem` is in this context instead of highlighting it with "`", like the code docs page or source code (ideally not)?
> > _[`nativelink-docs/docs/configuration/Assembling.mdx` line 79 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YuRcDdddzZBjMNZc:-Nz_YuRcDdddzZBjMNZd:bhgmryr) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L79)):_
> > > ```mdx
> > >         "eviction_policy": {
> > >           // 500mb.
> > >           "max_bytes": 500000000,
> > > ```
> > 
> > 
> > Friendly names have landed, we should use those for docs [da2c4a7](https://github.com/TraceMachina/nativelink/commit/da2c4a70662267b2f8e8992ea42a439a0e7ab2ec)
> > _[`nativelink-docs/docs/configuration/Assembling.mdx` line 98 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZO8C9f0o-OLj3lLv:-Nz_ZO8C9f0o-OLj3lLw:by64lyd) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L98)):_
> > > ```mdx
> > > ### Worker Array
> > > 
> > > The value of `workers` includes a top level array that embeds the worker metadata. This array always begins with the `local` object, which is the only item permitted at this time.
> > > ```
> > 
> > 
> > Can we give a one line statement of what being "local" means even if it sounds trivial ?
> > _[`nativelink-docs/docs/configuration/Assembling.mdx` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZhA6AWsK-WmVRYjr:-Nz_ZhA6AWsK-WmVRYjs:b-c4zplp) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L114)):_
> > > ```mdx
> > > ### Local Worker Object Members
> > > 
> > > The Local object has five components, `worker_api_endpoint`, `cas_fast_slow_store`, `upload_action_results`,`work_directory`, and `platform_properties`.
> > > ```
> > 
> > 
> > There is a lot to unpack here, should we expand a little bit on what each of them mean with human explained example?
> > _[`nativelink-docs/docs/configuration/Reference.mdx` line 14 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz__QCrELxokCl4gZVq:-Nz__QCrELxokCl4gZVr:b6blpc0) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Reference.mdx#L14)):_
> > > ```mdx
> > > <Tabs>
> > >     <TabItem value="stores" label="Stores" default>
> > >         | Key                                      | Type          | Description                                                                 | Example                                   |
> > > ```
> > 
> > 
> > Possible to add code generated docs or code linked html refs?
> 
> Do keep in mine that Assembling is a direct rip from a README in the codebase. I'd rather fix these is a separate PR and sync them instead of making the content diverge here, so we have more ability to automate docs in the future.

Also going to add code generated docs to the links once @aaronmondal lands the rustdoc PR. That will also be separate.

**Comment by blakehatch** [comment]
> This is fine. Let's merge this and iterate.

I'd rather keep them coupled together but either way probably a separate PR.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970)* status: 0 of 1 LGTMs obtained, and pending CI: Installation / ubuntu-22.04, and 6 discussions need to be resolved

___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 33 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_Xx77CMLF7SjP9Awl:-NzdIKmY14rrOuWv0f7Y:bibiba4) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L33)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Should we also use some language that hints keys can be referenced in other contexts?
</blockquote></details>

Maybe I'm not forseeing +90% of users configuring that granularly anyways.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 50 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YN8d01oLJJ2Dbzx5:-NzdIS9B7WNCfw2zciVm:b-a8dw8p) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L50)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Is there ability to use direct linking to the definition or reference to what `filesystem` is in this context instead of highlighting it with "`", like the code docs page or source code (ideally not)?
</blockquote></details>

Also can add in separate PR.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 79 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_YuRcDdddzZBjMNZc:-NzdI_BCAqh-vvFPgNcd:blf83c4) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L79)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Friendly names have landed, we should use those for docs https://github.com/TraceMachina/nativelink/commit/da2c4a70662267b2f8e8992ea42a439a0e7ab2ec
</blockquote></details>

Will fix in separate config PR.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 98 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZO8C9f0o-OLj3lLv:-NzdIiqk2FFj8Re49mKN:blf83c4) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L98)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can we give a one line statement of what being "local" means even if it sounds trivial ?
</blockquote></details>

Will fix in separate config PR.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 114 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-Nz_ZhA6AWsK-WmVRYjr:-NzdIjG66R7TFHV8oioj:blf83c4) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L114)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

There is a lot to unpack here, should we expand a little bit on what each of them mean with human explained example?
</blockquote></details>

Will fix in separate config PR.

**Review by blakehatch — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970#-:-NzdJQuqECE0pUM-QRKh:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Installation / ubuntu-22.04

**Review by allada — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/970)* status: 1 of 1 LGTMs obtained, and 4 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-NzfUgR47Fg0Tl8hs8ZI):*
nit: Please be more descriptive.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-NzfUsLLAvOy1olYkK5q:-NzfUsLLAvOy1olYkK5r:bsbfiaj) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L10)):*
> ```MDX
> 
> NativeLink uses a JSON file as the configuration format. This section of the
> documentation will breakdown the anatomy of this configuration file with step-by-step instructions on its assembly.
> ```

nit: `anatomy` is a needlessly large word.
___
*[`nativelink-docs/docs/configuration/Assembling.mdx` line 50 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-NzfV4PxAtTeVx1mRgdy:-NzfV4PxAtTeVx1mRgdz:blkna3c) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Assembling.mdx#L50)):*
> ```MDX
> 
> Once the store has been named and its object exists,
> the next key is the type of store. The options are `filesystem`, `memory`, `compression`, `dedup`, `fast_slow`, `verify`, and `experimental_s3_store`.
> ```

Can we not list these? This is going to get out of date quickly.
___
*[`nativelink-docs/docs/configuration/Examples.mdx` line 27 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/970#-NzfVHoxDL_TdRTKpCZw:-NzfVHoxDL_TdRTKpCZx:b17mhyh) ([raw file](https://github.com/TraceMachina/nativelink/blob/208bdebc531416caa465e4685b524f0d01bddfbe/nativelink-docs/docs/configuration/Examples.mdx#L27)):*
> ```MDX
>       borderRadius: '10px 10px 10px 10px'
>     }}>
> ```json5
> ```

nit: Did we test that all of these still work? This is dangerous and likely going to stop working with breaking changes. We really need a CI system to run these configs to ensure they continue to work.

**Pull request merged**
