### PR TITLE
Unify validate_output logic in CompletenessCheckingStore and CacheLookupScheduler

### LINKED ISSUE #677: Unify `validate_output` logic in `CompletenessCheckingStore` and `CacheLookupScheduler`
It looks like we have duplicated work here. We should probably just require `CacheLookupScheduler` to be pointed to a `CompletenessCheckingStore` to simplify the logic.

fyi: @blakehatch, @chrisstaite-menlo

### PR DESCRIPTION
**Pull request by blizzardc0der**
# Description

We have duplicated work in CacheLookupScheduler and CompletenessCheckingStore.
I made CacheLookupScheduler to be pointed to a CompletenessCheckingStore to simplify the logic.
I added a new method in the ac_utils so that we can point the validate_output logic with CacheLookupScheduler as well.

Fixes #677

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814)

### CODE REVIEW

**Comment by blizzardc0der** [comment]
I hope you to review this. @allada , @MarcusSorealheis .

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-store/src/completeness_checking_store.rs` line 55 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/814#-NuCfMtE2Shn0SRW5D13:-NuCfMtF6RtykLeWZHvu:bk5a982) ([raw file](https://github.com/TraceMachina/nativelink/blob/f0bb4adf1322fcf6a81dd7e3578a96f7f1c7b48f/nativelink-store/src/completeness_checking_store.rs#L55)):*
> ```XML
> /// that need to be checked and pass them into `handle_digest_infos_fn`
> /// as they are found.
> async fn check_output_directories(
> ```

Shouldn't this function and `validate_outputs_exist` be the things being unified?

I know their logic is slightly different, but I'm pretty sure this one is the purely logic.

**Review by allada — COMMENTED** [review]
Thanks for the PR!

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814#-:-NuCfbOn0mXLzhBPu24o:b-ek0rh5)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

**Review by blizzardc0der — COMMENTED** [review]
Thanks. I re-pushed. @allada.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814#-:-NuNtOsg1pCcohNKdoKq:b2vzbsv)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-store/src/completeness_checking_store.rs` line 55 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/814#-NuCfMtE2Shn0SRW5D13:-NuNtN4n1aeUkZ8W3isJ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f0bb4adf1322fcf6a81dd7e3578a96f7f1c7b48f/nativelink-store/src/completeness_checking_store.rs#L55)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Shouldn't this function and `validate_outputs_exist` be the things being unified?

I know their logic is slightly different, but I'm pretty sure this one is the purely logic.
</blockquote></details>

Done.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-store/src/ac_utils.rs` line 94 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/814#-NuPB7Es4DlOxCLlxqQN:-NuPB7Es4DlOxCLlxqQO:bs01j70) ([raw file](https://github.com/TraceMachina/nativelink/blob/b790ea9f0aaf2fd2d64e1227bf8d979da45d944d/nativelink-store/src/ac_utils.rs#L94)):*
> ```XML
> }
> 
> pub fn get_digests_info(
> ```

why not just pass in the proto and have a callback that is called every time a digest is found? Then have the calling logic deal with the details?

**Comment by blizzardc0der** [comment]
Thanks, I re-pushed. cc: @allada.

Done

> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814)_ status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved
> 
> _[`nativelink-store/src/ac_utils.rs` line 94 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/814#-NuPB7Es4DlOxCLlxqQN:-NuPB7Es4DlOxCLlxqQO:bs01j70) ([raw file](https://github.com/TraceMachina/nativelink/blob/b790ea9f0aaf2fd2d64e1227bf8d979da45d944d/nativelink-store/src/ac_utils.rs#L94)):_
> 
> > ```
> > }
> > 
> > pub fn get_digests_info(
> > ```
> 
> why not just pass in the proto and have a callback that is called every time a digest is found? Then have the calling logic deal with the details?

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/814)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/814#-NuPnEakC3kBruPFNpli:-NuPnEakC3kBruPFNplj:b-s3nio5) (no related file):*
Lets take a different approach, instead lets make remove all the validation logic from the `CacheLookupScheduler` and instead rely purely on the completeness checking store.

@chrisstaite-menlo, what do you think about forcing the `CacheLookupScheduler` to take a `CompletenessCheckingStore` instead of a general `Store`? Or should we just document that users probably want to use `CompletenessCheckingStore` in the config?

___

**Comment by chrisstaite** [comment]
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets take a different approach, instead lets make remove all the validation logic from the `CacheLookupScheduler` and instead rely purely on the completeness checking store.

@chrisstaite-menlo, what do you think about forcing the `CacheLookupScheduler` to take a `CompletenessCheckingStore` instead of a general `Store`? Or should we just document that users probably want to use `CompletenessCheckingStore` in the config?
</blockquote></details>

I don't have a strong opinion, so long as it's documented.

**Comment by allada** [comment]
Did you mean to close this? This PR was looking good it just needed a dependency from `CacheLookupScheduler` -> `CompletenessCheckingStore`.

**Comment by blizzardc0der** [comment]
No worries. I'm opening another PR on the same issue cuz my previous solution needs to be changed entirely.
cc: @allada

**Pull request closed without merging**
