### PR TITLE
Change port location assignment

### PR DESCRIPTION
**Pull request by adam-singer**
Tickle CI

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1167)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1167)* status: 0 of 1 LGTMs obtained, and pending CI: vale, and 1 discussions need to be resolved

___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 65 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1167#-O1wOPjC8xlgZcgA9cr5:-O1wOPjC8xlgZcgA9cr6:b5u5q6e) ([raw file](https://github.com/TraceMachina/nativelink/blob/1c27393ec8bed9a6ac562aea1890d760f1486cf6/deployment-examples/chromium/03_build_chrome_tests.sh#L65)):*
> ```Shell
> 
> # Fetch cache and schedular IP address for passing to ninja
> CACHE=$(kubectl get gtw cache-gateway -o=jsonpath='{.status.addresses[0].value}'):80
> ```

80? Doesn't that require root to bind to that port?

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1167)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 65 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1167#-O1wOPjC8xlgZcgA9cr5:-O1wQkOj1r8HTQm0cTmA:b-rkmf2m) ([raw file](https://github.com/TraceMachina/nativelink/blob/1c27393ec8bed9a6ac562aea1890d760f1486cf6/deployment-examples/chromium/03_build_chrome_tests.sh#L65)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

80? Doesn't that require root to bind to that port?
</blockquote></details>

This is in the context of kubernetes/docker land. It hasn't required root due to the virtual network and I've been testing it without root access.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1167#-:-O1wRVv0Dqy1R304yQXF:bnfp4nl)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1167#-O1wRXbC6MDbYPzWV9DQ):*
nit: Please expand this a bit.

**Comment by aaronmondal** [comment]
@allada This is already on main: https://github.com/TraceMachina/nativelink/commit/00a71341630701e8fffe21bf563b201810c50f13

**Pull request closed without merging**
