### PR TITLE
Expose fingerprint hash to metrics in redis store

### PR DESCRIPTION
**Pull request by allada**
To allow external services to know what the active fingerprint is to query redis directly, we expose the fingerprint hash via metrics.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347)

### CODE REVIEW

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-:-O6gI9w60spCJEFxp4Db:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-:-O7phcoUB_iFwq1PnFXY:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (LRE), Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04)

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (LRE), Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04), and 1 discussions need to be resolved

___
*[`nativelink-store/tests/redis_store_test.rs` line 669 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O7tdy3y56QBXuNV4j2_:-O7tdy3y56QBXuNV4j2a:b-rxe7it) ([raw file](https://github.com/TraceMachina/nativelink/blob/889612219557b44d320a8534e8138b3a5fc37468/nativelink-store/tests/redis_store_test.rs#L669)):*
> ```XML
> 
> #[nativelink_test]
> fn test_fingerprint_create_index() -> Result<(), Error> {
> ```

Instead of testing like this, lets just collect the metrics... something like:
```rs
let (layer, output_metrics) = MetricsCollectorLayer::new();

// Traverse all the MetricsComponent's. The `MetricsCollectorLayer` will
// collect all the metrics and store them in `output_metrics`.
tracing::subscriber::with_default(
    tracing_subscriber::registry().with(layer),
    || {
        let metrics_component = root_metrics_clone.read();
        MetricsComponent::publish(
            &*metrics_component,
            MetricKind::Component,
            MetricFieldData::default(),
        )
    },
)
.map_err(|e| make_err!(Code::Internal, "{e}"))
.err_tip(|| "While processing prometheus metrics")?;

// ... Data is now in `output_metrics.lock()`.
println!("{:?}", output_metrics.lock());
```

Then traverse `output_metrics` to ensure it has the value at the key you want.

See this for how it is used in prod:
https://github.com/TraceMachina/nativelink/blob/73dbf59c9cd341aabd6c69578a4398e2fde54278/src/bin/nativelink.rs#L486

**Comment by blakehatch** [comment]
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347)_ status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (LRE), Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04), and 1 discussions need to be resolved
> 
> _[`nativelink-store/tests/redis_store_test.rs` line 669 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O7tdy3y56QBXuNV4j2_:-O7tdy3y56QBXuNV4j2a:b-rxe7it) ([raw file](https://github.com/TraceMachina/nativelink/blob/889612219557b44d320a8534e8138b3a5fc37468/nativelink-store/tests/redis_store_test.rs#L669)):_
> 
> > ```
> > #[nativelink_test]
> > fn test_fingerprint_create_index() -> Result<(), Error> {
> > ```
> 
> Instead of testing like this, lets just collect the metrics... something like:
> 
> ```rust
> let (layer, output_metrics) = MetricsCollectorLayer::new();
> 
> // Traverse all the MetricsComponent's. The `MetricsCollectorLayer` will
> // collect all the metrics and store them in `output_metrics`.
> tracing::subscriber::with_default(
>     tracing_subscriber::registry().with(layer),
>     || {
>         let metrics_component = root_metrics_clone.read();
>         MetricsComponent::publish(
>             &*metrics_component,
>             MetricKind::Component,
>             MetricFieldData::default(),
>         )
>     },
> )
> .map_err(|e| make_err!(Code::Internal, "{e}"))
> .err_tip(|| "While processing prometheus metrics")?;
> 
> // ... Data is now in `output_metrics.lock()`.
> println!("{:?}", output_metrics.lock());
> ```
> 
> Then traverse `output_metrics` to ensure it has the value at the key you want.
> 
> See this for how it is used in prod:
> 
> https://github.com/TraceMachina/nativelink/blob/73dbf59c9cd341aabd6c69578a4398e2fde54278/src/bin/nativelink.rs#L486

Modified to test with this method.

**Review by allada — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347)* status: 1 of 1 LGTMs obtained, and 4 of 5 files reviewed, and pending CI: Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved

___
*[`nativelink-store/src/redis_store.rs` line 76 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O87_t1gDmCkRPoLlpnT:-O87_t1gDmCkRPoLlpnU:b-4xe1gu) ([raw file](https://github.com/TraceMachina/nativelink/blob/ac03e4341d7de39c94d774d8ae1d81bb05215038/nativelink-store/src/redis_store.rs#L76)):*
> ```XML
>     /// For metrics only.
>     #[metric(
>         help = "A unique identifier for the FT.CREATE command used to create the index template"
> ```

nit: Lets use `handler = to_hex`

then add the function as something like:
```rs
fn to_hex(value: u32) -> String {
  format!("{value:08x}")
}
```

This should make the json output it as a hex string.
___
*[`nativelink-store/tests/redis_store_test.rs` line 711 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O87_QfWDxXR8Avxkbpk:-O87_QfWDxXR8Avxkbpl:bmciycu) ([raw file](https://github.com/TraceMachina/nativelink/blob/ac03e4341d7de39c94d774d8ae1d81bb05215038/nativelink-store/tests/redis_store_test.rs#L711)):*
> ```XML
>     }));
> 
>     let root_metrics_clone = root_metrics.clone();
> ```

nit: Not needed, we are not moving the variable into the lambda, so it's a reference, meaning you can use `root_metrics` directly.
___
*[`nativelink-store/tests/redis_store_test.rs` line 743 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O87_F7-DSu05YPF0QVv:-O87_F7-DSu05YPF0QVw:bmmmguf) ([raw file](https://github.com/TraceMachina/nativelink/blob/ac03e4341d7de39c94d774d8ae1d81bb05215038/nativelink-store/tests/redis_store_test.rs#L743)):*
> ```XML
>     #[metric(group = "stores")]
>     stores: Arc<dyn RootMetricsComponent>,
>     #[metric(group = "servers")]
> ```

nit: Remove all the unused ones.

**Review by blakehatch — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, pre-commit-checks, vale

___
*[`nativelink-store/src/redis_store.rs` line 76 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O87_t1gDmCkRPoLlpnT:-O87fpx3AXeWzn92YAfG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ac03e4341d7de39c94d774d8ae1d81bb05215038/nativelink-store/src/redis_store.rs#L76)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Lets use `handler = to_hex`

then add the function as something like:
```rs
fn to_hex(value: u32) -> String {
  format!("{value:08x}")
}
```

This should make the json output it as a hex string.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 711 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O87_QfWDxXR8Avxkbpk:-O87du3i5UmBGrknl2m5:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ac03e4341d7de39c94d774d8ae1d81bb05215038/nativelink-store/tests/redis_store_test.rs#L711)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Not needed, we are not moving the variable into the lambda, so it's a reference, meaning you can use `root_metrics` directly.
</blockquote></details>

Done.
___
*[`nativelink-store/tests/redis_store_test.rs` line 743 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-O87_F7-DSu05YPF0QVv:-O87dvER6-PrqjbOWBMD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ac03e4341d7de39c94d774d8ae1d81bb05215038/nativelink-store/tests/redis_store_test.rs#L743)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Remove all the unused ones.
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347#-:-O87gSoi7H_9csBnDeX1:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by blakehatch — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1347)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
