### PR TITLE
Add NixOS support

### LINKED ISSUE #1229: Document development on NixOS
We support development on virtually every distribution since we ship our entire development environment with nix.

Ironically, the one distro that doesn't work out of the box is NixOS due to various assumptions on posix compliance. We should document how to set up the nativelink repo on NixOS.

cc @jaroeichler

### PR DESCRIPTION
**Pull request by jaroeichler**
# Description

Use nix-ld to run Bazel.

Fixes #1229 

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Used a pretty minimal system configuration and `Bazel test ...` passes 51 of 52 tests, `integration_tests/running_actions_manager_test` fails. 

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287)

### CODE REVIEW

**Comment by jaroeichler** [comment]
`services.envfs.enable` is only needed for some scripts that need `/bin/bash`. Is there a better way?

@SpamDoodler can you please check if this works on your system? I've made a few changes to what we've tried a few days ago. In particular, it works without `NIX_CC_USE_RESPONSE_FILE=0` on a pretty minimal system configuration.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287)* status: 0 of 2 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04, and 3 discussions need to be resolved

___
*[`flake.nix` line 80 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-O5RiFU84eEIY6KTfOmM:-O5RiFU84eEIY6KTfOmN:blmprjd) ([raw file](https://github.com/TraceMachina/nativelink/blob/7f23c94add616dd12e043c9e8e3df83d9ddc6f15/flake.nix#L80)):*
> ```Nix
>           "/run/current-system/sw/bin"
>           "${binutils.bintools}/bin"
>           "${coreutils}/bin"
> ```

nit: For kicks, consider using `uutils-coreutils-noprefix` as pure rust implementation of the coreutils :dancer:
___
*[`flake.nix` line 83 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-O5Ri_ay4zFB-OXkRqgD:-O5Ri_azB9Hw6qV18V0u:b9a93b9) ([raw file](https://github.com/TraceMachina/nativelink/blob/7f23c94add616dd12e043c9e8e3df83d9ddc6f15/flake.nix#L83)):*
> ```Nix
>           "${customClang}/bin"
>           "${git}/bin"
>           "${python3Full}/bin"
> ```

Interesting. This looks like it exposes several nonhermeticities in the `devShell`. Most of this should probably be in the main devShell as well.

Regarding the python dependency, why do we need the `Full` variant? What's the closure size difference here?
___
*[`flake.nix` line 490 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-O5RijA_BIu0D1D_iN-t:-O5RijA_BIu0D1D_iN-u:b-xatrt7) ([raw file](https://github.com/TraceMachina/nativelink/blob/7f23c94add616dd12e043c9e8e3df83d9ddc6f15/flake.nix#L490)):*
> ```Nix
>                 ln -fs ${nixosBazelrc} nixos.bazelrc
>                 export CC=customClang
>               fi
> ```

This should be a flake module similar to the `config.pre-commit.installationScript` and `config.local-remote-execution.installationScript`. This way users can use it as a generic "NixOS Bazel compatibility" module and are not bound to our choice of clang/binutils/python and may import it in arbitrary Bazel+Nix projects.

See: 

- https://github.com/TraceMachina/nativelink/blob/1b38a64cad4b9b9e099cfeaca6b7394685458377/flake.nix#L44
- (unused in our flake, but makes it importable) https://github.com/TraceMachina/nativelink/blob/1b38a64cad4b9b9e099cfeaca6b7394685458377/flake.nix#L479
- https://github.com/TraceMachina/nativelink/blob/main/local-remote-execution/flake-module.nix
- https://github.com/TraceMachina/nativelink/blob/main/local-remote-execution/modules/lre.nix

Also note that the symlink here is too naive and should be done similar to what we have in https://github.com/TraceMachina/nativelink/blob/1b38a64cad4b9b9e099cfeaca6b7394685458377/local-remote-execution/modules/lre.nix#L135

**Review by jaroeichler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287)* status: 0 of 2 LGTMs obtained, and 4 of 7 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved

___
*[`flake.nix` line 80 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-O5RiFU84eEIY6KTfOmM:-O5WS72b1mcaCxTXjDur:b6hgo7) ([raw file](https://github.com/TraceMachina/nativelink/blob/7f23c94add616dd12e043c9e8e3df83d9ddc6f15/flake.nix#L80)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: For kicks, consider using `uutils-coreutils-noprefix` as pure rust implementation of the coreutils :dancer:
</blockquote></details>

Let's go with that.
___
*[`flake.nix` line 83 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-O5Ri_ay4zFB-OXkRqgD:-O5WSrLc8ixnWcDMVNKP:brng0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/7f23c94add616dd12e043c9e8e3df83d9ddc6f15/flake.nix#L83)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Interesting. This looks like it exposes several nonhermeticities in the `devShell`. Most of this should probably be in the main devShell as well.

Regarding the python dependency, why do we need the `Full` variant? What's the closure size difference here?
</blockquote></details>

There's around 20M closure size difference. The only reason I went for that is that it's used somewhere else in the flake for some image. I've replaced it with `python3`
___
*[`flake.nix` line 490 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-O5RijA_BIu0D1D_iN-t:-O5WTTlV8W4tWLpZbHFE:bng8b7p) ([raw file](https://github.com/TraceMachina/nativelink/blob/7f23c94add616dd12e043c9e8e3df83d9ddc6f15/flake.nix#L490)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This should be a flake module similar to the `config.pre-commit.installationScript` and `config.local-remote-execution.installationScript`. This way users can use it as a generic "NixOS Bazel compatibility" module and are not bound to our choice of clang/binutils/python and may import it in arbitrary Bazel+Nix projects.

See: 

- https://github.com/TraceMachina/nativelink/blob/1b38a64cad4b9b9e099cfeaca6b7394685458377/flake.nix#L44
- (unused in our flake, but makes it importable) https://github.com/TraceMachina/nativelink/blob/1b38a64cad4b9b9e099cfeaca6b7394685458377/flake.nix#L479
- https://github.com/TraceMachina/nativelink/blob/main/local-remote-execution/flake-module.nix
- https://github.com/TraceMachina/nativelink/blob/main/local-remote-execution/modules/lre.nix

Also note that the symlink here is too naive and should be done similar to what we have in https://github.com/TraceMachina/nativelink/blob/1b38a64cad4b9b9e099cfeaca6b7394685458377/local-remote-execution/modules/lre.nix#L135
</blockquote></details>

I've pretty much copied your setup. An empty default of paths in `nixos.settings.path` is somehow intentional since I don't want to pass `customClang` to the module and just replacing it with `pkgs.clang` leads to `iostream` not found. Side note, `lib.mdDoc` is deprecated.

**Review by aaronmondal — APPROVED** [review]
Nice work!

:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-O5XCBx1DR6QCWndybTI:ban4mzi)* status: 1 of 2 LGTMs obtained, and all files reviewed

**Review by aaronmondal — APPROVED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-O5XCxN58ViVhoDcc6Lp:b-bn1n1c)* status: 1 of 2 LGTMs obtained, and all files reviewed (waiting on @adam-singer)

**Review by allada — APPROVED** [review]
-@adam-singer 
:lgtm:

> Reviewed 4 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-O9pY87o8MJ56TgJMJ3g:bei3kzc)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

**Review by allada — APPROVED** [review]
Can we rebase and land this?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-O9pYDW5EJsATo541a23:b-f9brho)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

**Comment by jaroeichler** [comment]
Sure, adjusted the nixos flake module path to the darwin flake module path

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-O9r7TRD57SUAXZdjI9f:bnfp4nl)* status: 2 of 2 LGTMs obtained, and all files reviewed, and pending CI: Web Platform Deployment / macos-14

**Review by aaronmondal — CHANGES_REQUESTED** [review]
@jaroeichler I believe there is some sort of rebase conflict going on here. The darwin logic in the flake no longer needs to be conditional and is already on main. For some reason darwin-related changes show up in this diff.

> Reviewed 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-OA48B-2Co2Tsulo7pH2:bd2ceoc)* status: 2 of 2 LGTMs obtained, and all files reviewed, and pending CI: Web Platform Deployment / macos-14

**Comment by jaroeichler** [comment]
@aaronmondal Thanks, didn't notice it when reviewing the diff. Should be fine now.

**Review by aaronmondal — APPROVED** [review]
Thanks :heart:

:lgtm:

> Reviewed 4 of 7 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1287#-:-OA4MRtt23u7A5BNOtsi:b-gxuego)* status: 2 of 2 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Pull request merged**
