### PR TITLE
[bug] Fix chromium demo

### PR DESCRIPTION
**Pull request by adam-singer**
# Description

Chromium demo is missing the `/shared` volume mount and port `:80` 

Fixes https://github.com/TraceMachina/nativelink/issues/1145 

## Type of change

Please delete options that aren't relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

run locally

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1144)

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1144#-:-O1XtZwx0pFJxmMtFAXq:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by adam-singer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1144#-:-O1XuWn971_euMAOnYZZ:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), pre-commit-checks, vale

**Review by adam-singer — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1144)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), pre-commit-checks, vale

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1144)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1144#-:-O1Y6d6JByTfiOHK8w3q:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
