### PR TITLE
Make max_bytes_per_stream optional in config

### PR DESCRIPTION
**Pull request by allada**
Defaults "max_bytes_per_stream" to 64Kib in config file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/474)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/474#-:-NlUlXcx-yLBsPkh72Wo:b-bn1n1c)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @adam-singer)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/474#-:-NlUphJY8jgPs6lcmdCf:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @allada)

___
*[`nativelink-config/src/cas_server.rs` line 126 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/474#-NlUn47tEhgd7uiQvH6g:-NlUn47tEhgd7uiQvH6h:bpjrl7v) ([raw file](https://github.com/TraceMachina/nativelink/blob/4cb0679049b099ed8f403d9e68b475b48171b81b/nativelink-config/src/cas_server.rs#L126)):*
> ```XML
>     /// 16KiB - 64KiB is optimal.
>     ///
>     /// Defaults: 64Kib
> ```

nit: `64Kib` -> `64KiB`
___
*[`nativelink-config/src/cas_server.rs` line 128 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/474#-NlUotpU20j-CC3w8991:-NlUotpU20j-CC3w8992:b63q8b1) ([raw file](https://github.com/TraceMachina/nativelink/blob/4cb0679049b099ed8f403d9e68b475b48171b81b/nativelink-config/src/cas_server.rs#L128)):*
> ```XML
>     /// Defaults: 64Kib
>     #[serde(default, deserialize_with = "convert_numeric_with_shellexpand")]
>     pub max_bytes_per_stream: usize,
> ```

What happens with serialization here if parses for a size larger than machine architecture (given usize is machine size specific)? 

It does seem the least bad choice to keep ubiquitous between specific size, wondering if configuration mishaps could happen here (and think probably very low)
___
*[`nativelink-service/src/bytestream_server.rs` line 176 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/474#-NlUnLVC55BztEi5A_3q:-NlUnLVC55BztEi5A_3r:blr32gf) ([raw file](https://github.com/TraceMachina/nativelink/blob/4cb0679049b099ed8f403d9e68b475b48171b81b/nativelink-service/src/bytestream_server.rs#L176)):*
> ```XML
>             stores.insert(instance_name.to_string(), store);
>         }
>         let max_bytes_per_stream = if config.max_bytes_per_stream == 0 {
> ```

Are there any maximum value constraints that we should guard here on? A size that might have the opposite regardless of situation?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/474)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @adam-singer)

___
*[`nativelink-config/src/cas_server.rs` line 126 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/474#-NlUn47tEhgd7uiQvH6g:-NlV-wAY9oTg7axgJkgP:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/4cb0679049b099ed8f403d9e68b475b48171b81b/nativelink-config/src/cas_server.rs#L126)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: `64Kib` -> `64KiB`
</blockquote></details>

Done.
___
*[`nativelink-config/src/cas_server.rs` line 128 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/474#-NlUotpU20j-CC3w8991:-NlV-z6I6s4owsKkyDr4:b4bh91e) ([raw file](https://github.com/TraceMachina/nativelink/blob/4cb0679049b099ed8f403d9e68b475b48171b81b/nativelink-config/src/cas_server.rs#L128)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

What happens with serialization here if parses for a size larger than machine architecture (given usize is machine size specific)? 

It does seem the least bad choice to keep ubiquitous between specific size, wondering if configuration mishaps could happen here (and think probably very low)
</blockquote></details>

I'm pretty sure it'll panic at parse time. Rust has undefined behavior protection even at runtime (in theory).
___
*[`nativelink-service/src/bytestream_server.rs` line 176 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/474#-NlUnLVC55BztEi5A_3q:-NlV09Ar9YzPwkrtS4dE:b-mxqgse) ([raw file](https://github.com/TraceMachina/nativelink/blob/4cb0679049b099ed8f403d9e68b475b48171b81b/nativelink-service/src/bytestream_server.rs#L176)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Are there any maximum value constraints that we should guard here on? A size that might have the opposite regardless of situation?
</blockquote></details>

In theory the maximum is how much ram you have. This is a config value, so it's generally considered a "safe" variable since it's a config set by the server and not a property sent by a user.

**Review by allada — COMMENTED** [review]
> Dismissed @adam-singer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/474)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @adam-singer)

**Pull request merged**
