### PR TITLE
Fix broken variables in NativeLink Cloud CI jobs and disable RBE test

### PR DESCRIPTION
**Pull request by bclark8923**
# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1293)

### CODE REVIEW

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1293#-:-O5V-riq9lx2UfZk7gvY:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, and 1 discussions need to be resolved

___
*[`.github/workflows/main.yml` line 63 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1293#-O5V-j-K9kIPpCpOpM51:-O5V-j-L7eLgQd5u0e9k:bw0laou) ([raw file](https://github.com/TraceMachina/nativelink/blob/2dd587980b5d721e9d4c1035694c9633fd9491bf/.github/workflows/main.yml#L63)):*
> ```YAML
>           --remote_header=x-nativelink-project=nativelink-ci \
>           --remote_executor=grpcs://scheduler-tracemachina-shared.build-faster.nativelink.net:443 \
>           --remote_default_exec_properties="container-image=docker://$RBE_IMAGE" \
> ```

This is the most annoying github thing.. almost looks like a shell variable but isn't. `${RBE_IMAGE}` doesn't work on github actions

**Review by aaronmondal — APPROVED** [review]
:lgtm:

fyi we need to fix the hash mismatch outlined in https://github.com/nlewo/nix2container/pull/150 to unblock this.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1293#-:-O5V6E8rA9jc-OtO81y4:b-nc8vxz)* status: 2 of 1 LGTMs obtained, and all files reviewed, and pending CI: Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, and 1 discussions need to be resolved

**Comment by aaronmondal** [comment]
Sent https://github.com/TraceMachina/nativelink/pull/1294 to fix the OCI workflow

**Review by bclark8923 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1293)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
