### PR TITLE
Adding drake toolchain prototype

### PR DESCRIPTION
**Pull request by adam-singer**
# Description

Introduce drake toolchain prototype. This isn't intended for general use atm and should be considered prototype. 

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942)

### CODE REVIEW

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942)* status: 0 of 1 LGTMs obtained, and pending CI: Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-22.04, vale, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/942#-Nz9lEm5DgfP2YWFfFQe):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: "Add drake toolchain configs" or "Add drake toolchain prototype"
</blockquote></details>

Done.
___
*[`tools/toolchain-drake/Dockerfile` line 15 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/942#-Nz9lVc1-FZV8UTASieg:-NzAcize9bXHTdK51bV9:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ca86740760b24a440ad259370dd3bde79101c593/tools/toolchain-drake/Dockerfile#L15)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This needs to be pinned so that we don't get a "Unpinned dependencies" score downgrade from the OpenSSF scorecard.
</blockquote></details>

Done.
___
*[`tools/toolchain-drake/Dockerfile` line 23 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/942#-Nz9mUM051fMpL6s6Yjv:-NzAckHUDh74_R5THepG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ca86740760b24a440ad259370dd3bde79101c593/tools/toolchain-drake/Dockerfile#L23)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is there a specific reason that we need `sslVerify=false`? If we're missing certificates, would it make sense to add the `cacerts` package?

nit: Do we want to always use the latest commit, or should the checkout be pinned?
nit: We could use a shallow clone at a specific commit to speed up the clone. This would improve reproducibility and reduce clone time.
</blockquote></details>

Done.
___
*[`tools/toolchain-drake/toolchain-drake.sh` line 56 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/942#-Nz9mCTV8wsjzA-FUHKc:-NzAcq1r7ujrCUPlH4I8:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ca86740760b24a440ad259370dd3bde79101c593/tools/toolchain-drake/toolchain-drake.sh#L56)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Consider breaking this line.
</blockquote></details>

Done.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942#-:-NzCxRQK76Fk0BOtiMRE:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: windows-2022 / stable

**Review by adam-singer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942#-:-NzFPtrU6bg6XweGDNBx:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: windows-2022 / stable

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by zbirenbaum — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942#-:-NzFiJZD9fyKpEcgiR2k:bg7igkv)* status: 3 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, and 1 discussions need to be resolved

___
*[`tools/toolchain-drake/toolchain-drake.sh` line 67 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/942#-NzFhfi8Afdr8D1IW203:-NzFhfi8Afdr8D1IW204:b-91wuup) ([raw file](https://github.com/TraceMachina/nativelink/blob/557d6b28662db6b77cf673d1435d8901544d6a2f/tools/toolchain-drake/toolchain-drake.sh#L67)):*
> ```Shell
> 
> # Patch flake.nix with sha256 value.
> sed -i -E "s|sha256 = \"\"; # DO NOT COMMIT DRAKE SHA256 VALUE|sha256 = \"${SHA256_HASH}\"; # DO NOT COMMIT DRAKE SHA256 VALUE|" "${FLAKE_NIX_FILE}"
> ```

nit: Maybe it's just reviewable but it's really difficult to make out what is going on on these lines due to the comment. Could you clean this up a bit?

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/942)* status: 3 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`tools/toolchain-drake/toolchain-drake.sh` line 67 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/942#-NzFhfi8Afdr8D1IW203:-NzFncC03pdbRt1f2Pv3:b-5izmqp) ([raw file](https://github.com/TraceMachina/nativelink/blob/557d6b28662db6b77cf673d1435d8901544d6a2f/tools/toolchain-drake/toolchain-drake.sh#L67)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

nit: Maybe it's just reviewable but it's really difficult to make out what is going on on these lines due to the comment. Could you clean this up a bit?
</blockquote></details>

This is a sed search and replace for a specific line. The problem we have is producing the toolchain is not within the reproducibility situation due to using the installer scripts provided by drake. As a compromise of not having to reverse eng their build dependencies at this time, we are generating the image, then applying a patch with the image hash to the flake.nix to generate the rest of the container layers. Also why this will be considered a prototype for now. The right solution would be to unroll explicitly all dependencies needed at their specific build/code points.

**Pull request merged**
