### PR TITLE
[Bug fix] Adds retry logic to redis store

### PR DESCRIPTION
**Pull request by allada**
Adds retry logic and configs for redis store. This will setup redis to reconnect and retry commands if the connection to redis is lost.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-:-O8u7qhB1acvyadoCrbq:b-bn1n1c)* status: 0 of 1 LGTMs obtained, and 0 of 7 files reviewed, and pending CI: Web Platform Deployment / ubuntu-24.04, pre-commit-checks (waiting on @adam-singer)

___
*[`nativelink-metric-collector/Cargo.toml` line 9 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O8u8n3N6-rkg6JKQBd5:-O8u8n3N6-rkg6JKQBd6:bcobqnq) ([raw file](https://github.com/TraceMachina/nativelink/blob/a0548ec31ee7d098d8cde91c85e87d377d8f9d7b/nativelink-metric-collector/Cargo.toml#L9)):*
> ```TOML
> [dependencies]
> nativelink-metric = { path = "../nativelink-metric" }
> opentelemetry = { version = "0.24.0", features = ["metrics"], default-features = false }
> ```

fyi: Fixes a test deps issue.
___
*[`nativelink-store/src/redis_store.rs` line 311 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O8u9K1c7e3LFPbfqe6c:-O8u9K1c7e3LFPbfqe6d:bdnb4zr) ([raw file](https://github.com/TraceMachina/nativelink/blob/a0548ec31ee7d098d8cde91c85e87d377d8f9d7b/nativelink-store/src/redis_store.rs#L311)):*
> ```XML
>         results: &mut [Option<u64>],
>     ) -> Result<(), Error> {
>         // TODO(allada) We could use pipeline here, but it makes retry more
> ```

fyi: This is most likely the cause of why cluster mode was not working.
___
*[`nativelink-store/src/redis_store.rs` line 378 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O8u9RhO1vpcOzGKqFNo:-O8u9RhO1vpcOzGKqFNp:bymi0b) ([raw file](https://github.com/TraceMachina/nativelink/blob/a0548ec31ee7d098d8cde91c85e87d377d8f9d7b/nativelink-store/src/redis_store.rs#L378)):*
> ```XML
>         );
> 
>         if is_zero_digest(key.borrow()) {
> ```

fyi: I tried to simplify this. We will optimize anything needed later... I turns out `fred` multiplexes commands on the same connection quite well, so we don't need to be very careful in "packing" our streams here, so there's a good chance we don't need all this old complexity.
___
*[`nativelink-store/src/redis_store.rs` line 418 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O8uAABT6L2V8CUPSlda:-O8uAABT6L2V8CUPSldb:bn9c6u) ([raw file](https://github.com/TraceMachina/nativelink/blob/a0548ec31ee7d098d8cde91c85e87d377d8f9d7b/nativelink-store/src/redis_store.rs#L418)):*
> ```XML
>                 Ok(async move {
>                     client
>                         .setrange::<(), _, _>(temp_key_ref, offset, chunk)
> ```

fyi: Changed to `setrange` so retries don't interfere with `append`. Also likely more efficient/safe.
___
*[`nativelink-store/src/redis_store.rs` line 1070 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O8uAgDC3glU5dMVMTuv:-O8uAgDC3glU5dMVMTuw:b-6gbsh7) ([raw file](https://github.com/TraceMachina/nativelink/blob/a0548ec31ee7d098d8cde91c85e87d377d8f9d7b/nativelink-store/src/redis_store.rs#L1070)):*
> ```XML
>         };
>         let stream = run_ft_aggregate()?
>             .or_else(|_| async move {
> ```

fyi: Just to simplify the code a bit.

**Review by SchahinRohani — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407)* status: 0 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-store/src/redis_store.rs` line 238 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O9mNI0C9dNX0y2IQphq:-O9mNI0C9dNX0y2IQphr:b-5sxil8) ([raw file](https://github.com/TraceMachina/nativelink/blob/45b4e8dad7f321a43e03963b756797ac782e1eb4/nativelink-store/src/redis_store.rs#L238)):*
> ```XML
>         let subscriber_client = builder
>             .build_subscriber_client()
>             .err_tip(|| "while creating redis subscriber client")?;
> ```

Shouldn't this PR throw an error if the redis connections fails in general? 

For making the first connection with a publish client for example?

This would fix issue #1266

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407)* status: 0 of 1 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-store/src/redis_store.rs` line 238 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-O9mNI0C9dNX0y2IQphq:-O9ovB5C6Kyz9I-Gdzdv:b2l7mbp) ([raw file](https://github.com/TraceMachina/nativelink/blob/45b4e8dad7f321a43e03963b756797ac782e1eb4/nativelink-store/src/redis_store.rs#L238)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

Shouldn't this PR throw an error if the redis connections fails in general? 

For making the first connection with a publish client for example?

This would fix issue #1266
</blockquote></details>

The redis library we use (`fred`) manages reconnects for us. This sets it all up. In this case no, we don't want to slow down the startup of nativelink just because we don't have a redis connection... instead we queue up commands then dispatch them when it connects.

**Review by SchahinRohani — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-:-O9owATd2zQfp81xFqPo:bnfp4nl)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer)

**Review by SchahinRohani — APPROVED** [review]
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407#-:-O9owKk78UFIMWqTt3NB:b-sd1e3m)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by SchahinRohani — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1407)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
