### PR TITLE
Add RedisOperation and RedisOperationState

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description
Creates groundwork for Redis State Manager implementation by introducing two new structs. RedisOperation represents an operation stored in redis and RedisOperationState represents the wrapped object which implements the ActionStateResult trait.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1020)

### CODE REVIEW

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1020)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), and 2 discussions need to be resolved

___
*[`nativelink-scheduler/BUILD.bazel` line 20 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1020#-O-j6UPe24YpcORf9Ha8:-O-lXDUWEBhsPewzKFlm:bqp7wcu) ([raw file](https://github.com/TraceMachina/nativelink/blob/d3ef560bb5c56011ebbcb14f4aba94f917bb4f5e/nativelink-scheduler/BUILD.bazel#L20)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

can redis stuff be scoped under a `redis` folder ?
</blockquote></details>

Let's do that in a followup if possible, happy to make a ticket for it. Right now it's all contained in one place so it's not much clutter. If we want to break it out into multiple files in a sub dir that's fine but will require a lot of overhead since there are 3 other PRs to rebase.
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 90 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1020#-O-j7-3q6ZEfn8mRgGTO:-O-lWZoZ2NKbl3Je2kM_:bs1y97) ([raw file](https://github.com/TraceMachina/nativelink/blob/d3ef560bb5c56011ebbcb14f4aba94f917bb4f5e/nativelink-scheduler/src/redis_operation_state.rs#L90)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Why are these `todo`? Would it be odd to return a `Result` from a "new" constructor?
</blockquote></details>

Blaise and I discussed this and the error handling here get's extremely complicated. They will have to be sent like event notifications and figuring out the best way to do it will take some thought.

Returning a result from a new constructor isn't an issue, but returning it from a spawn is.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1020#-:-O-mGAsY-mSMlg14uoT9:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1020)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 34 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1020#-O0Cv38B9M0Lr7jxfib0:-O0Cv38B9M0Lr7jxfib1:b-r905u5) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L34)):*
> ```XML
> use crate::operation_state_manager::{ActionStateResult, OperationStageFlags};
> 
> #[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
> ```

I don't love this enum and I really don't like the `parse_state_flags` method below it. The problem is that we 
___
*[`nativelink-scheduler/src/redis_operation_state.rs` line 43 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1020#-O0D45rQ-kfqWz8KMfqK:-O0D45rR4WrV8UQ0vI7Q:b8j6zdy) ([raw file](https://github.com/TraceMachina/nativelink/blob/786298cd1f6a6c5cc3caf4c6e9e3d0b803a3edcd/nativelink-scheduler/src/redis_operation_state.rs#L43)):*
> ```XML
> }
> 
> fn _parse_stage_flags(flags: &OperationStageFlags) -> Vec<OperationStage> {
> ```

I added some context on why this exists in the client pr where this function is actually called. The bottom line is I really don't like it but I'm not entirely sure what the best way to do this is and am open to suggestions.

I don't think this code should be merged, it's just too verbose.

**Comment by zbirenbaum** [comment]
Changes merged in #1023

**Pull request closed without merging**
