### PR TITLE
Fix possible deadlock if max_open_files set too low

### LINKED ISSUE #907: Possible deadlock if `max_open_files` set too low
A bug was discovered that if `max_open_files` is set too low and remote execution is enabled, it is possible for a worker to get locked up dealing with the files.

This was introduced in:
https://github.com/TraceMachina/nativelink/commit/7c9a07085298d1546b4459d6a22ec87bf8189395

The root cause is because the source and destination can both be files (which is very common for workers). We added an optimization that simply moves the files. This is great, except to keep system resources low, we try to keep using the same file descriptor. What ended up happening is the file would be small, and be able to ship all the bytes in one-go, the sender future would then be done, but the receiver has not even opened the file to where the data will be written. Since we don't close the file now in this path, it causes the reader to hold the file file permit and the writer file, cannot get a permit to be able to open the file to begin writing.

### PR DESCRIPTION
**Pull request by allada**
We now close the file permit if the write future takes too long.

fixes #907

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/908)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/908#-:-NxZN9BE7i2_1m4MNAq0:b-bn1n1c)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, vale, and 1 discussions need to be resolved (waiting on @adam)

___
*[`nativelink-util/src/lib.rs` line 39 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/908#-NxZN0ol8_Tuv0-Y2hWH:-NxZN0ol8_Tuv0-Y2hWI:bgrfb11) ([raw file](https://github.com/TraceMachina/nativelink/blob/0dfef3f58f53285a44b5eaadb291f40d46e95888/nativelink-util/src/lib.rs#L39)):*
> ```XML
> 
> /// Initialize tracing.
> pub fn init_tracing() -> Result<(), nativelink_error::Error> {
> ```

I did this to help debug tests, so figured I'd sneak it in.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/908#-:-NxaAAUB4JkCfpLFWtS1:bnfp4nl)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-macro/src/lib.rs` line 40 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa6MYiEomvP4wzocN1:-Nxa6MYiEomvP4wzocN2:b-qj28fw) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-macro/src/lib.rs#L40)):*
> ```XML
>             let _ = nativelink_util::init_tracing();
>             // If already set it's ok.
>             let _ = nativelink_util::fs::set_idle_file_descriptor_timeout(std::time::Duration::from_millis(100));
> ```

nit: Seem like something that should be a parameter defaulted to 100ms but configurable, 150-300ms hopefully should be max budget to complete a request in an ideal scenario 
___
*[`nativelink-store/src/filesystem_store.rs` line 805 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa78h184luAvzZmBTJ:-Nxa78h184luAvzZmBTK:b-dpmgfh) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/src/filesystem_store.rs#L805)):*
> ```XML
>             }),
>         );
>         drop(file);
> ```

nit: lets comment on why the drop since we are explicit about releasing the reference within a function 
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1421 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa7ieG2oaoUV6jbw-N:-Nxa7ieG2oaoUV6jbw-O:bl6x4r1) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/tests/filesystem_store_test.rs#L1421)):*
> ```XML
>     async fn update_with_whole_file_closes_file() -> Result<(), Error> {
>         let mut permits = vec![];
>         // Grab al permits to ensure only 1 permit is available.
> ```

nit: "Grab al" -> "Grab all"
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1473 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa7zws3atl3pobmS9l:-Nxa7zws3atl3pobmS9m:bhoilir) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/tests/filesystem_store_test.rs#L1473)):*
> ```XML
>     async fn update_with_whole_file_slow_path_when_low_file_descriptors() -> Result<(), Error> {
>         let mut permits = vec![];
>         // Grab al permits to ensure only 1 permit is available.
> ```

nit: "Grab al" -> "Grab all" 
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1492 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa8H5V8LGOR5ZYoTPN:-Nxa8H5V8LGOR5ZYoTPO:b-im28fk) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/tests/filesystem_store_test.rs#L1492)):*
> ```XML
>         let store = Box::pin(FastSlowStore::new(
>             // Note: The config is not needed for this test, so use dummy data.
>             &nativelink_config::stores::FastSlowStore {
> ```

nit: alias or import the struct (applied to same below, if existing code is like that I guess leave) 
___
*[`nativelink-util/src/fs.rs` line 372 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa9TwC8yH1yRtn0k95:-Nxa9TwC8yH1yRtn0k96:bu6nnvr) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-util/src/fs.rs#L372)):*
> ```XML
>         Ok((
>             permit,
>             std::fs::File::options()
> ```

this code makes me happy and sad at the same time. 
___
*[`nativelink-util/src/lib.rs` line 42 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa9dF3-HlVfPBGmlu3:-Nxa9dF3-HlVfPBGmlu4:bsujo0i) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-util/src/lib.rs#L42)):*
> ```XML
>     use tracing_subscriber::prelude::*;
> 
>     static LOGGING_INITIALIZED: std::sync::Mutex<bool> = std::sync::Mutex::new(false);
> ```

nit: use `std::sync::Mutex`

**Review by adam-singer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/908)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/908)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04

___
*[`nativelink-macro/src/lib.rs` line 40 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa6MYiEomvP4wzocN1:-Nxhwrc59a3GZeBZRUAJ:b-bu6rmi) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-macro/src/lib.rs#L40)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: Seem like something that should be a parameter defaulted to 100ms but configurable, 150-300ms hopefully should be max budget to complete a request in an ideal scenario
</blockquote></details>

I do agree, but also don't want to spend time dealing with macros on this. For now i'll leave it this way. When we need it parameterized lets do it then.

Keep in mind this is test-only code.
___
*[`nativelink-store/src/filesystem_store.rs` line 805 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa78h184luAvzZmBTJ:-NxhxHSY-4crS6KcvqY-:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/src/filesystem_store.rs#L805)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: lets comment on why the drop since we are explicit about releasing the reference within a function
</blockquote></details>

Done.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1421 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa7ieG2oaoUV6jbw-N:-NxhxOPFEOIBcO7-2x54:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/tests/filesystem_store_test.rs#L1421)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: "Grab al" -> "Grab all"
</blockquote></details>

Done.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1473 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa7zws3atl3pobmS9l:-NxhxPvu651fwyFxKa_u:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/tests/filesystem_store_test.rs#L1473)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: "Grab al" -> "Grab all"
</blockquote></details>

Done.
___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1492 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa8H5V8LGOR5ZYoTPN:-NxhxaPh69o8MDi6d-HM:bjz602w) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-store/tests/filesystem_store_test.rs#L1492)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: alias or import the struct (applied to same below, if existing code is like that I guess leave)
</blockquote></details>

Yeah to reduce the risk of name collision, we give full paths for all config variables. This is common in this entire file and most of the rest of the tests.
___
*[`nativelink-util/src/fs.rs` line 372 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa9TwC8yH1yRtn0k95:-NxhxnkHBZW7z_hn9zIm:b-jxngdl) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-util/src/fs.rs#L372)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

this code makes me happy and sad at the same time.
</blockquote></details>

Yeah. I found a case that we are using the same descriptor to write then read, and `std::fs::File::create()` opens in write-only mode.
___
*[`nativelink-util/src/lib.rs` line 42 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/908#-Nxa9dF3-HlVfPBGmlu3:-NxhyLoy1tu3pH8Z_KGU:b-zeh28w) ([raw file](https://github.com/TraceMachina/nativelink/blob/0b3ab20fff097f4eeb0bb61b10c3e0b96c4e92e4/nativelink-util/src/lib.rs#L42)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: use `std::sync::Mutex`
</blockquote></details>

I think you meant `parking_lot`. Done.

**Pull request merged**
