### PR TITLE
Fix LLVM 18 toolchains after fb0edae

### LINKED ISSUE #881: C++ toolchain has libcxx and libunwind version mismatch
We're supposed to be on 18.1.3, but somehow we get libcxx and libunwind from 17.0.6 into the build. 

This causes CI breakeages, e.g.

https://github.com/TraceMachina/nativelink/actions/runs/8833858855/job/24256606735?pr=879
https://github.com/TraceMachina/nativelink/actions/runs/8838275944/job/24269028250?pr=880

```
ERROR: /home/aaron/aaronmondal/nativelink/local-remote-execution/examples/BUILD.bazel:3:10: Linking local-remote-execution/examples/hello_lre failed: (Exit 1): customClang fa
iled: error executing CppLink command (from target //local-remote-execution/examples:hello_lre) /nix/store/p8ck07vfxiszzqpcz0p2l0afb6nmlxmx-customClang/bin/customClang @bazel
-out/k8-fastbuild/bin/local-remote-execution/examples/hello_lre-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
clang version 18.1.3
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/r3cfvnc01wssfqhp5kg8725v94idkysy-clang-18.1.3/bin
Found candidate GCC installation: /nix/store/nn152mgpdfcw92b3b03g9kmnlpd9jris-gcc-13.2.0/lib/gcc/x86_64-unknown-linux-gnu/13.2.0
Found candidate GCC installation: /nix/store/nn152mgpdfcw92b3b03g9kmnlpd9jris-gcc-13.2.0/lib64/gcc/x86_64-unknown-linux-gnu/13.2.0
Selected GCC installation: /nix/store/nn152mgpdfcw92b3b03g9kmnlpd9jris-gcc-13.2.0/lib64/gcc/x86_64-unknown-linux-gnu/13.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found HIP installation: /usr/local, version 5.7.31921
 "/usr/lib/llvm/18/bin/ld.lld" --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -pie -o bazel-out/k8-fastbuild/bin/local-remote-execution/examples/hello_lre /nix/store/35pq4hr29
c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/Scrt1.o /nix/store/35pq4hr29c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/crti.o /nix/store/5b4is024ajpfphzx5fvf5wqqy3i3y45r-clang-wrapper
-18.1.3/resource-root/lib/linux/clang_rt.crtbegin-x86_64.o -L/nix/store/35pq4hr29c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib -L/nix/store/nn152mgpdfcw92b3b03g9kmnlpd9jris-gcc-13
.2.0//lib -L/nix/store/d8c0am4jck9188ajr9swx6kmcqrh8zkl-gcc-13.2.0-libgcc/lib -L/nix/store/g7hla2jnfwyys9zxqp7n4w5wf20dqks8-clang-18.1.3-lib/lib -L/nix/store/1jvrjkymv56pbva6
hfsbdavf8h44dn1g-libunwind-18.1.3/lib -L/nix/store/nn152mgpdfcw92b3b03g9kmnlpd9jris-gcc-13.2.0/lib64/gcc/x86_64-unknown-linux-gnu/13.2.0 -L/nix/store/nn152mgpdfcw92b3b03g9kmn
lpd9jris-gcc-13.2.0/lib64/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib -dynamic-linker=/nix/store/35pq4hr29c3sl
79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/ld-linux-x86-64.so.2 -S -no-as-needed -z relro -z now bazel-out/k8-fastbuild/bin/local-remote-execution/examples/_objs/hello_lre/hello.pi
c.o --push-state -as-needed -lstdc++ --pop-state --push-state -as-needed -lm --pop-state /nix/store/5b4is024ajpfphzx5fvf5wqqy3i3y45r-clang-wrapper-18.1.3/resource-root/lib/li
nux/libclang_rt.builtins-x86_64.a --as-needed -lunwind --no-as-needed -lc /nix/store/5b4is024ajpfphzx5fvf5wqqy3i3y45r-clang-wrapper-18.1.3/resource-root/lib/linux/libclang_rt
.builtins-x86_64.a --as-needed -lunwind --no-as-needed /nix/store/5b4is024ajpfphzx5fvf5wqqy3i3y45r-clang-wrapper-18.1.3/resource-root/lib/linux/clang_rt.crtend-x86_64.o /nix/
store/35pq4hr29c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/crtn.o
```

### PR DESCRIPTION
**Pull request by aaronmondal**
Pull the LLVM major version out to the root-level flake so that the entire repository is uniformly configured from that single line.

Fixes LRE not using Mold properly. The switch reduces link time for C++ actions by ~95%.

Fixes #881

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/883)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@allada +@adam-singer +@blakehatch 

This should unbreak CI.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/883#-:-NwMgnPLELSvkOUFseYt:b2ltvcb)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, and @blakehatch)

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/883#-:-NwMidoJ0zpLYLs0HrAY:bnfp4nl)* status: 1 of 3 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer and @blakehatch)

___
*[`flake.nix` line 163 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/883#-NwMiLOX1zAMMWe3YFq3:-NwMiLOX1zAMMWe3YFq4:b-mlv614) ([raw file](https://github.com/TraceMachina/nativelink/blob/5604c6baeca57c137ae7826c90f5d0061c1900f5/flake.nix#L163)):*
> ```Nix
>             name = "nixpkgs-patched";
>             src = self.inputs.nixpkgs;
>             patches = [./tools/nixpkgs_link_libunwind_and_libcxx.diff];
> ```

Any upstream ticket or reference for this patch?

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/883)* status: 1 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer and @blakehatch)

___
*[`flake.nix` line 163 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/883#-NwMiLOX1zAMMWe3YFq3:-NwMs_IU7m53yQsyZ15x:b1al9q5) ([raw file](https://github.com/TraceMachina/nativelink/blob/5604c6baeca57c137ae7826c90f5d0061c1900f5/flake.nix#L163)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Any upstream ticket or reference for this patch?
</blockquote></details>

Done.

This is custom. I linked the issue that tracks the general problem.

**Review by aaronmondal — COMMENTED** [review]
-@adam-singer -@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/883#-:-NwMvW6H5koRT2v7gmrc:bck5ko0)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/883)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Pull request merged**
