### PR TITLE
[Refactor] Stores now return Arc for construction

### PR DESCRIPTION
**Pull request by allada**
We implicitly use all stores as Arc's anyway, so this PR just
makes it easier for stores to grab a Weak to self for some
specific cases.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/989)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
fyi: @adam-singer 
+@zbirenbaum 

note: This PR is pending the memory store PR to land first.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/989#-:-O-7rB8z7w70g6ErGFzr:b-fauf93)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @zbirenbaum)

**Review by adam-singer — COMMENTED** [review]
> Reviewed 11 of 17 files at r1, 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/989)* status: 0 of 1 LGTMs obtained (waiting on @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/989)* status: 0 of 1 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, pre-commit-checks (waiting on @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/989#-:-O-KTdeR9L8ZEfbmH9MD:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc, pre-commit-checks

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/989)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
