### PR TITLE
Release nativelink v0.2.0

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@MarcusSorealheis +@adam-singer +@allada +@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572#-:-NmCdmFJ9EuF562mSdzH:bqhjtm3)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Comment by MarcusSorealheis** [comment]
can we rename the binary `nativelink`?

**Review by aaronmondal — COMMENTED** [review]
@MarcusSorealheis Yeah I'm also in favor of doing that before we cut this. I can change this for nix/cargo/bazel/k8s but I'm not familiar enough with the existing terraform deployments.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572#-:-NmCeUwuCkCX0YEriWCv:b6079yl)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Comment by MarcusSorealheis** [comment]
You only need to change the `top-level` Cargo.toml and the file in `src/bin/nativelink.rs`.

**Review by aaronmondal — COMMENTED** [review]
#573  

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572#-:-NmCnmiB4sw97QUMWvp8:bboj3ir)* status: 0 of 4 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572#-:-NmDJhje4EVtytry1jQP:bnfp4nl)* status: 1 of 4 LGTMs obtained (waiting on @adam-singer, @blakehatch, and @MarcusSorealheis)

**Review by MarcusSorealheis — APPROVED** [review]

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572#-:-NmDOmu2DBR1Fljev8m0:bnfp4nl)* status: 2 of 4 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @blakehatch and @MarcusSorealheis)

**Review by MarcusSorealheis — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572)* status: 2 of 4 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04) (waiting on @blakehatch)

**Review by MarcusSorealheis — APPROVED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572)* status: 3 of 4 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04) (waiting on @blakehatch)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/572#-NmDRyJ9AnWRTJlN4dj3:-NmDRyJ9AnWRTJlN4dj4:bg7igkv) (no related file):*
:lgtm: 

___

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572)* status: 3 of 3 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/572#-NmDRyJ9AnWRTJlN4dj3:-NmDTOhMBD8zO9qaT9hL:b-896fix) (no related file):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

:lgtm:
</blockquote></details>

Done.

___

**Review by aaronmondal — COMMENTED** [review]
> Dismissed @MarcusSorealheis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/572)* status: <span>:shipit:</span> complete! 3 of 3 LGTMs obtained

**Pull request merged**
