### PR TITLE
Add configuration breakdown page

### LINKED ISSUE #724: Add Configuration Field Breakdown in nativelink-docs

### PR DESCRIPTION
**Pull request by blakehatch**
# Description
Adds a page to list out all configuration options to aid in customization. Can be viewed by running `yarn start` in `/nativelink-docs` folder and going to the `Configuration` page.

Fixes #724 

## Type of change
- [x] This change requires a documentation update

## Checklist
- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725)

Preview Deployment: https://nativelink-docs-git-fork-blakehat-0da362-native-link-web-assets.vercel.app/Configuration

### CODE REVIEW

**Review by adam-singer — COMMENTED** [review]
Is it possible to preview this change deployed as a draft before landed?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725#-:-NsLBHRK-XaGo63hvUD6:b-m780ai)* status: 0 of 1 LGTMs obtained

**Comment by blakehatch** [comment]
> Is it possible to preview this change deployed as a draft before landed?
> 
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725#-:-NsLBHRK-XaGo63hvUD6:b-m780ai)_ status: 0 of 1 LGTMs obtained

https://nativelink-docs-git-fork-blakehat-0da362-native-link-web-assets.vercel.app/Configuration

Sorry I need to remember to link these in the PR for all major documentation changes.

**Review by MarcusSorealheis — COMMENTED** [review]
Thanks for the link.

In general, it's a big step in the right direction but it's not quite complete enough even for a merge. 

At a high level, all i see is a long list of configuration options but it's not clear where they belong in the configuration file. The configuration file is a beat itself and that's the reason for the breakdown.

Now, I would switch to approve if by approving this it means we can do more of the work as a fast follow. I would just be totally overwhelmed by a docs page that says copy this code and these are the options. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725#-:-NsL_yil5B8wxeYc7j6F:bydc86g)* status: 0 of 1 LGTMs obtained

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-docs/docs/Configuration.mdx` line 149 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/725#-NsLacJtCrmCEldEmclS:-NsLacJuDtUmAOTXFOyB:b-j2h4g8) ([raw file](https://github.com/TraceMachina/nativelink/blob/618d0ad427d1507af57d39939c5d09ff16d8e921/nativelink-docs/docs/Configuration.mdx#L149)):*
> ```MDX
>     }
>     ```
>     
> ```

lovely. I think it avoids quotes, back ticks, and string literals. 
___
*[`nativelink-docs/docs/Configuration.mdx` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/725#-NsLaq6S7eZQ4l7TpTSk:-NsLaq6S7eZQ4l7TpTSl:b9ncfb5) ([raw file](https://github.com/TraceMachina/nativelink/blob/618d0ad427d1507af57d39939c5d09ff16d8e921/nativelink-docs/docs/Configuration.mdx#L251)):*
> ```MDX
> 
>     ### 2. Paste default sample where needed in custom [deployment](https://github.com/blakehatch/nativelink/tree/main/deployment-examples).
>     ### 3. Change settings to preferred values.
> ```

it's not clear for sure that this is all for a store.

**Comment by blakehatch** [comment]
> Thanks for the link.
> 
> In general, it's a big step in the right direction but it's not quite complete enough even for a merge.
> 
> At a high level, all i see is a long list of configuration options but it's not clear where they belong in the configuration file. The configuration file is a beat itself and that's the reason for the breakdown.
> 
> Now, I would switch to approve if by approving this it means we can do more of the work as a fast follow. I would just be totally overwhelmed by a docs page that says copy this code and these are the options.
> 
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725#-:-NsL_yil5B8wxeYc7j6F:bydc86g)_ status: 0 of 1 LGTMs obtained

I agree there needs to be more context to the configuration options. I'll probably section them off with tabs and some examples to provide more context. Then we can make an additional PR improving this further once we have more user feedback.

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm: I said we merge this one and iterate.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725#-:-NsMD_CmAkHIExJj6Huj:b-k4mca8)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-docs/docs/Configuration.mdx` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/725#-NsLb2zl9OInpA_xuokj:-NsLb2zl9OInpA_xuokk:b-4sl2z5) ([raw file](https://github.com/TraceMachina/nativelink/blob/618d0ad427d1507af57d39939c5d09ff16d8e921/nativelink-docs/docs/Configuration.mdx#L251)):*
> ```MDX
> 
>     ### 2. Paste default sample where needed in custom [deployment](https://github.com/blakehatch/nativelink/tree/main/deployment-examples).
>     ### 3. Change settings to preferred values.
> ```

it's not clear for sure that this is all for setting up a CAS. It's clear in the sense that the example was here.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-docs/docs/Configuration.mdx` line 149 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/725#-NsLacJtCrmCEldEmclS:-NsME0VPBBTs7VzQmZpl:b-93v0pe) ([raw file](https://github.com/TraceMachina/nativelink/blob/618d0ad427d1507af57d39939c5d09ff16d8e921/nativelink-docs/docs/Configuration.mdx#L149)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

lovely. I think it avoids quotes, back ticks, and string literals.
</blockquote></details>

Yes this is really helpful since Vale hates our config and we shouldn't change it for that.
___
*[`nativelink-docs/docs/Configuration.mdx` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/725#-NsLaq6S7eZQ4l7TpTSk:-NsME5xh4qaaeC1P3Udp:b-83od3n) ([raw file](https://github.com/TraceMachina/nativelink/blob/618d0ad427d1507af57d39939c5d09ff16d8e921/nativelink-docs/docs/Configuration.mdx#L251)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

it's not clear for sure that this is all for a store.
</blockquote></details>

Noted
___
*[`nativelink-docs/docs/Configuration.mdx` line 251 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/725#-NsLb2zl9OInpA_xuokj:-NsME7C20xp371O6n5wf:bjr5i9o) ([raw file](https://github.com/TraceMachina/nativelink/blob/618d0ad427d1507af57d39939c5d09ff16d8e921/nativelink-docs/docs/Configuration.mdx#L251)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

it's not clear for sure that this is all for setting up a CAS. It's clear in the sense that the example was here.
</blockquote></details>

It's for setting up both configurations since some customers will not just need CAS, but cas is the default to show up for a reason.

**Review by blakehatch — COMMENTED** [review]
> Dismissed @MarcusSorealheis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725)* status: 1 of 1 LGTMs obtained

**Comment by MarcusSorealheis** [comment]
I think we should try to break the tabs out. The long list of configs is basically unintelligible because of information overload. It's like the importance of section headings in a textbook.

**Review by blakehatch — COMMENTED** [review]
Yes broke them out for this version so the info is more digestible. Will iterate on this though

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725#-:-NsMSZuAB560y6bJxh-P:bidsak2)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable

**Review by blakehatch — COMMENTED** [review]
> Dismissed @MarcusSorealheis from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/725)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable

**Pull request merged**
