### PR TITLE
Refactor Store API to use StoreKey

### LINKED ISSUE #934: Store API should support anything that can be converted into a `str`
Currently the store api requires all keys to be `DigestInfo`, but in reality it should accept something that turns into a `str`.

### PR DESCRIPTION
**Pull request by allada**
This enables us to use arbitrary strings when using the Store API.

closes #934

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/964)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

This is dependent on https://reviewable.io/reviews/TraceMachina/nativelink/935

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/964#-:-NzWMFCQ1N3xsiPrvcKL:bh9glaq)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Installation / ubuntu-22.04, Vercel, asan / ubuntu-22.04, integration-tests (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale (waiting on @adam-singer)

**Review by adam-singer — APPROVED** [review]
reviewed from `r1->r2`
:lgtm:

> Reviewed 37 of 37 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/964#-:-NzWeSv_C3cNkuBV8k6C:b-r4msb0)* status: 1 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, and 3 discussions need to be resolved

___
*[`nativelink-store/src/size_partitioning_store.rs` line 57 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/964#-NzWc-1DECyg8FhUql2B:-NzWc-1DECyg8FhUql2C:b-2eek1h) ([raw file](https://github.com/TraceMachina/nativelink/blob/f3554fe7613e03106e0b6dfb749c7d61ab9c5a8c/nativelink-store/src/size_partitioning_store.rs#L57)):*
> ```XML
>             keys.iter().map(|v| v.borrow()).partition(|k| {
>                 let StoreKey::Digest(digest) = k else {
>                     all_digests = false;
> ```

Should we capture what `k` is to be part of the error message below? 
___
*[`nativelink-store/src/size_partitioning_store.rs` line 105 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/964#-NzWcCO10rOiR-98V89r:-NzWcCO10rOiR-98V89s:b-ogredy) ([raw file](https://github.com/TraceMachina/nativelink/blob/f3554fe7613e03106e0b6dfb749c7d61ab9c5a8c/nativelink-store/src/size_partitioning_store.rs#L105)):*
> ```XML
>             _ => {
>                 return Err(make_input_err!(
>                     "SizePartitioningStore only supports Digest keys"
> ```

capture `key` for error message? Same question for method below.
___
*[`nativelink-util/src/evicting_map.rs` line 270 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/964#-NzWcnu-2HHl75vj_miz:-NzWcnu-2HHl75vj_mj-:bs0mhli) ([raw file](https://github.com/TraceMachina/nativelink/blob/f3554fe7613e03106e0b6dfb749c7d61ab9c5a8c/nativelink-util/src/evicting_map.rs#L270)):*
> ```XML
>     where
>         It: IntoIterator<Item = R>,
>         K: Borrow<Q>,
> ```

It would be really worth explaining the reasoning for `K` & `R` around this functions, might be in the call site, We should double down on explaining why or assumptions of why this works here.

**Review by allada — COMMENTED** [review]
> Reviewed 4 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/964)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-store/src/size_partitioning_store.rs` line 57 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/964#-NzWc-1DECyg8FhUql2B:-NzZ8LLa6_DduJYTSUD7:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f3554fe7613e03106e0b6dfb749c7d61ab9c5a8c/nativelink-store/src/size_partitioning_store.rs#L57)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Should we capture what `k` is to be part of the error message below?
</blockquote></details>

Done.
___
*[`nativelink-util/src/evicting_map.rs` line 270 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/964#-NzWcnu-2HHl75vj_miz:-NzZ7chn7ibLyJiNMkCc:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/f3554fe7613e03106e0b6dfb749c7d61ab9c5a8c/nativelink-util/src/evicting_map.rs#L270)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

It would be really worth explaining the reasoning for `K` & `R` around this functions, might be in the call site, We should double down on explaining why or assumptions of why this works here.
</blockquote></details>

Done.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/964#-:-NzZMfGt5Iu-U35ZEFFo:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
