### PR TITLE
Implement Serialize/Deserialize for ActionStage

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description
Implements Serialize/Deserialize for ActionStage to allow for storage
and retrieval from stores such as Redis.

towards: #1182

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)

### CODE REVIEW

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 769 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-O2RDl0QD7lXS0m3AW0M:-O2RDl0QD7lXS0m3AW0N:bp7fbbf) ([raw file](https://github.com/TraceMachina/nativelink/blob/a329715aa954970ad62838b423706531d4fd1862/nativelink-util/src/action_messages.rs#L769)):*
> ```XML
> }
> 
> impl Serialize for ActionStage {
> ```

I fought this for a few hours over the weekend and today, but while doing Serialize is fairly simple without a wrapper type is fairly simple,  I couldn't figure out how to do this for `Deserialize` without implementing more complex things like `Visitors`. If @jhpratt or @caass have more experience with this please let me know if there's a better way.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 825 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-O2RIdlo8y9AMKLIhEa8:-O2RaZuw0urlpTKq5IM7:bjrt846) ([raw file](https://github.com/TraceMachina/nativelink/blob/a329715aa954970ad62838b423706531d4fd1862/nativelink-util/src/action_messages.rs#L825)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

Unless I'm mistaken, there's a helper attribute from `serde` that lets you derive `Deserialize` by way of another type, essentially avoiding this manual impl.
</blockquote></details>

You're referring to `deserialize_with` right? I tried it out but enums make it a little more complicated unless I'm missing something

**Review by jhpratt — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-:-O2SujC72xAuUSowLW37:bnfp4nl)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 825 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-O2RIdlo8y9AMKLIhEa8:-O2SuVFFEOlvBSYeaXCN:b-5pz54g) ([raw file](https://github.com/TraceMachina/nativelink/blob/a329715aa954970ad62838b423706531d4fd1862/nativelink-util/src/action_messages.rs#L825)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

You're referring to `deserialize_with` right? I tried it out but enums make it a little more complicated unless I'm missing something
</blockquote></details>

Yes, that's the attribute. If it's simpler to do it this way, then by all means do that. It's not as if it's significant overhead.

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 769 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-O2RDl0QD7lXS0m3AW0M:-O2TAti70aUZHT3JteKx:bjhpp94) ([raw file](https://github.com/TraceMachina/nativelink/blob/a329715aa954970ad62838b423706531d4fd1862/nativelink-util/src/action_messages.rs#L769)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

I have implemented deserializers with visitors. My recommendation is to avoid it if reasonably possible — it's not fun and is extremely error prone.
</blockquote></details>

Is this to work around `CompletedFromCache(ProtoActionResult)` ?  I thought there was some patch that allowed for the protobuf generator to sprinkle `Serialize` / `Deserialize` on those protos to make them compatible with serialization traits

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 769 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-O2RDl0QD7lXS0m3AW0M:-O2TC6ep7MCiVDiFJe2G:b8lubcu) ([raw file](https://github.com/TraceMachina/nativelink/blob/a329715aa954970ad62838b423706531d4fd1862/nativelink-util/src/action_messages.rs#L769)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Is this to work around `CompletedFromCache(ProtoActionResult)` ?  I thought there was some patch that allowed for the protobuf generator to sprinkle `Serialize` / `Deserialize` on those protos to make them compatible with serialization traits
</blockquote></details>

Unfortunately while we can put those derive flags on all the structs we generate, they are missing on the underlying Prost types. There’s definitely a way to get it working, but it’s likely a larger undertaking than it seems at first glance.

I do think there’s a way to do this without cloning so that’s not to say this PR can’t be improved

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-:-O2b5YMf1I85G3JAowN6:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Installation / ubuntu-22.04, Remote / large-ubuntu-22.04, and 2 discussions need to be resolved

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)* status: 2 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 769 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1186#-O2RDl0QD7lXS0m3AW0M:-O2b6otA4gsecsDSaFYx:bewmci4) ([raw file](https://github.com/TraceMachina/nativelink/blob/a329715aa954970ad62838b423706531d4fd1862/nativelink-util/src/action_messages.rs#L769)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Unfortunately while we can put those derive flags on all the structs we generate, they are missing on the underlying Prost types. There’s definitely a way to get it working, but it’s likely a larger undertaking than it seems at first glance.

I do think there’s a way to do this without cloning so that’s not to say this PR can’t be improved
</blockquote></details>

Improved this a lot and think everyone is happy with where it's at.

**Review by jhpratt — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1186)* status: 2 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

**Pull request merged**
