### PR TITLE
Enable Bazel on darwin

### PR DESCRIPTION
**Pull request by SchahinRohani**
# Description

With this PR `bazel test ...` passes on darwin.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1364)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Fantastic PR!

We should also add macos runners here as well to ensure that it doesn't regress.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-:-O7fAoAO6szhEk6u5st4:b-2uh674)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, Web Platform Deployment / ubuntu-24.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), and 7 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f80Ty2ALhpxSIe5ZT):*




_Suggestion:_
```
B
```
___
*[`flake.nix` line 75 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f8Isx68NCsURDmtEh:-O7f8Isx68NCsURDmtEi:b4c9val) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/flake.nix#L75)):*
> ```Nix
>           pkgs.darwin.apple_sdk.frameworks.Security
>           pkgs.libiconv
>           pkgs.darwin.apple_sdk.frameworks.CoreFoundation
> ```

nit: sort alphabetically



_Suggestion:_
```Nix
          pkgs.darwin.apple_sdk.frameworks.CoreFoundation
          pkgs.darwin.apple_sdk.frameworks.Security
          pkgs.libiconv
```
___
*[`flake.nix` line 425 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f8WRQAWmC9f9xbc4w:-O7f8WRQAWmC9f9xbc4x:b-6kfgwj) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/flake.nix#L425)):*
> ```Nix
>           prefix = "lre";
>         };
> ```

nit: remove inconsistent newline
___
*[`flake.nix` line 493 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f8cVS1MCJ3sHKW97I:-O7f8cVS1MCJ3sHKW97J:b6k9pz4) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/flake.nix#L493)):*
> ```Nix
>             if [[ "$(uname)" == "Darwin" ]]; then
>               ${config.darwin.installationScript}
>             fi
> ```

Instead of adding this here, add it in a similar way to how we add the darwin-only deps in the packages, i.e. something like this:

```nix
++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
  # If on darwin, then generate darwin.bazelrc which configures
  # darwin libs & frameworks when running in the nix environment.
  ${config.darwin.installationScript}
];
```

This way the entire installation script will only be built if we're actually on darwin. With the current implementation we'd still have to generate the installationScript even on linux, where things might behave in unexpected ways.
___
*[`local-remote-execution/examples/BUILD.bazel` line 7 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f9qBSB0v3zywDi8Av:-O7f9qBSB0v3zywDi8Aw:b203eg7) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/local-remote-execution/examples/BUILD.bazel#L7)):*
> ```Starlark
>     srcs = ["hello.cpp"],
>     copts = ["--verbose"],
>     target_compatible_with = [
> ```

Let's leave a comment here to explain that this is only supposed to test LRE and that this matches the config in the lre platform.
___
*[`tools/darwin/modules/darwin.nix` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7fAH9B8C3tIxTE8xL6:-O7fAH9B8C3tIxTE8xL7:b-akdkrl) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/tools/darwin/modules/darwin.nix#L18)):*
> ```Nix
>         # These are the libs and frameworks used by darwin.
> 
>         build --@rules_rust//:extra_rustc_flags=-L${pkgs.libiconv}/lib,-Lframework=${pkgs.darwin.apple_sdk.frameworks.Security}/Library/Frameworks,-Lframework=${pkgs.darwin.apple_sdk.frameworks.CoreFoundation}/Library/Frameworks
> ```

What is the reasoning behind using the apple_std instead of e.g. darwin.CF and darwin.Security?
___
*[`tools/darwin/modules/darwin.nix` line 19 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7fAaW3B4IVGFIsM7nX:-O7fAaW3B4IVGFIsM7nY:btk9qmv) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/tools/darwin/modules/darwin.nix#L19)):*
> ```Nix
> 
>         build --@rules_rust//:extra_rustc_flags=-L${pkgs.libiconv}/lib,-Lframework=${pkgs.darwin.apple_sdk.frameworks.Security}/Library/Frameworks,-Lframework=${pkgs.darwin.apple_sdk.frameworks.CoreFoundation}/Library/Frameworks
>         build --@rules_rust//:extra_exec_rustc_flags=-L${pkgs.libiconv}/lib,-Lframework=${pkgs.darwin.apple_sdk.frameworks.Security}/Library/Frameworks,-Lframework=${pkgs.darwin.apple_sdk.frameworks.CoreFoundation}/Library/Frameworks
> ```

Do we need all of these search paths in both the extra_exec and regular rustc flags? Maybe we can reduce these two lines in some places.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1364)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-14, Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, and 3 discussions need to be resolved

___
*[`local-remote-execution/examples/BUILD.bazel` line 3 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7jo04-Bh9JyRbst4sP:-O7jo04-Bh9JyRbst4sQ:undefined) ([raw file](https://github.com/TraceMachina/nativelink/blob/401f0138801ee2f1501e8e44fe43966d520f41ec/local-remote-execution/examples/BUILD.bazel#L3)):*
> ```Starlark
> load("@rules_cc//cc:defs.bzl", "cc_binary")
> 
> # This example matches the config of the lre config
> ```





_Suggestion:_
```Starlark
platform
```

**Review by SchahinRohani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1364)* status: 0 of 1 LGTMs obtained, and 7 of 8 files reviewed, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, Remote / large-ubuntu-22.04, and 3 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f80Ty2ALhpxSIe5ZT):*
Done.
___
*[`flake.nix` line 493 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7f8cVS1MCJ3sHKW97I:-O7fwucA0xHdWkaWXnCj:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/flake.nix#L493)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Instead of adding this here, add it in a similar way to how we add the darwin-only deps in the packages, i.e. something like this:

```nix
++ pkgs.lib.optionals pkgs.stdenv.isDarwin [
  # If on darwin, then generate darwin.bazelrc which configures
  # darwin libs & frameworks when running in the nix environment.
  ${config.darwin.installationScript}
];
```

This way the entire installation script will only be built if we're actually on darwin. With the current implementation we'd still have to generate the installationScript even on linux, where things might behave in unexpected ways.
</blockquote></details>

Done.
___
*[`local-remote-execution/examples/BUILD.bazel` line 3 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7jo04-Bh9JyRbst4sP:-O7k3GEM9sCc6cLkk4sU:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/401f0138801ee2f1501e8e44fe43966d520f41ec/local-remote-execution/examples/BUILD.bazel#L3)):*
> ```Starlark
> load("@rules_cc//cc:defs.bzl", "cc_binary")
> 
> # This example matches the config of the lre config
> ```

Done.
___
*[`tools/darwin/modules/darwin.nix` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7fAH9B8C3tIxTE8xL6:-O7k3J1E4NDgy7RFvn1N:buj2z1p) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/tools/darwin/modules/darwin.nix#L18)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

What is the reasoning behind using the apple_std instead of e.g. darwin.CF and darwin.Security?
</blockquote></details>

I prefer the packages from here: https://search.nixos.org/packages?channel=unstable. 
Thats why we are using darwin.CF and darwin.Security in the darwin flake module.
___
*[`tools/darwin/modules/darwin.nix` line 19 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-O7fAaW3B4IVGFIsM7nX:-O7fwyokDJpICsJPIeAV:b2nign6) ([raw file](https://github.com/TraceMachina/nativelink/blob/3a085cf43f87ac05a833dd7674a5f8f25af3d45e/tools/darwin/modules/darwin.nix#L19)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Do we need all of these search paths in both the extra_exec and regular rustc flags? Maybe we can reduce these two lines in some places.
</blockquote></details>

yes

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1364#-:-O7kDauIDyx-aCTAaSzK:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
