### PR TITLE
Rewrite contribution documentation

### PR DESCRIPTION
**Pull request by aaronmondal**
This should help new contributors to get started more easily. The new guidelines are more explicit than the previous ones and go into more detail on common development workflows.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@nfarah86 +@blakehatch +@MarcusSorealheis 

See https://github.com/aaronmondal/nativelink/blob/rewrite-contribution-docs/CONTRIBUTING.md for a human-readable version.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827#-:-NuZmpOF3PqklwheAGXr:blzge7e)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @blakehatch, @MarcusSorealheis, and @nfarah86)

**Review by MarcusSorealheis — COMMENTED** [review]
Directionally, this seems fine. The only gripe I have is that you have power shell specific instructions but not distinguish when instructions are for unix based systems. That is something you need to do because you call out windows power shell. There are only a few areas. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827#-:-NudihiOEwWlpWQxIAEN:bs7ak4u)* status: 0 of 3 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04) (waiting on @blakehatch and @nfarah86)

**Review by blakehatch — CHANGES_REQUESTED** [review]
I like these changes, especially how detail things like the rebase instructions are. Mostly formatting and some minor clarity changes I believe are needed.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827#-:-NueA94jEZraYM316jpx:b9op7qz)* status: 0 of 3 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), and 6 discussions need to be resolved (waiting on @MarcusSorealheis and @nfarah86)

___
*[`CONTRIBUTING.md` line 38 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue8zvo-wCx_7LB_R8R:-Nue8zvo-wCx_7LB_R8S:b101uj4) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L38)):*
> ```Markdown
>    ```
> 
>    > [!WARNING]
> ```

Not formatting correctly in human readible form. I believe the carrot has to be indented all the way to the left.
___
*[`CONTRIBUTING.md` line 57 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9fFj2mSH9O66tOcm:-Nue9fFj2mSH9O66tOcn:btxbve3) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L57)):*
> ```Markdown
>    ```
> 
>    > [!TIP]
> ```

Ditto on formatting
___
*[`CONTRIBUTING.md` line 110 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9hGgEmUzkSbi3F8x:-Nue9hGgEmUzkSbi3F8y:btxbve3) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L110)):*
> ```Markdown
>    ```
> 
>    > [!NOTE]
> ```

Ditto on formatting
___
*[`CONTRIBUTING.md` line 115 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9iN7CuoGy1xNHmcb:-Nue9iN7CuoGy1xNHmcc:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L115)):*
> ```Markdown
>    > branches or make changes to the nix files.
> 
>    > [!TIP]
> ```

Ditto
___
*[`CONTRIBUTING.md` line 148 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9j_h-c6Gso2A6Zbz:-Nue9j_h-c6Gso2A6Zc-:b-89a4l7) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L148)):*
> ```Markdown
>    ```
> 
>    > [!TIP]
> ```

Ditto
___
*[`CONTRIBUTING.md` line 288 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9u6CEnUxhuLJ8rY1:-Nue9u6CEnUxhuLJ8rY2:b-irvf6s) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L288)):*
> ```Markdown
> ### Running pre-commit hooks
> 
> Assuming you're in the nix development environment:
> ```

Explain actually how to get into a nix development environment and know whether you're in it. Something like:

Getting in: `nix develop`

Checking if you're in `env`

**Comment by MarcusSorealheis** [comment]
> Assuming you're in the nix development environment:

As a general rule, we should try to assume nothing in our instructions.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827#-:-NufQILyCnSjoefzVIwT:bnfp4nl)* status: 0 of 3 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), and 6 discussions need to be resolved (waiting on @blakehatch, @MarcusSorealheis, and @nfarah86)

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 6 discussions need to be resolved (waiting on @blakehatch, @MarcusSorealheis, and @nfarah86)

___
*[`CONTRIBUTING.md` line 38 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue8zvo-wCx_7LB_R8R:-NvgoFIq9Q5Ur1TNoFlD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L38)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Not formatting correctly in human readible form. I believe the carrot has to be indented all the way to the left.
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 57 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9fFj2mSH9O66tOcm:-NvgoFtpAnPgwcoma9Fq:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L57)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Ditto on formatting
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 110 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9hGgEmUzkSbi3F8x:-NvgoGIdD19ZFLTOozzn:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L110)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Ditto on formatting
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 115 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9iN7CuoGy1xNHmcb:-NvgoGf47PlbzucadOFC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L115)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 148 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9j_h-c6Gso2A6Zbz:-NvgoH9yCITqDtvBq0zY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L148)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 288 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/827#-Nue9u6CEnUxhuLJ8rY1:-NvgoK1I0VmKUQGKEASc:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b252c0dc857330ddb2fbe1e85cb5488621ccb6e/CONTRIBUTING.md#L288)):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Explain actually how to get into a nix development environment and now how you're in it. Something like:

Getting in: `nix develop`

Checking if you're in `env`
</blockquote></details>

Done.

**Review by blakehatch — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827#-:-Nw5gfxf306qVlgg5PlC:bg7igkv)* status: 1 of 3 LGTMs obtained (waiting on @MarcusSorealheis and @nfarah86)

**Review by aaronmondal — COMMENTED** [review]
-@MarcusSorealheis -@nfarah86 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/827#-:-Nw5m6LLAi3qCdGZUCfE:bujkq6z)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
