### PR TITLE
Errors are now properly handled in subscription

### PR DESCRIPTION
**Pull request by allada**
We no longer drop errors in subscription handling.

Also cleanup some small todo!'s.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 
+@zbirenbaum  

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-:-O1SJR8G8RfFsmxYpLv4:b60nmr4)* status: 0 of 2 LGTMs obtained, and pending CI: vale (waiting on @adam-singer and @zbirenbaum)

**Review by adam-singer — COMMENTED** [review]
> Reviewed 19 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135)* status: 0 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-util/src/action_messages.rs` line 44 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1SltUJ12Vr2Et2Hjh9:-O1SltUK6CvxPUe8txIv:bxelit3) ([raw file](https://github.com/TraceMachina/nativelink/blob/db0ecc28a8db2dc424c5ef426436f7af82b0d59a/nativelink-util/src/action_messages.rs#L44)):*
> ```XML
> 
> /// Exit code sent if there is an internal error.
> pub const INTERNAL_ERROR_EXIT_CODE: i32 = -178;
> ```

Could we resuse existing encodings form https://doc.rust-lang.org/std/process/struct.ExitCode.html#

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135)* status: 0 of 2 LGTMs obtained, and pending CI: vale (waiting on @adam-singer and @zbirenbaum)

___
*[`nativelink-util/src/action_messages.rs` line 44 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1SltUJ12Vr2Et2Hjh9:-O1T6lbiCBjjUZiUPpll:b-7jw8v7) ([raw file](https://github.com/TraceMachina/nativelink/blob/db0ecc28a8db2dc424c5ef426436f7af82b0d59a/nativelink-util/src/action_messages.rs#L44)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Could we resuse existing encodings form https://doc.rust-lang.org/std/process/struct.ExitCode.html#
</blockquote></details>

Maybe, but this code is only to ensure we have a mostly-uniqueish code if the proto forgot to set it.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135)* status: 0 of 2 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 305 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1TEw9gC-xrEUGWEmtC:-O1TEw9gC-xrEUGWEmtD:b-eslrit) ([raw file](https://github.com/TraceMachina/nativelink/blob/d0fd233e9b1070173734415b67d2560f8d857ce8/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L305)):*
> ```XML
>             Err(err) => return Err(err),
>             Ok(Some(subscription)) => return Ok(subscription),
>             Ok(None) => { /* Add item to queue. */ }
> ```

nit: Can we put a flag here to mark this as todo?
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 351 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1TDmsy9GsrfFCJURVv:-O1TDmsy9GsrfFCJURVw:b5eq2w0) ([raw file](https://github.com/TraceMachina/nativelink/blob/d0fd233e9b1070173734415b67d2560f8d857ce8/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L351)):*
> ```XML
>         let unique_key = match unique_qualifier {
>             ActionUniqueQualifier::Cachable(unique_key) => unique_key,
>             ActionUniqueQualifier::Uncachable(_unique_key) => return Ok(None),
> ```

nit: Can we either do something with this `_unique_key` or just set it to `_` to follow convention?
___
*[`nativelink-scheduler/tests/simple_scheduler_test.rs` line 1581 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1TE0sJ-wNv0E9_1iaW:-O1TE0sJ-wNv0E9_1iaX:bbz2geq) ([raw file](https://github.com/TraceMachina/nativelink/blob/d0fd233e9b1070173734415b67d2560f8d857ce8/nativelink-scheduler/tests/simple_scheduler_test.rs#L1581)):*
> ```XML
>         };
>         let mut received_state = action_state.as_ref().clone();
>         if let ActionStage::Completed(stage) = &mut received_state.stage {
> ```

nit: I'm really hesitant to add more tests which do any sort of raw string comparison with error messages. I remember similar tests causing a lot of confusion previously during the refactor. Could we just assert that some error is thrown, or better yet, create an error code corresponding to it like `MAX_ATTEMPTS_EXCEEDED`?

Then we could just implement display for it and have that enum value be this string.

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-:-O1TF8pE-o4ox-i32gvV:bnfp4nl)* status: 1 of 2 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r5, 34 of 34 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-:-O1TFdtb1xYF0zrq0Fau:bnfp4nl)* status: 2 of 2 LGTMs obtained, and 3 discussions need to be resolved

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1135)* status: 2 of 2 LGTMs obtained, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 305 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1TEw9gC-xrEUGWEmtC:-O1TOPew9ihg1QmtqKY0:bpl26p3) ([raw file](https://github.com/TraceMachina/nativelink/blob/d0fd233e9b1070173734415b67d2560f8d857ce8/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L305)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

nit: Can we put a flag here to mark this as todo?
</blockquote></details>

This is not a todo, this is simply saying `continue we are adding to the queue`.
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 351 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1TDmsy9GsrfFCJURVv:-O1TOarH7ubJVNiqgczX:b9vkbkz) ([raw file](https://github.com/TraceMachina/nativelink/blob/d0fd233e9b1070173734415b67d2560f8d857ce8/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L351)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

nit: Can we either do something with this `_unique_key` or just set it to `_` to follow convention?
</blockquote></details>

`_unique_key` is just saying what the value is. Sure i can make it underscore, but it's the same thing but unnamed.
___
*[`nativelink-scheduler/tests/simple_scheduler_test.rs` line 1581 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/1135#-O1TE0sJ-wNv0E9_1iaW:-O1TOqMm8OWPSv86wsmf:b-lnl6ek) ([raw file](https://github.com/TraceMachina/nativelink/blob/d0fd233e9b1070173734415b67d2560f8d857ce8/nativelink-scheduler/tests/simple_scheduler_test.rs#L1581)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

nit: I'm really hesitant to add more tests which do any sort of raw string comparison with error messages. I remember similar tests causing a lot of confusion previously during the refactor. Could we just assert that some error is thrown, or better yet, create an error code corresponding to it like `MAX_ATTEMPTS_EXCEEDED`?

Then we could just implement display for it and have that enum value be this string.
</blockquote></details>

I didn't add a test, this is making the test pass. We want to make sure it fails because of max attempts, and the only way to do that is via the error message. Before this was not an issue because we had it a hard codded message, but now it's a dynamic message, so it required the test to have more conditions to unwrap it.

**Pull request merged**
