### PR TITLE
backport v0.1 changes

### PR DESCRIPTION
**Pull request by zbirenbaum**
# Description
Includes the following changes from v0.1 PR:
- Minor refactor of functionally same code
- Refactor fs.rs to use call_with_permit scheme
- Add timeout function for filesystem_store::FilesystemStore rename call
- Add safe request timeout for running actions manager 
- Add root directory for action

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/733)

### CODE REVIEW

**Comment by zbirenbaum** [comment]
I'll turn these points into separate commits with their individual messages before merging if that would help to keep things clean, but I wanted to get this uploaded since there's a lot here and one of the tests is failing

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/733)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-store/src/filesystem_store.rs` line 580 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/733#-NsV3eC42uU2hpfxfm45:-NsV3eC52cORDtqIneLu:b-ibnc9y) ([raw file](https://github.com/TraceMachina/nativelink/blob/e21da6c9230979447c55545e22a14e0b47cd15e0/nativelink-store/src/filesystem_store.rs#L580)):*
> ```XML
>             data_size += data_len as u64;
>         }
>         if data_size == 0 && !is_zero_digest(&final_digest) {
> ```

This is the check that causes the test to fail. Since it was newly introduced in v0.1 and the tests were never updated on that branch,  I'm not sure whether this is intended and the digest in the test is incorrect, or if it is necessary to add an exception here for empty directories @allada

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/733)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1052 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/733#-NsV7Zvo2_nIUpDpzqC3:-NsV7ZvpA6Kg8kLzjnv6:b-li1mgt) ([raw file](https://github.com/TraceMachina/nativelink/blob/af8f6e44949ab68238e9381358521b36d61d2151/nativelink-store/tests/filesystem_store_test.rs#L1052)):*
> ```XML
>                     eviction_policy: None,
>                     ..Default::default()
>                 },
> ```

This test is failing now that it is updated to the version in v0.1, but it was passing when I ran the previous version of this test against the rest of the v0.1 changes. Not sure if this means it's a test issue or a code issue.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/733)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-store/tests/filesystem_store_test.rs` line 1052 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/733#-NsV7Zvo2_nIUpDpzqC3:-NsV8qbT9smRHOS6LVCq:b-2v5l3) ([raw file](https://github.com/TraceMachina/nativelink/blob/af8f6e44949ab68238e9381358521b36d61d2151/nativelink-store/tests/filesystem_store_test.rs#L1052)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

This test is failing now that it is updated to the version in v0.1, but it was passing when I ran the previous version of this test against the rest of the v0.1 changes. Not sure if this means it's a test issue or a code issue.
</blockquote></details>

The test this causes to fail is `running_actions_manager_tests::download_to_directory_folder_download_test`, there's another test that is failing after I added the version of it from the v0.1 branch, but it's likely unrelated

**Review by aaronmondal — COMMENTED** [review]
It seems like there are a bunch of different changes happening at once here. Could you split this up into e.g. separate PRs for the fuctional changes and a PR for the non-functional ones?

Note that the bazel build runs clippy by default as part of `bazel test ...`. Unfortunately we don't have similar automation for the Cargo build but the Nix flake installs cargo with the same clippy that is used in CI.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/733#-:-NsV_2CJAc-Frv9ITAGg:b-y3ysa2)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

**Review by zbirenbaum — COMMENTED** [review]
Sure, I'll close this and turn it into a few PRs. I think that would make it easier to debug the test issues

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/733#-:-NsWAN-p2r8l7z9SmOYp:b-snwxdp)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

**Pull request closed without merging**
