### PR TITLE
Update Go dependencies

### PR DESCRIPTION
**Pull request by aaronmondal**
Includes a few fixes to deprecated symbols.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1095)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@MarcusSorealheis +@allada +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1095#-:-O1E3Ntr6NbeSHYMZfB7:b3nvy9z)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer, @allada, and @MarcusSorealheis)

**Review by blakehatch — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1095#-:-O1ImfhH6qVZqKXfkgpo:bg7igkv)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer, @allada, and @MarcusSorealheis)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1095#-:-O1In_N73viJasfjTdOd:bnfp4nl)* status: 1 of 3 LGTMs obtained (waiting on @allada and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
-@allada -@MarcusSorealheis 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1095#-:-O1IslLDAISE1eAuiTjm:b2dy29q)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
