### PR TITLE
Update `docs` generation

### PR DESCRIPTION
**Pull request by SchahinRohani**
# Description

Update the docs generation by enhancing the md-to-mdx lib. Also add a polished version of the README.md

Preview [Docs Link](https://nativelink-docs-0c7ggmkz1wfy.deno.dev)

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
I like the direction where this is going, but there are too many things happening at once here. Let's break this up into two parts:

- Your proposed refactor (which tbh seems somewhat unnecessary)
- The extension to the functionality, i.e. the tailwind logic.

I'd like to suggest to only focus on the functionality extension as the refactor doesn't seem necessary and adds review time/friction.

> Reviewed 12 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-:-O66KBUf34dj6P4ilOAr:bmpcn62)* status: 0 of 2 LGTMs obtained, and 12 of 17 files reviewed, and 3 discussions need to be resolved

___
*[`docs/astro.config.ts` line 13 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66HqIH6HDpR9zMwaJj:-O66HqII0KiJr3pZ-6A-:b3gg7yo) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/astro.config.ts#L13)):*
> ```XML
> import { rehypeMermaid } from "@beoe/rehype-mermaid"; // "rehype-mermaid";
> import rehypeAutolinkHeadings from "rehype-autolink-headings";
> // import { default as playformCompress } from "@playform/compress";
> ```

If this is not needed let'r remove this line entirely.
___
*[`docs/package.json` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66I33OA8Pe8TG2ZFto:-O66I33P8EJZXSOHAZ4L:b-bjkti9) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/package.json#L10)):*
> ```JSON
>     "biome": "biome",
>     "docs": "bun run docs.build && bun run docs.generate",
>     "docs.build": "cd .. && unset TMPDIR TMP; bazelisk build nativelink-config:docs_json && cd docs && bun run src/utils/docs.build.ts",
> ```

Let's try to find more intuitive/descriptive names for this.
___
*[`docs/src/utils/docs.build.ts` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66IiXrDFrCgPVoI7sv:-O66IiXsD8E2NlJ9dvgf:bqn0rem) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/src/utils/docs.build.ts#L1)):*
> ```XML
> import { generateDocs } from "./metaphase_aot";
> ```

Splitting this out seems unnecessary. I'm fine with renaming, but let's keep the logic in a single file.

**Review by SchahinRohani — COMMENTED** [review]
Reverted the refactor completely as per your feedback. That said, I found it more productive to separate the raw file processing from the AST transformations, but I can definitely work within a more minimal file structure if that’s the preferred approach. "Unnecessary" is always in the eye of the beholder, right? 😄 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-:-O6BR7Ox9bC8pD99B4HH:b-e6edw7)* status: 0 of 2 LGTMs obtained, and 8 of 19 files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Docs Deployment / macos-14, Docs Deployment / ubuntu-24.04, Installation / macos-13, Installation / macos-14, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved

___
*[`docs/astro.config.ts` line 13 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66HqIH6HDpR9zMwaJj:-O6BQQu7AeWLoP_n5RN6:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/astro.config.ts#L13)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

If this is not needed let'r remove this line entirely.
</blockquote></details>

Done.
___
*[`docs/package.json` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66I33OA8Pe8TG2ZFto:-O6BQJvuAK81_aZCd3fE:bndbr2h) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/package.json#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's try to find more intuitive/descriptive names for this.
</blockquote></details>

How about `bun run generate.docs` and `bun run build.docs`?
___
*[`docs/src/utils/docs.build.ts` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66IiXrDFrCgPVoI7sv:-O6BQoxqEXlHnZu4_O9V:bgyq40q) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/src/utils/docs.build.ts#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Splitting this out seems unnecessary. I'm fine with renaming, but let's keep the logic in a single file.
</blockquote></details>

Reverted back to "metaphase_aot.ts".

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Cool, this is a much nicer diff! Just some more adjustments to reduce diff size, then we should be fine. Also, links in the preview seem to have lost their underlines, which is an accessibility issue. Let's bring those underlines back.

> Reviewed 11 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-:-O6CH2P86SwFwSlUuhZ5:b3ou2wz)* status: 0 of 2 LGTMs obtained, and all files reviewed, and 10 discussions need to be resolved

___
*[`docs/package.json` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O66I33OA8Pe8TG2ZFto:-O6CBhpr7HZ-EHHNlWel:b-je097) ([raw file](https://github.com/TraceMachina/nativelink/blob/a3d284f4f66401fa37e530ff6e8571c660686f1e/docs/package.json#L10)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

How about `bun run generate.docs` and `bun run build.docs`?
</blockquote></details>

Hmm maybe something like `docs.generate-config` and `docs.generate-mdx`? In any case, I think it's fine if we change this later.
___
*[`docs/src/utils/md_to_mdx.ts` line 7 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CE6a48j7q2kqlKB-T:-O6CE6a48j7q2kqlKB-U:b1kjrys) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L7)):*
> ```XML
> import remarkStringify from "remark-stringify";
> 
> export function generateFrontMatter(
> ```

Let's move this back to it's old place to reduce the diff size.
___
*[`docs/src/utils/md_to_mdx.ts` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CEMa_2VLLr1Hd1CMd:-O6CEMa_2VLLr1Hd1CMe:bkjfyog) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L27)):*
> ```XML
> };
> 
> export async function transformMarkdownToMdx(
> ```

Move this back to it's old place to reduce diff size
___
*[`docs/src/utils/md_to_mdx.ts` line 44 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CERzi017Y_XGUAfHD:-O6CERzi017Y_XGUAfHE:b-ryumhi) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L44)):*
> ```XML
>     : [...content];
> 
>   // // Apply transformations for target IDs
> ```

nit: double comment
___
*[`docs/src/utils/md_to_mdx.ts` line 89 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CF10g4EoPPcVktR45:-O6CF10g4EoPPcVktR46:bkjfyog) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L89)):*
> ```XML
> }
> 
> function removeValeAndGitCliffComments(markdown: string): string {
> ```

Move this back to it's old place to reduce diff size
___
*[`docs/src/utils/md_to_mdx.ts` line 95 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CF6iPAoRJBXohKhNi:-O6CF6iPAoRJBXohKhNj:bkjfyog) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L95)):*
> ```XML
> }
> 
> export function parseMarkdown(markdown: string): Root {
> ```

Move this back to it's old place to reduce diff size
___
*[`docs/src/utils/md_to_mdx.ts` line 99 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CFC-a-biAQiaetPDF:-O6CFC-b4ib4zfo-a_hG:bkjfyog) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L99)):*
> ```XML
> }
> 
> function processLines(lines: string[]) {
> ```

Move this back to it's old place to reduce diff size
___
*[`docs/src/utils/md_to_mdx.ts` line 183 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CGE3h6b89ZLKZFErW:-O6CGE3i1cwR2CEu2pKV:bkjfyog) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L183)):*
> ```XML
> }
> 
> function isCodeBlock(line: string): boolean {
> ```

Move this back to it's old place to reduce diff size
___
*[`docs/src/utils/md_to_mdx.ts` line 204 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CFVTX79ssvw5rd0ac:-O6CFVTX79ssvw5rd0ad:b-k6pgsj) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L204)):*
> ```XML
> 
> // AST
> import type {
> ```

put imports to the top of the file
___
*[`docs/src/utils/md_to_mdx.ts` line 217 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CCEN58maLrNU16oF8:-O6CCEN58maLrNU16oF9:b-z74zvn) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L217)):*
> ```XML
> import { visit } from "unist-util-visit";
> 
> // import { findNodesById, logFirstNNodes } from "./debug";
> ```

nit: remove comment
___
*[`docs/src/utils/md_to_mdx.ts` line 467 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CDlwYEgLvYs43-jjg:-O6CDlwYEgLvYs43-jjh:bz718kf) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L467)):*
> ```XML
>       // Remove the entire <picture> tag and replace it with the two  tags
>       .replace(
>         /<picture>[\s\S]*?<source\s+media="[^"]*dark[^"]*"\s+srcset="[^"]*"[^>]*>\s*<source\s+media="[^"]*light[^"]*"\s+srcset="[^"]*"[^>]*>\s*]*src="[^"]*"[^>]*>\s*<\/picture>/g,
> ```

Since we're only looking for the picture tag, can't we simplify this regex to only look for the start and end picture tags?

**Review by SchahinRohani — COMMENTED** [review]
Underlines are back, applied it with tailwind.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-:-O6CIVam2JOIk96zpqh7:b6wmtub)* status: 0 of 2 LGTMs obtained, and 17 of 19 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Docs Deployment / macos-14, Docs Deployment / ubuntu-24.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 8 discussions need to be resolved

___
*[`docs/src/utils/md_to_mdx.ts` line 7 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CE6a48j7q2kqlKB-T:-O6CPdq26Oru1-Bn5ztx:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L7)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's move this back to it's old place to reduce the diff size.
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CEMa_2VLLr1Hd1CMd:-O6CPcvl-5OfzhpF1WlR:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L27)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Move this back to it's old place to reduce diff size
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 89 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CF10g4EoPPcVktR45:-O6CPVJQ8oYHeKNHPasm:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L89)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Move this back to it's old place to reduce diff size
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 95 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CF6iPAoRJBXohKhNi:-O6CPWf84bKMhjHZQop9:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L95)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Move this back to it's old place to reduce diff size
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 99 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CFC-a-biAQiaetPDF:-O6CPXDU8LeditWTDWt0:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L99)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Move this back to it's old place to reduce diff size
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 183 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CGE3h6b89ZLKZFErW:-O6CPZx84c09ifCexOr4:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L183)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Move this back to it's old place to reduce diff size
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 204 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CFVTX79ssvw5rd0ac:-O6CP_tq6rmU09imDHIB:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L204)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

put imports to the top of the file
</blockquote></details>

Done.
___
*[`docs/src/utils/md_to_mdx.ts` line 467 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6CDlwYEgLvYs43-jjg:-O6CIyyK4CuRwNzObfQZ:bws22dh) ([raw file](https://github.com/TraceMachina/nativelink/blob/566f5670b46974448e12f6b3132038d8ae744ff8/docs/src/utils/md_to_mdx.ts#L467)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Since we're only looking for the picture tag, can't we simplify this regex to only look for the start and end picture tags?
</blockquote></details>

For the Logo we are looking for an explicit html picture node in the ast , it could break different picture nodes if the regex match them.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

Has perfect lighthouse scores on desktop now. Nice work!

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-:-O6CnOp12ejBBiLkY5ed:b-wwzr1)* status: 1 of 2 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Docs Deployment / macos-14, Installation / macos-13, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`docs/src/styles/tailwind.css` line 7 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-O6Cn0nOEtP_c1Y2xDE0:-O6Cn0nOEtP_c1Y2xDE1:byt10a8) ([raw file](https://github.com/TraceMachina/nativelink/blob/fa1fbbce078746f449bdbc7183c54f283ea5ef4e/docs/src/styles/tailwind.css#L7)):*
> ```CSS
> }
> 
> a.astro-3ii7xxms,
> ```

nit: This looks like it's some generated component tag. Will the hashes persist? If this is the only way to get the links, let's leave a comment explaining how these hashes came to be and what to look out for if/when they change.

**Review by blakehatch — APPROVED** [review]
Very ncie QOL changes and also got the same lighthouse scores as Aaron! :lgtm: 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280#-:-O6MY1d3EWC6Ku1PjLKm:b-gw1jqv)* status: 2 of 2 LGTMs obtained, and all files reviewed, and 1 discussions need to be resolved

**Review by aaronmondal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1280)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained, and all files reviewed

**Pull request merged**
