### PR TITLE
Enable Nativelink Cloud Cache workflow for macos-14

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1374)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@blakehatch +@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1374#-:-O7uWo8M0eA-mYb3ChoJ:b-kcf889)* status: 0 of 2 LGTMs obtained, and 0 of 1 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / ubuntu-24.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @allada and @blakehatch)

**Review by blakehatch — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1374#-:-O7udc1-CjSpaoH9vhOh:bg7igkv)* status: 1 of 2 LGTMs obtained, and 0 of 1 files reviewed, and pending CI: Remote / large-ubuntu-22.04 (waiting on @allada)

**Review by aaronmondal — COMMENTED** [review]
-@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1374#-:-O7vWW2NDFPsVJWMle7C:b-r9zead)* status: 1 of 1 LGTMs obtained, and 0 of 1 files reviewed

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1374)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1374)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
