### PR TITLE
Rename example configs to json5

### LINKED ISSUE #1507: Invalid json example configs
The example configs are using comments which are not allowed in json.

### PR DESCRIPTION
**Pull request by SchahinRohani**
# Description

Rename json to jsonc, which is just json with comments.

Fixes #1507

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1508)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Nice change! Way more readable through syntax highlighting.

Since we’re using json5 internally, let’s use that as the new file type.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1508#-:-OCrRNv1EYaCtMQlDcMF:b9ziir2)* status: 0 of 1 LGTMs obtained, and 0 of 13 files reviewed, and pending CI: Bazel Dev / macos-13, Cargo Dev / macos-13, Coverage, Installation / macos-13, Installation / macos-14, NativeLink.com Cloud / Remote Cache / macos-14, Remote / large-ubuntu-22.04, macos-13

**Review by SchahinRohani — COMMENTED** [review]
As you wish.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1508#-:-OCti_gx1OJ3KwobxzpE:bmnqrfh)* status: 0 of 1 LGTMs obtained, and 0 of 14 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 13 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1508#-:-OCu5dyo1qjGR_x_s37C:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04

**Comment by aaronmondal** [comment]
@SchahinRohani I believe the failing job in this case might be caused by some missing change in the k8s setup. Since the worker deployment stays in unready state, my guess is that it can't find the configmap.

**Review by MarcusSorealheis — APPROVED** [review]
thanks Schahin!
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1508#-:-ODNwpgn-k_cCeaLAkTm:b-8eecy9)* status: 2 of 1 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04

**Review by SchahinRohani — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1508)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
