### PR TITLE
Update README for More Clarity

### LINKED ISSUE #729: Quickstart has an empty directory with no files, throwing a `not found` error
When running the bazel test command inside the `nativelink` main repo, I'm getting a not found error:

{ code: NotFound, messages: ["No such file or directory (os error 2)", "Failed to remove file \"/tmp/nativelink/data-worker-test/tmp_path-cas/36517273a9afe4dace58ea5e99842a8a638131b3bf3e33c56216000000000000-12441\""] }

Running on:
bazel 7.0.2-homebrew

Slack chat: https://nativelink.slack.com/archives/C06758HJQF8/p1709776707727789

Main Idea for failure: 
The remote execution part is failing. If you do remove the --remote_executor=grpc://127.0.0.1:50051 \ line, it will correctly compile using just the remote_cache

### PR DESCRIPTION
**Pull request by nfarah86**
# Description

added mac os warning

Fixes #729 

## Type of change

Please delete options that aren't relevant.
- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
@nfarah86 Since this is doing more than just adding the warning section, could you split this into two PRs?

FYI the stylechecker warnings are visualized in the regular GitHub review view here: https://github.com/TraceMachina/nativelink/pull/803/files

The config for that checker is here: https://github.com/TraceMachina/nativelink/blob/main/.vale.ini

To run the checks manually:

 - Set up nix and flakes (for instance with this installer: https://github.com/NixOS/experimental-nix-installer)
- Run `nix develop` in the repository. 
- (Alternatively, install direnv with e.g. `nix profile install nixpkgs#direnv` and hook it into your shell like https://direnv.net/docs/hook.html. This way the flake automatically activates when you `cd` into the repository).
- Run `pre-commit run -a`. If you're in the nix flake this will also run automatically every time you create a commit and will stop the commit if it doesn't pass the pre-commit CI locally.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803#-:-Nu1EVcT1s8RAgkvxSwX:bx6km6j)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

**Review by nfarah86 — COMMENTED** [review]
Hey @aaronmondal is it ok to change the commit messages to reflect the macos warning and  that I updated the readme for more clarity? I setup nix and ran pre commit hooks. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803#-:-Nu1KAyg4ysRYpC8MyQZ:bf8ccaq)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Sure. Changes to the commit title and message are part of the review in reviewable.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803#-:-Nu1_IT55ypv5S88WGNB:b-j0pyty)* status: 0 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1_oztB2xaSKa0bkrC):*
If you edit this message while doing a `git commit --amend` it'll show up here as a change.
___
*[`README.md` line 78 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1a_7w2dfLykZ_nV2G:-Nu1a_7w2dfLykZ_nV2H:beoznd2) ([raw file](https://github.com/TraceMachina/nativelink/blob/2447f2086b962fc554a1f732fa6841c2990875a6/README.md#L78)):*
> ```Markdown
> and `worker`.
> 
> 
> ```

Let's not turn of vale unless it's absolutely necessary.

If it raises a false positive because it doesn't know a valid word you can add it to the vocabulary here: https://github.com/TraceMachina/nativelink/blob/main/.github/styles/config/vocabularies/TraceMachina/accept.txt

**Review by nfarah86 — COMMENTED** [review]
Updated - how does it look now?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803#-:-Nu1obNqB2ZnqRDmR16p:b80fylr)* status: 0 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks, and 2 discussions need to be resolved

**Review by blakehatch — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803#-:-Nu4i8xN4p35Eeqy0s-u:bg7igkv)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1_oztB2xaSKa0bkrC):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

If you edit this message while doing a `git commit --amend` it'll show up here as a change.
</blockquote></details>

Or `git commit --amend -m "..."` so you don't have to exit vim 😂

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1_oztB2xaSKa0bkrC):*
<details><summary><i>Previously, blakehatch (Blake Hatch) wrote…</i></summary><blockquote>

Or `git commit --amend -m "..."` so you don't have to exit vim 😂
</blockquote></details>

With `-m` you'd lose the original message. I.e. the diff between messages wouldn't really be a diff but something else every time you have some larger commit. Also, neovim automatically color-codes too long commit titles and auto-linebreaks the commit message body :nerd_face:

@nfarah86 The format we use for commits is

1. Capitalized title
2. No trailing period
3. Short and concise, but precise title, if possible shorter than 72 characters
4. Details in the body (also limited to 72 characters except for links) if necessary.
5. Imperative tone
6. If the message contains `and`, it's probably something that should be split into two commits

You can see examples when you run `git log` in a terminal.

The relevant part here is that a `git log` invocation should be readable on a terminal. Most editors auto-linebreak so in those cases you wouldn't notice issues with extremely long lines, but when you use a terminal on a server it gives much better user experience. The guidelines are fairly "default", but AFAIK we don't have it documented anywhere (which we should probably change).

**Review by nfarah86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1_oztB2xaSKa0bkrC):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

With `-m` you'd lose the original message. I.e. the diff between messages wouldn't really be a diff but something else every time you have some larger commit. Also, neovim automatically color-codes too long commit titles and auto-linebreaks the commit message body :nerd_face:

@nfarah86 The format we use for commits is

1. Capitalized title
2. No trailing period
3. Short and concise, but precise title, if possible shorter than 72 characters
4. Details in the body (also limited to 72 characters except for links) if necessary.
5. Imperative tone
6. If the message contains `and`, it's probably something that should be split into two commits

You can see examples when you run `git log` in a terminal.

The relevant part here is that a `git log` invocation should be readable on a terminal. Most editors auto-linebreak so in those cases you wouldn't notice issues with extremely long lines, but when you use a terminal on a server it gives much better user experience. The guidelines are fairly "default", but AFAIK we don't have it documented anywhere (which we should probably change).
</blockquote></details>

Done.
___
*[`README.md` line 78 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1a_7w2dfLykZ_nV2G:-Nu5-6EY0sU9rlguProu:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2447f2086b962fc554a1f732fa6841c2990875a6/README.md#L78)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

fyi @nfarah86 you can Type `Done` in this message to resolve it or click on the `Resolve` button to unblock this comment.
</blockquote></details>

Done.

**Comment by nfarah86** [comment]
> > _[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803)_ status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved
> 
> _[`README.md` line 78 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/803#-Nu1a_7w2dfLykZ_nV2G:-Nu4qaZg5Xab0m46xK2L:b-ckri3n) ([raw file](https://github.com/TraceMachina/nativelink/blob/2447f2086b962fc554a1f732fa6841c2990875a6/README.md#L78)):_
> 
> Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…
> fyi @nfarah86 you can Type `Done` in this message to resolve it or click on the `Resolve` button to unblock this comment.

The resolve button is not showing up for me :(

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/803#-:-Nu5SdP75xdPizl-VfB9:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
