### PR TITLE
Harden CI against too long running jobs

### PR DESCRIPTION
**Pull request by aaronmondal**
The Nix flake update in 8a63295 pinned `nixpkgs` to a commit where `pkgs.clang` wasn't in the global Nix cache for MacOS. This caused subsequent jobs to build Clang in CI, making those jobs run for several hours.

We can't really predict whether packages are in the Nix store and usually this isn't an issue. One potential explanation for Clang not being in the global Nix store could be that a recent GHA incident caused the global Nix cache to not be properly updated for a while.

This commit introduces timouts to all jobs to prevent this from happening in the future. In other words, we'll now kill jobs if they take too long to run in an attempt to keep build times reasonably low.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/917)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@allada +@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/917#-:-NxxkeHN-CAWqiqUTJUZ:bchhibo)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer and @allada)

**Review by zbirenbaum — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/917)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @allada)

**Review by zbirenbaum — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/917#-:-Nxy-a47CN5kxb6Pq2OU:bg7igkv)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @allada)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/917#-:-Nxy-fk8D9VM-Sf8aahM:bnfp4nl)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @allada)

**Review by aaronmondal — COMMENTED** [review]
-@allada -@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/917#-:-Nxy39jQ-S0bj3s1D7um:b-y3f1vg)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
