### PR TITLE
ByteStreamServer now responds with no-data-received instead of NotFound

### PR DESCRIPTION
**Pull request by allada**
If a client tries to upload a file, but the first payload fails, the client may call query_write_status(), which we now return "0" (no data received yet) instead of NotFound to increase compatibility with clients.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1341)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1341#-:-O6MmnvF6F68di0we8t1:b-bn1n1c)* status: 0 of 2 LGTMs obtained, and 0 of 2 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (Legacy Dockerfile Test), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer)

**Review by adam-singer — APPROVED** [review]
Looking at the bytestream.proto, it doesn't seem to mention expectation to retry if complete is false, do you know where that expectation is documented within bazel (non-blocker, curious on how we know this will fix the issue beyond observation of behavior). What I was able to dig up is https://github.com/bazelbuild/bazel/blob/720d5b1dc7bd7ae3db6697237a115c169a77e23d/src/test/java/com/google/devtools/build/lib/remote/ByteStreamUploaderTest.java#L1681 and seems to indicate retry settings do control attempt counts based on `committed size = 0 && completed = false`

:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1341#-:-O6MqZLe7gKlXfMZoi74:b-d1ke1o)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Cargo Dev / macos-13, Installation / macos-13, Installation / macos-14, macos-13, windows-2022 / stable

**Review by allada — COMMENTED** [review]
I didn't look deep into bazel's impl, but logically if we drop the first payload we never know what the resource_name is, so we can't resume it. According to spec, we are allowed to restart the stream from any checkpoint that is < what the client sent, so setting it to 0 if it is not found is just telling the client to start over.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1341#-:-O6Mu0sr8pwtEDcOcKsE:bipszw5)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Cargo Dev / macos-13, macos-13, windows-2022 / stable

**Review by MarcusSorealheis — COMMENTED** [review]
Amazing. 😻

**Pull request merged**
