### PR TITLE
Fix image publishing workflow after 1a43ef9

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/777)

### CODE REVIEW

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/777#-:-NtMVyvp2ryf9kD9qUzB:bnfp4nl)* status: 1 of 4 LGTMs obtained (waiting on @allada, @blakehatch, and @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/777)* status: 1 of 4 LGTMs obtained (waiting on @allada and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
-@allada -@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/777#-:-NtMW3Mm9N5v6PrkqSbJ:b-cqd5zh)* status: 1 of 2 LGTMs obtained (waiting on @zbirenbaum)

**Review by zbirenbaum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/777#-:-NtMWPaT43k7wx_qVNmq:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Pull request merged**
