### PR TITLE
Create Glossary

### PR DESCRIPTION
**Pull request by nfarah86**
# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes # (issue)
#770 

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
yes, I ran yarn start.

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/957)

### CODE REVIEW

**Comment by nfarah86** [comment]
@aaronmondal I don't know if the CLAssistant is lagging- but I signed the document and updated my global git configurations and my settings profile has an email address. 
Screenshot 2024-06-01 at 12 03 06 AM

**Comment by aaronmondal** [comment]
Your commit is not linked to your github account and not verified. I think you need to change the email and username that you use with git.

**Comment by aaronmondal** [comment]
You can see whether your commit is verified and whether it links to your account correctly by visiting yor fork's commit page:

https://github.com/nfarah86/nativelink/commits/DOCS-new-glossary/

**Comment by nfarah86** [comment]
Screenshot 2024-06-01 at 6 56 30 AM
I updated git- @aaronmondal let me know if this is what you meant.

**Comment by nfarah86** [comment]
I signed the commit with my ssh key - which matches the ssh keys I publically uploaded. I don't know GitHub is saying it's "unverified" - both keys match

**Comment by MarcusSorealheis** [comment]
You need to sign the commit. You can sign commits with `-S` or modify the global config to auto sign.

**Comment by nfarah86** [comment]
Thanks Marcus!  I signed with -S.  The thing is, it’s not finding my public
ssh keys. Aaron mentioned that he’s seen this before and that I should try
 ssh-keygen -t ed25519 -C ***@***.***". I think GitHub’s
instructions could be somewhat incorrect. I’ll give this a shot soon.

**Comment by MarcusSorealheis** [comment]
@nfarah86 did you sign with `-S`?

**Comment by MarcusSorealheis** [comment]
>I think GitHub’s
instructions could be somewhat incorrect.

This is quite unlikely though possible. Can we double check? I can jump on a call.

**Comment by nfarah86** [comment]
@MarcusSorealheis @aaronmondal I think I know what's going on. Originally, when I created my keys a few months back, I put it as an `authentication`, not `signing`.  Let me rework this- I may have a hunch on what's going on. 
Screenshot 2024-06-02 at 10 37 47 AM

**Comment by nfarah86** [comment]
whoo hooo! that worked!!! I'm now verified.

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/957#-:-NzP2mJRCVjmp6ocv1qQ:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @nfarah86)

**Comment by nfarah86** [comment]
merging

**Review by nfarah86 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/957#-:-NzPKFVz9sQ4PTmks9gJ:bnfp4nl)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

**Review by nfarah86 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/957)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
