### PR TITLE
Add subscribe API to Store API

### PR DESCRIPTION
**Pull request by allada**
This adds the basic subscribe to the Store API that allows users to subscribe to individual keys and listen for when they change. The default store subscribe implementation will poll every 10 seconds for changes. Future PRs will be landed to specialize specific stores to make it optimized for stores that support a more optimized way to subscribe (like redis or memory).

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924)

### CODE REVIEW

**Review by adam-singer — CHANGES_REQUESTED** [review]
needs tests 

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-NyLbgHV13xuDvRBQ_PD:b-chehkp)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 102 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/924#-NyLbKdN2RJSBmzM0IAi:-NyLbKdN2RJSBmzM0IAj:b-15i2rw) ([raw file](https://github.com/TraceMachina/nativelink/blob/45f46097ce33a8c887b1d8b978e9d7f0306b08d3/nativelink-util/src/default_store_key_subscribe.rs#L102)):*
> ```XML
>         loop {
>             tokio::select! {
>                 _ = tokio::time::sleep(std::time::Duration::from_secs(10)) => {
> ```

import vs fully qualified name
also if we go with this implementation as a first pass should we make the interval an experimental configuration option?

**Review by allada — COMMENTED** [review]
+@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-Nzo0ZwtBh4NiIGWYunB:b-bn1n1c)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer)

___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 102 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/924#-NyLbKdN2RJSBmzM0IAi:-Nzo0YxU1PkbVIi_CV0C:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/45f46097ce33a8c887b1d8b978e9d7f0306b08d3/nativelink-util/src/default_store_key_subscribe.rs#L102)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

import vs fully qualified name
also if we go with this implementation as a first pass should we make the interval an experimental configuration option?
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
+@caass 

fyi: @zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-Nzo0biPBlJry4pS-R8k:b7kjrro)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer and @caass)

**Review by caass — APPROVED** [review]
Awesome :)

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-Nzp6-XhAlxMkJ3fEKA4:b903kkx)* status: 0 of 2 LGTMs obtained, and 6 discussions need to be resolved (waiting on @adam-singer and @caass)

___
*[`nativelink-scheduler/tests/simple_scheduler_test.rs` line 49 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp1a9mBzoqEAXTzdgU:-Nzp1a9n1QnwnKapcSKg:bl90ttn) ([raw file](https://github.com/TraceMachina/nativelink/blob/b7a7e364e78b07a907407856354a61c54e12406f/nativelink-scheduler/tests/simple_scheduler_test.rs#L49)):*
> ```XML
>     rx: &mut mpsc::UnboundedReceiver<UpdateForWorker>,
> ) {
>     use pretty_assertions::assert_eq;
> ```

Why'd you take this out?
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp2wuA25G4a4A7uUo0:-Nzp2wuA25G4a4A7uUo1:b-q2pkwn) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L41)):*
> ```XML
> #[async_trait]
> impl<S: StoreDriver + ?Sized> StoreSubscriptionItem for DefaultStoreSubscriptionItem<S> {
>     async fn get_key<'a>(&'a self) -> Result<StoreKey<'a>, Error> {
> ```

Nit: Can this explicit lifetime be made implicit?
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 65 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp3Nfv08nFeahJHuyC:-Nzp3Nfv08nFeahJHuyD:bucrcm) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L65)):*
> ```XML
>     let (mut writer, reader) = make_buf_channel_pair();
>     // Note: We wrap the future, so if the future is dropped, the writer will be dropped.
>     let read_fut = async move { store.get_part(key, &mut writer, 0, None).await };
> ```

Does this need to be a block like this? Or can you just do like `let read_fut = store.get_part(key, &mut writer, 0, None)`
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 66 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp3k7wCq5NzgjQH0U7:-Nzp3k7wCq5NzgjQH0U8:b-vkfj4) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L66)):*
> ```XML
>     // Note: We wrap the future, so if the future is dropped, the writer will be dropped.
>     let read_fut = async move { store.get_part(key, &mut writer, 0, None).await };
>     let (read_res, write_res) = futures::join!(read_fut, async move {
> ```

Minor I feel like this could be also extracted into `write_fut` for consistency and readability.
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 83 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp4ARRAh-06xVn1i2G:-Nzp4ARRAh-06xVn1i2H:bx0oocl) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L83)):*
> ```XML
>         return read_res.merge(write_res);
>     }
>     write_res
> ```

Minor, this can be changed to `read_res.and(write_res)`



_Code quote:_
```XML
    if read_res.is_err() {
        return read_res.merge(write_res);
    }
    write_res
```
___
*[`nativelink-util/src/store_trait.rs` line 659 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp5Lja4RWIUE_O07Ax:-Nzp5Lja4RWIUE_O07Ay:be68d3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/store_trait.rs#L659)):*
> ```XML
>     }
> 
>     /// See: `Store::subscribe()` for details.
> ```

BTW if you put square brackets around this, it'll auto-link and I can jump to the definition in my editor
```rust
/// See [`Store::subscribe`] for details.
```

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-O-3GMeV0yLzewNLm36A:bnfp4nl)* status: 1 of 2 LGTMs obtained, and 5 discussions need to be resolved (waiting on @caass)

___
*[`nativelink-util/Cargo.toml` line 42 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-O-3EIry-5bCWVfea1jR:-O-3EIry-5bCWVfea1jS:bdhslhk) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/Cargo.toml#L42)):*
> ```TOML
> rand = "0.8.5"
> mock_instant = "0.3.2"
> nativelink-store = { path = "../nativelink-store" }
> ```

This seems strange, why would `nativelink-store` take a dependency on `nativelink-util` and `nativelink-util` take a dev dependency on `nativelink-store`?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924)* status: 1 of 2 LGTMs obtained, and pending CI: Vercel, pre-commit-checks, and 2 discussions need to be resolved (waiting on @caass)

___
*[`nativelink-scheduler/tests/simple_scheduler_test.rs` line 49 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzo1RZ8-KW0QhvyXkk1:-Nzo1RZ8-KW0QhvyXkk2:b1zut7q) ([raw file](https://github.com/TraceMachina/nativelink/blob/b7a7e364e78b07a907407856354a61c54e12406f/nativelink-scheduler/tests/simple_scheduler_test.rs#L49)):*
> ```XML
>     rx: &mut mpsc::UnboundedReceiver<UpdateForWorker>,
> ) {
>     use pretty_assertions::assert_eq;
> ```

fyi: residual from another recent change. Was throwing a warning.
___
*[`nativelink-scheduler/tests/simple_scheduler_test.rs` line 49 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp1a9mBzoqEAXTzdgU:-O-3tvWg3CJwppUamwno:bx2hd3q) ([raw file](https://github.com/TraceMachina/nativelink/blob/b7a7e364e78b07a907407856354a61c54e12406f/nativelink-scheduler/tests/simple_scheduler_test.rs#L49)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Why'd you take this out?
</blockquote></details>

I forgot to publish the comment above.
___
*[`nativelink-util/Cargo.toml` line 42 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-O-3EIry-5bCWVfea1jR:-O-3u3rN6m6YFueLUIno:bd15xfl) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/Cargo.toml#L42)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

This seems strange, why would `nativelink-store` take a dependency on `nativelink-util` and `nativelink-util` take a dev dependency on `nativelink-store`?
</blockquote></details>

The new `default_store_key_subscribe_test.rs` uses it. Since it uses it only in the binary files and not the lib files there's no circular dependencies.

Remember: `store_trait.rs` is in `nativelink-util`, not in `nativelink-store`.
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp2wuA25G4a4A7uUo0:-O-3uala0hh8d6ZXGGRj:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L41)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Nit: Can this explicit lifetime be made implicit?
</blockquote></details>

Done.
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 65 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp3Nfv08nFeahJHuyC:-O-3ucPW0XznDz58sQzB:b-wmpskr) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L65)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Does this need to be a block like this? Or can you just do like `let read_fut = store.get_part(key, &mut writer, 0, None)`
</blockquote></details>

The `Note` above explains. But we want to make sure the drop function on `writer` is called when the future is done.
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 66 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp3k7wCq5NzgjQH0U7:-O-3uq086ukU51eh5XHV:b-x0t8kd) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L66)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Minor I feel like this could be also extracted into `write_fut` for consistency and readability.
</blockquote></details>

Done. I usually do this pattern when one future is `polling` and the other is doing the real work.
___
*[`nativelink-util/src/default_store_key_subscribe.rs` line 83 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp4ARRAh-06xVn1i2G:-O-3vI0y4y5onlTJUVuo:bahzbmo) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/default_store_key_subscribe.rs#L83)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

Minor, this can be changed to `read_res.and(write_res)`
</blockquote></details>

`.merge()` concats the error messages together, making this line-by-it-self `read_res.and(write_res)` has no value because we'd still need the `read_res` if-statement above.

I could make all of this `read_res.merge(write_res)`, but since it's not obvious which one returns the non-error, I decided to make the code self-describing.
___
*[`nativelink-util/src/store_trait.rs` line 659 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/924#-Nzp5Lja4RWIUE_O07Ax:-O-3wNGa4jckucDuzFBV:b-r0xgm7) ([raw file](https://github.com/TraceMachina/nativelink/blob/ef1feabbadbca262770e2c0c9f1576caf3eeca81/nativelink-util/src/store_trait.rs#L659)):*
<details><summary><i>Previously, caass (Cass Fridkin) wrote…</i></summary><blockquote>

BTW if you put square brackets around this, it'll auto-link and I can jump to the definition in my editor
```rust
/// See [`Store::subscribe`] for details.
```
</blockquote></details>

Done. And fixed the others while I was here.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-O-4pNBN7Uaw2j-W3Cja:bnfp4nl)* status: 1 of 2 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04 (waiting on @caass)

**Review by allada — COMMENTED** [review]
-@caass

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924#-:-O-6mPjyEA7D9vYLCWv7:bhl61nv)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

**Review by allada — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by allada — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/924)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
