### PR TITLE
Add warning for TLS

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
# Description

Tonic has changed its behaviour such that the TLS configuration is ignored within transport/service/connector.rs if the scheme isn't https.  Firstly, add support for grpcs scheme by swapping it out in the endpoint Uri if set. Secondly, add a warning to the unsuspecting user that sets the TLS configuration, but not the correct scheme.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I spent a long time trying to figure out why my TLS configuration wasn't working with the Tonic upgrade to 0.10.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/tls_utils.rs` line 75 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/609#-NoOHQeu-DIuLMPkyXza:-NoOHQeu-DIuLMPkyXzb:bpekmxo) ([raw file](https://github.com/TraceMachina/nativelink/blob/54bf3871c2bb2dfd700a5aefc0dd18bddcec7202/nativelink-util/src/tls_utils.rs#L75)):*
> ```XML
>         };
>         if endpoint.scheme_str() != Some("https") {
>             tracing::warn!("You have set TLS configuration on {endpoint}, these will be ignored because the scheme is insecure.  Set to https or grpcs.");
> ```

I'm thinking maybe we should not allow TLS to be configured if "https" is not used. What do you think about returning an error here instead?

It looks like all places that use this function are all on construction, so in theory the program would just not start.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609)* status: 0 of 1 LGTMs obtained

___
*[`nativelink-util/src/tls_utils.rs` line 75 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/609#-NoOHQeu-DIuLMPkyXza:-NoS3ClDAqFszSJXXpCJ:be3joq5) ([raw file](https://github.com/TraceMachina/nativelink/blob/54bf3871c2bb2dfd700a5aefc0dd18bddcec7202/nativelink-util/src/tls_utils.rs#L75)):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

I considered an error, but couldn't decide.  Happy to go either way.
</blockquote></details>

Yeah lets do an error. Devs will have a higher chance of reading stderr/out if it crashes than at runtime.

**Review by adam-singer — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609)* status: 0 of 1 LGTMs obtained

**Review by chrisstaite-menlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609)* status: 0 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

___
*[`nativelink-util/src/tls_utils.rs` line 75 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/609#-NoOHQeu-DIuLMPkyXza:-NoSXW2X0vyD01CllLE2:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/54bf3871c2bb2dfd700a5aefc0dd18bddcec7202/nativelink-util/src/tls_utils.rs#L75)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Yeah lets do an error. Devs will have a higher chance of reading stderr/out if it crashes than at runtime.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609#-:-NoSkeyrBn0EyIp_kFOp:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/609#-:-NoSuRJ253Yb9vh8LGox:bnfp4nl)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
