### PR TITLE
Restructure files to be more appropriate

### PR DESCRIPTION
**Pull request by allada**
Mostly just moving files and functions around to be more appropriate.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1131)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-:-O1QFc5O7Dd7Mb1mCLJE:b-djxp74)* status: 0 of 2 LGTMs obtained, and pending CI: vale (waiting on @adam-singer and @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-:-O1SjtwR0pd7BFMr5eTS:bnfp4nl)* status: 1 of 2 LGTMs obtained, and 10 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 44 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sf4VeCnYSOAAe3FUv:-O1Sf4VeCnYSOAAe3FUw:b-6fbo78) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L44)):*
> ```XML
> /// How often the owning database will have the AwaitedAction touched
> /// to keep it from being evicted.
> const KEEPALIVE_DURATION: Duration = Duration::from_secs(10);
> ```

Can we inline this one, https://github.com/rust-lang/rust/issues/57391, lets avoid the global `const` for any potential weird rust bugs. 
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 46 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sf_3vEiryC_vdHk7N:-O1Sf_3vEiryC_vdHk7O:b-vc9b4e) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L46)):*
> ```XML
> const KEEPALIVE_DURATION: Duration = Duration::from_secs(10);
> 
> fn filter_check(awaited_action: &AwaitedAction, filter: &OperationFilter) -> bool {
> ```

nit: is there anything else we could call this besides `filter_check`, `filter_predicate` seems to indicate what it is, tho not what the definition of the predicate is. Trying to read this and ask myself "What kind of filter predicate is this?" 
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 153 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SgURH0ZYQdADjm4qC:-O1SgURH0ZYQdADjm4qD:b-8fx2u7) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L153)):*
> ```XML
> 
>     /// Channel to notify when a client operation id is dropped.
>     client_operation_drop_tx: mpsc::UnboundedSender<Arc<AwaitedAction>>,
> ```

:+1: 
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 174 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sgc2_754YtuPDI5EM:-O1Sgc2_754YtuPDI5EN:b-6z6vun) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L174)):*
> ```XML
>                 make_err!(
>                     Code::Internal,
>                     "Could not find action info MemorySchedulerStateManager::update_operation"
> ```

Can we make `operation_id && maybe_worker_id` part of this err message, that way we can possibly have clues to which operation this might of stem from? I'd bet we probably do serialize that information upstream, tho unsure.
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 183 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sh3pb-XO_XOPV2vW3:-O1Sh3pb-XO_XOPV2vW4:b-bgo0ea) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L183)):*
> ```XML
>             return Err(make_err!(
>                 Code::Internal,
>                 "Action {operation_id:?} is already completed with state {:?}",
> ```

Include `maybe_worker_id`
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 231 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1ShASn5eaSr71OkKn4:-O1ShASn5eaSr71OkKn5:bhz345e) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L231)):*
> ```XML
>                         error: Some(err.clone().merge(make_err!(
>                             Code::Internal,
>                             "Job cancelled because it attempted to execute too many times and failed"
> ```

Encode the important bits of information here related to worker id, operation id, etc. 
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 305 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1ShXsy5s_7MITEeRdo:-O1ShXsy5s_7MITEeRdp:b-exjmvu) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L305)):*
> ```XML
>                     spawn!("state_manager_client_drop_rx", async move {
>                         /// Number of events to pull from the stream at a time.
>                         const MAX_DROP_HANDLES_PER_CYCLE: usize = 1024;
> ```

nit: we could promote this outside of the impl scope
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 276 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SixZ40Z0L11wme2GM:-O1SixZ5CTZAbtOWZwJS:b-jco1zi) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L276)):*
> ```XML
>                 event!(
>                     Level::ERROR,
>                     "sorted_action_info_hash_keys and action_info_hash_key_to_awaited_action are out of sync",
> ```

nit: is there any useful serialized information we can output here that doesn't screen barf? 
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 364 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SjUcb2ca4heClBgX0:-O1SjUcb2ca4heClBgX1:b-svru73) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L364)):*
> ```XML
>                 "Could not find existing action with name: {unique_qualifier}"
>             ))
>             .err_tip(|| "In state_manager::try_subscribe")?;
> ```

nit: would be good to know both `client_operation_id && unique_qualifier` if we reach these failure cases.
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 370 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sjd_i2qLcXtUswb2Q:-O1Sjd_i2qLcXtUswb2R:b-23pykp) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L370)):*
> ```XML
>         if awaited_action.get_current_state().stage.is_finished() {
>             return Err(make_input_err!(
>                 "Subscribing an item that is already completed should be handled by CacheLookupScheduler."
> ```

nit: same including what the stage was

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1131)* status: 1 of 2 LGTMs obtained, and 11 discussions need to be resolved

___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/client_awaited_action.rs` line 70 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SrObcCU3dUdFPOWIA:-O1SrObcCU3dUdFPOWIB:bezjjbd) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/client_awaited_action.rs#L70)):*
> ```XML
> 
> /// Trait to be able to use the [`EvictingMap`] with [`ClientAwaitedAction`].
> /// Note: We only use [`EvictingMap`] for a time based evictiong, which is
> ```

It doesn't seem like ClientAwaitedAction is iterable so having values for these at all seems a bit strange

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1131)* status: 1 of 2 LGTMs obtained, and 5 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 44 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sf4VeCnYSOAAe3FUv:-O1T4uIS3fVlvAEg-mhi:bhr9x52) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L44)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can we inline this one, https://github.com/rust-lang/rust/issues/57391, lets avoid the global `const` for any potential weird rust bugs.
</blockquote></details>

I don't think this linked ticket has to do with the issue you were seeing.
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 46 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sf_3vEiryC_vdHk7N:-O1T1LBG-I74myUm9mPG:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L46)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: is there anything else we could call this besides `filter_check`, `filter_predicate` seems to indicate what it is, tho not what the definition of the predicate is. Trying to read this and ask myself "What kind of filter predicate is this?"
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 174 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sgc2_754YtuPDI5EM:-O1T1gBmEKGnNVwqhlrD:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L174)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Can we make `operation_id && maybe_worker_id` part of this err message, that way we can possibly have clues to which operation this might of stem from? I'd bet we probably do serialize that information upstream, tho unsure.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 183 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sh3pb-XO_XOPV2vW3:-O1T4mPuB7Tbhb_wuFtI:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L183)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Include `maybe_worker_id`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 231 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1ShASn5eaSr71OkKn4:-O1T28nY2c1VryF3fX_e:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L231)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Encode the important bits of information here related to worker id, operation id, etc.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs` line 305 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1ShXsy5s_7MITEeRdo:-O1T2RGdAUWh85hlETuA:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/memory_scheduler_state_manager.rs#L305)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: we could promote this outside of the impl scope
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 276 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SixZ40Z0L11wme2GM:-O1T4kqhCwBrh14fnVr-:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L276)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: is there any useful serialized information we can output here that doesn't screen barf?
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 364 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SjUcb2ca4heClBgX0:-O1T330C2ZhFMP6IPlwz:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L364)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: would be good to know both `client_operation_id && unique_qualifier` if we reach these failure cases.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs` line 370 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1Sjd_i2qLcXtUswb2Q:-O1T3PjUCPoiB7ea8kzI:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/awaited_action_db.rs#L370)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: same including what the stage was
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/client_awaited_action.rs` line 70 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1131#-O1SrObcCU3dUdFPOWIA:-O1T4YCU4W1DFfoDbTeL:bi46awf) ([raw file](https://github.com/TraceMachina/nativelink/blob/7342c4bd1da172b515108a0694b281dcba6fef65/nativelink-scheduler/src/memory_scheduler_state/awaited_action_db/client_awaited_action.rs#L70)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

It doesn't seem like ClientAwaitedAction is iterable so having values for these at all seems a bit strange
</blockquote></details>

Yeah, that's why the note exists. Because `EvictingMap` requires items to be `LenEntry`, but we are only using `EvictingMap` for the time based eviction (not time based).

**Pull request merged**
