### PR TITLE
Fix clippy::map_unwrap_or

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1103)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
Lets not land any of these until the new scheduler code is in. We are going to be in some big rebase hell if we do.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1103#-:-O1FfgjCCUR12vSc6b_S:b-kvz9b7)* status: 0 of 1 LGTMs obtained

**Review by adam-singer — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1103)* status: 0 of 1 LGTMs obtained

**Review by SchahinRohani — COMMENTED** [review]
Superseded by #1415  

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1103#-:-O9uVNH5AKyYpid76NZ4:b-8sx1ne)* status: 0 of 1 LGTMs obtained, and all files reviewed

**Comment by SchahinRohani** [comment]
Superseded by #1415

**Pull request closed without merging**
