### PR TITLE
Add BEP (Build Event Protocol) protos

### PR DESCRIPTION
**Pull request by allada**
In prep to support the BEP (Build Event Protocol), we are adding the proto definitions to the repo and related generated code.

towards: #925

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/926)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@blakehatch 

fyi: @adam-singer , @aaronmondal 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/926#-:-NyN9Wnu8vN9tq2ErEma:b-rfmgzt)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @blakehatch)

**Review by blakehatch — COMMENTED** [review]
You will want to add another proto that adds RPCs for listening to granular build events and higher-level lifecycle events (build started, build ended, etc) such as this:

https://github.com/ChristianBelloni/bazel-bep/blob/master/proto/publish_build_event.proto

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/926#-:-NyNAdym3HxhlLbX7AFf:b-6ustby)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by allada — COMMENTED** [review]
I accidentally added the wrong BEP... apparently bazel has a slightly different proto definition than google's.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/926#-:-NyNEoKC8yslIpfYWe1P:b-ui19wb)* status: 0 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks (waiting on @blakehatch)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/926#-:-NyRzl9l8nklTbb8-veD:bnfp4nl)* status: 0 of 1 LGTMs obtained (waiting on @blakehatch)

**Pull request closed without merging**
