### PR TITLE
Migrate Mintlify to Docusaurus

### LINKED ISSUE #542: Change docs to Docusaurus
The current documentation is lacking. We should migrate to Docusaurus or similar.

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

Migrate over NativeLink Docs to Docusaurus.

Fixes #542

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] This change requires a documentation update

Will need to migrate deployment to our own Vercel org from the Mintlify dashboard

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586)

### CODE REVIEW

**Comment by blakehatch** [comment]
@MarcusSorealheis I recommend taking a look at the built-in blog system that Docusaurus has it's pretty cool if you'd prefer to have it hosted on our own site instead of externally.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Oh damn this looks so good!

Apart from the comments, a few more things:

- When I start this I get a 404 on the homepage. Clicking on the `Docs` button then brings me to the correct pages. This might just be because it's the development server, but it seems likely that this is an actual bug.
- I tested this with bun which seems to work out of the box with `bun install` and `bun start`. The bun installation is ~27x faster (2sec vs 55sec) than the yarn installation, so we should probably use that instead :rocket:
- We should add `pkgs.bun` (or `pkgs.yarn`, if bun turns out to be bugged after all) to the flake here: https://github.com/TraceMachina/nativelink/blob/546484b86cf9c6c0f1343e68ecf12e9e4e8c5c2d/flake.nix#L147

I think a bunch of the template files need to be removed or adjusted, but this seems to be much better.

I'm noticing that we now use `.md` instead of `.mdx` for the documentation files. Is it still correct to have the sections like

```md
---
some info
---
```

in there?

> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586#-:-NmzSflu2ZsRw2MxnKMY:b-w9e4jh)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, pre-commit-checks

___
*[`nativelink-docs/docusaurus.config.js` line 12 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzQif2CxpEIUCsLSV0:-NmzQif2CxpEIUCsLSV1:buqclor) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/docusaurus.config.js#L12)):*
> ```JavaScript
> const config = {
>   title: 'NativeLink',
>   tagline: 'Dinosaurs are cool',
> ```

Is this tagline intentional?
___
*[`nativelink-docs/docusaurus.config.js` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzQq14BFu-pZhMAUa6:-NmzQq14BFu-pZhMAUa7:borwxrq) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/docusaurus.config.js#L18)):*
> ```JavaScript
>   url: 'https://docs.nativelink.dev',
>   // Set the /<baseUrl>/ pathname under which your site is served
>   // For GitHub pages deployment, it is often '/<projectName>/'
> ```

Let's remove all comments that "explain" how to configure docusaurus.
___
*[`nativelink-docs/blog/2019-05-28-first-blog-post.md` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRGPC2EzhcJlI1kIi:-NmzRGPC2EzhcJlI1kIj:b-5hifju) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2019-05-28-first-blog-post.md#L6)):*
> ```Markdown
> authors:
>   name: Gao Wei
>   title: Docusaurus Core Team
> ```

Redundant.
___
*[`nativelink-docs/blog/2019-05-29-long-blog-post.md` line 8 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRLY1-YK_jK-6o_Jp:-NmzRLY1-YK_jK-6o_Jq:b-7ropln) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2019-05-29-long-blog-post.md#L8)):*
> ```Markdown
> ---
> 
> This is the summary of a very long blog post,
> ```

ditto
___
*[`nativelink-docs/blog/2021-08-01-mdx-blog-post.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRPnPC_AkaI4IYV19:-NmzRPnPC_AkaI4IYV1A:b-7ropln) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2021-08-01-mdx-blog-post.mdx#L1)):*
> ```MDX
> ---
> ```

ditto
___
*[`nativelink-docs/blog/authors.yml` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRRnH65RGN1lkLka5:-NmzRRnI207L4ihfFguT:b-ntvxsz) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/authors.yml#L1)):*
> ```YAML
> endi:
> ```

We'll need to figure out what to put here.
___
*[`nativelink-docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRbit22B_TpOg8fez:-NmzRbit22B_TpOg8ff-:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg#L0)):*
redundant?
___
*[`nativelink-docs/blog/2021-08-26-welcome/index.md` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRewH764VXinhatgf:-NmzRewH764VXinhatgg:b-7ropln) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2021-08-26-welcome/index.md#L1)):*
> ```Markdown
> ---
> ```

ditto
___
*[`nativelink-docs/src/components/HomepageFeatures/index.js` line 7 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzS6lK4s0keg89ON0m:-NmzS6lK4s0keg89ON0n:bwyumsh) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/src/components/HomepageFeatures/index.js#L7)):*
> ```JavaScript
> const FeatureList = [
>   {
>     title: 'Easy to Use',
> ```

This needs to be adjusted to our information.
___
*[`nativelink-docs/src/pages/markdown-page.md` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSFPL6XMK6zUH4zWZ:-NmzSFPL6XMK6zUH4zW_:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/src/pages/markdown-page.md#L1)):*
> ```Markdown
> ---
> ```

redundant?
___
*[`nativelink-docs/static/img/docusaurus.png` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSJHW40ffyC5xz_8k:-NmzSJHW40ffyC5xz_8l:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/docusaurus.png#L0)):*
redundant?
___
*[`nativelink-docs/static/img/docusaurus-social-card.jpg` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSKuuDA_RtqpFhKYL:-NmzSKuuDA_RtqpFhKYM:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/docusaurus-social-card.jpg#L0)):*
redundant?
___
*[`nativelink-docs/static/img/favicon.ico` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSNY-2coLGQeFrbVO:-NmzSNY-2coLGQeFrbVP:b-i1jkcf) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/favicon.ico#L0)):*
Is this our icon?
___
*[`nativelink-docs/static/img/logo.svg` line 0 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSQSN9VTwXoul4r4s:-NmzSQSN9VTwXoul4r4t:b-i1jkcf) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/logo.svg#L0)):*
Is this our icon?
___
*[`nativelink-docs/static/img/undraw_docusaurus_mountain.svg` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSWM26mTt4RBBwH8K:-NmzSWM26mTt4RBBwH8L:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/undraw_docusaurus_mountain.svg#L1)):*
> ```SVG
> <svg xmlns="http://www.w3.org/2000/svg" width="1088" height="687.962" viewBox="0 0 1088 687.962">
> ```

redundant?
___
*[`nativelink-docs/static/img/undraw_docusaurus_react.svg` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSYfxBCMKf7Mf1O8n:-NmzSYfxBCMKf7Mf1O8o:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/undraw_docusaurus_react.svg#L1)):*
> ```SVG
> <svg xmlns="http://www.w3.org/2000/svg" width="1041.277" height="554.141" viewBox="0 0 1041.277 554.141">
> ```

redundant?
___
*[`nativelink-docs/static/img/undraw_docusaurus_tree.svg` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSa5V8-kS9ahV6YBl:-NmzSa5V8-kS9ahV6YBm:bwkqr3r) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/undraw_docusaurus_tree.svg#L1)):*
> ```SVG
> <svg xmlns="http://www.w3.org/2000/svg" width="1129" height="663" viewBox="0 0 1129 663">
> ```

redundant?
___
*[`nativelink-docs/docs/About.mdx` line 22 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRixp6oJgCvm1skvQ:-NmzRixp6oJgCvm1skvR:b-yvb002) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/docs/About.mdx#L22)):*
> ```MDX
> Supports Unix-based operating systems and Windows.
> 
> ## 🎯 Goals
> ```

fyi: I think for the initial migration it's fine to leave this. We can "fix" any content-related changes in subsequent commits.

**Review by blakehatch — COMMENTED** [review]
1. I was rerouting to Quickstart manually in index.js which is how you configured a subdomain for docs before but they have a new cleaner solution I migrated to however I broke the base route. It had a clean solution just by adding "Slug: /" to the header comment to have the base path direct to it.
2. I agree this should easily work with bun since it's a simple static site, updated the README to recommend bun.
3. Updated the flake.
4. We can either use md or mdx, however mdx is a superset of md so I converted all of them to mdx for consistency sake and to avoid confusion if future devs (most likely future me lol) gets confused why mdx features aren't working for certain files.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586#-:-NnCVMHuEriZuI0bV235:bu9nlb2)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, pre-commit-checks

___
*[`nativelink-docs/docusaurus.config.js` line 12 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzQif2CxpEIUCsLSV0:-NnCWOKB-y3JI9g9hpJ1:bjjiqsp) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/docusaurus.config.js#L12)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this tagline intentional?
</blockquote></details>

No this was a default left in, change.
___
*[`nativelink-docs/docusaurus.config.js` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzQq14BFu-pZhMAUa6:-NnCYXFtDHbD_9qLxPCH:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/docusaurus.config.js#L18)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's remove all comments that "explain" how to configure docusaurus.
</blockquote></details>

Done.
___
*[`nativelink-docs/blog/2019-05-28-first-blog-post.md` line 6 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRGPC2EzhcJlI1kIi:-NnCYaUm232Q2LjYhm41:b-mi1miv) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2019-05-28-first-blog-post.md#L6)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Redundant.
</blockquote></details>

Removed blog directory entirely as we're keeping external for now
___
*[`nativelink-docs/blog/2019-05-29-long-blog-post.md` line 8 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRLY1-YK_jK-6o_Jp:-NnCYfsk1M7e8OkV8byM:b-mi1miv) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2019-05-29-long-blog-post.md#L8)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed blog directory entirely as we're keeping external for now
___
*[`nativelink-docs/blog/2021-08-01-mdx-blog-post.mdx` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRPnPC_AkaI4IYV19:-NnCYgKv9EMLu_eyTjYa:b-mi1miv) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2021-08-01-mdx-blog-post.mdx#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed blog directory entirely as we're keeping external for now
___
*[`nativelink-docs/blog/authors.yml` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRRnH65RGN1lkLka5:-NnCYgj-DCiptbqNffqZ:b-mi1miv) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/authors.yml#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

We'll need to figure out what to put here.
</blockquote></details>

Removed blog directory entirely as we're keeping external for now
___
*[`nativelink-docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRbit22B_TpOg8fez:-NnCYhMnEgEQsBeyGsto:b-mi1miv) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed blog directory entirely as we're keeping external for now
___
*[`nativelink-docs/blog/2021-08-26-welcome/index.md` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRewH764VXinhatgf:-NnCYhqi59GvzsEHNLvX:b-mi1miv) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/blog/2021-08-26-welcome/index.md#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed blog directory entirely as we're keeping external for now
___
*[`nativelink-docs/src/components/HomepageFeatures/index.js` line 7 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzS6lK4s0keg89ON0m:-NnCZihB-5C6GwdTK3tm:b7xyuzc) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/src/components/HomepageFeatures/index.js#L7)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This needs to be adjusted to our information.
</blockquote></details>

Removed directory as we're not using Docusaurus for the marketing page.
___
*[`nativelink-docs/src/pages/markdown-page.md` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSFPL6XMK6zUH4zWZ:-NnCZnMN-wMs5aECiqqi:b-qhdiwy) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/src/pages/markdown-page.md#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed pages as we're not adding any routing other than to docs.
___
*[`nativelink-docs/static/img/docusaurus.png` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSJHW40ffyC5xz_8k:-NnC_b-x6SJ6Wv5IW4e4:bnqo7pf) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/docusaurus.png#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed as not needed.
___
*[`nativelink-docs/static/img/docusaurus-social-card.jpg` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSKuuDA_RtqpFhKYL:-NnC_diC2B-GVIVXQj6S:bnqo7pf) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/docusaurus-social-card.jpg#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed as not needed.
___
*[`nativelink-docs/static/img/favicon.ico` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSNY-2coLGQeFrbVO:-NnC_eiT0DVR9COsi4-a:b8llne8) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/favicon.ico#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this our icon?
</blockquote></details>

No replaced it with the svg favicon, removed.
___
*[`nativelink-docs/static/img/logo.svg` line  at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSQSN9VTwXoul4r4s:-NnC_ij29xBePcRy9ucH:b-kj8xw8) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/logo.svg#L)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this our icon?
</blockquote></details>

No, removed.
___
*[`nativelink-docs/static/img/undraw_docusaurus_mountain.svg` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSWM26mTt4RBBwH8K:-NnC_sYA9DoRS0Y_8m7J:bss4a2b) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/undraw_docusaurus_mountain.svg#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed.
___
*[`nativelink-docs/static/img/undraw_docusaurus_react.svg` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSYfxBCMKf7Mf1O8n:-NnC_tKY3LPtcaEj0362:bss4a2b) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/undraw_docusaurus_react.svg#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed.
___
*[`nativelink-docs/static/img/undraw_docusaurus_tree.svg` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzSa5V8-kS9ahV6YBl:-NnC_tvO3k8QdsMgN6wE:bss4a2b) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/static/img/undraw_docusaurus_tree.svg#L1)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

Removed.
___
*[`nativelink-docs/docs/About.mdx` line 22 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NmzRixp6oJgCvm1skvQ:-NnCYiP9EQsgsz2jzhQS:b-sb70fl) ([raw file](https://github.com/TraceMachina/nativelink/blob/0a525f58cea33028c45703595871c2262a39aa21/nativelink-docs/docs/About.mdx#L22)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

fyi: I think for the initial migration it's fine to leave this. We can "fix" any content-related changes in subsequent commits.
</blockquote></details>

Agreed main focus is migrating infrastructure and swapping out DNS quickly/smoothly to self-host the domain.

**Review by blakehatch — COMMENTED** [review]
Unfortunately I double checked and builds were not working correctly with bun so leaving yarn as the recommended package manager for now until I can get building to work.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586#-:-NnCa0tGAns2h3IpYNxV:b-6bb104)* status: 0 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, pre-commit-checks

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586#-:-NnEfHaMAmRJdYmaJy77:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by aaronmondal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586)* status: 1 of 1 LGTMs obtained

___
*[`.gitignore` line 15 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NnEfqaN6xu2P7m4_uOE:-NnEfqaN6xu2P7m4_uOF:b-t877ob) ([raw file](https://github.com/TraceMachina/nativelink/blob/8f3d121ec797676d22273698db878185d61a1d13/.gitignore#L15)):*
> ```ignore
> result
> .bazelrc.user
> /node_modules
> ```

nit: Since we have the other gitignore in the `nativelink-docs` directory, is this still needed?
___
*[`nativelink-docs/package.json` line 3 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NnEg1983sHQaGhyhwKD:-NnEg1983sHQaGhyhwKE:b-p5nlrs) ([raw file](https://github.com/TraceMachina/nativelink/blob/8f3d121ec797676d22273698db878185d61a1d13/nativelink-docs/package.json#L3)):*
> ```JSON
> {
>   "name": "my-website",
>   "version": "0.0.0",
> ```

nit: name field.

nit: Not sure whether this could have implications for "multiple-version-docs". I.e. should this have the same version as nativelink?

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/586)* status: 1 of 1 LGTMs obtained

___
*[`nativelink-docs/package.json` line 3 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NnEg1983sHQaGhyhwKD:-NnEy0zm6_0JD4pc6AcX:bezafkp) ([raw file](https://github.com/TraceMachina/nativelink/blob/8f3d121ec797676d22273698db878185d61a1d13/nativelink-docs/package.json#L3)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: name field.

nit: Not sure whether this could have implications for "multiple-version-docs". I.e. should this have the same version as nativelink?
</blockquote></details>

Seems like the standard for this is to make is as clear as possible to know what's the latest version of the documentation so should probably try to have it mirror the version for nativelink?
___
*[`.gitignore` line 15 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/586#-NnEfqaN6xu2P7m4_uOE:-NnExNea0s3Vn7DEVwS7:b-jdgzi) ([raw file](https://github.com/TraceMachina/nativelink/blob/8f3d121ec797676d22273698db878185d61a1d13/.gitignore#L15)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Since we have the other gitignore in the `nativelink-docs` directory, is this still needed?
</blockquote></details>

No, will remove. Having separate gitignores will scale better for the monorepo.

**Pull request merged**
