### PR TITLE
Fix cargo install tag and start command

### LINKED ISSUE #652: Update cas to nativelink in docs site for running instructions

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

Please include a summary of the changes and the related issue. Please also
include relevant motivation and context.

Fixes #652

- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/654)

### CODE REVIEW

**Review by tyr-one — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/654)* status: 0 of 1 LGTMs obtained, and pending CI: asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13 (waiting on @blakehatch)

**Review by tyr-one — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/654#-:-NpfnzXB-vPiFefLjIge:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13 (waiting on @blakehatch)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/654#-:-NpfrmDY15L-nz9VTdle:bnfp4nl)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04) (waiting on @blakehatch)

**Review by blakehatch — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/654#-:-NpfwhsGCXdabMgrVBru:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
