### PR TITLE
Introduce the NativeLink Cloud flake module

### PR DESCRIPTION
**Pull request by aaronmondal**
This change enables LRE by default and adds a config file that connects Nix users to the NativeLink Cloud. This means that users running Bazel from within the nix flake can fetch artifacts directly from CI builds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1365)

### CODE REVIEW

**Comment by aaronmondal** [comment]
(still needs some adjustments to the nativelink-cloud workflows)

**Review by aaronmondal — COMMENTED** [review]
+@SchahinRohani 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1365#-:-O7kJgmz8fdGJ-pxGf7M:bj5atnp)* status: 0 of 1 LGTMs obtained, and 0 of 8 files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (LRE), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, windows-2022 / stable (waiting on @SchahinRohani)

**Review by SchahinRohani — APPROVED** [review]
Looks fantastic and makes it even faster and convenient to work with nix & bazel!

:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1365#-:-O7kJviq2ggkfPmyBHOI:b-1w02c4)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache (LRE), Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, windows-2022 / stable

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1365)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Pull request merged**
