### PR TITLE
Support digest function in GrpcStore

### LINKED ISSUE #1325: 💎 Support digest_function in GrpcStore
When using an alternative hash function to the default (sha256), GRPC store doesn't receive which hash function to use.

### PR DESCRIPTION
**Pull request by asr2003**
# Description

- Updated `ResourceInfo` to default `digest_function` to `sha256` if not provided.
- Ensured backward compatibility for existing functionality.

Fixes #1325 
/claim #1325

## Type of change

Please delete options that aren't relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1509)

### CODE REVIEW

**Comment by asr2003** [comment]
Debugging the unexpected interruption in the read requests when it is blake3. Also is sha256 is as updated as fallback. Is it intended?
Let me know then I will refine more based on this

**Comment by MarcusSorealheis** [comment]
I understand the comment?

**Comment by asr2003** [comment]
I mean before digest function is None when not explicitly provided in
ResourceInfo.

Now we added fallback behaviour as sha256

**Comment by asr2003** [comment]
@aaronmondal @MarcusSorealheis It's ready for your review!

**Comment by MarcusSorealheis** [comment]
@asr2003 Please squash this into one commit

**Comment by asr2003** [comment]
Sorry @MarcusSorealheis . I have messed up this branch during rebase. Instead I have opened #1548 , a new PR with clean and squashed all of them into one

**Comment by asr2003** [comment]
Closing in favor of #1548

**Pull request closed without merging**
