### PR TITLE
Refresh readme

### PR DESCRIPTION
**Pull request by krishmoran**
# Description

Updates README for clarity, organization, and contributor engagement:

Content Refinements:
- Simplified and expanded the introduction for better clarity and
  comprehension
- Reorganized "Getting Started" section:
  * Grouped installation instructions separately from build instructions
  * Improved topological organization for a more intuitive user experience

Community Focus:
- Added new section highlighting open-source contributors, project
  statistics, and how to contribute
- Aim: Foster community growth and encourage more engagement with the
  product and team

These changes are designed to provide a more user-friendly, informative, and
engaging experience for both new visitors and potential contributors to
NativeLink.

(Visual changes added for better outreach conversion in PR #1074, waiting to be added)

Fixes # (issue)

## Type of change

Please delete options that aren't relevant.

- [x] This change requires a documentation update

## Checklist

- [x] Updated documentation if needed
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078)* status: 0 of 1 LGTMs obtained, and 5 discussions need to be resolved

___
*[`README.md` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0wyA_5Az6Xw7JTwHWd:-O0wyA_5Az6Xw7JTwHWe:b2f5v0d) ([raw file](https://github.com/TraceMachina/nativelink/blob/3117a333f5e4df97068e91c4bb38e95d549045ca/README.md#L10)):*
> ```Markdown
> ## What's NativeLink?
> 
> NativeLink is a blazingly fast, high-performance build cache and remote execution system that accelerates software compilation and testing while reducing infrastructure costs. It optimizes build processes for large-scale projects by intelligently caching build artifacts and distributing tasks across multiple machines, delivering exceptional speed improvements. NativeLink powers over one billion requests per month for customers using the system in production workloads.
> ```

TBH I'm not a fan of this rewrite. 

- It screams "generated by an LLM".
- Its more verbose and more tiring to read.
- Using the term "blazingly" unironically seems weird.
- Blazing speed and high performance are essentially the same thing. We're missing efficiency from this wich is a crucial differentiator, perhaps even more crucial than the actual speed of execution.
- It doesn't only target large-scale projects. Small projects are just as important. Project size doesn't necessarily correlate with complexity and "advanced" build requirements.
- There are more things that aren't exactly correct, but the point is that the previous description (while certainly not perfect) is a better and more accurate description of what NativeLink is.

I propose leaving the start of the readme as-is for now and deferring changes here to another commit.
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x6uaU0sVLbgV0Ng1H:-O0x6uaU0sVLbgV0Ng1I:bqmezw5) ([raw file](https://github.com/TraceMachina/nativelink/blob/3117a333f5e4df97068e91c4bb38e95d549045ca/README.md#L43)):*
> ```Markdown
> Choose one of the following methods to install NativeLink:
> 
> #### 📦 Installing with Cargo
> ```

I believe quadruple hashtags don't get rendered as links in the sidebar of the docs.
___
*[`README.md` line 159 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x4GxM4MATUoYnldtM:-O0x4GxM4MATUoYnldtN:b76vw29) ([raw file](https://github.com/TraceMachina/nativelink/blob/3117a333f5e4df97068e91c4bb38e95d549045ca/README.md#L159)):*
> ```Markdown
> curl -O https://raw.githubusercontent.com/TraceMachina/nativelink/main/nativelink-config/examples/basic_cas.json
> 
> ### you can modify the example above to replace the filesystem store with the memory store if you favor speed over data durability.
> ```

Single '#'. Capitalize sentence.

With the exeption of links, try to keep the maximum line length below 80. This way code snippets become more readable on mobile devices and it makes the document easier to read and edit with terminal-based editors.
___
*[`README.md` line 239 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x0_rqAfjzxdKSHmYy:-O0x0_rqAfjzxdKSHmYz:bva93d4) ([raw file](https://github.com/TraceMachina/nativelink/blob/3117a333f5e4df97068e91c4bb38e95d549045ca/README.md#L239)):*
> ```Markdown
> ## ✍️ Authors
> 
> <a href="https://github.com/tracemachina/nativelink/graphs/contributors">
> ```

This document is automatically transformed to an mdx file and hosted on https://docs.nativelink.com/tutorials/setup/. The transformer script is likely to not work properly with the angle braces out of the box and might need adjustment https://github.com/TraceMachina/nativelink/blob/main/docs/scripts/md_to_mdx.ts.
___
*[`README.md` line 246 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x1iiTDrO3MmKTPg2P:-O0x1iiUAhH9rkH-9Kkn:bg1hz7l) ([raw file](https://github.com/TraceMachina/nativelink/blob/3117a333f5e4df97068e91c4bb38e95d549045ca/README.md#L246)):*
> ```Markdown
> ## 🤝 Contributing
> 
> Visit our [Contributing](https://github.com/tracemachina/nativelink/blob/main/CONTRIBUTING.md) guide to learn how to contribute to NativeLink. It only takes ~5 minutes to get started!
> ```

The sentence "it only takes 5 minutes to get started" might come off as condescending. If it takes a user more than 5 minutes to get started they shouldn't feel bad about it.

It seems safer to remove the sentence.

**Comment by krishmoran** [comment]
@aaronmondal Thanks for these, will wait to change a few of these until installation instructions are migrated as we chatted about. When you get a chance, could you drop a few bullet points on the intro on whats inaccurate/incorrect so I can revise accordingly?

**Review by krishmoran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`README.md` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0wyA_5Az6Xw7JTwHWd:-O1JJ_vo2Xyq4Xc1fyOe:b-ca5aef) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

TBH I'm not a fan of this rewrite. 

- It screams "generated by an LLM".
- Its more verbose and more tiring to read.
- Using the term "blazingly" unironically seems weird.
- Blazing speed and high performance are essentially the same thing. We're missing efficiency from this wich is a crucial differentiator, perhaps even more crucial than the actual speed of execution.
- It doesn't only target large-scale projects. Small projects are just as important. Project size doesn't necessarily correlate with complexity and "advanced" build requirements.
- There are more things that aren't exactly correct, but the point is that the previous description (while certainly not perfect) is a better and more accurate description of what NativeLink is.

I propose leaving the start of the readme as-is for now and deferring changes here to another commit.
</blockquote></details>

addressed in our call. Waiting on your specific edits 
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x6uaU0sVLbgV0Ng1H:-O1JJDV04lvr9MrmlmHo:b-eujagi) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L43)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

I believe quadruple hashtags don't get rendered as links in the sidebar of the docs.
</blockquote></details>

installation being moved to other file -- will be removed in rebase
___
*[`README.md` line 159 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x4GxM4MATUoYnldtM:-O1JInUh6PENULJtSJX1:b-7rl0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L159)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Single '#'. Capitalize sentence.

With the exeption of links, try to keep the maximum line length below 80. This way code snippets become more readable on mobile devices and it makes the document easier to read and edit with terminal-based editors.
</blockquote></details>

done.
___
*[`README.md` line 239 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x0_rqAfjzxdKSHmYy:-O1JJ4dwDJjhCSVii2h7:b-7rl0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L239)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This document is automatically transformed to an mdx file and hosted on https://docs.nativelink.com/tutorials/setup/. The transformer script is likely to not work properly with the angle braces out of the box and might need adjustment https://github.com/TraceMachina/nativelink/blob/main/docs/scripts/md_to_mdx.ts.
</blockquote></details>

done.
___
*[`README.md` line 246 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x1iiTDrO3MmKTPg2P:-O1JJ5LoA-SkJbIb1wiZ:b-7rl0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L246)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

The sentence "it only takes 5 minutes to get started" might come off as condescending. If it takes a user more than 5 minutes to get started they shouldn't feel bad about it.

It seems safer to remove the sentence.
</blockquote></details>

done.

**Review by krishmoran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved

___
*[`README.md` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0wyA_5Az6Xw7JTwHWd:-O1TKkOK544M03Vrtn_v:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L10)):*
<details><summary><i>Previously, krishmoran (Krish Moran) wrote…</i></summary><blockquote>

addressed in our call. Waiting on your specific edits
</blockquote></details>

done
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O0x6uaU0sVLbgV0Ng1H:-O1TKmrD9Spaq1SpWXj-:b-7rl0jd) ([raw file](https://github.com/TraceMachina/nativelink/blob/d50d1c366fbe1e43fb86649906db96ed11db7efd/README.md#L43)):*
<details><summary><i>Previously, krishmoran (Krish Moran) wrote…</i></summary><blockquote>

installation being moved to other file -- will be removed in rebase
</blockquote></details>

done.

**Review by blakehatch — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-:-O1TKv_YDEovc72fvFTp:bg7igkv)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved

**Review by aaronmondal — CHANGES_REQUESTED** [review]
Looks good!

I believe there is some rebase issue. The diff looks like it's changing things that are already on main. Could you rebase one more time? As soon as this is resolved we should be fine to merge.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-:-O1XbFoJ3gFAOuC09qR8:b-tis5w1)* status: 1 of 1 LGTMs obtained, and 2 discussions need to be resolved

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XaVff0IyyRjrqXTCA):*
Either put a commit message that differs from the title, or probably easier, just remove the message altogether. The title alone is fine for this PR.
___
*[`README.md` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1Xb6yECUAKprE0ooV7:-O1Xb6yECUAKprE0ooV8:b-60ztng) ([raw file](https://github.com/TraceMachina/nativelink/blob/c90d3cb557997f22cd205e1369d3724c7643e18e/README.md#L10)):*
> ```Markdown
>     </picture>
>   </a>
> </p>
> ```

Is this `</p>` intended?

**Review by krishmoran — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-:-O1Xjlof3rs3MCbKdg4m:bb7f2mf)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 2 discussions need to be resolved

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XaVff0IyyRjrqXTCA):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Either put a commit message that differs from the title, or probably easier, just remove the message altogether. The title alone is fine for this PR.
</blockquote></details>

done
___
*[`README.md` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1Xb6yECUAKprE0ooV7:-O1XjBLwDb_sq4Donetl:b-lvwanw) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this `</p>` intended?
</blockquote></details>

yes

done

**Review by aaronmondal — APPROVED** [review]
:lgtm:

Mentioned a few nits that you might want to double-check before we land. Let me know when you're happy with things and I'll merge.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-:-O1XqlxS15wj89dm-GSE:b-80ydk4)* status: 2 of 1 LGTMs obtained, and pending CI: Installation / ubuntu-22.04, Remote / large-ubuntu-22.04, and 4 discussions need to be resolved

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XaVff0IyyRjrqXTCA):*
<details><summary><i>Previously, krishmoran (Krish Moran) wrote…</i></summary><blockquote>

done
</blockquote></details>

Hmm the message body is still here. But it's ok I'll fix it during merge.
___
*[`README.md` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1Xb6yECUAKprE0ooV7:-O1XqZ5H610Q6feriFHY:blx95mq) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L10)):*
<details><summary><i>Previously, krishmoran (Krish Moran) wrote…</i></summary><blockquote>

yes

done
</blockquote></details>

Ah this was just displayed confusingly in reviewable.
___
*[`README.md` line 19 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XrGX36_taITEOc4We:-O1XrGX36_taITEOc4Wf:b-usa2td) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L19)):*
> ```Markdown
> [License](https://opensource.org/licenses/Apache-2.0)
> 
> ## What's NativeLink?
> ```

nit: Note that this won't have an emoji in the sidebar. (If that's intended, no problem - just letting you know in case it's unintended).
___
*[`README.md` line 24 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XrBS-4HbS0liix8PD:-O1XrBS-4HbS0liix8PE:b-oi8sw) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L24)):*
> ```Markdown
> 
> NativeLink is trusted in production environments to reduce costs and developer iteration times--handling over **one billion requests** per month for its customers, including large corporations such as **Samsung**.
> ```

nit: remove one newline here (just one, not two)
___
*[`README.md` line 114 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1Xqy4ZARl_gCCsN5mJ:-O1Xqy4ZARl_gCCsN5mK:b-oi8sw) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L114)):*
> ```Markdown
>   
> </a>
> ```

nit: remove one newline here (just one, not two)
___
*[`README.md` line 122 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XsLMDCn4IjbWLJSwb:-O1XsLMDCn4IjbWLJSwc:bw18a1l) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L122)):*
> ```Markdown
> ## 📊 Stats
> 
> Alt
> ```

nit: Double-check that the clickability of this image is how you want it. Markdown sometimes acts a bit funky with this stuff. For instance, we have wrappers around the badges at the top of the file because otherwise the links just point to the raw svgs instead of actual links.

**Review by krishmoran — COMMENTED** [review]
thanks, done

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-:-O1YJ4aZB1s_wJskcnFt:b9ilnk4)* status: 2 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13

___
*[`-- commits` line 4 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XaVff0IyyRjrqXTCA):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Hmm the message body is still here. But it's ok I'll fix it during merge.
</blockquote></details>

done
___
*[`README.md` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1Xb6yECUAKprE0ooV7:-O1YJ7tK54GH08119tt2:b-7rl0jr) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Ah this was just displayed confusingly in reviewable.
</blockquote></details>

done 
___
*[`README.md` line 19 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XrGX36_taITEOc4We:-O1YJBcL3Y_g48LbXnPd:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L19)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Note that this won't have an emoji in the sidebar. (If that's intended, no problem - just letting you know in case it's unintended).
</blockquote></details>

done
___
*[`README.md` line 24 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XrBS-4HbS0liix8PD:-O1YJAr_5zcXZad9LW8x:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L24)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: remove one newline here (just one, not two)
</blockquote></details>

done
___
*[`README.md` line 114 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1Xqy4ZARl_gCCsN5mJ:-O1YJANO0y--6UP2bQOU:bb7f2mf) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L114)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: remove one newline here (just one, not two)
</blockquote></details>

done
___
*[`README.md` line 122 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-O1XsLMDCn4IjbWLJSwb:-O1YJCbtAYvNwgifCask:b-959hsp) ([raw file](https://github.com/TraceMachina/nativelink/blob/f9625acd3066916dcc9abe24828780e615c97af3/README.md#L122)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Double-check that the clickability of this image is how you want it. Markdown sometimes acts a bit funky with this stuff. For instance, we have wrappers around the badges at the top of the file because otherwise the links just point to the raw svgs instead of actual links.
</blockquote></details>


done

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1078#-:-O1YL1u67ic1IanHlo7R:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13

**Pull request merged**
