### PR TITLE
Implementation of ClientStateManager

### PR DESCRIPTION
**Pull request by adam-singer**
# Description

Implementation of `ClientStateManager` where the beginnings of being able to tuck mutations behind a trait for `StateManager`. `StateManager` now wraps the `StateManagerImpl` for inner state structure `StateManagerImpl`. All mutations should be done on a lock on `inner` in the future. Moving implementation code of `add_action` and `filter_operations` into `ClientStateManager` trait. Updated accessor code from `state_manager` to `state_manager.inner`.

Fixes [#990](https://github.com/nativelink/nativelink/issues/990)

## Type of change

Please delete options that aren't relevant.

- [x] Refactor

## How Has This Been Tested?

Existing tests

## Checklist

- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/985)

### CODE REVIEW

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/985)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/client_action_state_result.rs` line 25 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-5A0C45Z7EjgrykVK4:-O-5A0C45Z7EjgrykVK5:b-l6mwxj) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/client_action_state_result.rs#L25)):*
> ```XML
> 
> pub(crate) struct ClientActionStateResult {
>     //notify_channel: Receiver<Arc<ActionState>>,
> ```

remove

**Review by allada — COMMENTED** [review]
Looks good.

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/985#-:-O-6mIx5C-LN3Zpqc0k0:b-vs1pr4)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 7 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/client_action_state_result.rs` line 31 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6l9IXETUUZwXYin_g:-O-6l3ja--R8BfOsJHO5:bmtnapx) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/client_action_state_result.rs#L31)):*
> ```XML
> impl ClientActionStateResult {
>     pub(crate) fn new(mut rx: Receiver<Arc<ActionState>>) -> Self {
>         rx.mark_changed();
> ```

nit: Add comment on why we are marking it changed.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 185 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6lSrB3M1F6PHQ4jxr:-O-6lSrB3M1F6PHQ4jxs:b-ewdjdg) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L185)):*
> ```XML
>         filter: OperationFilter,
>     ) -> Result<ActionStateResultStream, Error> {
>         let unique_qualifier = &filter
> ```

nit: Add todo to build this out to a proper filter.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 194 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6lkV254c0VMXRVjpl:-O-6lkV254c0VMXRVjpm:bf2fxop) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L194)):*
> ```XML
>             .and_then(|action_info| self.inner.queued_actions.get(action_info))
>             .or_else(|| self.inner.active_actions.get(unique_qualifier));
>         let client_action_state_result: Pin<Box<Iter<IntoIter<Arc<dyn ActionStateResult>>>>> =
> ```

nit: Can we remove this type? Forcing the compiler down a specific type route reduces possible optimizations.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 197 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6lXBsAF0uSCnDBspR:-O-6lXBsAF0uSCnDBspS:b-7u1eh2) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L197)):*
> ```XML
>             Box::pin(
>                 awaited_action
>                     .map(|aa| {
> ```

`aa`?
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 200 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6luokACBX_rPRGNU2:-O-6luokACBX_rPRGNU3:b1teqqq) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L200)):*
> ```XML
>                         let rx = aa.notify_channel.subscribe();
>                         let action_result: Vec<Arc<dyn ActionStateResult>> =
>                             vec![Arc::new(ClientActionStateResult::new(rx))];
> ```

nit: Use a fixed array instead, no need to make a heap allocation.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 203 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6m4Di1DWXcZxMKvCI:-O-6m4Di1DWXcZxMKvCJ:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L203)):*
> ```XML
>                         stream::iter(action_result)
>                     })
>                     .unwrap_or_else(|| stream::iter(Vec::new())),
> ```

nit: ditto.

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/985)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 3 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/client_action_state_result.rs` line 31 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6l9IXETUUZwXYin_g:-O-7zJGmBVpwfKkC-juZ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/client_action_state_result.rs#L31)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Add comment on why we are marking it changed.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 185 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6lSrB3M1F6PHQ4jxr:-O-7zi4QB7BHW2U4nPzc:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L185)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Add todo to build this out to a proper filter.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 194 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6lkV254c0VMXRVjpl:-O-8-4geAfp3Ced2f9vN:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L194)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Can we remove this type? Forcing the compiler down a specific type route reduces possible optimizations.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 197 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6lXBsAF0uSCnDBspR:-O-8-YPi4rdp4AYlqxAj:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L197)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

`aa`?
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 200 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6luokACBX_rPRGNU2:-O-83BXQ0euc-WIqKPW7:bh7v5j9) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L200)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Use a fixed array instead, no need to make a heap allocation.
</blockquote></details>

Seems like some error between fixed size vec and `stream::iter` where the size is encoded into the type signature

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/985)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Vercel, asan / ubuntu-22.04, integration-tests (20.04), pre-commit-checks, ubuntu-22.04, vale, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 200 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6luokACBX_rPRGNU2:-O-871PC76-nuXP4vLxQ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L200)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Seems like some error between fixed size vec and `stream::iter` where the size is encoded into the type signature

</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 203 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/985#-O-6m4Di1DWXcZxMKvCI:-O-872LW7ATzJRyVaZaL:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7ddd76e86b8d2ee965a64ffb5d10f7d3566a037c/nativelink-scheduler/src/scheduler_state/state_manager.rs#L203)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: ditto.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/985#-:-O-Ea9oaED6ceW2usDRj:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nativelink/nativelink/985#-:-O-HggT_3S2vW8xfML0h:bnfp4nl)* status: 1 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/nativelink/nativelink/985#-O-Hft8Z7o9hcc3hBGUD):*
nit: missing title.

**Review by allada — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/985)* status: 1 of 1 LGTMs obtained, and pending CI: Publish image, Publish nativelink-worker-lre-cc

**Pull request merged**
