### PR TITLE
Migrate all logging to the tracing library

### PR DESCRIPTION
**Pull request by allada**
This is a significant internal change to move completely away from the last of the "log" crate and move to "tracing".

The major advantage of doing this, is that we can now trace functions across future boundaries usin tracing's instrumentation.

We will now be requiring all tokio::spawn's usage to be properly instrumented.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/871)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@aaronmondal (this should make you happy)
+@adam-singer 

fyi: @chrisstaite-menlo 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/871#-:-Nw2x5M09-GCGVCi3p_7:b-vs478j)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @aaronmondal and @adam-singer)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/871#-Nw2xFoiBcLxUK4qTfS-:-Nw2xFoiBcLxUK4qTfS0:b-j8pk33) (no related file):*
If we keep expanding this usage, there's a good chance we can hook into `.err_tip()` or something. There's a lot of challenges and potential disadvantages though.

___

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/871)* status: 0 of 2 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved (waiting on @aaronmondal and @adam-singer)

___
*[`nativelink-service/src/ac_server.rs` line 166 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/871#-Nw2xpsK4d99h0x5kFOF:-Nw2xpsL5BJt711zcVoo:b-mmpp61) ([raw file](https://github.com/TraceMachina/nativelink/blob/0849c5580822c1d84db97187016833599423ee52/nativelink-service/src/ac_server.rs#L166)):*
> ```XML
> #[tonic::async_trait]
> impl ActionCache for AcServer {
>     #[allow(clippy::blocks_in_conditions)]
> ```

blah, stupid clippy doesn't like the way this macro rewrites the code :-(
___
*[`nativelink-util/src/retry.rs` line 159 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/871#-Nw2yaCr7fKrd-nDmBzV:-Nw2yaCr7fKrd-nDmBzW:b-94ah9a) ([raw file](https://github.com/TraceMachina/nativelink/blob/0849c5580822c1d84db97187016833599423ee52/nativelink-util/src/retry.rs#L159)):*
> ```XML
>                     Some(RetryResult::Retry(err)) => {
>                         if !self.should_retry(&err.code) {
>                             event!(Level::ERROR, ?attempt, ?err, "Not retrying permanent error");
> ```

note: Decided to upgrade this error to `error` instead of `info`..
___
*[`nativelink-worker/src/running_actions_manager.rs` line 528 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/871#-Nw2ylPq5xBqt1UimCo3:-Nw2ylPrEZbEAFizEwi2:b951c4u) ([raw file](https://github.com/TraceMachina/nativelink/blob/0849c5580822c1d84db97187016833599423ee52/nativelink-worker/src/running_actions_manager.rs#L528)):*
> ```XML
> }
> 
> async fn do_cleanup(
> ```

I found a bug due to the improved logging, so I figured I'd fix it. I can break this out into it's own patch, but it'd screw a bit with what I'd done already in this file.

The error was that if the future got dropped, it'd then cause `drop()` to be called and we have an assert in there to ensure our action's get cleaned up. To get around this, we now emit an error, but then do cleanup in a spawn.
___
*[`src/bin/nativelink.rs` line 667 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/871#-Nw2zVPE7T1k-KflSVOl:-Nw2zVPE7T1k-KflSVOm:b-czwfjk) ([raw file](https://github.com/TraceMachina/nativelink/blob/0849c5580822c1d84db97187016833599423ee52/src/bin/nativelink.rs#L667)):*
> ```XML
>                 // is ever dropped we will cleanup our data.
>                 let scope_guard = guard(
>                     Arc::downgrade(&connected_clients_mux),
> ```

fyi: Also figured, I'd fix this... We shouldn't hold a strong reference for cleanup code. No risk, as the code is written now, but good hygine.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/871#-:-Nw3CAfo3PyPRTYNgQ3i:bnfp4nl)* status: 1 of 2 LGTMs obtained, and 1 discussions need to be resolved (waiting on @aaronmondal)

**Review by aaronmondal — APPROVED** [review]
I love this! :heart: 

:lgtm_strong: 

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/871#-:-Nw5qSLK-GWsrzacRUwE:b-sf4xf5)* status: 2 of 2 LGTMs obtained, and 1 discussions need to be resolved

___
*[`src/bin/nativelink.rs` line 696 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/871#-Nw5qN7X6AXisU8IeehR:-Nw5qN7X6AXisU8IeehS:bgvwqdw) ([raw file](https://github.com/TraceMachina/nativelink/blob/0849c5580822c1d84db97187016833599423ee52/src/bin/nativelink.rs#L696)):*
> ```XML
>                 .map_ok_or_else(
>                     |err| {
>                         use std::error::Error;
> ```

nit: Is this use correct?

**Pull request merged**
