### PR TITLE
WIP: RedisAwaitedActionDb

### PR DESCRIPTION
**Pull request by zbirenbaum**
Commit for early feedback and design planning.

# Description

Notable partial or full TODO items include:
- Handling drop events
- Serialize/Deserialize impl for ActionState
- Make client actually accessible from RedisStore
- Error handling
- Return sorted AwaitedActions with ChunkStream 

## Type of change

Please delete options that aren't relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)

### CODE REVIEW

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 9 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 112 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ejf1PEMkSiLFhLNYy:-O2Ejf1PEMkSiLFhLNYz:b-rgimup) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L112)):*
> ```XML
> 
> impl RedisAwaitedActionDbImpl {
>     pub async fn get_operation_subscriber_count(&mut self, operation_id: &OperationId) -> usize {
> ```

Inline these helpers or move up the Err->Option handling so that they are actually doing something to save LoC.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 171 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ejqz87lKwLYYkLaqV:-O2Ejqz87lKwLYYkLaqW:b-77cye8) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L171)):*
> ```XML
>         };
> 
>         // TODO: Create a spawn which will wait on this drop_rx to notify the db of the drop
> ```

Implement this
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 350 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Eh8G_420K22MfaDqS:-O2Eh8G_420K22MfaDqT:b-kvxseq) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L350)):*
> ```XML
>     }
> 
>     async fn get_all_awaited_actions(
> ```

It is very difficult to get this data in the right format for this signature without just using unwrap or logging events to discard errors.

I wasn't able to figure out how to get the closure to accept returning a result but I'm sure there's a way to do so and all this can be moved above the for loop with proper error handling.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 378 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2EhaPL8AkIzJrrs3Eh:-O2EhaPMB0Q8vNhWSctz:b-hp141d) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L378)):*
> ```XML
>     ) -> Result<Option<Self::Subscriber>, Error> {
>         let result = self.get_operation_id_by_client_id(client_id).await;
>         let operation_id = match result {
> ```

The Err -> Option handling here should probably be done in the helper functions above.
___
*[`nativelink-scheduler/src/awaited_action_db/awaited_action.rs` line 61 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ehh7_2W45h_vtawwl:-O2Ehh7_2W45h_vtawwm:bd6z5aq) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/awaited_action_db/awaited_action.rs#L61)):*
> ```XML
> }
> 
> impl AwaitedAction {
> ```

These functions should be simple with serde_json since json can go to/from bytes.
___
*[`nativelink-store/src/redis_store.rs` line 57 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ei-2JCTU5hXGz3JTC:-O2Ei-2JCTU5hXGz3JTD:byfn2qc) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-store/src/redis_store.rs#L57)):*
> ```XML
> pub enum ConnectionKind {
>     Cluster(ClusterConnection),
>     Single((redis::Client, ConnectionManager)),
> ```

This was something @allada and I did partially together, but ultimately I wasn't able to get access to the Client by including it here.

Since I was able to get returning this somewhat compiling, I kept it, but I don't think this solution is going to work. Since it's nested below 2-3 levels of fairly complicated generics the types are really finicky.
___
*[`nativelink-store/src/redis_store.rs` line 141 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ei_sp8w4e9RnFoXet:-O2Ei_sp8w4e9RnFoXeu:bib0n3s) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-store/src/redis_store.rs#L141)):*
> ```XML
>         let client = redis::Client::open(params).map_err(from_redis_err)?;
>         let client_clone = client.clone();
>         let init = async move { Ok((client_clone.clone(), client_clone.get_connection_manager().await.unwrap())) };
> ```

@jhpratt and I spent some time on this and could only get it to compile by using this code. Unfortunately returning it here didn't seem to make it accessible in the return value the way @allada and I thought it would, so I just returned the client as part of the tuple.
___
*[`nativelink-store/src/redis_store.rs` line 268 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ej-Z65b0DMRdymvnN:-O2Ej-Z65b0DMRdymvnO:b-mmtm5) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-store/src/redis_store.rs#L268)):*
> ```XML
> 
>         todo!()
>         // if config.addresses.is_empty() {
> ```

Technically this code compiles, but it causes error messages for all the tests to pass the client through. Until we decide on how to make the client accessible from inside the constructor it's easiest to just mark it `todo!` so there aren't a bunch of compiler errors thrown by the test cases.
___
*[`nativelink-util/src/action_messages.rs` line 768 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2EjKK09H4a5jtFO7UX:-O2EjKK09H4a5jtFO7UY:bws61rf) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-util/src/action_messages.rs#L768)):*
> ```XML
> }
> 
> impl Serialize for ActionStage {
> ```

Should be fairly trivial, I think I have a snippet for this somewhere.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 16 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 67 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N3Un93i4Gkwcr8ORQ:-O2N3Un93i4Gkwcr8ORR:b-bg8ool) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L67)):*
> ```XML
> enum RedisActionEvent {
>     /// A client has sent a keep alive message.
>     // ClientKeepAlive(ClientOperationId),
> ```

note: keep-alives still need to be processed to prevent the operation from being dropped in redis.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 225 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N6uX495FMYwJSfQDk:-O2N6uX495FMYwJSfQDl:b-q3250s) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L225)):*
> ```XML
>         let client = store.get_client();
>         let weak_inner = Arc::downgrade(&inner);
>         let _joinhandle = background_spawn!("redis_action_change_listener", async move {
> ```

nit: This join handle should be on the returned struct. This will allow the connection to be cleaned up if this struct is destroyed.

Also, don't use `background_spawn!` use `spawn!`
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 237 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N7KTx0e-jrX4ax31I:-O2N7KTx0e-jrX4ax31J:bvj9buq) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L237)):*
> ```XML
>             let mut stream = pubsub.into_on_message();
>             loop {
>                 let msg = stream.next().await.unwrap();
> ```

nit: Sadly this needs to be more complicated. It needs to probably use the raw poll functions, so we don't `upgrade()` on every cycle and instead only upgrade once, then traverse any items in our buffer, then release the upgrade.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 243 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N9riA1G5sKcn_AWmA:-O2N9riA1G5sKcn_AWmB:b30ukf5) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L243)):*
> ```XML
>                         let mut inner_mut = inner_mutex.lock().await;
>                         let tx = inner_mut.get_operation_sender(state.operation_id()).await.unwrap();
>                         tx.send_replace(state);
> ```

nit: Put comment here on why not to use `.send()`.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 276 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2NA3X62RRy1wmW6T4F:-O2NA3X62RRy1wmW6T4G:ba86ujx) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L276)):*
> ```XML
>                 let sub = self.subscribe_to_operation(&operation_id).await;
>                 let key = format!("cid:{client_id}");
>                 self.store.update_oneshot(StoreKey::from(key), operation_id.to_string().into()).await?;
> ```

nit: I don't think you need `StoreKey::from`, it should implicitly take a `String` and do conversion for you.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 277 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2NAgYZBSp8-yY2MJJB:-O2NAgYZBSp8-yY2MJJC:baag2tz) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L277)):*
> ```XML
>                 let key = format!("cid:{client_id}");
>                 self.store.update_oneshot(StoreKey::from(key), operation_id.to_string().into()).await?;
>                 self.inc_operation_subscriber_count(&operation_id).await;
> ```

We should not be doing the increment of subscriber count here. It needs to happen inside the construction of the `sub` object. We could easily end up with a memory problems here because of this:
```
1. Subscribe to operation and acquire an owned `RedisAwaitedActionSubscriber`
2. Future dies while `update_oneshot` is being processed.
3. `RedisAwaitedActionSubscriber::drop()` is called
4. `drop()` function calls `dec_operation_subscriber_count()`, which the `inc_operation_subscriber_count()` was never called, so the state is out-of-sync.
```
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 288 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2NCL_WAk1sO3wEtdg_:-O2NCL_WAk1sO3wEtdga:b-5quns) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L288)):*
> ```XML
>                         self.store.update_oneshot(StoreKey::from(key), operation_id.to_string().into()).await?;
> 
>                         let key = format!("ahk:{}", &action_info.unique_qualifier);
> ```

Action Hash Key needs to happen after Operation ID insertion or we could end up pointing to something that doesn't exist.

Remember any time `.await` is called, think: "what might happen if the function returns here?"
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 350 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Eh8G_420K22MfaDqS:-O2NDtHtAeyQ8SbDo_1m:b-zah17k) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L350)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

It is very difficult to get this data in the right format for this signature without just using unwrap or logging events to discard errors.

I wasn't able to figure out how to get the closure to accept returning a result but I'm sure there's a way to do so and all this can be moved above the for loop with proper error handling.
</blockquote></details>

The way you generally want to handle this is by using an `ErrorRedisSubscriber` or something that always returns a stream of only the error with `.left_stream() `and `.right_stream()` for the real stream.

**Review by jhpratt — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 16 discussions need to be resolved

___
*[`nativelink-store/src/redis_store.rs` line 141 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ei_sp8w4e9RnFoXet:-O2REuyb1rprlit_idfN:b-wpb7kw) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-store/src/redis_store.rs#L141)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

@jhpratt and I spent some time on this and could only get it to compile by using this code. Unfortunately returning it here didn't seem to make it accessible in the return value the way @allada and I thought it would, so I just returned the client as part of the tuple.
</blockquote></details>

Would you like me to take a look at this in more detail? What we discussed on the call was largely to unblock your work by simply making it compile, regardless of whether it was the best in the end.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 16 discussions need to be resolved

___
*[`nativelink-store/src/redis_store.rs` line 141 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2Ei_sp8w4e9RnFoXet:-O2RGqZS82pLrTi2Ws8E:b-neb3fi) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-store/src/redis_store.rs#L141)):*
<details><summary><i>Previously, jhpratt (Jacob Pratt) wrote…</i></summary><blockquote>

Would you like me to take a look at this in more detail? What we discussed on the call was largely to unblock your work by simply making it compile, regardless of whether it was the best in the end.
</blockquote></details>

Let's sync on it when you have a chance. I think the ideal case would be embedding it in a field like the connection where it already exists, so we can pull it out when needed but still have it hidden for the tests.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), pre-commit-checks, vale, and 13 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 225 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N6uX495FMYwJSfQDk:-O2RSSzt272Tklkj-cpC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L225)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: This join handle should be on the returned struct. This will allow the connection to be cleaned up if this struct is destroyed.

Also, don't use `background_spawn!` use `spawn!`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 237 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N7KTx0e-jrX4ax31I:-O2RTww44mT8sCjkggA8:b-3aogbz) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L237)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Sadly this needs to be more complicated. It needs to probably use the raw poll functions, so we don't `upgrade()` on every cycle and instead only upgrade once, then traverse any items in our buffer, then release the upgrade.
</blockquote></details>

Should we be creating a new struct that implements future to handle this? Or do you mean calling `poll_next()`?
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 243 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2N9riA1G5sKcn_AWmA:-O2RSowcClw0Z4pO_Cex:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L243)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Put comment here on why not to use `.send()`.
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 276 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2NA3X62RRy1wmW6T4F:-O2RTVnj6LYDc7zUh1Yi:b5i985y) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L276)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: I don't think you need `StoreKey::from`, it should implicitly take a `String` and do conversion for you.
</blockquote></details>

Done. It doesn't take a `String` but it does take `&str` so I changed all those instances to use `.as_str()`
___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 288 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2NCL_WAk1sO3wEtdg_:-O2RUirmASa23vYmParR:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L288)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Action Hash Key needs to happen after Operation ID insertion or we could end up pointing to something that doesn't exist.

Remember any time `.await` is called, think: "what might happen if the function returns here?"
</blockquote></details>

Done.

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: docker-compose-compiles-nativelink (20.04), pre-commit-checks, vale, and 13 discussions need to be resolved

___
*[`nativelink-util/src/action_messages.rs` line 768 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2EjKK09H4a5jtFO7UX:-O2RV9Ba7E0cl-S3TuhW:bbm87gk) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-util/src/action_messages.rs#L768)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

Should be fairly trivial, I think I have a snippet for this somewhere.
</blockquote></details>

#1186

**Review by zbirenbaum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1182)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 13 discussions need to be resolved

___
*[`nativelink-scheduler/src/redis_awaited_action_db.rs` line 277 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1182#-O2NAgYZBSp8-yY2MJJB:-O2T6YrJ9V0CcsCP7ptY:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b17d637f0b8c2977e7c834152dfda91ddb81e041/nativelink-scheduler/src/redis_awaited_action_db.rs#L277)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We should not be doing the increment of subscriber count here. It needs to happen inside the construction of the `sub` object. We could easily end up with a memory problems here because of this:
```
1. Subscribe to operation and acquire an owned `RedisAwaitedActionSubscriber`
2. Future dies while `update_oneshot` is being processed.
3. `RedisAwaitedActionSubscriber::drop()` is called
4. `drop()` function calls `dec_operation_subscriber_count()`, which the `inc_operation_subscriber_count()` was never called, so the state is out-of-sync.
```
</blockquote></details>

Done.

**Pull request closed without merging**
