### PR TITLE
Update the Fixed Buffer Dependency

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

The version of `Fixed-Buffer` used by the project is a bit out of date. I'm updating the dependency to the most recent version, which introduced quite a few changes to the library that improve safety. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/502)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
It's failing because the `Cargo.Bazel.lock` file needs to be update via `CARGO_BAZEL_REPIN=1 bazel test ...` (it's ok if the command itself fails locally, but it should output an updated lockfile).

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/502#-:-Nlyuk6X-TE4HzhhUZ2Z:bgh7mvq)* status: 0 of 3 files reviewed, all discussions resolved

**Review by allada — COMMENTED** [review]
> Reviewed 3 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/502)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @MarcusSorealheis)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/502#-NlzgpFn8-AmuWXUmzN3:-NlzgpFn8-AmuWXUmzN4:bcyglez) (no related file):*
It looks like `async_fixed_buffer` and the related tests can be outright deleted. It looks like we don't use it any more in the code and use `buf_channel` everywhere instead.

I think this file is residual from when we used the `AsyncRead`/`AsyncWrite` style of reading/writing instead of `AsyncStream` style writing.

___
___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/502#-NlzfzXm0kjL45sKkfa9):*
nit: Squash these please.

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/502)* status: all files reviewed, 3 unresolved discussions (waiting on @MarcusSorealheis)

___
*[`nativelink-util/Cargo.toml` line 20 at r10](https://reviewable.io/reviews/TraceMachina/nativelink/502#-Nlzs60O5nlLNJCydnz_:-Nlzs60O5nlLNJCydnza:bwhauqh) ([raw file](https://github.com/TraceMachina/nativelink/blob/44d36cf91d8a3765940b05935ae5d8bf591820d6/nativelink-util/Cargo.toml#L20)):*
> ```TOML
> lru = "0.12.1"
> parking_lot = "0.12.1"
> pin-project = "1.1.3"
> ```

Is this needed?

**Comment by MarcusSorealheis** [comment]
> Is this needed?

Nor is pin project lite

**Review by allada — COMMENTED** [review]
> Reviewed 2 of 5 files at r10, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/502)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`nativelink-util/Cargo.toml` line 20 at r10](https://reviewable.io/reviews/TraceMachina/nativelink/502#-Nlzs60O5nlLNJCydnz_:-Nm--2LJ3EcVAcdYBvXE:b-nbmdot) ([raw file](https://github.com/TraceMachina/nativelink/blob/44d36cf91d8a3765940b05935ae5d8bf591820d6/nativelink-util/Cargo.toml#L20)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Not any more.

**Pull request closed without merging**
