### PR TITLE
Factor out health status checks to it's own service file

### PR DESCRIPTION
**Pull request by blizzardc0der**
# Description
Health status checks should be in it's own service called Health Service.
I made a new service for checking health status.

Fixes https://github.com/TraceMachina/nativelink/issues/643

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)

### CODE REVIEW

**Comment by blizzardc0der** [comment]
I hope you to review this. @allada , @MarcusSorealheis .

**Review by adam-singer — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved

___
*[`nativelink-service/src/health_server.rs` line 47 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NuS1UFRDDwnisgNOC2e:-NuS1UFRDDwnisgNOC2f:b-3dz9j8) ([raw file](https://github.com/TraceMachina/nativelink/blob/c4b136b5a9cbfa7607d3819ec4ccad7ac6a28a0b/nativelink-service/src/health_server.rs#L47)):*
> ```XML
>     }
> 
>     pub async fn check_health_status(&self, json_content_type: &'static str) -> Response<String> {
> ```

I don't think there is value yet in passing `json_content_type` since currently we are serializing only with `serde_json5`. We could introduce a renderer/formatter/writer pattern here at some point, to keep things incremental I'd suggest not doing that yet and don't pass a parameter.

**Review by blizzardc0der — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 2 discussions need to be resolved

___
*[`nativelink-service/src/health_server.rs` line 47 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NuS1UFRDDwnisgNOC2e:-NudRDIz6KKDWhwPP2MK:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c4b136b5a9cbfa7607d3819ec4ccad7ac6a28a0b/nativelink-service/src/health_server.rs#L47)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

I don't think there is value yet in passing `json_content_type` since currently we are serializing only with `serde_json5`. We could introduce a renderer/formatter/writer pattern here at some point, to keep things incremental I'd suggest not doing that yet and don't pass a parameter.
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 412 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NuUYjtV8xNEGUnM8ZyS:-NudRF7W88fFpu33ydq0:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c4b136b5a9cbfa7607d3819ec4ccad7ac6a28a0b/src/bin/nativelink.rs#L412)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We want to make this similar to the other services and load them in in the same manner (config).

see the area in this file around `.add_optional_service(`

We want this health checker to implement that service api and it should be enabled based on the config.
</blockquote></details>

Done.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823#-:-NufS7M3-fTMvL_nJSE_:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), and 1 discussions need to be resolved

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 2 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/823#-Nuj1qCU2e0bnPdXBEmm):*
Please update this with:
```
[Breaking] Factor out health status checks to its own service

Health status checks are now a proper service and no longer enabled by
default.

Add `"health": {},` under your services config to enable.
```
___
*[`nativelink-service/src/health_server.rs` line 30 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/823#-Nuj4p_sEuHh0ewS1vCR:-Nuj4p_sEuHh0ewS1vCS:bhwl29g) ([raw file](https://github.com/TraceMachina/nativelink/blob/450bf362f5b4c1d3215591a4b4f3e34078d50c86/nativelink-service/src/health_server.rs#L30)):*
> ```XML
> #[derive(Clone)]
> pub struct HealthServer {
>     health_registry_builder: Arc<AsyncMutex<HealthRegistryBuilder>>,
> ```

nit: This should not be part of this class. You probably want to bring in `HealthRegistry` during construction. The builder should be kept outside of this class.
___
*[`src/bin/nativelink.rs` line 412 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NuUYjtV8xNEGUnM8ZyS:-Nuj5mUf2bRQ2pVHmunF:b-abujzw) ([raw file](https://github.com/TraceMachina/nativelink/blob/c4b136b5a9cbfa7607d3819ec4ccad7ac6a28a0b/src/bin/nativelink.rs#L412)):*
<details><summary><i>Previously, blizzardc0der (Blizzardc0der) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You want to implement `tower_service::Service` for `HealthServer` then use `.add_service` or `.add_optional_service`. This will offload nearly all the complexity to that module.

**Review by allada — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 1 of 1 LGTMs obtained, and pending CI: integration-tests (20.04), integration-tests (22.04), and 2 discussions need to be resolved

**Review by blizzardc0der — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/823#-Nuj1qCU2e0bnPdXBEmm):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Please update this with:
```
[Breaking] Factor out health status checks to its own service

Health status checks are now a proper service and no longer enabled by
default.

Add `"health": {},` under your services config to enable.
```
</blockquote></details>

Done.
___
*[`src/bin/nativelink.rs` line 412 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NuUYjtV8xNEGUnM8ZyS:-NvNcHwC0ANxU4rz5vvW:bb7o29e) ([raw file](https://github.com/TraceMachina/nativelink/blob/c4b136b5a9cbfa7607d3819ec4ccad7ac6a28a0b/src/bin/nativelink.rs#L412)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

You want to implement `tower_service::Service` for `HealthServer` then use `.add_service` or `.add_optional_service`. This will offload nearly all the complexity to that module.
</blockquote></details>

It's currently derived from `tower_service::Service`, although it can't be added by `.add_service` or `.add_optional_service` because they are functions of `tonic::Service` which is GRPC server not Http Server.
So instead, I added that service by `route_service` function.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823#-:-NvPJdUV-Mtcw-zx9-nv:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 8 discussions need to be resolved

___
*[`nativelink-service/src/health_server.rs` line 14 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPH4Wu6hMxI-WGwfed:-NvPH4Wv5EOw08btwOAw:b-d48frw) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L14)):*
> ```XML
> // See the License for the specific language governing permissions and
> // limitations under the License.
> use futures::StreamExt;
> ```

nit: for consistency new line above.
___
*[`nativelink-service/src/health_server.rs` line 30 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPHHY-5RzqF9xSHGYj:-NvPHHY-5RzqF9xSHGYk:bs1a6l9) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L30)):*
> ```XML
> #[derive(Clone)]
> pub struct HealthServer {
>     pub health_registry_status: HealthRegistry,
> ```

nit: This should not be public. If it's needed make an access function. Making it public allows anyone to update it if they have a it mutable.
___
*[`nativelink-service/src/health_server.rs` line 34 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPHCUgEpadqlKN2l0l:-NvPHCUhEHDl5kpytoVC:b5avlss) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L34)):*
> ```XML
> 
> impl HealthServer {
>     pub async fn new(health_registry_status: HealthRegistry) -> Result<Self, Error> {
> ```

nit: just call all these `health_registry`. It's confusing to call it `_status`.
___
*[`nativelink-service/src/health_server.rs` line 52 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPHpFd-7Xq3l4EzimL:-NvPHpFd-7Xq3l4EzimM:b-4km7d9) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L52)):*
> ```XML
>     fn call(&mut self, _req: Request<Body>) -> Self::Future {
>         let health_registry_status = self.health_registry_status.clone();
>         let fut = async move {
> ```

nit:
```rs
Pin::box(async move {
  //...
})
```
___
*[`nativelink-service/src/health_server.rs` line 53 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPHhba2LCeTSNPCQbr:-NvPHhba2LCeTSNPCQbs:b-dvb5ep) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L53)):*
> ```XML
>         let health_registry_status = self.health_registry_status.clone();
>         let fut = async move {
>             let health_status_descriptions: Vec<HealthStatusDescription> = health_registry_status
> ```

nit: Move this above (outside this future, then we won't need to clone it (above).
___
*[`nativelink-service/src/health_server.rs` line 83 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPInt08MU5Kg7fDKvG:-NvPInt08MU5Kg7fDKvH:bbdx7w4) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L83)):*
> ```XML
>                     .status(StatusCode::INTERNAL_SERVER_ERROR)
>                     .header(
>                         hyper::header::CONTENT_TYPE,
> ```

nit: Please import these and use them instead of listing out the namespaces.
___
*[`nativelink-util/src/health_utils.rs` line 167 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPJQFL3G2Y-oyBbyHc:-NvPJQFL3G2Y-oyBbyHd:b-qbelbv) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-util/src/health_utils.rs#L167)):*
> ```XML
>     fn health_status_report(
>         &self,
>     ) -> Pin<Box<dyn Stream<Item = HealthStatusDescription> + '_ + Send>>;
> ```

nit: `'_` should always be at end.
___
*[`nativelink-util/src/health_utils.rs` line 175 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPJSsy-L91wGNNujdP:-NvPJSsy-L91wGNNujdQ:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-util/src/health_utils.rs#L175)):*
> ```XML
>     fn health_status_report(
>         &self,
>     ) -> Pin<Box<dyn Stream<Item = HealthStatusDescription> + '_ + Send>> {
> ```

nit: ditto.

**Review by allada — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-22.04, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 3 discussions need to be resolved

___
*[`nativelink-service/Cargo.toml` line 14 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvX-_Vg5gEeWo02mqHp:-NvX-_Vg5gEeWo02mqHq:b-wl5xe) ([raw file](https://github.com/TraceMachina/nativelink/blob/0638fa21ea20527c47666fc658c02c5d99d4e741/nativelink-service/Cargo.toml#L14)):*
> ```TOML
> nativelink-scheduler = { path = "../nativelink-scheduler" }
> 
> async-lock = "3.3.0"
> ```

nit: unused.
___
*[`nativelink-service/src/health_server.rs` line 53 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvPHhba2LCeTSNPCQbr:-NvX073ZENbluGZ8z4q1:b-59ov2c) ([raw file](https://github.com/TraceMachina/nativelink/blob/caf1ed719d286c2409edc46786efa6568fbcc190/nativelink-service/src/health_server.rs#L53)):*
<details><summary><i>Previously, blizzardc0der (Blizzardc0der) wrote…</i></summary><blockquote>

Just fyi, I've tried your solution but it didn't work.
`tower::Service` trait's `call` function is defined as synchronous function.
Although, the `health_status_description` variable needs to determined in `async` function.
So I added this line above using `block_on` function to call `async` function inside `call` function.

`let health_status_descriptions: Vec<HealthStatusDescription> = futures::executor::block_on(async move {
            self.health_registry.health_status_report().collect().await
  });`

Although, when I tested it with Postman about `/status` endpoint, it didn't work and hang.
So I didn't apply this changes.
</blockquote></details>

ok, it's fine this way, but the reason you are probably fighting it is because of the future lifetime. You could bind it to the same lifetime as `self` and it would probably be happy.
___
*[`nativelink-service/src/health_server.rs` line 21 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvX-JBNACGFMZyTgSzQ:-NvX-JBNACGFMZyTgSzR:b-quedrt) ([raw file](https://github.com/TraceMachina/nativelink/blob/0638fa21ea20527c47666fc658c02c5d99d4e741/nativelink-service/src/health_server.rs#L21)):*
> ```XML
>     HealthRegistry, HealthStatus, HealthStatusDescription, HealthStatusReporter,
> };
> use std::future::Future;
> ```

nit: `std`'s go first followed by a new line (see other files for example).
___
*[`nativelink-service/src/health_server.rs` line 43 at r6](https://reviewable.io/reviews/TraceMachina/nativelink/823#-NvWz9Iu6CH4BHmx6nHI:-NvWz9Iv0KyHlBuWUwRL:b1flgix) ([raw file](https://github.com/TraceMachina/nativelink/blob/0638fa21ea20527c47666fc658c02c5d99d4e741/nativelink-service/src/health_server.rs#L43)):*
> ```XML
>     type Response = Response<hyper::Body>;
>     type Error = std::convert::Infallible;
>     type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;
> ```

nit: It looks like there's some new syntax in rust you can use here to let the compiler know about the exact future:
```rs
impl Service<Request<hyper::Body>> for HealthServer {
    type Response = Response<hyper::Body>;
    type Error = std::convert::Infallible;
    type Future = impl Future<Output = Result<Self::Response, Self::Error>> + Send>;

    fn call(&mut self, _req: Request<Body>) -> impl Self::Future {
      async move {
        //...
      }
    }
}
```

see: https://rust-lang.github.io/async-fundamentals-initiative/evaluation/challenges/dyn_traits.html

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 4 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, integration-tests (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 1 discussions need to be resolved

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Publish image, Vercel, asan / ubuntu-22.04, integration-tests (20.04), pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 1 discussions need to be resolved

**Review by allada — APPROVED** [review]
> Reviewed 13 of 13 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Review by allada — APPROVED** [review]
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/823)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Pull request merged**
