### PR TITLE
Draw a General Purpose Diagram

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

This diagram is a general purpose diagram for describing NativeLink to people new to the project and looking to understand it conceptually.

## Type of change

Documentation

- [x] This change requires a documentation update

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/705)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/705)* status: 0 of 1 LGTMs obtained

___
*[`README.md` line 83 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/705#-Ns6hNVRD1-AyXtLFNef:-Ns6hNVS-UgLHlfArCgP:b1qxsj3) ([raw file](https://github.com/TraceMachina/nativelink/blob/2ae1ec592188dc424a2327f21fe2e4ed41a28e32/README.md#L83)):*
> ```Markdown
>     build server (client)->>scheduler pool: queue jobs
>     scheduler pool->>worker pool: route jobs
>     worker pool->>cas: compute digests
> ```

nit: Don't say `compute digests` say `upload results` or `upload artifacts` or something.
___
*[`README.md` line 86 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/705#-Ns6hZdTBszmAOKSnK2X:-Ns6hZdTBszmAOKSnK2Y:b-f25i8t) ([raw file](https://github.com/TraceMachina/nativelink/blob/2ae1ec592188dc424a2327f21fe2e4ed41a28e32/README.md#L86)):*
> ```Markdown
>     worker pool->>scheduler pool: result download instructions
>     scheduler pool->>build server (client): result download instructions
>     cas->>build server (client): service queries
> ```

This arrow needs to be pointed from `client -> cas` as well.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/705)* status: 0 of 1 LGTMs obtained

___
*[`README.md` line 86 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/705#-Ns6hZdTBszmAOKSnK2X:-NsA96e87lf8XQEZrBxY:b-7mdc5r) ([raw file](https://github.com/TraceMachina/nativelink/blob/2ae1ec592188dc424a2327f21fe2e4ed41a28e32/README.md#L86)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This arrow needs to be pointed from `client -> cas` as well.
</blockquote></details>

Is it possible to do this as an arrow directly from `build server` to `cas` and vice-versa? It's not very clear what dashed line means here.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/705)* status: 0 of 1 LGTMs obtained

___
*[`README.md` line 86 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/705#-Ns6hZdTBszmAOKSnK2X:-NsA9Q263-oAeUjiJr01:b-5x7hgc) ([raw file](https://github.com/TraceMachina/nativelink/blob/2ae1ec592188dc424a2327f21fe2e4ed41a28e32/README.md#L86)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Is it possible to do this as an arrow directly from `build server` to `cas` and vice-versa? It's not very clear what dashed line means here.
</blockquote></details>

I suggest having two lines, one from `build server -> cas` and another `build server <- cas` one with the request and the other with the response.

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/705)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`README.md` line 86 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/705#-Ns6hZdTBszmAOKSnK2X:-NsApSyL2DJdOwJnIFg8:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2ae1ec592188dc424a2327f21fe2e4ed41a28e32/README.md#L86)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I suggest having two lines, one from `build server -> cas` and another `build server <- cas` one with the request and the other with the response.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/705#-:-NsApus1B9poNPfv9hPu:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

**Pull request merged**
