### PR TITLE
Introduce Local Remote Execution

### PR DESCRIPTION
**Pull request by aaronmondal**
Provide generated toolchain configurations and a reproducible remote execution toolchain container with a C++ toolchain that can be used for fully hermetic integration tests.

Once it's stabilized this allows us to distribute application-specific toolchain containers and to share CI caches with contributors to eliminate redundant rebuilds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)

### CODE REVIEW

**Review by adam-singer — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: all files reviewed, 4 unresolved discussions (waiting on @aaronmondal, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`flake.nix` line 38 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUqPOg6JHLzeCg_Wt5:-NlUqPOg6JHLzeCg_Wt6:b-gl52qe) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/flake.nix#L38)):*
> ```Nix
>           customStdenv = import ./tools/llvmStdenv.nix { inherit pkgs; };
> 
>           # TODO(aaronmondal): This doesn't work with rules_rust yet.
> ```

tioli: Can we github issue this for backlog and link issue id here instead?
___
*[`local-remote-execution/generated/cc/BUILD` line 95 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUtfCY-7yoh3xuzq3F:-NlUtfCY-7yoh3xuzq3G:b-kqro9r) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L95)):*
> ```Starlark
>     cpu = "k8",
>     cxx_builtin_include_directories = [
>         "/nix/store/i7sgy7izmjhdajnjmqzfp7v5j9jhy0qp-clang-wrapper-16.0.6/resource-root/include",
> ```

Are these hashes stable across machines?
___
*[`local-remote-execution/generated/cc/BUILD` line 113 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUtpH77v3a2DzmgmtB:-NlUtpH77v3a2DzmgmtC:b-vpft3g) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L113)):*
> ```Starlark
>         "-L/nix/store/1na9hqj99809qdydgqqkipr2b8gqprzb-libunwind-16.0.6/lib",
>         "-lc++",
>         "-Wl,-rpath,/nix/store/nn3wm6dxy3ps0835kgc9jx4601l1ai5q-libcxx-16.0.6/lib,-rpath,/nix/store/zb21z3mhidfrl3nw6i5a6hrzm84xx7jb-libcxxabi-16.0.6/lib,-rpath,/nix/store/1na9hqj99809qdydgqqkipr2b8gqprzb-libunwind-16.0.6/lib,-rpath,/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27/lib",
> ```

Been awhile for me in regards to native linking, what is the general rule of thumb on ordering of libcxx/libcxxabi/libunwind/glibc? 
___
*[`local-remote-execution/generated/cc/BUILD` line 149 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUuZu47CsAd-O7wO_j:-NlUuZu47CsAd-O7wO_k:bzc2hfz) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L149)):*
> ```Starlark
>         "-no-canonical-prefixes",
>         "-Wno-builtin-macro-redefined",
>         "-D__DATE__=\"redacted\"",
> ```

Why `redacted` and does this get defined later in the pipeline?

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 12 of 25 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: all files reviewed, 14 unresolved discussions (waiting on @aaronmondal, @blakehatch, and @MarcusSorealheis)

___
*[`.bazelrc` line 60 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV2PD88g_5_odFXOvX:-NlV2PD88g_5_odFXOvY:bo96wsl) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/.bazelrc#L60)):*
> ```
> # Local remote execution flags.
> 
> build:lre --incompatible_enable_cc_toolchain_resolution
> ```

nit: Lets reference ticket:
https://github.com/bazelbuild/bazel/issues/7260
___
*[`.bazelrc` line 61 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV1Nvf5iczFwDJ65R1:-NlV1Nvf5iczFwDJ65R2:bdlrpkz) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/.bazelrc#L61)):*
> ```
> 
> build:lre --incompatible_enable_cc_toolchain_resolution
> build:lre --define=EXECUTOR=remote
> ```

Lets reference this ticket:
https://github.com/bazelbuild/bazel/issues/7254
___
*[`.bazelrc` line 62 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV24kUALlStX0fOTeK:-NlV24kUALlStX0fOTeL:b-hmhi9i) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/.bazelrc#L62)):*
> ```
> build:lre --incompatible_enable_cc_toolchain_resolution
> build:lre --define=EXECUTOR=remote
> build:lre --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
> ```

nit: Maybe use `--repo_env` instead?

Also maybe reference:
https://github.com/bazelbuild/bazel/issues/19714#issuecomment-1745604978
___
*[`local-remote-execution/README.md` line 21 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV3HKx8phFq82Zc3FV:-NlV3HKx8phFq82Zc3FW:bjjfo70) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/README.md#L21)):*
> ```Markdown
> 
> First, create an OCI image containing with the toolchains. Make sure to run this
> command *not* from within this directory, but from the root of the nativelink
> ```

nit: Lets just say:
```
Make sure you run this command from the WORKSPACE root (project root).
```

The way it's currently worded is kinda weird due to the use of "not" (negative word).
___
*[`local-remote-execution/README.md` line 41 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV4UVB7TxoHcvxjg79:-NlV4UVB7TxoHcvxjg7A:b-m5426r) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/README.md#L41)):*
> ```Markdown
> ```
> 
> If you have the remote execution container deployed as a remote executor you can
> ```

nit: 
`as a remote executor` -> `as a worker`

maybe?
___
*[`local-remote-execution/README.md` line 42 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV4_aL2EKc-fwS2q36:-NlV4_aL2EKc-fwS2q37:bacbrfb) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/README.md#L42)):*
> ```Markdown
> 
> If you have the remote execution container deployed as a remote executor you can
> use switch to remote execution. For instance when using the [Kubernetes
> ```

nit: remove `use`
___
*[`local-remote-execution/rbe_configs_gen_skip_pull.diff` line 9 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV4vn03kaGZZzVZhSA:-NlV4vn03kaGZZzVZhSB:bb1gpp1) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/rbe_configs_gen_skip_pull.diff#L9)):*
> ```Diff
>  		dockerPath:     "docker",
>  	}
> -	if _, err := runCmd(d.dockerPath, "pull", d.containerImage); err != nil {
> ```

Is there an upstream bug for this, if so, can we add it as a commit message to this diff?
___
*[`local-remote-execution/examples/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV52rd6F4zO4N9oZiL:-NlV52rd6F4zO4N9oZiM:b-qajkof) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/examples/BUILD.bazel#L6)):*
> ```Starlark
>     name = "hello_lre",
>     srcs = ["hello.cpp"],
>     # Enable verbose logging just for this target
> ```

nit: end in period.
___
*[`local-remote-execution/generated/LICENSE` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV5CSP2tzysEGkJlBw:-NlV5CSP2tzysEGkJlBx:b1htlku) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/generated/LICENSE#L1)):*
> ```
> 
> ```

nit: Is this required? I don't think we need to ship the apache license if we are bundling it with our own code. In this case anyway we are also Apache2 licensed, so it shouldn't be an issue.
___
*[`local-remote-execution/generated/cc/cc_wrapper.sh` line 25 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV5a8dBq4jezKGsVzB:-NlV5a8dBq4jezKGsVzC:bvdpyk2) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/generated/cc/cc_wrapper.sh#L25)):*
> ```Shell
> 
> # Call the C++ compiler
> /nix/store/51cw7fa986m44q5rw0rxvl0pbskhccw8-customClang/bin/customClang "$@"
> ```

nit: remove `set -eu` and prefix this with `exec`. This will cause the command to "assume control" of the process reducing a `fork` call and one less process for the system to manage.

But if this is generated meh.

**Comment by MarcusSorealheis** [comment]
once the above comments are addressed, I will doin a pass.

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: 20 of 25 files reviewed, 7 unresolved discussions (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`.bazelrc` line 61 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV1Nvf5iczFwDJ65R1:-NlVPCiIDjPk34vLiIwC:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/.bazelrc#L61)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Lets reference this ticket:
https://github.com/bazelbuild/bazel/issues/7254
</blockquote></details>

Done.
___
*[`local-remote-execution/rbe_configs_gen_skip_pull.diff` line 9 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV4vn03kaGZZzVZhSA:-NlVECh0DToh8r9_7n8q:b-satwsv) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/rbe_configs_gen_skip_pull.diff#L9)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Is there an upstream bug for this, if so, can we add it as a commit message to this diff?
</blockquote></details>

This is not a bug. We're disabling this because it lets us directly load the image into the docker-daemon instead of pulling it from an intermediary container registry. Skipping this hash is not a generally safe practice and only works here because our images are reproducible.

I plan to rewrite the entire rbe_configs_gen tool. In our case it's technically not necessary to use images at all and if we do want to generate toolchains from images we  can use more modern/performant tools under the hood.
___
*[`local-remote-execution/generated/LICENSE` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV5CSP2tzysEGkJlBw:-NlVDY4EEWZRj0w7a1cq:bqjznmr) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/generated/LICENSE#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Is this required? I don't think we need to ship the apache license if we are bundling it with our own code. In this case anyway we are also Apache2 licensed, so it shouldn't be an issue.
</blockquote></details>

Generated. I plan to rewrite the `rbe_configs_gen` tool entirely. Until then let's keep this around just to be sure. It should be safe to remove this again later on.
___
*[`local-remote-execution/generated/cc/BUILD` line 95 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUtfCY-7yoh3xuzq3F:-NlVCrYn3H_8iMYEU-E4:bxt3dyc) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L95)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Are these hashes stable across machines?
</blockquote></details>

Yes. This is the reason why LRE works. Since these packages are reprocudible in nix, this will have the same hash on every `x86_64-linux` system. This also acts as an important safeguard mechanism: If for whatever reason we can't reproduce this hash on a machins the toolchain will hard-error instead of using a potentiall not binary-identical tool that happens to live in e.g. `/usr/bin`.
___
*[`local-remote-execution/generated/cc/BUILD` line 113 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUtpH77v3a2DzmgmtB:-NlVAYbb9DKVxZdVfZAK:b-tjbl3s) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L113)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Been awhile for me in regards to native linking, what is the general rule of thumb on ordering of libcxx/libcxxabi/libunwind/glibc?
</blockquote></details>

Generally linking order should roughly reflect how "low level" a library is. So it would make sense to link libcxx before libcxxabi. It can get more tricky with less standard compilations like CUDA, HIP and OpenCL, and also when using sanitizers. But here it most likely doesn't matter. I'd be surprised if these libraries shared any symbols.

Glibc is usually linked last as it's the lowest level library.
___
*[`local-remote-execution/generated/cc/BUILD` line 149 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUuZu47CsAd-O7wO_j:-NlVA4-oBbpz421l1wbr:b-ysghq9) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L149)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Why `redacted` and does this get defined later in the pipeline?
</blockquote></details>

These flags are generated. Every `cc_toolchain_config` should set this to prevent dates timestamps from leaking into the build and making it irreproducible. This will automatically be added to all `cc_*` build compiler invocations.
___
*[`local-remote-execution/generated/cc/cc_wrapper.sh` line 25 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV5a8dBq4jezKGsVzB:-NlV9zrO9PmCDNb7mMOj:beh4dpg) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/generated/cc/cc_wrapper.sh#L25)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: remove `set -eu` and prefix this with `exec`. This will cause the command to "assume control" of the process reducing a `fork` call and one less process for the system to manage.

But if this is generated meh.
</blockquote></details>

Generated.

**Review by adam-singer — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: 24 of 25 files reviewed, 5 unresolved discussions (waiting on @aaronmondal, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`local-remote-execution/generated/cc/BUILD` line 149 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlUuZu47CsAd-O7wO_j:-NlVZf9MBpPByZ9-88u9:bjnnx2b) ([raw file](https://github.com/TraceMachina/nativelink/blob/1ed81bb3e673758938d3af1e64596f2dedb46586/local-remote-execution/generated/cc/BUILD#L149)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

These flags are generated. Every `cc_toolchain_config` should set this to prevent dates timestamps from leaking into the build and making it irreproducible. This will automatically be added to all `cc_*` build compiler invocations.
</blockquote></details>

Makes sense. Was going to ask if "redacted" is commonly used as a value name, seems so https://github.com/search?q=-D__DATE__%3D%5C%22redacted%5C%22&type=code&p=1 
___
*[`tools/generate-toolchains.nix` line 15 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlVdEG_AnHx3ynZmg6b:-NlVdEGa1GZ_1ynRGlRE:b-7yrrs0) ([raw file](https://github.com/TraceMachina/nativelink/blob/6133196deb463d2a8dcc210e5df7e3c7115416b4/tools/generate-toolchains.nix#L15)):*
> ```Nix
>   set -xeuo pipefail
> 
>   cd $(git rev-parse --show-toplevel)
> ```

Capture as a bash variable and reuse?

```
SRC_ROOT=$(git rev-parse --show-toplevel)
cd "${SRC_ROOT}"
[...]
--output_src_root=${SRC_ROOT}
```

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: 24 of 25 files reviewed, 7 unresolved discussions (waiting on @aaronmondal, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`local-remote-execution/README.md` line 3 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlVgM646uIyu7zK83pe:-NlVgM646uIyu7zK83pf:b-1dt4f5) ([raw file](https://github.com/TraceMachina/nativelink/blob/6133196deb463d2a8dcc210e5df7e3c7115416b4/local-remote-execution/README.md#L3)):*
> ```Markdown
> # Local Remote Execution
> 
> This provides rapidly upgradeable framework to construct and iterate on custom
> ```

This line is repeating the same information in the next line, maybe a copy error? 
___
*[`local-remote-execution/examples/BUILD.bazel` line 6 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlVhJvc5V9lk3gBusW7:-NlVhJvc5V9lk3gBusW8:b-jns9b0) ([raw file](https://github.com/TraceMachina/nativelink/blob/6133196deb463d2a8dcc210e5df7e3c7115416b4/local-remote-execution/examples/BUILD.bazel#L6)):*
> ```Starlark
>     name = "hello_lre",
>     srcs = ["hello.cpp"],
>     # Enable verbose logging just for this target.
> ```

Probably can remove this comment, seem low value

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: 20 of 25 files reviewed, 4 unresolved discussions (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`tools/generate-toolchains.nix` line 15 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlVdEG_AnHx3ynZmg6b:-NlW3UlZ8-6-zVaNjhJ7:bpd0ifa) ([raw file](https://github.com/TraceMachina/nativelink/blob/6133196deb463d2a8dcc210e5df7e3c7115416b4/tools/generate-toolchains.nix#L15)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Capture as a bash variable and reuse?

```
SRC_ROOT=$(git rev-parse --show-toplevel)
cd "${SRC_ROOT}"
[...]
--output_src_root=${SRC_ROOT}
```
</blockquote></details>

Oh yeah that's much better. Note that nix syntax requires the `${` to be escaped as `''${` and `${something}` is shorthand for "nix eval something".

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: 21 of 25 files reviewed, 2 unresolved discussions (waiting on @aaronmondal, @adam-singer, @blakehatch, and @MarcusSorealheis)

___
*[`local-remote-execution/rbe_configs_gen_skip_pull.diff` line 9 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV4vn03kaGZZzVZhSA:-NlWNvAg4dWYIcKP4VZt:b-onkiqo) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/rbe_configs_gen_skip_pull.diff#L9)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This is not a bug. We're disabling this because it lets us directly load the image into the docker-daemon instead of pulling it from an intermediary container registry. Skipping this hash is not a generally safe practice and only works here because our images are reproducible.

I plan to rewrite the entire rbe_configs_gen tool. In our case it's technically not necessary to use images at all and if we do want to generate toolchains from images we  can use more modern/performant tools under the hood.
</blockquote></details>

Can we write this as a commit message on this diff?

**Review by allada — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471#-:-NlWOARgA6Sbd7vUAghh:bnfp4nl)* status: 21 of 25 files reviewed, 2 unresolved discussions (waiting on @aaronmondal, @adam-singer, @blakehatch, and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: 20 of 25 files reviewed, 1 unresolved discussion (waiting on @adam-singer, @allada, @blakehatch, and @MarcusSorealheis)

___
*[`local-remote-execution/rbe_configs_gen_skip_pull.diff` line 9 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/471#-NlV4vn03kaGZZzVZhSA:-NlYUc0b39rhI3AcKQ9j:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/22b5cd86c14d04a3b431189befa0eaf960d8377d/local-remote-execution/rbe_configs_gen_skip_pull.diff#L9)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Can we write this as a commit message on this diff?
</blockquote></details>

Done.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471#-:-NlZBi0D2XlUCSwKBfv4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @allada, @blakehatch, and @MarcusSorealheis)

**Review by adam-singer — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: all files reviewed, 1 unresolved discussion (waiting on @allada, @blakehatch, and @MarcusSorealheis)

**Review by adam-singer — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/471)* status: all files reviewed, 1 unresolved discussion (waiting on @allada, @blakehatch, and @MarcusSorealheis)

**Pull request merged**
