### PR TITLE
Add documentation and machine type variables for gcp.

### PR DESCRIPTION
**Pull request by adam-singer**
# Description

* Add basic documentation on using gcp terraform scripts, not comprehensive (atm) but enough to get started.
* Changed default machine type for scheduler and turned all machine types as variable parameters. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

`terraform validate` && `terraform plan`

## Checklist

- [x] Updated documentation if needed
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/457)

### CODE REVIEW

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/457)* status: all files reviewed, 10 unresolved discussions (waiting on @adam-singer)

___
*[`deployment-examples/terraform/GCP/README.md` line 30 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95FCqErn2GWu2Aj3s:-Nl95FCqErn2GWu2Aj3t:bb6vyz7) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L30)):*
> ```Markdown
> 
> After this is applied goto the
> [Cloud DNS settings](https://console.cloud.google.com/net-services/dns/zones),
> ```

Instead we should give a `gcloud` command to get these or a terraform command to get these values. I think it'd be easier to follow.
___
*[`deployment-examples/terraform/GCP/README.md` line 48 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95Tdw6XS03h6D14sI:-Nl95Tdw6XS03h6D14sJ:b-d8sd4w) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L48)):*
> ```Markdown
> REGION=us-central1
> ZONE=us-central1-a
> PREFIX=exdev
> ```

nit: I'd remove this, they don't need to know this by default.
___
*[`deployment-examples/terraform/GCP/README.md` line 72 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95l1E-KU1cBzquFJH:-Nl95l1E-KU1cBzquFJI:bqxo952) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L72)):*
> ```Markdown
> ```sh
> PROJECT_ID=example-sandbox
> REGION=us-central1
> ```

hmmm, I think we can now extract the `zone` and `region` values from the `global` config. Might be worth doing before publishing these docs?
___
*[`deployment-examples/terraform/GCP/README.md` line 74 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95xshDz4-JRsRXfH4:-Nl95xshDz4-JRsRXfH5:b-iipjm8) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L74)):*
> ```Markdown
> REGION=us-central1
> ZONE=us-central1-a
> PREFIX=exdev
> ```

nit: ditto
___
*[`deployment-examples/terraform/GCP/README.md` line 85 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl961kU4ao7AcHIe2JT:-Nl961kU4ao7AcHIe2JU:b-8ab0xv) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L85)):*
> ```Markdown
> 
> A complete and successful deployment should be able to run remote execution
> commands from bazel (or other supported build systems).
> ```

should also say something like:
```
... after a few mins for the DNS records and load balancers to pickup the new resources (usually <10 mins)
```
___
*[`deployment-examples/terraform/GCP/README.md` line 105 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl96Rev26HlRSDGGkuq:-Nl96Rev26HlRSDGGkur:b-uiri3g) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L105)):*
> ```Markdown
> SERVICE_ACCOUNT=123-compute@developer.gserviceaccount.com
> OS_IMAGE=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20231201
> DISK=projects/example-sandbox/zones/us-central1-a/diskTypes/pd-standard
> ```

nit:
```
DISK=projects/example-sandbox/zones/$ZONE/diskTypes/pd-standard
```
___
*[`deployment-examples/terraform/GCP/README.md` line 142 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl96ssWBTAlfsY1zIt6:-Nl96ssWBTAlfsY1zIt7:b-eb92ye) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L142)):*
> ```Markdown
> 
> DNS_ZONE=example-sandbox.example.com
> CAS="cas.${DNS_ZONE}"
> ```

nit: Variable never set.
___
*[`deployment-examples/terraform/GCP/README.md` line 143 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl96w634iTPD6aBzQ9C:-Nl96w634iTPD6aBzQ9D:b-5v3gaq) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L143)):*
> ```Markdown
> DNS_ZONE=example-sandbox.example.com
> CAS="cas.${DNS_ZONE}"
> EXECUTOR="scheduler.${DNS_ZONE}"
> ```

nit: ditto.
___
*[`deployment-examples/terraform/GCP/README.md` line 168 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl9759fBOGs-m_XfEO0:-Nl9759fBOGs-m_XfEO1:bjdcvml) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L168)):*
> ```Markdown
> (or any other cloned project).
> 
> ## Notes
> ```

nit: lets remove this section.
___
*[`deployment-examples/terraform/GCP/README.md` line 182 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl97Epr3Xj_Pu0Vb5Ah:-Nl97Epr3Xj_Pu0Vb5Ai:b-geugd7) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L182)):*
> ```Markdown
> 
> If things need to be torn down due to misconfiguration or fumbles, leveraging
> the `project_prefix` will allow scoping of the resource names in such a way
> ```

`project_prefix` is also used so users can launch multiple deployments in the same project. (like two devs working at the same time).

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/457)* status: all files reviewed, 10 unresolved discussions (waiting on @allada)

___
*[`deployment-examples/terraform/GCP/README.md` line 30 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95FCqErn2GWu2Aj3s:-NlAJO6J5H7J00RP5ii1:bioqeox) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L30)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Instead we should give a `gcloud` command to get these or a terraform command to get these values. I think it'd be easier to follow.
</blockquote></details>

We could do either commands, going to go with the last terrraform example since its less verbose but not super scriptable. Oddly enough `state show` doesn't serialize into json. 

```sh
# Print name servers with gcloud
gcloud dns record-sets describe $DNS_ZONE --type=NS --zone=${$PREFIX}-dns-zone

# Print name servers with terraform
terraform show -json | jq '.values.root_module.child_modules[].resources[] | select(.address=="module.native_link.data.google_dns_managed_zone.dns_zone") | .values.name_servers'

terraform state show module.native_link.data.google_dns_managed_zone.dns_zone
```
___
*[`deployment-examples/terraform/GCP/README.md` line 72 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95l1E-KU1cBzquFJH:-NlAOFUo4eygZrfujoGu:bowjdfu) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L72)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

hmmm, I think we can now extract the `zone` and `region` values from the `global` config. Might be worth doing before publishing these docs?
</blockquote></details>

I'd need to read some more docs on terraform, mostly just followed what existed, `variables.tf` defined in module, global and dev, all defining the same information. I would assume we could DRY those up a bit. If we remove the mention of zone and region I would be comfortable doing that on a second pr, terraform is still new to me. 

I'd also like to remove the gcloud command that explains launching a "workspace" as it feels bit one off, replace it with a different terraform plan. 
___
*[`deployment-examples/terraform/GCP/README.md` line 142 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl96ssWBTAlfsY1zIt6:-NlALCYG2RP62nsaL22U:bp2hv6n) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L142)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Variable never set.
</blockquote></details>

Not sure what you mean, it is set in the line above

```sh
$ DNS_ZONE=example-sandbox.example.com
$ CAS="cas.${DNS_ZONE}"
$ EXECUTOR="scheduler.${DNS_ZONE}"
$ echo $CAS $EXECUTOR
cas.example-sandbox.example.com scheduler.example-sandbox.example.com
```
___
*[`deployment-examples/terraform/GCP/README.md` line 182 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl97Epr3Xj_Pu0Vb5Ah:-NlAKBDu85CE9ZQ_nrQv:bqn7opz) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L182)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

`project_prefix` is also used so users can launch multiple deployments in the same project. (like two devs working at the same time).
</blockquote></details>

This is a good point, I'd like to lift that reasoning higher up. I didn't want to explicitly document all parameters or at least not yet in a readme. Might reconsider to get started quickly it can be some overhead to parse terraform scripts directly.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/native-link/457)* status: 6 of 10 files reviewed, 2 unresolved discussions

___
*[`deployment-examples/terraform/GCP/README.md` line 48 at r1](https://reviewable.io/reviews/TraceMachina/native-link/457#-Nl95Tdw6XS03h6D14sI:-NlAj9-XB1u9EzxY_Q_F:bfyb44y) ([raw file](https://github.com/TraceMachina/native-link/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L48)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Most of these are no longer needed.

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/457)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @allada)

___
*[`deployment-examples/terraform/GCP/README.md` line 48 at r1](https://reviewable.io/reviews/tracemachina/nativelink/457#-Nl95Tdw6XS03h6D14sI:-NlOrixQEaOJ8wbaqz_3:b-896fix) ([raw file](https://github.com/tracemachina/nativelink/blob/abee88ff96fdab44b94ab7cad9fbf24e4f23928f/deployment-examples/terraform/GCP/README.md#L48)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: Most of these are no longer needed.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/457#-:-NlWPeG46flEWXVhrUER:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @adam-singer)

**Review by allada — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adam-singer)

**Review by adam-singer — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tracemachina/nativelink/457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @adam-singer)

**Pull request merged**
