### PR TITLE
Move installation instructions to new docs

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1127)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@blakehatch +@MarcusSorealheis +@bclark8923 cc @krishmoran

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1127#-:-O1Oq6Q66LcJqHL7ktc1:babyys0)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @bclark8923, @blakehatch, and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
Preview in this PR: https://github.com/aaronmondal/nativelink/pull/41

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1127#-:-O1OqZkO-Ori7M-r8HeE:b-q8mfa6)* status: 0 of 3 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @bclark8923, @blakehatch, and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
@MarcusSorealheis I fixed the broken contributing link. The one in the top-level readme should be fine as soon as it's merged. It needs to be a full URL so that it works both in the GitHub README and in the setup section in the docs.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1127#-:-O1PT2nK1TLGnhfeXYHV:b-w760w4)* status: 0 of 3 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @bclark8923, @blakehatch, and @MarcusSorealheis)

**Review by blakehatch — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1127#-:-O1Q6L2M28vqgl_vNVZl:bnfp4nl)* status: 1 of 3 LGTMs obtained (waiting on @bclark8923 and @MarcusSorealheis)

**Review by aaronmondal — COMMENTED** [review]
-@MarcusSorealheis -@bclark8923 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1127#-:-O1QcUFG03fDLU5lr_0g:bsej6xk)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
