### PR TITLE
Fix semver image workflow after 646253d

### PR DESCRIPTION
**Pull request by aaronmondal**
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/844)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@MarcusSorealheis +@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/844#-:-Nv4SsOS7htb48falNgX:bqshewl)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer, @blakehatch, and @MarcusSorealheis)

**Review by MarcusSorealheis — COMMENTED** [review]
I’m assuming lre-cc is fine for an image. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/844#-:-Nv4ZT_S-wqzYwNojPlW:bpmwjvo)* status: 0 of 3 LGTMs obtained (waiting on @adam-singer and @blakehatch)

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/844#-:-Nv4ZbEB8XnNfrQiCbVi:bnfp4nl)* status: 1 of 3 LGTMs obtained (waiting on @adam-singer and @blakehatch)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/844#-:-Nv5LtXU4i67AOhZu3dG:bnfp4nl)* status: 2 of 3 LGTMs obtained (waiting on @blakehatch)

**Review by blakehatch — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/844#-:-Nv5d2PDEyT5pqg0tYJt:bg7igkv)* status: <span>:shipit:</span> complete! 3 of 3 LGTMs obtained

**Pull request merged**
