### PR TITLE
Digest function now auto-detected from request

### PR DESCRIPTION
**Pull request by allada**
The digest function the client requested is now properly implemented
in the OriginContext. This allows us to inspect what digest-function
the client requested from anywhere in the code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@adam-singer 

This is dependent on the previous PR landing first.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899#-:-NxBEy7g0T9cVXSEuAFl:bc3w3nb)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer)

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899#-:-NxE1v4kA4LtWsZF9D7O:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by allada — COMMENTED** [review]
I think this is the final form.

Local testing shows it working, but still need more larger testing.

I can break this into 1 maybe 2 PRs if you prefer, but most of this is related.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899#-:-NxJtWHE2JGpKkxgv2KB:bd0r1mr)* status: 1 of 1 LGTMs obtained, and pending CI: Vercel, pre-commit-checks

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 34 of 34 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899#-:-NxLS5Fa1jiWd2seKcvI:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/tests/cache_lookup_scheduler_test.rs` line 119 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/899#-NxKSD6_-enALLXMhxD6:-NxKSD6_-enALLXMhxD7:bvtwyar) ([raw file](https://github.com/TraceMachina/nativelink/blob/01a86dd98a8fca114ed4538b909f969f34ab31ad/nativelink-scheduler/tests/cache_lookup_scheduler_test.rs#L119)):*
> ```XML
>         let action_name = ActionInfoHashKey {
>             instance_name: "instance".to_string(),
>             digest_function: DigestHasherFunc::Sha256.proto_digest_func().try_into()?,
> ```

Why does this need to do a `try_into` when the other passed ones in `action_messages_test.rs` didnt?

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Vercel, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, vale, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/tests/cache_lookup_scheduler_test.rs` line 119 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/899#-NxKSD6_-enALLXMhxD6:-NxO2NG7EXfYrdnViTBV:b-h5pedd) ([raw file](https://github.com/TraceMachina/nativelink/blob/01a86dd98a8fca114ed4538b909f969f34ab31ad/nativelink-scheduler/tests/cache_lookup_scheduler_test.rs#L119)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Why does this need to do a `try_into` when the other passed ones in `action_messages_test.rs` didnt?
</blockquote></details>

Copy pasta failure. Fixed.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899#-:-NxQb7452mUsdvmQEn8a:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, and 1 discussions need to be resolved

___
*[`nativelink-scheduler/tests/property_modifier_scheduler_test.rs` line 251 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/899#-NxQ_1IA5OWBIl1A4Vnd:-NxQ_1IA5OWBIl1A4Vne:b-w0kmc2) ([raw file](https://github.com/TraceMachina/nativelink/blob/c6259b97b52837846f5f12bf1a7667b320be83c1/nativelink-scheduler/tests/property_modifier_scheduler_test.rs#L251)):*
> ```XML
>         let action_name = ActionInfoHashKey {
>             instance_name: "instance".to_string(),
>             digest_function: DigestHasherFunc::Sha256.proto_digest_func().try_into()?,
> ```

nit: `DigestHasherFunc::Sha256.proto_digest_func().try_into()?` -> `DigestHasherFunc::Sha256`

**Review by adam-singer — APPROVED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/899)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04

**Pull request merged**
