### PR TITLE
Document a Breakdown of Configuration

### PR DESCRIPTION
**Pull request by MarcusSorealheis**
# Description

This PR is the beginning of more work to breakdown in a step-by-step fashion how to configure a NativeLink deployment. 

Beginning of addressing #681  

## Type of change

Documentation

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

WIP

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680)

### CODE REVIEW

**Comment by MarcusSorealheis** [comment]
cc @Ely-S and @allada and @blakehatch 

more coming.

**Review by adam-singer — COMMENTED** [review]
I like the step wise approach, adding small component visuals might help reader scan document quicker and go back for details, ofc when ready for that 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680#-:-Nraae9nAzqtYGR5zXrh:b19vd8x)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, pre-commit-checks

___
*[`nativelink-config/examples/example-nl-config.md` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrm_YME0Ihr48Eqt3rV:-Nrm_YME0Ihr48Eqt3rW:b-ty3yyz) ([raw file](https://github.com/TraceMachina/nativelink/blob/c81582819fe49a20eb7c483c7b09143b56e124c5/nativelink-config/examples/example-nl-config.md#L1)):*
> ```Markdown
> NativeLink uses a JSON file as the configuration format. This section of the
> ```

Shouldn't this be named `Readme.md`?
___
*[`nativelink-config/examples/example-nl-config.md` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrm_k6VCfcn99tkgzZG:-Nrm_k6VCfcn99tkgzZH:b-1r0gvg) ([raw file](https://github.com/TraceMachina/nativelink/blob/c81582819fe49a20eb7c483c7b09143b56e124c5/nativelink-config/examples/example-nl-config.md#L27)):*
> ```Markdown
> ### Store Name
> 
> The value of `stores` includes top-level keys, which are the names of stores. The following example, defines the `AC_MAIN_STORE`.
> ```

nit: "user supplied names of stores"
___
*[`nativelink-config/examples/example-nl-config.md` line 44 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrm_zRP8skwL-M3nCyR:-Nrm_zRP8skwL-M3nCyS:b-4sg16y) ([raw file](https://github.com/TraceMachina/nativelink/blob/c81582819fe49a20eb7c483c7b09143b56e124c5/nativelink-config/examples/example-nl-config.md#L44)):*
> ```Markdown
> 
> Once the store has been named and its object exists,
> the next key is the type of store. The options are `filesystem`, `memory`, `compression`, `dedup`, `fast_slow`, `verify`, and `experimental_s3_store`.
> ```

I'm not sure if we should do this. This will make our documentation out of date really fast if we name them here.

I think what we should do instead is write a new readme for each store. Alternatively we should auto-gen the readme based on the rustdocs.

In fact this entire readme could probably be generated from our rust doc and published to [docs.rs](https://docs.rs/).

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), integration-tests (20.04), pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

___
*[`nativelink-config/examples/example-nl-config.md` line 1 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrm_YME0Ihr48Eqt3rV:-NroDsr94zNJrUZ_tN9V:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/c81582819fe49a20eb7c483c7b09143b56e124c5/nativelink-config/examples/example-nl-config.md#L1)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

Shouldn't this be named `Readme.md`?
</blockquote></details>

Done.
___
*[`nativelink-config/examples/example-nl-config.md` line 44 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrm_zRP8skwL-M3nCyR:-NroDtr235h-qnPp6PZs:bn6d8ey) ([raw file](https://github.com/TraceMachina/nativelink/blob/c81582819fe49a20eb7c483c7b09143b56e124c5/nativelink-config/examples/example-nl-config.md#L44)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I'm not sure if we should do this. This will make our documentation out of date really fast if we name them here.

I think what we should do instead is write a new readme for each store. Alternatively we should auto-gen the readme based on the rustdocs.

In fact this entire readme could probably be generated from our rust doc and published to [docs.rs](https://docs.rs/).
</blockquote></details>

My feeling is that this is almost a tutorial. It will go away or become outdated like our existing docs. The goal is to move the ball forward at all.

**Comment by aaronmondal** [comment]
FYI the linter errors are visible when you look at the file on github: https://github.com/TraceMachina/nativelink/pull/680/files

**Comment by blakehatch** [comment]
I was able to figure out how to surface this README in the rustdoc so that the example breakdown and the overview of configuration can be easily accessed on the first page of the rust doc. Would then be super easy to share with a link to [docs.rs](https://docs.rs/) for the config section.

Put up a separate issue for setting up generating this file but I think this is fine for now.

Going to also put up a PR that conveniently surfaces the existing docs for the stores and config using the existing documentation in the code so it doesn't have to be combed through. Would be helpful if this gets landed first so I can point to it for this one.

**Review by allada — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, pre-commit-checks

___
*[`nativelink-config/examples/README.md` line 123 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-NrvZcQpBhs4-jK8mtx2:-NrvZcQpBhs4-jK8mtx3:b-e9tybe) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L123)):*
> ```Markdown
>       },
>       "work_directory": "/tmp/nativelink/work",
>       "platform_properties": {
> ```

We are not explaining these at all. I feel this is quite important to get right and explain.
___
*[`nativelink-config/examples/README.md` line 158 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-NrvZkkUB1PRFEid6Zpf:-NrvZkkUB1PRFEid6Zpg:bwia2cg) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L158)):*
> ```Markdown
>   ### Scheduler Name
> 
> The value of `schedulers` includes top-level keys, which are the names of stores. The following example, defines the `MAIN_SCHEDULER`.
> ```

nit: We should make it more clear that `MAIN_SCHEDULER` is user defined and has no special meaning other than a unique name.
___
*[`nativelink-config/examples/README.md` line 201 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-NrvZwka1uC9lnX9Y1Cc:-NrvZwka1uC9lnX9Y1Cd:bn9atwj) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L201)):*
> ```Markdown
>       "simple": {
>         "supported_platform_properties": {
>           "cpu_count": "minimum",
> ```

ditto. We also need to explain what `minimum`, `exact` and `priority` are and when each should be used.
___
*[`nativelink-config/examples/README.md` line 268 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrv_APu5u4nkYZ8n1tw:-Nrv_APu5u4nkYZ8n1tx:b-lt8xib) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L268)):*
> ```Markdown
>       "cas": {
>         "main": {
>           "cas_store": "WORKER_FAST_SLOW_STORE"
> ```

We should also explicitly state that these store names must be defined in the `stores` mapping.
___
*[`nativelink-config/examples/README.md` line 302 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrv_KvG9FN0HjMaAIER:-Nrv_KvG9FN0HjMaAIES:b-w9vmxo) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L302)):*
> ```Markdown
> ```
> 
>  ### Private Server
> ```

This is weird. This is not a requirement of nativelink. It's a best practice. It has the exact same mapping and layout as the public one, but for security reasons these apis should only be available to trusted sources.

**Review by MarcusSorealheis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, pre-commit-checks

___
*[`nativelink-config/examples/README.md` line 158 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-NrvZkkUB1PRFEid6Zpf:-Ns1L2fY2PEgnJlFScPI:b90xbz6) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L158)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

nit: We should make it more clear that `MAIN_SCHEDULER` is user defined and has no special meaning other than a unique name.
</blockquote></details>

I agree however, we should have defaults and keys/labels that identify what it is followed by another key for encapsulating configuration values.  a common pattern is:

```json
{
  "scheduler_name": "MAIN_SCHEDULER",
  "configuration_data": { <currently the value of the dynamic MAIN_SCHEDULER key>} 
}
```

There are many many reasons why you want to have consistent key vs a dynamic one, but we are not at the phase to fight that. It's just a placeholder for now. 
___
*[`nativelink-config/examples/README.md` line 201 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-NrvZwka1uC9lnX9Y1Cc:-Ns1Lyh35KP59I7j2yV0:b4n6xhg) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L201)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

ditto. We also need to explain what `minimum`, `exact` and `priority` are and when each should be used.
</blockquote></details>

Agreed. Should I add a TODO. This can be a subsequent PR and can go in the documentation site, which I can do today.
___
*[`nativelink-config/examples/README.md` line 268 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrv_APu5u4nkYZ8n1tw:-Ns1M4iX7FlH-2TbDoAm:b-2hx0so) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L268)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

We should also explicitly state that these store names must be defined in the `stores` mapping.
</blockquote></details>

This page does not accomplish all of the documentation needs. It is only a step forward again.
___
*[`nativelink-config/examples/README.md` line 302 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrv_KvG9FN0HjMaAIER:-Ns1MAKKD0Mf0cIfX1ug:b-uz5jl5) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L302)):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

This is weird. This is not a requirement of nativelink. It's a best practice. It has the exact same mapping and layout as the public one, but for security reasons these apis should only be available to trusted sources.
</blockquote></details>

I can change it to specify that it is not a requirement for NativeLink, but again this is an example and its a best practice for security so I think we should keep it for now.

**Review by allada — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680)* status: 0 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`nativelink-config/examples/README.md` line 201 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-NrvZwka1uC9lnX9Y1Cc:-Ns1yZH46gHEubAC7ZwB:b71hpis) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L201)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

Agreed. Should I add a TODO. This can be a subsequent PR and can go in the documentation site, which I can do today.
</blockquote></details>

Either is fine.
___
*[`nativelink-config/examples/README.md` line 302 at r3](https://reviewable.io/reviews/TraceMachina/nativelink/680#-Nrv_KvG9FN0HjMaAIER:-Ns1yjbC2oHi3Y6Z3t6B:bpbhcul) ([raw file](https://github.com/TraceMachina/nativelink/blob/824ae18d6669a733bd1ddd8922257703fa5fbf92/nativelink-config/examples/README.md#L302)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

I can change it to specify that it is not a requirement for NativeLink, but again this is an example and its a best practice for security so I think we should keep it for now.
</blockquote></details>

I'd rather just call it out. I don't like the idea of saying "you must use a private server". This especially matters in the event a user only uses the CAS without remote execution, because there'd be no reason to setup a private server.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/680#-:-NsAsvpOBpqKSrbmW6hN:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), integration-tests (20.04), macos-13, pre-commit-checks, publish-image, ubuntu-20.04 / stable, ubuntu-22.04, vale

**Pull request merged**
