### PR TITLE
Migrate to Bazelisk

### PR DESCRIPTION
**Pull request by aaronmondal**
This commit changes the Nix-side Bazel setup to Bazelisk which decouples the Bazel version from what's available in the nix store.

This lets us more freely increment Bazel versions while still providing the correct versions automatically.

A nice side effect of this is that we can finally remove the WORKSPACE file.

This change has no effect on the Bazel versions that NativeLink supports as clients. This is purely an internal build dependency change.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@allada +@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912#-:-Nxn8NS63eGhy90x1v2_:b4y6pzi)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @adam-singer, @allada, and @blakehatch)

**Review by blakehatch — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912#-:-Nxn9smt7qs7a7iVa76Y:bg7igkv)* status: 1 of 3 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer and @allada)

**Review by MarcusSorealheis — COMMENTED** [review]
This is absolutely not something we should rush. We should consider compatibility?  It we must also consider our customers. Maybe you can prepare a blog breakdown of everything that changes in 8. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912#-:-NxnhMAe6KsRlj9I-FFX:b-y5338w)* status: 1 of 3 LGTMs obtained, and pending CI: Cargo Dev / macos-13, macos-13 (waiting on @adam-singer and @allada)

**Review by adam-singer — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912)* status: 1 of 3 LGTMs obtained, and pending CI: macos-13, and 1 discussions need to be resolved (waiting on @allada)

___
*[`.bazelversion` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/912#-NxoCupt7Dttct7jMmZa:-NxoCupt7Dttct7jMmZb:b94gd3s) ([raw file](https://github.com/TraceMachina/nativelink/blob/074c82f3af6f37b12c93b68895938f45c1486d1a/.bazelversion#L1)):*
> ```
> 8.0.0-pre.20240422.4
> ```

tbh, I don't think we should depend on any `pre` tag of bazel unless we get something major from it that we are blocked on.

**Comment by MarcusSorealheis** [comment]
Please make this a draft PR.

**Review by aaronmondal — COMMENTED** [review]
@MarcusSorealheis Technically, this isn't too big of a change, as we haven't used the workspace logic for a long time and IIRC Bazel 8 just flips it off by default. Compatibility-wise it wouldn't have any effect since our production builds are using Nix/Cargo. We only use Bazel as a convenient way to get incremental builds during development, i.e. we can consider it a `devtool` dependency.

That said, the thing I'm after with this commit works with Bazel 7 as well (removing the obsolete empty WORKSPACE file), so I set it to `7.1.2` now.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912#-:-Nxoh1W00hWa0_AcIT8A:b-fls3o6)* status: 1 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, and 1 discussions need to be resolved (waiting on @adam-singer and @allada)

___
*[`.bazelversion` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/912#-NxoCupt7Dttct7jMmZa:-Nxoi_hPAQbSvmtf_gWW:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/074c82f3af6f37b12c93b68895938f45c1486d1a/.bazelversion#L1)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

tbh, I don't think we should depend on any `pre` tag of bazel unless we get something major from it that we are blocked on.
</blockquote></details>

Done.

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912#-:-Nxriayo14BA0wqADEJJ:bnfp4nl)* status: 2 of 3 LGTMs obtained, and 1 discussions need to be resolved (waiting on @adam-singer)

**Review by aaronmondal — COMMENTED** [review]
-@adam-singer 

> Dismissed @adam-singer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/912#-:-NxsMpr35DjqemrZhLAU:b-sd1e3m)* status: <span>:shipit:</span> complete! 2 of 2 LGTMs obtained

**Pull request merged**
