### PR TITLE
deployment-examples: chromium

### PR DESCRIPTION
**Pull request by adam-singer**
# Description

Creating an example of how to build chromium unit tests using nativelink. 

Fixes # (issue)

https://github.com/TraceMachina/nativelink/issues/779

## Type of change

Please delete options that aren't relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please also list any relevant details for your test configuration

## Checklist

- [ ] Updated documentation if needed
- [ ] Tests added/amended
- [ ] `bazel test //...`  passes locally
- [ ] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
Generally LGTM. I think it's fine if this isn't perfect initially. We should probably deduplicate all the unspecific K8s files. Maybe symlinks?

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-NtanYpX0kbnRUTcuUd8:b1juain)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, pre-commit-checks

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtagyLf4gfcNAJb6IZo):*
nit: Looks like this is some residue from rebasing
___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtaiQRz6ZM8NIrKTRhC:-NtaiQRz6ZM8NIrKTRhD:b-k0zntu) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/03_build_chrome_tests.sh#L10)):*
> ```Shell
> fi
> 
> if [ -d "${HOME}/chromium" ]; then
> ```

nit: I'm not sure how compatible this would be, but we might be able to put this into a Dockerfile which is based on Ubuntu, similar to https://github.com/TraceMachina/nativelink/pull/730/files#diff-934dfe8efcc8cf1ba1d5f7f24ff1c0568e34832676fa950de194344f2d2172a7

No strong opinion though.
___
*[`deployment-examples/chromium/README.md` line 1 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtalWT15BfLW98wmbkn:-NtalWT15BfLW98wmbko:b-u53wrm) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/README.md#L1)):*
> ```Markdown
> # Chromium example
> ```

nit: Consider adding a `> [!WARN]` section to clarify that this only works on Ubuntu hosts. There is also some improved documentation at https://github.com/TraceMachina/nativelink/pull/730/files#diff-006f58c2e5cef6ef1bc72e75b151f7c88208e248e1a9a963816390b8fa530e14 that could be helpful as general reference.
___
*[`deployment-examples/chromium/README.md` line 43 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtakI0U66Sx_stBHTfx:-NtakI0V5gT6NcLu9S__:b-eglt1j) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/README.md#L43)):*
> ```Markdown
> ```
> 
> 
> ```

This probably shouldn't be ignored by vale. If there are any words missing from the vocabulary (like "Chromium") you can add it to https://github.com/TraceMachina/nativelink/blob/main/.github/styles/config/vocabularies/TraceMachina/accept.txt. This way we can also make sure that we don't accidentally use the wrong capitalization (not sure whether it's "chromium" or "Chromium").

FYI words in backticks (e.g. `ActionScheduler`) are also ignored by vale, but this tends to be more useful in API docs.
___
*[`deployment-examples/chromium/scheduler.json` line 29 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Ntam7VbDp0ILANUwgei:-Ntam7VbDp0ILANUwgej:bpmj3y4) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/scheduler.json#L29)):*
> ```JSON
>       // TODO(adams): max_bytes_per_stream
>       "simple": {
>         "supported_platform_properties": {
> ```

nit: Do we need all of this? If so, it might make sense to document the importance of this section.
___
*[`deployment-examples/chromium/worker-chromium.json` line 56 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtamJZaANZS9VDbPZTt:-NtamJZaANZS9VDbPZTu:by4tbwv) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/worker-chromium.json#L56)):*
> ```JSON
>       "platform_properties": {
>         "cpu_count": {
>           "values": ["16"],
> ```

nit: Could `nproc` be a better choice? https://github.com/TraceMachina/nativelink/blob/a6976e095403dfd7cf03c554c8ce681af40622e5/deployment-examples/docker-compose/worker.json#L54
___
*[`deployment-examples/chromium/worker-chromium.yaml` line 21 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtamcKf39SJWPgNI1Nd:-NtamcKf39SJWPgNI1Ne:b-aajttb) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/worker-chromium.yaml#L21)):*
> ```YAML
>           env:
>             - name: RUST_LOG
>               value: debug,h2=off,tower=off,hyper=off
> ```

nit: Reminder to double check the log level to whatever we think is best for this example. No strong opinion on the concrete value.
___
*[`deployment-examples/kubernetes/worker-lre-cc.json.template` line 52 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Ntan5uZAoWm9IJE0eIV:-Ntan5uZAoWm9IJE0eIW:b-hrl9sp) ([raw file](https://github.com/TraceMachina/nativelink/blob/a6976e095403dfd7cf03c554c8ce681af40622e5/deployment-examples/kubernetes/worker-lre-cc.json.template#L52)):*
> ```
>         "ac_store": "GRPC_LOCAL_AC_STORE",
>       },
>       "work_directory": "~/.cache/nativelink/work",
> ```

I believe this is a residue from rebasing.
___
*[`deployment-examples/kubernetes/worker-lre-java.json.template` line 28 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtanE4g-M0JZ21vo1M6:-NtanE4h2xjUi9pQJnNZ:b-7ropln) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/kubernetes/worker-lre-java.json.template#L28)):*
> ```
>           "filesystem": {
>             "content_path": "/tmp/.cache/nativelink/data-worker-test/content_path-cas",
>             "temp_path": "/tmp/.cache/nativelink/data-worker-test/tmp_path-cas",
> ```

ditto

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-NtrA84KEqG7vCcmcb3U:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`.github/styles/config/vocabularies/TraceMachina/accept.txt` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Ntr9J9c2O7emXcyaet0:-Ntr9J9c2O7emXcyaet1:b79vx3w) ([raw file](https://github.com/TraceMachina/nativelink/blob/334447527e111952fa2c5ae20fe01d0634afbd90/.github/styles/config/vocabularies/TraceMachina/accept.txt#L27)):*
> ```help
> parsable
> rebase
> [Cc]hromium
> ```

nit: Consider only allowing capitalized "Chromium".
___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtaiQRz6ZM8NIrKTRhC:-Ntr9WSj0HqzOVVmmAZe:b-vt7ptx) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/03_build_chrome_tests.sh#L10)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Same, I don't have a strong opinion. I do wonder if there a penalty for using docker on the client side where lots of files read/write in docker.
</blockquote></details>

Let's leave this as is for now. We can change it later.
___
*[`deployment-examples/chromium/README.md` line 10 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Ntr9dkm0yppLPCmL0fT:-Ntr9dkm0yppLPCmL0fU:bwplizk) ([raw file](https://github.com/TraceMachina/nativelink/blob/334447527e111952fa2c5ae20fe01d0634afbd90/deployment-examples/chromium/README.md#L10)):*
> ```Markdown
> > will check if the image is Ubuntu and fail otherwise.
> ```

nit: One newline

**Review by aaronmondal — APPROVED** [review]
fyi you can exclude the keys from the failing pre-commit checks here: https://github.com/TraceMachina/nativelink/blob/09b32c94d3cc7780816585e9b87f69c56cf931ae/tools/pre-commit-hooks.nix#L45

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-NtrAFRHEpzn-tjkwL8f:bthcfwd)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`.github/styles/config/vocabularies/TraceMachina/accept.txt` line 27 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Ntr9J9c2O7emXcyaet0:-Ntva6vK44WabgSGMHzy:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/334447527e111952fa2c5ae20fe01d0634afbd90/.github/styles/config/vocabularies/TraceMachina/accept.txt#L27)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Consider only allowing capitalized "Chromium".
</blockquote></details>

Done.
___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtaiQRz6ZM8NIrKTRhC:-NtvaGjF-uYzxogPIzxY:blyjgit) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/03_build_chrome_tests.sh#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Let's leave this as is for now. We can change it later.
</blockquote></details>

sgtm, I do have a different patch that does use docker client, we could roll that into this. 
Done.
___
*[`deployment-examples/chromium/README.md` line 10 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Ntr9dkm0yppLPCmL0fT:-NtvafEV4paO3xd28455:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/334447527e111952fa2c5ae20fe01d0634afbd90/deployment-examples/chromium/README.md#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: One newline
</blockquote></details>

Done.

**Review by allada — COMMENTED** [review]
FWIW, I'd rather use symlinks in code bases, as it makes code search more usable and reduces chance of "only changing in once place".

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-Ntxj5jBCrLXG92vm1Na:b-i7u9fy)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by adam-singer — COMMENTED** [review]
Used symlinks

Done.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-Nu08H3l7C79979kDl88:b6lmud8)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved

___
*[`deployment-examples/chromium/worker-chromium.json` line 56 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtamJZaANZS9VDbPZTt:-Nu08FsbCr13s2YQmin8:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/worker-chromium.json#L56)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit: Could `nproc` be a better choice? https://github.com/TraceMachina/nativelink/blob/a6976e095403dfd7cf03c554c8ce681af40622e5/deployment-examples/docker-compose/worker.json#L54
</blockquote></details>

Done.

**Review by adam-singer — COMMENTED** [review]
@aaronmondal @allada using a symlink won't work for all of the script files since there are differences between them, we could parameterize out everything, I think that would be best for a later and muddle this example a bit. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-Nu0NxYo60YH-jtHPJXk:b-92tnb7)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04, and 1 discussions need to be resolved

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks

___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 10 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/786#-NtaiQRz6ZM8NIrKTRhC:-Nu18Rg85_qKbL0BjDrT:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2f820a0e69a2a6e4f8c7c5c8c1a33247f45236dc/deployment-examples/chromium/03_build_chrome_tests.sh#L10)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

sgtm, I do have a different patch that does use docker client, we could roll that into this. 
Done.
</blockquote></details>

Done.

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 38 files at r3, 40 of 40 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-Nu1c-FpCHW7JfjfgFpY:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 1 discussions need to be resolved

___
*[`deployment-examples/chromium/README.md` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Nu1bntU0kmYm771LnDj:-Nu1bntU0kmYm771LnDk:buseua2) ([raw file](https://github.com/TraceMachina/nativelink/blob/13298e7c7c9905a998f38c01ddf91e5d8b8640bc/deployment-examples/chromium/README.md#L10)):*
> ```Markdown
> > will check if the image is Ubuntu and fail otherwise.
> 
> All commands should be run from nix to ensure all dependencies exists in the environment.
> ```

nit  `exsist`

**Review by zbirenbaum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 1 of 1 LGTMs obtained, and pending CI: pre-commit-checks, and 2 discussions need to be resolved

___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Nu6OhSH5cNBSNSSkJxt:-Nu6OhSH5cNBSNSSkJxu:b-shsyx0) ([raw file](https://github.com/TraceMachina/nativelink/blob/13298e7c7c9905a998f38c01ddf91e5d8b8640bc/deployment-examples/chromium/03_build_chrome_tests.sh#L10)):*
> ```Shell
> fi
> 
> if [ -d "${HOME}/chromium" ]; then
> ```

I ran into a problem on this line where the depot tools portion below didn't properly update my path and fetch wasn't found. Logging back in and starting nix again fixed the path issue, but then it assumed that the chromium checkout existed when it didn't since an empty directory was there.

I would change the check for existing chromium to be

`if [ -d "${HOME}/chromium/src" ]; then`

Especially since that's where it cd's anyways

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 1 of 1 LGTMs obtained, and pending CI: Remote / large-ubuntu-22.04, docker-compose-compiles-nativelink (22.04), pre-commit-checks, windows-2022 / stable, and 1 discussions need to be resolved

___
*[`deployment-examples/chromium/03_build_chrome_tests.sh` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Nu6OhSH5cNBSNSSkJxt:-NuS3utxE9CQQCuyUZ_c:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/13298e7c7c9905a998f38c01ddf91e5d8b8640bc/deployment-examples/chromium/03_build_chrome_tests.sh#L10)):*
<details><summary><i>Previously, zbirenbaum (Zach Birenbaum) wrote…</i></summary><blockquote>

I ran into a problem on this line where the depot tools portion above didn't properly update my path and fetch wasn't found. Logging back in and starting nix again fixed the path issue, but then it assumed that the chromium checkout existed when it didn't since an empty directory was there.

I would change the check for existing chromium to be

`if [ -d "${HOME}/chromium/src" ]; then`

Especially since that's where it cd's anyways
</blockquote></details>

Done.
___
*[`deployment-examples/chromium/README.md` line 10 at r4](https://reviewable.io/reviews/TraceMachina/nativelink/786#-Nu1bntU0kmYm771LnDj:-NuS40yZ49cMNJFcoQBM:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/13298e7c7c9905a998f38c01ddf91e5d8b8640bc/deployment-examples/chromium/README.md#L10)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

nit  `exsist`
</blockquote></details>

Done.

**Review by zbirenbaum — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786#-:-NuUbcWc4GGtfP5rU6qw:bg7igkv)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 37 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 37 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by adam-singer — COMMENTED** [review]
> Reviewed 2 of 7 files at r2, 3 of 40 files at r4, 33 of 37 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 37 files at r5.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/786)* status: 2 of 1 LGTMs obtained, and pending CI: pre-commit-checks

**Pull request merged**
