### PR TITLE
StateManager will now cleanup actions on client disconnect

### PR DESCRIPTION
**Pull request by allada**
StateManager will now properly remove items from the maps if the client disconnects after a set amount of time. Currently these values are hard codded, but will be easy to transition them to use config variables once we design it out.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1107)

### CODE REVIEW

**Review by allada — COMMENTED** [review]
+@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-:-O1FnqZkAWyeb3AU0oQm:b-gyszd7)* status: 0 of 1 LGTMs obtained, and 1 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/scheduler_state/workers.rs` line 165 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1Fn8sI7RINcBVfSz3Z:-O1Fn8sI7RINcBVfSz3_:b313vve) ([raw file](https://github.com/TraceMachina/nativelink/blob/0d93671ba51be41a1a6b0297260cfc5ca0766ebc/nativelink-scheduler/src/scheduler_state/workers.rs#L165)):*
> ```XML
>                 .err_tip(|| "in update_operation on SimpleScheduler::update_action");
>             if let Err(err) = update_operation_res {
>                 let result = Result::<(), _>::Err(err.clone())
> ```

note: A worker can now send updates about an action that the state manager does not know about. This is ok, since the `Workers` struct now owns the platform properties and resource management of the node instead of state manager.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1107)* status: 0 of 1 LGTMs obtained, and pending CI: vale, and 1 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/simple_scheduler.rs` line 57 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1FnyxeC4hN08_R2OdI:-O1FnyxeC4hN08_R2OdJ:bz7dlgs) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/simple_scheduler.rs#L57)):*
> ```XML
> 
> /// Default time in seconds before a client is evicted.
> // TODO!(make this a config and documented)
> ```

fyi: My system is to use `todo!` anywhere that we need to cleanup code before merging into main.

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 8 of 12 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-:-O1J0N4aDRxM8GOq6kly:bnfp4nl)* status: 0 of 1 LGTMs obtained, and 8 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 48 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1It5HK8KApjNrvsHdL:-O1It5HK8KApjNrvsHdM:bd6snin) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L48)):*
> ```XML
> /// How often the owning database will have the AwaitedAction touched
> /// to keep it from being evicted.
> const KEEPALIVE_TIMER: Duration = Duration::from_secs(10);
> ```

nit: its not really a timer, MAYBE `KEEPALIVE_GRACE_PERIOD`  `KEEPALIVE_DURATION` ? 
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 97 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1Iu9tF2QJQI1uurwgJ:-O1Iu9tF2QJQI1uurwgK:b1v3lm6) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L97)):*
> ```XML
>     // ClientAwaitedAction is dropped, but will never actually be
>     // None except during the drop.
>     client_operation_id: Option<ClientOperationId>,
> ```

Would be it overly pedantic to build a custom type for holding a `client_operation_id` that allows for it to be set once and dropped? That way we are not implying state around `Option` in corner conditions, also `Option` doesn't encode if it was set multiple times? 

```
pub struct SetVar<T> {
    value: Option<T>,
    set_count: u8,
    set_count_max: u8,
}

impl<T> SetVar<T> {
    pub fn new(set_count_max: u8) -> Self {
        Self {
            value: None,
            set_count: 0,
            set_count_max: set_count_max
        }
    }

    pub fn set(&mut self, value: T) -> Result<(), &'static str> {
        if self.set_count_max == self.set_count {
           Err("Value can only be set once")
        } else {
            self.value = Some(value);
            self.set_count += 1;
            Ok(())
        }
    }

    pub fn drop_value(&mut self) -> Result<(), &'static str> {
        if self.set_count >= 1 {
            self.value = None;
            self.set_count = self.set_count_max;
            Ok(())
        } else if self.set_count == 0 {
            Err("Value has not been set yet")
        } else {
            Err("Value has already been dropped")
        }
    }

    pub fn get(&self) -> Option<&T> {
        self.value.as_ref()
    }

    pub fn is_set(&self) -> bool {
        self.set_count >= 1
    }
}

// Example:
let client_operation_id = SetVar<ClientOperationId>::new(1).set(a_client_operation_id);
```
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 140 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1Iy-du91Wb4jjBIZoY:-O1Iy-du91Wb4jjBIZoZ:bxnniem) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L140)):*
> ```XML
> }
> 
> /// Trit to be able to use the [`EvictingMap`] with [`ClientAwaitedAction`].
> ```

nit: `Trit`?
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 179 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1IyXLQ5EjTYQT-HBFO:-O1IyXLQ5EjTYQT-HBFP:bvg5rpd) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L179)):*
> ```XML
> #[allow(clippy::mutable_key_type)]
> impl AwaitedActionDb {
>     /// Touches the client operation id to keep it from being evicted.
> ```

nit: ```/// Refreshes/Updates the time to live of the [`ClientOperationId`] in the [`EvictionMap`] by touching the key.``` ?
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 209 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1IzA0T8la-p8nfOPWK:-O1IzA0UCK_ow_uWFe9_:b-wirxfp) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L209)):*
> ```XML
>         if !did_remove {
>             event!(
>                 Level::ERROR,
> ```

nit: Leave a simple comment to downgrade this event `Level` if it shows to be noisy and not an error? 
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 254 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1IzX_H1P-CRPUdYPth:-O1IzX_H1P-CRPUdYPti:bxzbmpv) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L254)):*
> ```XML
>         let sort_info = awaited_action.get_sort_info();
>         let sort_key = sort_info.get_previous_sort_key();
>         let btree = self.get_sort_map_for_state(&awaited_action.get_current_state().stage);
> ```

nit: `sorted_awaited_action_btree`
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 523 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1J-Pj_-FOOHStmoRGI:-O1J-Pj_-FOOHStmoRGJ:b-i9v0s1) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L523)):*
> ```XML
>                         client_operation_to_awaited_action: EvictingMap::new(
>                             config,
>                             SystemTime::now(),
> ```

nit: For better control on testing would it make sense to pass in `SystemTime::now()` in `StateManager::new()` since could be a fixed / mocked type later? Puts the burden on the caller tho generally not having control of time under test tends to be a pita.

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1107)* status: 0 of 1 LGTMs obtained, and 3 discussions need to be resolved (waiting on @zbirenbaum)

___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 48 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1It5HK8KApjNrvsHdL:-O1J_aRA9U6RFWlA1-pf:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L48)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: its not really a timer, MAYBE `KEEPALIVE_GRACE_PERIOD`  `KEEPALIVE_DURATION` ?
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 97 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1Iu9tF2QJQI1uurwgJ:-O1J_nGc7ObOEJdPwdP6:b-im6c03) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L97)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

Would be it overly pedantic to build a custom type for holding a `client_operation_id` that allows for it to be set once and dropped? That way we are not implying state around `Option` in corner conditions, also `Option` doesn't encode if it was set multiple times? 

```
pub struct SetVar<T> {
    value: Option<T>,
    set_count: u8,
    set_count_max: u8,
}

impl<T> SetVar<T> {
    pub fn new(set_count_max: u8) -> Self {
        Self {
            value: None,
            set_count: 0,
            set_count_max: set_count_max
        }
    }

    pub fn set(&mut self, value: T) -> Result<(), &'static str> {
        if self.set_count_max == self.set_count {
           Err("Value can only be set once")
        } else {
            self.value = Some(value);
            self.set_count += 1;
            Ok(())
        }
    }

    pub fn drop_value(&mut self) -> Result<(), &'static str> {
        if self.set_count >= 1 {
            self.value = None;
            self.set_count = self.set_count_max;
            Ok(())
        } else if self.set_count == 0 {
            Err("Value has not been set yet")
        } else {
            Err("Value has already been dropped")
        }
    }

    pub fn get(&self) -> Option<&T> {
        self.value.as_ref()
    }

    pub fn is_set(&self) -> bool {
        self.set_count >= 1
    }
}

// Example:
let client_operation_id = SetVar<ClientOperationId>::new(1).set(a_client_operation_id);
```
</blockquote></details>

Hmmm, the current way this is normally handled is to create an `Inner` struct, but that feels overkill for such a small struct.

Other libraries do it worse, they use: https://doc.rust-lang.org/std/mem/fn.forget.html
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 140 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1Iy-du91Wb4jjBIZoY:-O1Ja1ou3hnH4XDlmg8u:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L140)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: `Trit`?
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 179 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1IyXLQ5EjTYQT-HBFO:-O1JaAONE__dm-fmGMfw:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L179)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: ```/// Refreshes/Updates the time to live of the [`ClientOperationId`] in the [`EvictionMap`] by touching the key.``` ?
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 209 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1IzA0T8la-p8nfOPWK:-O1JaVRj7FjuJYWJ-WtQ:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L209)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: Leave a simple comment to downgrade this event `Level` if it shows to be noisy and not an error?
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 254 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1IzX_H1P-CRPUdYPth:-O1JaaET4LnlFpmwMzaS:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L254)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: `sorted_awaited_action_btree`
</blockquote></details>

Done.
___
*[`nativelink-scheduler/src/scheduler_state/state_manager.rs` line 523 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-O1J-Pj_-FOOHStmoRGI:-O1Javip0uKgDWR4qS9j:b7pceu7) ([raw file](https://github.com/TraceMachina/nativelink/blob/b60e10f14d4d0e9f96616c3c6b5c6ec6c3aed46e/nativelink-scheduler/src/scheduler_state/state_manager.rs#L523)):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

nit: For better control on testing would it make sense to pass in `SystemTime::now()` in `StateManager::new()` since could be a fixed / mocked type later? Puts the burden on the caller tho generally not having control of time under test tends to be a pita.
</blockquote></details>

Normally I'd 100% agree, however in this case, because of all the `Weak` calls, it'd require a lot of changes for no tests to use it currently.

I started to do it, but realized a lot of structs would need to be templated. Keep in mind in the long run I plan on deprecating `AwaitedActionDb` and moving to `MemoryStore`, but that's further down the line.

**Review by allada — COMMENTED** [review]
-@zbirenbaum 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1107#-:-O1JcPvS8n_SA9FKSzUm:b-qo69s9)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
