### PR TITLE
Add support for mTLS

### LINKED ISSUE #467: Add support for mTLS
Now we're transitioning to building production builds with native-link we find it necessary to secure our AC to avoid the possibility of malicious actors on the network injecting bad objects into our builds.  The simplest method to perform this is to simply provide mTLS.

This should support verification from a CA and also a CRL file to allow revocation to be performed.

### PR DESCRIPTION
**Pull request by chrisstaite-menlo**
# Description

There is a need to secure the Action Cache for production builds which is not possible with out authentication of the store.  This can be provided by mTLS and the ability to make the action cache read only for some servers.

Fixes #467

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Have a test system made of a storage, scheduler, build workers and Reclient consumers all utilising mTLS.

## Checklist

- [x] Updated documentation if needed
- [x] Tests added/amended
- [x] `bazel test //...`  passes locally
- [x] PR is contained in a single commit, using `git amend` see some [docs](https://www.atlassian.com/git/tutorials/rewriting-history)

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)

### CODE REVIEW

**Review by adam-singer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @chrisstaite-menlo)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NlUyewk0jqOM-Ep0TzZ:-NlUyewk0jqOM-Ep0Tz_:b-jb52l4) (no related file):*
@chrisstaite-menlo what is the dependency here between tls and readonly store? I think it would be better if we teased apart this into two different pull requests. Thoughts @aaronmondal @allada 

___

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 3 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @aaronmondal, @adam-singer, and @allada)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NlUyewk0jqOM-Ep0TzZ:-NlV1g5z5t3Rms9L6shc:bbidt5k) (no related file):*
<details><summary><i>Previously, adam-singer (Adam Singer) wrote…</i></summary><blockquote>

@chrisstaite-menlo what is the dependency here between tls and readonly store? I think it would be better if we teased apart this into two different pull requests. Thoughts @aaronmondal @allada
</blockquote></details>

It's all for the same purpose, to protect the action cache from being polluted from outside of the build network.  Without it a user can simply inject results into the action cache.

___

**Review by allada — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @aaronmondal, @adam-singer, and @allada)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NlUyewk0jqOM-Ep0TzZ:-Nlg8Jdq0FcHOWUcgXNW:b7qkhka) (no related file):*
<details><summary><i>Previously, chrisstaite-menlo (Chris Staite) wrote…</i></summary><blockquote>

It's all for the same purpose, to protect the action cache from being polluted from outside of the build network.  Without it a user can simply inject results into the action cache.
</blockquote></details>

I do agree we should do this in two PRs, but this PR is not all that big, so I'm not too strict on it in this particular case case.

I'll leave it to @adam-singer for the final call though.

___

**Review by adam-singer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @aaronmondal and @allada)

*[a discussion](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NlUyewk0jqOM-Ep0TzZ:-NlgMEN3DQ-XgwtKxCth:bwmmcxq) (no related file):*
<details><summary><i>Previously, allada (Nathan (Blaise) Bruer) wrote…</i></summary><blockquote>

I do agree we should do this in two PRs, but this PR is not all that big, so I'm not too strict on it in this particular case case.

I'll leave it to @adam-singer for the final call though.
</blockquote></details>

sg, we can continue to review on this one

___

**Review by allada — COMMENTED** [review]
Sorry for the hold up on this Chris. We were in the middle of a sprint to release push and didn't want to land new features. Now that we have it all out, internally we are in stabilization mode for a little bit. I think it's completely fine for external contribution features to be excluded from our "stabilization push".

It turns out we also need this for some other work we are doing internally, so we really appreciate this work :smile: 

> Reviewed 12 of 19 files at r1, all commit messages.
> Dismissed @adam-singer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470#-:-NmEprWc4FYbol6DZ3OQ:be69tqo)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-20.04, Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), pre-commit-checks, ubuntu-20.04, ubuntu-22.04, windows-2022

___
*[`nativelink-config/src/stores.rs` line 483 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NliVERA5RN33p1BGDmP:-NliVERA5RN33p1BGDmQ:b-3l43kk) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/nativelink-config/src/stores.rs#L483)):*
> ```XML
> }
> 
> impl TryFrom<&ClientTlsConfig> for tonic::transport::ClientTlsConfig {
> ```

nit: I'd rather keep everything in `nativelink-config` pure and near zero code (with the exception of macros).

Can we make a function that does the conversion at the place it's used instead? I suspect this function will only ever be called once in a single place, so putting it where it's called seems logical to me.
___
*[`nativelink-scheduler/src/grpc_scheduler.rs` line 80 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEmwVW38BnoaHW1W4g:-NmEmwVW38BnoaHW1W4h:be5aoit) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/nativelink-scheduler/src/grpc_scheduler.rs#L80)):*
> ```XML
> 
>         let endpoint = Uri::try_from(&config.endpoint)
>             .map_err(|e| make_err!(Code::Internal, "Unable to parse endpoint {}: {:?}", config.endpoint, e))?;
> ```

nit: We can now use the syntax:
```rs
.map_err(|e| make_err!(Code::Internal, "Unable to parse endpoint {config.endpoint}: {e:?}"))?;
```

(same below)
___
*[`nativelink-store/src/grpc_store.rs` line 104 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEo-dh9ZQu6bVJEJJ7:-NmEo-dh9ZQu6bVJEJJ8:bt66gs4) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/nativelink-store/src/grpc_store.rs#L104)):*
> ```XML
>                 .map_err(|e| make_input_err!("Invalid URI for worker endpoint : {:?}", e))?;
> 
>             let endpoint_transport = if let Some(tls_config) = &tls_config {
> ```

nit: Lets abstract this into a helper file, since there's a few duplicates.
___
*[`nativelink-worker/src/local_worker.rs` line 399 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEoCIzA3uHs650y-As:-NmEoCIzA3uHs650y-At:b-5v3gaq) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/nativelink-worker/src/local_worker.rs#L399)):*
> ```XML
>                     .connect_timeout(timeout_duration)
>                     .timeout(timeout_duration);
>                 let endpoint = if let Some(tls_config) = tls_config {
> ```

nit: ditto.
___
*[`src/bin/cas.rs` line 52 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEpmgtAgVdflSCH725:-NmEpmgtAgVdflSCH726:bzolpj) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L52)):*
> ```XML
> use tokio::net::TcpListener;
> use tokio::task::spawn_blocking;
> use tokio_rustls::rustls::pki_types::PrivatePkcs1KeyDer;
> ```

nit: Combine this and one below.
___
*[`src/bin/cas.rs` line 54 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEpkrpAIH8q-TiMsk4:-NmEpkrq3Y-SSJnpapE7:b-diqesk) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L54)):*
> ```XML
> use tokio_rustls::rustls::pki_types::PrivatePkcs1KeyDer;
> use tokio_rustls::rustls::pki_types::PrivateSec1KeyDer;
> use tokio_rustls::rustls::RootCertStore;
> ```

nit: Add to below block.
___
*[`src/bin/cas.rs` line 446 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEoMKs3UGy2NV0pbGO:-NmEoMKs3UGy2NV0pbGP:b-q8efat) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L446)):*
> ```XML
> 
>         // Configure our TLS acceptor if we have TLS configured.
>         let maybe_tls_acceptor = server_cfg.tls.map_or(Ok(None), |tls_config| {
> ```

nit: I think it might now be worth moving all this into the same helper file (referenced above).

This main file is getting a bit bloated, so I think from now on we need to start moving data to helpers.

I think there's enough TLS functions to make a nice useful TLS helper file.
___
*[`src/bin/cas.rs` line 489 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEpZx5BnUpeBb7pTyy:-NmEpZx5BnUpeBb7pTyz:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L489)):*
> ```XML
>                     client_auth_roots
>                         .add(cert)
>                         .map_err(|e| make_err!(Code::Internal, "Could not read client CA: {:?}", e))?;
> ```

nit: ditto
___
*[`src/bin/cas.rs` line 494 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEpWLv2LjwzLOlDGtj:-NmEpWLv2LjwzLOlDGtk:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L494)):*
> ```XML
>                     let mut crl_reader = std::io::BufReader::new(
>                         std::fs::File::open(client_crl_file)
>                             .err_tip(|| format!("Could not open CRL file {}", client_crl_file))?,
> ```

nit: ditto
___
*[`src/bin/cas.rs` line 497 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEpXUMEAyL9SfHIJ92:-NmEpXUMEAyL9SfHIJ93:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L497)):*
> ```XML
>                     );
>                     crls(&mut crl_reader)
>                         .err_tip(|| format!("Could not extract CRLs from file {}", client_crl_file))?
> ```

nit: ditto
___
*[`src/bin/cas.rs` line 507 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NmEpZAo4peBNsVLioYJ:-NmEpZAo4peBNsVLioYK:b-iipjm8) ([raw file](https://github.com/TraceMachina/nativelink/blob/3b83cfe6555631eb73f3e4a9e59178112e39ce2d/src/bin/cas.rs#L507)):*
> ```XML
>                     .with_crls(crls)
>                     .build()
>                     .map_err(|e| make_err!(Code::Internal, "Could not create WebPkiClientVerifier: {:?}", e))?
> ```

nit: ditto

**Review by allada — COMMENTED** [review]
Hey Chris. Would you like one of us to pickup this PR?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470#-:-No4QO_QB8SDoYOWOBIE:bxwvnyi)* status: 0 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-20.04, Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), pre-commit-checks, ubuntu-20.04, ubuntu-22.04, windows-2022

**Comment by chrisstaite-menlo** [comment]
I'm happy to do it, I was just waiting for the go-ahead that you'd finished the major rework in the stabilisation.  I assume that's now the case and I'll update this.

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 11 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Bazel Dev / ubuntu-22.04, Local / ubuntu-22.04, Vercel, docker-compose-compiles-nativelink (20.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 19 of 23 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by adam-singer — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 0 of 1 LGTMs obtained

**Review by adam-singer — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470#-:-NoIHoaX1IRl5ojlXssO:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Review by chrisstaite-menlo — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470)* status: 1 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Review by allada — APPROVED** [review]
Awesome, Great job!
:lgtm:

> Reviewed 1 of 19 files at r1, 14 of 23 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470#-:-NoJjEQY6ivD-7wlhufM:b-xjux9v)* status: 2 of 1 LGTMs obtained

___
*[`nativelink-worker/src/local_worker.rs` line 384 at r5](https://reviewable.io/reviews/TraceMachina/nativelink/470#-NoJiHG16CgbaEBhkNgu:-NoJiHG16CgbaEBhkNgv:b-cnxto6) ([raw file](https://github.com/TraceMachina/nativelink/blob/87c8836e020181f4bf6566cd124696e9a83520df/nativelink-worker/src/local_worker.rs#L384)):*
> ```XML
>                 let timeout_duration = Duration::from_secs_f32(timeout);
> 
>                 let tls_config = tls_utils::load_client_config(&config.worker_api_endpoint.tls_config)?;
> ```

nit: Lets `.err_tip()` this.

**Review by chrisstaite-menlo — COMMENTED** [review]
@adam-singer just waiting on you to resolve so we can merge.

> Reviewed 3 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470#-:-NoLeHRj90Z3Pw9dxONK:b-i5hxin)* status: 2 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Local / ubuntu-22.04, Vercel, asan / ubuntu-22.04, pre-commit-checks, publish-image, ubuntu-20.04, ubuntu-20.04 / stable

**Review by adam-singer — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/470#-:-NoLfhvg59kccCIodAFm:bnfp4nl)* status: 2 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), publish-image, ubuntu-20.04, windows-2022 / stable

**Pull request merged**
