### PR TITLE
Add Git-Cliff Changelog

### PR DESCRIPTION
**Pull request by blakehatch**
# Description

#518

Add Changelog for 0.1.0-alpha that is automatically generated by git-cliff. Should be reusable for future releases might require minor regex changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/515)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/515)* status: all files reviewed, 3 unresolved discussions (waiting on @blakehatch and @MarcusSorealheis)

___
*[`CHANGELOG.md` line 5 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/515#-Nm06SU2EvSTWR0PeowP:-Nm06SU2EvSTWR0PeowQ:b-q4tazy) ([raw file](https://github.com/TraceMachina/nativelink/blob/2d47507dbcc43178aa87bab6906116de289a3e50/CHANGELOG.md#L5)):*
> ```Markdown
> All notable changes to this project will be documented in this file.
> 
> ## [0.1.0-alpha] - 2023-12-19
> ```

Super nice. Let's stick to `0.1.0` without the alpha though.
___
*[`CHANGELOG.md` line 437 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/515#-Nm06ZNg0BGVoKTjshz9:-Nm06ZNg0BGVoKTjshzA:b31prpy) ([raw file](https://github.com/TraceMachina/nativelink/blob/2d47507dbcc43178aa87bab6906116de289a3e50/CHANGELOG.md#L437)):*
> ```Markdown
> - [BreakingChange] Scheduler config now supports multiple impls - ([384f14e](https://github.com/TraceMachina/nativelink/commit/384f14e593e88294ffbe01471416b8d1424442ac))
> 
> 
> ```

Even this generated file should go through the pre-commit hooks.
___
*[`cliff.toml` line 89 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/515#-Nm06z8w-kB8-CwUYC1k:-Nm06z8w-kB8-CwUYC1l:bp1mnbz) ([raw file](https://github.com/TraceMachina/nativelink/blob/2d47507dbcc43178aa87bab6906116de289a3e50/cliff.toml#L89)):*
> ```TOML
>   { message = "Remove", group = "⚙️ Miscellaneous" },
>   { message = "Separate", group = "🛠️ Refactor" },
>   { message = ".*", group = "⚙️ Miscellaneous" },
> ```

We should have one category for version updates and bumps.

**Review by blakehatch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/515)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aaronmondal and @MarcusSorealheis)

___
*[`CHANGELOG.md` line 5 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/515#-Nm06SU2EvSTWR0PeowP:-Nm08VMH1D0aK70Sj5cj:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2d47507dbcc43178aa87bab6906116de289a3e50/CHANGELOG.md#L5)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Super nice. Let's stick to `0.1.0` without the alpha though.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 437 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/515#-Nm06ZNg0BGVoKTjshz9:-Nm08XbS-DubfSJWX0QN:bpqujkh) ([raw file](https://github.com/TraceMachina/nativelink/blob/2d47507dbcc43178aa87bab6906116de289a3e50/CHANGELOG.md#L437)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Even this generated file should go through the pre-commit hooks.
</blockquote></details>

Oops these should not be getting through on two file commits mb 😅
___
*[`cliff.toml` line 89 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/515#-Nm06z8w-kB8-CwUYC1k:-Nm0DIr0-fLqtdO2CxPO:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/2d47507dbcc43178aa87bab6906116de289a3e50/cliff.toml#L89)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

We should have one category for version updates and bumps.
</blockquote></details>

Done.

**Comment by MarcusSorealheis** [comment]
Please mention any issues this may be related to.

**Comment by MarcusSorealheis** [comment]
> Super nice. Let's stick to 0.1.0 without the alpha though.

@aaronmondal Why?

**Review by MarcusSorealheis — APPROVED** [review]
Seems good to go for me. I'm curious why no Alpha but I will follow up.

**Review by aaronmondal — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/515)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @blakehatch)

**Review by aaronmondal — APPROVED** [review]
LGTM.

As a follow-up we should add a ~weekly running cronjob to auto-update this log. We can do something similar to the cronjobs we already have here: https://github.com/TraceMachina/nativelink/blob/main/.github/workflows/codeql.yaml or here: https://github.com/TraceMachina/nativelink/blob/main/.github/workflows/scorecard.yaml but without the `on push` invocations. That way it'll only run once a week and won't clutter our history.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/515#-:-Nm25P-NArqmZehiI_Yw:b-g3zxuk)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @blakehatch)

**Review by blakehatch — COMMENTED** [review]
Agreed however if we do this we should adopt stricter commit message standards (probably https://www.conventionalcommits.org/en/v1.0.0/) and then clean up the regex parser and filter out non standard commit messages. With filtering in place we could actually filter out more superfluous commits as well by default if they're intentionally not written in conventional commit structure and avoid cluttering up the history by default.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/515#-:-Nm26A3FBY7F1ZWHPwmH:bb0oe9h)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @blakehatch)

**Pull request merged**
