### PR TITLE
Update images for docs

### PR DESCRIPTION
**Pull request by bclark8923**
# Description

Updates the favicon and header images for docs.nativelink.com

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/930)

### CODE REVIEW

**Review by aaronmondal — CHANGES_REQUESTED** [review]
@bclark8923 It's complaining that the svg doesn't have a correct line ending. When you create the commit from inside the nix flake it'll auto-add the correct line ending.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/930#-:-NygvzkP-cB3b6qCnl-z:b3auisv)* status: 0 of 1 LGTMs obtained, and pending CI: Cargo Dev / macos-13, pre-commit-checks, and 4 discussions need to be resolved

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/930#-NygwMBu4JqmXeUGI4Jc):*
nit: Update images for docs

(this way our changelog autoupdater should properly slot this in)
___
*[`nativelink-docs/docusaurus.config.js` line 13 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/930#-NygwZv_-hKpKiY9w3L-:-NygwZv_-hKpKiY9w3L0:bgulwcs) ([raw file](https://github.com/TraceMachina/nativelink/blob/0298bd3c9aef505e9b8fa5855d3d9daf35756ad5/nativelink-docs/docusaurus.config.js#L13)):*
> ```JavaScript
>   title: 'NativeLink',
>   tagline: 'An extremely fast and efficient build cache and remote executor for Bazel RBE',
>   favicon: 'img/favicon.ico',
> ```

Do we have an svg variant of this?
___
*[`nativelink-docs/static/img/dark.svg` line 1128 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/930#-Nygwkvn-kBQnnJxSVjD:-Nygwkvn-kBQnnJxSVjE:b-8brh6p) ([raw file](https://github.com/TraceMachina/nativelink/blob/0298bd3c9aef505e9b8fa5855d3d9daf35756ad5/nativelink-docs/static/img/dark.svg#L1128)):*
> ```SVG
>     <path class="cls-177" d="M1001.64,31.06h22.17v62.93h1.05l10.34-12.14,16.18-17.23h25.47l-29.96,30.56,33.11,46.75h-26.37l-22.47-34.16-7.34,7.34v26.82h-22.17V31.06Z"/>
>   </g>
> </svg>
> ```

CI is complaining about this one
___
*[`nativelink-docs/static/img/light.svg` line 1123 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/930#-Nygx-icC28-k__HECzY:-Nygx-icC28-k__HECzZ:bs4q9op) ([raw file](https://github.com/TraceMachina/nativelink/blob/0298bd3c9aef505e9b8fa5855d3d9daf35756ad5/nativelink-docs/static/img/light.svg#L1123)):*
> ```SVG
>     <path class="cls-77" d="M1001.66,31.05h22.17v62.92h1.05l10.34-12.13,16.18-17.23h25.47l-29.96,30.56,33.11,46.74h-26.36l-22.47-34.15-7.34,7.34v26.81h-22.17V31.05Z"/>
>   </g>
> </svg>
> ```

Ditto.

**Review by bclark8923 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/930)* status: 0 of 1 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 4 discussions need to be resolved

___
*[`nativelink-docs/docusaurus.config.js` line 13 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/930#-NygwZv_-hKpKiY9w3L-:-Nyh4cTF7-ivETghxt17:b-67xdnu) ([raw file](https://github.com/TraceMachina/nativelink/blob/0298bd3c9aef505e9b8fa5855d3d9daf35756ad5/nativelink-docs/docusaurus.config.js#L13)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

Do we have an svg variant of this?
</blockquote></details>

I'd recommend using an .ico as it packages multiple sizes in one file for browsers to choose what to render (16x16, 32x32, 48x48 & 64x64)

**Review by aaronmondal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/930#-:-Nyh9KL5AhMo9U-n1-vc:bnfp4nl)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04 / stable, windows-2022 / stable

**Review by bclark8923 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/930)* status: 1 of 1 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable

**Pull request merged**
