### PR TITLE
Correctly wait for LRE/Remote tekton pipelines

### LINKED ISSUE #1454: LRE/Remote sometimes tries to wait for tekton pipelineruns before they're triggered
This can lead to flaky runs like here: https://github.com/TraceMachina/nativelink/actions/runs/11638914077/job/32414391566

### PR DESCRIPTION
**Pull request by aaronmondal**
Fixes #1454

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1455)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@SchahinRohani 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1455#-:-OAeupdw-yrC9JPtgKAb:bj5atnp)* status: 0 of 1 LGTMs obtained, and 0 of 1 files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable (waiting on @SchahinRohani)

**Review by SchahinRohani — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1455)* status: 0 of 1 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04 (waiting on @SchahinRohani)

**Review by SchahinRohani — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1455#-:-OAhZlV2-FfC9l4SplmS:bnfp4nl)* status: 1 of 1 LGTMs obtained, and all files reviewed, and pending CI: Remote / large-ubuntu-22.04

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1455)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained, and all files reviewed

**Comment by aaronmondal** [comment]
Lmao this was unexpectedly hard :rofl:

**Pull request merged**
