### PR TITLE
Introduce the `NativeLink Operator`

### PR DESCRIPTION
**Pull request by aaronmondal**
A single `kubectl apply -k` now deploys NativeLink in a self-configuring, self-healing and self-updating fashion.

To achieve this we implement a two-stage depoyment to asynchronously reconciliate various parts of NativeLink Kustomizations.

First, we deploy Flux Alerts that trigger Tekton Pipelines on GitRepository updates to bring required images into the cluster.

Second, and technically at the same time, we start a Flux Kustomization to deploy a NativeLink Kustomization.

This is similar to the previous 01_operations and 02_applicaion scripts, but now happens fully automated in the cluster and no longer requires a local Nix installation as all tag evaluations have become implementation details of the Tekton Pipelines.

This commit also changes the K8s resource layout to a "best-practice" Kustomize directory layout. This further reduces code duplication and gives third parties greater flexibility and more useful reference points to build custom NativeLink setups.

Includes an overhaul of the Kubernetes documentation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@allada +@blakehatch

cc @MarcusSorealheis @bclark8923 @kubevalet

New docpages at:

- https://df0124ed.nativelink.pages.dev/guides/kubernetes/
- https://df0124ed.nativelink.pages.dev/guides/chromium/

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O18s5pm0pmYVQ0gJOX7:bj7n8gb)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable (waiting on @adam-singer, @allada, and @blakehatch)

**Review by MarcusSorealheis — CHANGES_REQUESTED** [review]
This PR is massive and there is no simple opportunity for breaking it up. just annoying.

The docs look good, though. Nice.

> Reviewed 3 of 61 files at r1.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1BN5dyEnEAVS3hDC2l:bh8hep9)* status: 0 of 3 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

___
*[`deploy/chromium-example/kustomization.yaml` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1BMipYBJ3Z9EIKEKFI:-O1BMipZCrd24qumf49S:bnawqjr) ([raw file](https://github.com/TraceMachina/nativelink/blob/cfad74df5c37bf0684a324b15c5a888e9647f64e/deploy/chromium-example/kustomization.yaml#L18)):*
> ```YAML
>     - op: replace
>       path: /spec/url
>       value: https://github.com/aaronmondal/nativelink
> ```

why isn't this pointing to the TraceMachina repo?
___
*[`deploy/dev/kustomization.yaml` line 26 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1BMsZY2gfmDR2VPcAh:-O1BMsZY2gfmDR2VPcAi:b-7tdrph) ([raw file](https://github.com/TraceMachina/nativelink/blob/cfad74df5c37bf0684a324b15c5a888e9647f64e/deploy/dev/kustomization.yaml#L26)):*
> ```YAML
>     - op: replace
>       path: /spec/url
>       value: https://github.com/aaronmondal/nativelink
> ```

again
___
*[`deploy/kubernetes-example/kustomization.yaml` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1BMvPN4moRq637TiMe:-O1BMvPN4moRq637TiMf:b-t7ip01) ([raw file](https://github.com/TraceMachina/nativelink/blob/cfad74df5c37bf0684a324b15c5a888e9647f64e/deploy/kubernetes-example/kustomization.yaml#L18)):*
> ```YAML
>     - op: replace
>       path: /spec/url
>       value: https://github.com/aaronmondal/nativelink
> ```

again

**Review by MarcusSorealheis — COMMENTED** [review]
What i don't like is that the Chromium example received a Pulumi dependency. Is that required?

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1BNTdQE5OexITdKrhn:b5elxh)* status: 0 of 3 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
> This PR is massive and there is no simple opportunity for breaking it up. just annoying.

After looking into reducing the size of this PR I think there are some parts that I can break out. I'll send PRs for those parts which hopefully also makes it a bit clearer why/how I'm making these changes.

> What i don't like is that the Chromium example received a Pulumi dependency. Is that required?

We always had the pulumi dependency for the Chromium example. It's just more apparent now. However, this PR paves the way to reduce that dependency.

The way the examples generally work is:

1. Start a K8s cluster and prepare some dependencies in it. This is done via Pulumi.
2. Build or fetch NativeLink container images and toolchains. This was previously done via the `01_operations` shell scripts. Now it happens automatically inside the cluster. This fixes https://github.com/TraceMachina/nativelink/issues/1012 which is a blocker for MacOS.
3. Deploy the actual NativeLink deployments. This was previously done via the `02_application` scripts and now also happens inside the cluster, so now it's no longer necessary to invoke any shell scripts manually.

What the new `deploy` and `kubernetes` directories do is essentially create "building blocks" for creating NativeLink K8s deployments. For instance, if you had an existing Helm chart (wink) you could now use these building blocks to deploy that chart as well. This also turns non-production parts of the examples, like the insecure example certs into Components. This way they're more easily swappable with e.g. "real" CAs. Same for the HttpRoutes which would require functional Gateway API Gateways in the cluster. Now it's possible to omit those routes and configure your own ingress logic instead.

The next step here is to also migrate the Tekton Pipelines out of the `native-cli` and into the `kubernetes` directory so that they're deployed via Flux instead of Pulumi. After that we've clearly separated concerns between Pulumi and K8s and the `kubectl apply -k https://github.com/TraceMachina/nativelink//deploy/<somestack>` should be self-contained enough that users can start running it against arbitrary K8s clusters.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1DGTjV9cPeZOgHyL4L:bzibuys)* status: 0 of 3 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

___
*[`deploy/chromium-example/kustomization.yaml` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1BMipYBJ3Z9EIKEKFI:-O1DKMVpBSE1-QjZuHPh:bhpqzc3) ([raw file](https://github.com/TraceMachina/nativelink/blob/cfad74df5c37bf0684a324b15c5a888e9647f64e/deploy/chromium-example/kustomization.yaml#L18)):*
<details><summary><i>Previously, MarcusSorealheis (Marcus Eagan) wrote…</i></summary><blockquote>

why isn't this pointing to the TraceMachina repo?
</blockquote></details>

This is so that the LRE-remote job https://github.com/TraceMachina/nativelink/actions/runs/9824654274/job/27123866843?pr=1088 passes. Since the deployments in this PR arent on main yet we'll have to bring them in before we can change this. However, we can set them to the TraceMachina repo and disable the LRE job in CI and then immediately reenable it after these changes have landed.

I just noticed that it's also possible to create a dedicated `CI` overlay that sets this to the actual PR branch dynamically. This is probably what we want so I'll look into this more.

Keeping this comment (and the other two) open so that I don't forget to change these overrides. (and the `flux` branch override).

**Review by MarcusSorealheis — COMMENTED** [review]
sgtm

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1Di0etA-RKDpLtOEat:bb7ohn6)* status: 0 of 3 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
I broke out various parts of this PR in:

- #1094
- #1095 
- #1096 
- #1098 
- #1100

I'll rebase this PR after these have been merged.

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1EzDqKCa_0X2eWGEES:b-20qf44)* status: 0 of 3 LGTMs obtained, and 3 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

**Review by adam-singer — COMMENTED** [review]
@aaronmondal happy to sync up offline and test out these changes locally to get a better sense what this means for using these locally 

> Reviewed 42 of 61 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1JCLoO2_8yfTSe0Rxs:b-qhs1y6)* status: 0 of 3 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved (waiting on @allada and @blakehatch)

___
*[`docs/src/content/docs/guides/chromium.mdx` line 25 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1JBosDAyPWB30fV-TG:-O1JBosDAyPWB30fV-TH:b-ktrr4y) ([raw file](https://github.com/TraceMachina/nativelink/blob/b83ae4357603d4e5a0a2a9f31cf23e5dc0df60ed/docs/src/content/docs/guides/chromium.mdx#L25)):*
> ```MDX
> 
> ```bash
> # TODO(aaronmondal): Point to the main repo before merging.
> ```

nit: leaving this here so we don't for get it
___
*[`docs/src/content/docs/guides/kubernetes.mdx` line 26 at r2](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1JBt9D9TD1eaLs1pNT:-O1JBt9D9TD1eaLs1pNU:b90tuz4) ([raw file](https://github.com/TraceMachina/nativelink/blob/b83ae4357603d4e5a0a2a9f31cf23e5dc0df60ed/docs/src/content/docs/guides/kubernetes.mdx#L26)):*
> ```MDX
> 
> ```bash
> # TODO(aaronmondal): Point to the main repo before merging.
> ```

nit: before landing

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-O1KWWsABnaFULloqoV4:bnfp4nl)* status: 0 of 3 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), macos-13, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, windows-2022 / stable, and 5 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

**Review by MarcusSorealheis — DISMISSED** [review]
I get this error when I try to run native up with Docker running on Ubuntu 24:

```bash
Diagnostics:
  docker:index:Container (kind-registry):
    error: Docker native provider returned an unexpected error from Configure: failed to connect to any docker daemon

Resources:
    2 unchanged

Duration: 1s

2024/08/20 17:44:51 component error: pulumi error: decoding YAML: rpc error: code = Canceled desc = context canceled
```

**Comment by MarcusSorealheis** [comment]
For clarity on my last comment:

1. this is on your branch based on the guide
2. all my dependencies are up to date.

**Comment by aaronmondal** [comment]
@SchahinRohani @MarcusSorealheis Ok I rebased it and at least in GHA it seems to actually work 🥳  https://github.com/TraceMachina/nativelink/actions/runs/11526946795/job/32091907234?pr=1088

@SchahinRohani FYI this is not ready for merging yet. IIRC some Kustomization templates are missing to ensure that the GHA workflows actually test the PRs that trigger them instead of the default latest main commit.

**Comment by aaronmondal** [comment]
Ready to merge, modulo the references to my repo after reviews

**Review by SchahinRohani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5, 10 of 17 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-OAOQGp9-xpazbYkW-Z3:bnfp4nl)* status: 0 of 3 LGTMs obtained, and 55 of 67 files reviewed, and pending CI: Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, and 11 discussions need to be resolved (waiting on @adam-singer, @allada, and @blakehatch)

___
*[`README.md` line 62 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAOQJ2A0JCori5LHoE4:-OAOQJ2A0JCori5LHoE5:b-hlevnb) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/README.md#L62)):*
> ```Markdown
> The setups below are **production-grade** installations. See the [contribution docs](https://nativelink.com/docs/contribute/nix/) for instructions on how to build from source with [Bazel](https://nativelink.com/docs/contribute/bazel/), [Cargo](https://nativelink.com/docs/contribute/cargo/), and [Nix](https://nativelink.com/docs/contribute/nix/).
> 
> You can find a few example deployments in the [Docs](https://docs.nativelink.com/guides/kubernetes).
> ```

The docs path should be relative "/docs/guides/kubernetes", if we want to have it self contained.
___
*[`deploy/chromium-example/kustomization.yaml` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1BMipYBJ3Z9EIKEKFI:-OAOQr3cAVaXxgFp8zDf:bgcbinx) ([raw file](https://github.com/TraceMachina/nativelink/blob/cfad74df5c37bf0684a324b15c5a888e9647f64e/deploy/chromium-example/kustomization.yaml#L18)):*
<details><summary><i>Previously, aaronmondal (Aaron Siddhartha Mondal) wrote…</i></summary><blockquote>

This is so that the LRE-remote job https://github.com/TraceMachina/nativelink/actions/runs/9824654274/job/27123866843?pr=1088 passes. Since the deployments in this PR arent on main yet we'll have to bring them in before we can change this. However, we can set them to the TraceMachina repo and disable the LRE job in CI and then immediately reenable it after these changes have landed.

I just noticed that it's also possible to create a dedicated `CI` overlay that sets this to the actual PR branch dynamically. This is probably what we want so I'll look into this more.

Keeping this comment (and the other two) open so that I don't forget to change these overrides. (and the `flux` branch override).
</blockquote></details>

nit: Don't forget to change the link
___
*[`deploy/kubernetes-example/kustomization.yaml` line 18 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAOR-MK2q1Yy1Yx9Edm:-OAOR-MK2q1Yy1Yx9Edn:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/deploy/kubernetes-example/kustomization.yaml#L18)):*
> ```YAML
>     - op: replace
>       path: /spec/url
>       value: https://github.com/aaronmondal/nativelink
> ```

nit: point to nativelink repository
___
*[`deploy/kubernetes-example/kustomization.yaml` line 32 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAOR0_v4h_sXfRWZcsI:-OAOR0_w9wbgbZriE6Da:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/deploy/kubernetes-example/kustomization.yaml#L32)):*
> ```YAML
>     - op: replace
>       path: /spec/eventMetadata/flakeOutput
>       value: github:aaronmondal/nativelink/flux#nativelink-worker-lre-cc
> ```

nit: point to nativelink repository
___
*[`deploy/kubernetes-example/kustomization.yaml` line 46 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAOR1IEBAqvxIykf5QZ:-OAOR1IEBAqvxIykf5Q_:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/deploy/kubernetes-example/kustomization.yaml#L46)):*
> ```YAML
>     - op: replace
>       path: /spec/eventMetadata/flakeOutput
>       value: github:aaronmondal/nativelink/flux#nativelink-worker-init
> ```

nit: point to nativelink repository
___
*[`web/platform/src/content/docs/docs/deployment-examples/chromium.mdx` line 26 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAORCbVAK9FwfsRwkX7:-OAORCbVAK9FwfsRwkX8:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/web/platform/src/content/docs/docs/deployment-examples/chromium.mdx#L26)):*
> ```MDX
> ```bash
> # TODO(aaronmondal): Point to the main repo before merging.
> git clone https://github.com/aaronmondal/nativelink && \
> ```

nit: point to nativelink repository
___
*[`web/platform/src/content/docs/docs/deployment-examples/chromium.mdx` line 51 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAORF1H-UDkBbH3DKq5:-OAORF1H-UDkBbH3DKq6:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/web/platform/src/content/docs/docs/deployment-examples/chromium.mdx#L51)):*
> ```MDX
> ```bash
> kubectl apply -k \
>     https://github.com/aaronmondal/nativelink//deploy/chromium-example?ref=flux
> ```

nit: point to nativelink repository
___
*[`web/platform/src/content/docs/docs/deployment-examples/kubernetes.mdx` line 27 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAORKFjETNP-mPOPt5V:-OAORKFjETNP-mPOPt5W:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/web/platform/src/content/docs/docs/deployment-examples/kubernetes.mdx#L27)):*
> ```MDX
> ```bash
> # TODO(aaronmondal): Point to the main repo before merging.
> git clone https://github.com/aaronmondal/nativelink && \
> ```

nit: point to nativelink repository
___
*[`web/platform/src/content/docs/docs/deployment-examples/kubernetes.mdx` line 52 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAORLPA9-rP_AHRfKa3:-OAORLPA9-rP_AHRfKa4:b-b4rhj6) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/web/platform/src/content/docs/docs/deployment-examples/kubernetes.mdx#L52)):*
> ```MDX
> ```bash
> kubectl apply -k \
>     https://github.com/aaronmondal/nativelink//deploy/kubernetes-example?ref=flux
> ```

nit: point to nativelink repository

**Review by aaronmondal — COMMENTED** [review]
-@adam-singer -@blakehatch -@allada 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-:-OAR9CaQ0KeSEsz2Cm1g:b-ejmvk)* status: 2 of 1 LGTMs obtained, and 55 of 67 files reviewed, and 2 discussions need to be resolved

___
*[`README.md` line 62 at r8](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-OAOQJ2A0JCori5LHoE4:-OAR5e2A05XUm6HDwuBe:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/7308caa1e7116a689190b53b34d3705b05ca565b/README.md#L62)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

The docs path should be relative "/docs/guides/kubernetes", if we want to have it self contained.
</blockquote></details>

Done.
___
*[`deploy/chromium-example/kustomization.yaml` line 18 at r1](https://reviewable.io/reviews/TraceMachina/nativelink/1088#-O1BMipYBJ3Z9EIKEKFI:-OAR8GQOByaEWtu6v3hd:b-896fix) ([raw file](https://github.com/TraceMachina/nativelink/blob/cfad74df5c37bf0684a324b15c5a888e9647f64e/deploy/chromium-example/kustomization.yaml#L18)):*
<details><summary><i>Previously, SchahinRohani (Schahin) wrote…</i></summary><blockquote>

nit: Don't forget to change the link
</blockquote></details>

Done.

**Review by aaronmondal — COMMENTED** [review]
> Reviewed 31 of 61 files at r1, 10 of 14 files at r2, 6 of 6 files at r3, 13 of 17 files at r6, 1 of 1 files at r8, 6 of 6 files at r9, all commit messages.
> Dismissed @MarcusSorealheis and @SchahinRohani from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/1088)* status: 2 of 1 LGTMs obtained, and all files reviewed, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / macos-13, Bazel Dev / macos-14, Bazel Dev / ubuntu-24.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Coverage, Installation / macos-13, Installation / macos-14, Installation / ubuntu-22.04, Local / ubuntu-22.04, NativeLink.com Cloud / Remote Cache / macos-14, NativeLink.com Cloud / Remote Cache / ubuntu-24.04, Publish image, Publish nativelink-worker-init, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Web Platform Deployment / macos-14, Web Platform Deployment / ubuntu-24.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (22.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable

**Pull request merged**
