### PR TITLE
Introduce the `native` CLI

### PR DESCRIPTION
**Pull request by aaronmondal**
This command line tool overhauls the initial setup for Kubernetes
deployments.

The new tool gives us more information when something doesn't work out
as intended and brings the the cluster setup considerably closer to what
one would expect in a production grade system.

The nativelink image and worker containers are now fully built
in the cluster via Tekton Pipelines. Rebuilds may be triggered with curl
requests instead of the old `nix run .#xxx.copyTo` workflow. This makes
the setup more generic and provides clearer pointers on how to bring the
system into continuously updating production workflows.

The `native` tool is technically fully self-contained. The examples
still make use of some local paths, but it's now possible to set up the
cluster and deploy NativeLink in it without cloning the nativelink
repository. This requires slightly modified `01_operations.sh` scripts
which we'll add as a new example.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
@kubevalet +@adam-singer +@allada +@blakehatch +@MarcusSorealheis +@nfarah86 +@zbirenbaum

(Make sure to click "combine commits for review" in reviewable, as this has gone through a few iterations and might be confusing to review otherwise)

Example usage of the new curl commands is here: https://github.com/aaronmondal/nativelink/blob/native-cli/deployment-examples/kubernetes/01_operations.sh

A preview of the logs that you'll now see when invoking `native up` in the development environment is here: https://github.com/TraceMachina/nativelink/actions/runs/8697038997/job/23851493633?pr=851#step:5:246

The changed behavior for the K8s examples is here: https://github.com/aaronmondal/nativelink/tree/native-cli/deployment-examples/kubernetes

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851#-:-NvYwHeU9FwtwXUPshlN:b-j700sf)* status: 0 of 6 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, Vercel, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer, @allada, @blakehatch, @MarcusSorealheis, @nfarah86, and @zbirenbaum)

**Comment by nfarah86** [comment]
The chromium  deployment example has an error with `line 148: goma_ctl: command not found
Subprocess failed with return code 1271`

If the error can't be resolved soonish- we should include in the readme that this error will happen and they won't be able to run the example.

**Review by adam-singer — COMMENTED** [review]
@nfarah86 if you are seeing this locally it is a bug with depot tools, needs to be re checked out from source. If this is being seen in one of our local images then they have been updated, I'd give it another try or ping me offline. 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851#-:-NvbNMqOA54K-XMJE6Kn:b-iom62b)* status: 0 of 6 LGTMs obtained (waiting on @allada, @blakehatch, @MarcusSorealheis, @nfarah86, and @zbirenbaum)

**Review by adam-singer — APPROVED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851)* status: 0 of 6 LGTMs obtained (waiting on @adam-singer, @allada, @blakehatch, @MarcusSorealheis, @nfarah86, and @zbirenbaum)

**Review by MarcusSorealheis — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851)* status: 0 of 6 LGTMs obtained (waiting on @adam-singer, @allada, @blakehatch, @nfarah86, and @zbirenbaum)

**Review by aaronmondal — COMMENTED** [review]
-@allada -@nfarah86 -@zbirenbaum -@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851#-:-Nve36HT5H66D6MK_0is:bsar76e)* status: 0 of 2 LGTMs obtained (waiting on @adam-singer and @MarcusSorealheis)

**Review by MarcusSorealheis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851#-:-Nve3Src3Iw9JWkqx9yN:bnfp4nl)* status: 1 of 2 LGTMs obtained (waiting on @adam-singer)

**Review by aaronmondal — COMMENTED** [review]
-@adam-singer 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/851#-:-Nve3X69E989JGsMOu8o:b-sd1e3m)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

**Pull request merged**
