### PR TITLE
Generalize k8s workers

### PR DESCRIPTION
**Pull request by aaronmondal**
Different worker images may now reuse the same `worker.json` config
file. This significantly simplifies the Kubernetes setup and provides a
clear path towards using custom worker images.

The Kubernetes example is now a fairly standard kustomize application
and should be straightforward to port to Helm charts that support remote
execution.

- - -
This change is [Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/812)

### CODE REVIEW

**Review by aaronmondal — COMMENTED** [review]
+@adam-singer +@allada +@blakehatch

cc @thelabdude
FYI the first commit here is from https://github.com/TraceMachina/nativelink/pull/809

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/812#-:-Nu6dMz73RY9VlypCe7g:b-kdw3cc)* status: 0 of 3 LGTMs obtained, and pending CI: Analyze (javascript-typescript), Analyze (python), Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, Cargo Dev / ubuntu-22.04, Local / ubuntu-22.04, Publish image, Publish nativelink-worker-lre-cc, Remote / large-ubuntu-22.04, asan / ubuntu-22.04, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), integration-tests (20.04), integration-tests (22.04), macos-13, pre-commit-checks, ubuntu-20.04 / stable, ubuntu-22.04, ubuntu-22.04 / stable, vale, windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04 (waiting on @adam-singer, @allada, and @blakehatch)

**Review by allada — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/812#-:-NuGaRz129Z7Gr3MoWbr:bnfp4nl)* status: 1 of 3 LGTMs obtained (waiting on @adam-singer and @blakehatch)

**Review by adam-singer — APPROVED** [review]
@aaronmondal lets sync to update https://github.com/TraceMachina/nativelink/pull/786 when this lands 

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/812#-:-NuPRSdU0TV_8yqhzQaN:b-j5hqng)* status: 2 of 3 LGTMs obtained (waiting on @blakehatch)

**Review by aaronmondal — COMMENTED** [review]
-@blakehatch 

> *[Reviewable](https://reviewable.io/reviews/TraceMachina/nativelink/812#-:-NuRRlvvEN9HkOqJ94_8:b-lpnp7r)* status: 2 of 2 LGTMs obtained, and pending CI: Bazel Dev / ubuntu-22.04, Cargo Dev / macos-13, docker-compose-compiles-nativelink (20.04), docker-compose-compiles-nativelink (22.04), windows-2022 / stable, zig-cc ubuntu-20.04, zig-cc ubuntu-22.04

**Pull request merged**
